### ISSUE TITLE
'scalaVersion in ThisBuild' has no effect

### ISSUE THREAD

**Issue by 404-** [sbt/sbt#1088]
in the absence of build.sbt, specifying scalaVersion in project/Build.scala has no effect. for example given project/Build.scala as:

```
import sbt._
import Keys._

object MyBuild extends Build {
  scalaVersion in ThisBuild := "2.10.2"
}
```

running: sbt "show scalaVersion"
yields:
[info] 2.10.3

**Comment by dansanduleac** [comment]
That's because a [Full Definition](http://www.scala-sbt.org/release/docs/Getting-Started/Full-Def.html#relating-build-sbt-to-build-scala) is plain scala code. The "assignment" (`scalaVersion in ThisBuild := "2.10.2"`) is just an expression whose type is `Setting[_]`, it does nothing on its own in a scala file because settings don't know how to "add themselves" - they are instead loaded from a few specific places by sbt.

You need to add it to [Build](http://www.scala-sbt.org/release/api/index.html#sbt.Build).settings, which is one of the places that sbt loads settings from (another is .sbt files), like:

```
import sbt._
import Keys._

object MyBuild extends Build {
  override lazy val settings = super.settings ++ Seq(
    scalaVersion in ThisBuild := "2.10.2"
  )
}
```

`Build.settings` originally contains the "default settings" that sbt needs to function, so you have to _append_ your settings to those, not just replace `Build.settings` with your own settings, otherwise you'll get a lot of "undefined setting" errors.

**Comment by 404-** [comment]
That makes perfect sense. Thank you for the detailed explanation, Dan!
