### ISSUE TITLE
Aggregation is not working as expected within a task definition

### ISSUE THREAD

**Issue by shengmin** [sbt/sbt#1110]
The following is a sample build script that can illustrate the issue:

``` scala
lazy val taskA = taskKey[Unit]("Some task")

lazy val A = Project(
  id = "A",
  base = file("A")
)

lazy val B: Project = Project(
  id = "B",
  base = file("."),
  settings = Seq(
    taskA := Def.task {
      // This only cleans the target directory of root but not the target directory of A
      val a: Unit = (clean in Compile).value
      // Neither does this work as expected
      val b: Unit = (clean in Compile in B).value
    }
  )
) aggregate(A)
```

When I execute `sbt B/taskA`, I would expect it to clean the target directory of **A** as well

**Comment by jsuereth** [comment]
I think you may be confusing aggregation's feature.   What aggregation does on project B is that it runs the _same task_ on project A that was called on project B.

So `sbt B/taskA` will _also_ call `sbt A/taskA`.  However, it does not (nor should) call any underlying tasks.

However, since you've aggregated the two projects, you could run `sbt B/clean` and it should clean A.

Let us know if we need to improve docs in this fashion (or patches welcome).

**Comment by shengmin** [comment]
Thanks for explaining how aggregation works under the hood :) And yes, it'd be helpful to include something like your comment in the docs.
