### ISSUE TITLE
Incremental compiler should always run the java compiler

### ISSUE THREAD

**Issue by dragos** [sbt/sbt#1178]
In _mixed_ mode, if there are Scala errors issued by the **Java** parser in `scalac`, java sources are not recompiled. This can lead to very confusing behavior in the IDE, where there's no bytecode generated, but no error messages.

Because the Java parser in Scala is not 100% compatible with Java, the Eclipse IDE won't show errors in Java sources when they are reported by scalac (for example, see [this ticket](https://www.assembla.com/spaces/scala-ide/tickets/1000361)) -- an error marker would prevent launching, for example.

**Comment by jvican** [comment]
Should we close this?

**Comment by dragos** [comment]
I don't think the problem was solved.

**Comment by jvican** [comment]
True, my bad @dragos.
  
So, IIUC, you suggest to always run the Java compiler even if the Scala compilation fails. You want it to get sane error messages from Javac -- so that you know that Scala dependencies are missing and were not compiled. Please, confirm this is what you had in mind and I'll port it over to the Zinc repository.

**Comment by jvican** [comment]
Ported to Zinc, can be closed. https://github.com/sbt/zinc/issues/343
