### ISSUE TITLE
plugin review: sbt-xjc

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#119]
Hi Mark,

I've put together a little plugin for compiling XSD to Java JAXB sources. The fun of porting old builds!

I think I've finally understood `inConfig`, so the exercise was worthwhile. Let me know if you spot any bad habits that I can remedy.

https://github.com/retronym/sbt-xjc
https://github.com/retronym/sbt-xjc/blob/master/src/main/scala/com/github/retronym/sbtxjc/SbtXjcPlugin.scala

Thanks,

-jason

**Comment by harrah** [comment]
Overall, it looks well done!
1. Make `xjcSettings0` public.  That way, if users have another configuration, like `IntegrationTest`, they can just do `++ inConfig(IntegrationTest)(xjcSettings0)` if they want it for that configuration as well.
2. Scoping inputs by the task 'xjc' is a good idea in my opinion.
3. I assume that it is standard to include the xsd files in the resulting binary, which is why you default to pulling them from unmanaged resource directories.  Otherwise, I'd use something like a `src/main/xjc` directory by default.
4. I'm pretty sure [this line](https://github.com/harrah/xsbt/blob/0.10/main/Defaults.scala#L116) means you can simplify the 'sourceManaged' definition to
   ```sourceManaged in xjc ~= (_ / "xjc")

```
Because you defined your own `sourceManaged` in a configuration, it should already have the configuration name appended.  You can check whether this is the case with `show compile:source-managed(for xjc)`.  I think you'll see the configuration name twice right now.

5. I'm currently thinking a good practice is to log a single line at the info level for an important task.  So, I think you could add a "Processing N XSD files in $label with xjc..." and maybe for the xjc-clean something similar.  I haven't done this consistently myself, but I think I will going forward.

    For $label, you could use the special, undocumented, [only recently properly implemented](https://github.com/harrah/xsbt/commit/bf8b577e4fb9532202e5c281e7d1aac403f74da8) `resolvedScoped` setting.  This provides the `ScopedKey[_]` for the defining setting.  That is, this:

        someKey <<= resolvedScoped( key => println( Project.display(key)) ) 

    would print `.../some-key`, where `...` is whatever scope someKey is in (after all inConfig and other transformations are applied).

6. In the README, you probably want a blank line between the settings for plugins definition.  You might want to mention that the java.net repository is needed for the fluentApiSettings.  The name of the settings method is SbtXjcPlugin.xjcSettings, not settings.  The options are nicely presented.

7.  If SbtXjcPlugin extends `Plugin`, sbt will automatically import its contents for the 'eval' and 'set' commands as well as in build.sbt files.  No settings get automatically injected into projects as long as you don't override `settings`.
```

**Comment by retronym** [comment]
Is there a way to refer to task scoped keys in the console, for example:

```
> show {file:/Users/jason/code/sbt-xjc/}sbt-xjc/*:transitive-classifiers(for update-classifiers)  
[error] Expected end of input.
[error] show {file:/Users/jason/code/sbt-xjc/}sbt-xjc/*:transitive-classifiers(for update-classifiers)
[error]   
```

The parser supports it; but when I debugged into it, `index.tasks(proj, keyConf._2, keyConf._1.label)` returned an empty set within 

```

        for {
            proj <- optProjectRef(index, current)
            confAmb <- config( index configs proj )
            keyConf <- key(index, proj, configs(confAmb, defaultConfigs, proj), keyMap)
            taskExtra <- taskExtrasParser(index.tasks(proj, keyConf._2, keyConf._1.label), keyMap, IMap.empty) }
        yield {
            val (key, conf) = keyConf
            val (task, extra) = taskExtra
            ScopedKey( Scope( toAxis(proj, Global), toAxis(conf map ConfigKey.apply, Global), task, extra), key )
        }
```

**Comment by retronym** [comment]
Thanks for the detailed comments, I've incorporated them.

**Comment by harrah** [comment]
Yeah, it is currently restricted to only allow task keys that are actually used.  If you set the value of that setting directly, it should be allowed.  (In this case, it will delegate to the global task scope, so there is a value, but it still won't parse.)  You can open a bug for it.
