### ISSUE TITLE
CustomPomParser produces unparseable ivy descriptor

### ISSUE THREAD

**Issue by dansanduleac** [sbt/sbt#1191]
_Edit: the issue lies differently than where I initially thought, so I explanded below to explain._

CustomPomParser adds this tag named `sbtTransformHash` in the `<info>` of ivy descriptors that are imported from a POM.
This seems to work fine when the imported ivy is in the ivy cache, but if I:
- `ivy.install` it to some ivy repository, say "local"
- do a `resolver.getDependency` on the module and force ivy to ignore the cache by setting `changing=true`, where `resolver` is the local ivy resolver

I get a parse error (the module in this case is `scala-swing;2.10.3`):

```
[debug] downloading N:\externals\org.scala-lang\scala-swing\2.10.3\ivys\ivy.xml ...
[debug]         ext-copies: downloading N:\externals\org.scala-lang\scala-swing\2.10.3\ivys\ivy.xml
[debug]         ext-copies: downloading N:\externals\org.scala-lang\scala-swing\2.10.3\ivys\ivy.xml.sha1
[debug] sha1 OK for N:\externals\org.scala-lang\scala-swing\2.10.3\ivys\ivy.xml
[debug]         [SUCCESSFUL ] org.scala-lang#scala-swing;2.10.3!ivy.xml(ivy.original) (32ms)

java.text.ParseException: [xml parsing: ivy-2.10.3.xml.original:16:21: cvc-complex-type.2.4.a: Invalid content was found starting with element 'sbtTransformHash'. One of '{WC[##other:""]}' is expected. in file:/C:/Users/dsandul/.ivy2/cache/org.scala-lang/scala-swing/ivy-2.10.3.xml.original
[error] , unknown tag sbtTransformHash in file:/C:/Users/dsandul/.ivy2/cache/org.scala-lang/scala-swing/ivy-2.10.3.xml.original
        at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.checkErrors(AbstractModuleDescriptorParser.java:89)
        at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.getModuleDescriptor(AbstractModuleDescriptorParser.java:344)
        at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser.parseDescriptor(XmlModuleDescriptorParser.java:118)
        at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser.parseDescriptor(AbstractModuleDescriptorParser.java:48)
        at org.apache.ivy.core.cache.DefaultRepositoryCacheManager$MyModuleDescriptorProvider.provideModule(DefaultRepositoryCacheManager.java:714)
        at org.apache.ivy.core.cache.ModuleDescriptorMemoryCache.getStale(ModuleDescriptorMemoryCache.java:68)
        at org.apache.ivy.core.cache.DefaultRepositoryCacheManager.getStaledMd(DefaultRepositoryCacheManager.java:731)
        at org.apache.ivy.core.cache.DefaultRepositoryCacheManager.cacheModuleDescriptor(DefaultRepositoryCacheManager.java:1193)
        at sbt.IvySbt$$anon$2.cacheModuleDescriptor(Ivy.scala:364)
        at org.apache.ivy.plugins.resolver.BasicResolver.parse(BasicResolver.java:536)
        at org.apache.ivy.plugins.resolver.BasicResolver.getDependency(BasicResolver.java:271)
        at sbt.ConvertResolver$$anon$3.sbt$ConvertResolver$DescriptorRequired$$super$getDependency(ConvertResolver.scala:64)
        at sbt.ConvertResolver$DescriptorRequired$class.getDependency(ConvertResolver.scala:96)
        at sbt.ConvertResolver$$anon$3.getDependency(ConvertResolver.scala:64)
...
```

The ivy file contains the tag

``` xml
<sbtTransformHash>7174be3135c2a95a21c158fb6beb5a9621b5b898</sbtTransformHash>
```

in its `<info>`.
This is happening despite the fact that I'm doing this within a correct Ivy context, like so:

``` scala
val resolv = taskKey[Unit]("Resolve scala-swing")

resolv := {
  ivyModule.value.withModule(streams.value.log) { (ivy, md, default) =>
    import org.apache.ivy.core.module.id._
    import org.apache.ivy.core.module.descriptor._
    import org.apache.ivy.core.resolve._
    val myResolver = ivy.getSettings.getResolver("local")
    val mrid = new ModuleRevisionId(new ModuleId("org.scala-lang", "scala-swing"), "2.10.3")
    val data = new ResolveData(ivy.getResolveEngine, new ResolveOptions)
    myResolver.getDependency(new DefaultDependencyDescriptor(mrid, true, true), data)
  }
}
```

I'm using sbt `0.13.2-M3`.

**Comment by jannic** [comment]
This issue seems to be not completely fixed. I sometimes get ivys which contain the e:sbtTransformHash tag without a corresponding namespace definiton in the xml header. In that case, the resulting ivy can not be used with ivy.install, as in the original report.

Unfortunately, I don't understand why or when this happens, exactly. But I was able to find a minimal test case: Create a new project with a build.sbt which just contains:

```
libraryDependencies += "org.apache.geronimo.specs" % "geronimo-jta_1.1_spec" % "1.1.1"
```

Build the project to cause downloading the file, and look at the generated ivy file in the ivy cache directory, in my case:

```
~/.ivy2/cache/org.apache.geronimo.specs/geronimo-jta_1.1_spec/ivy-1.1.1.xml
```

This file contains only one xmlns declaration, xmlns:m="http://ant.apache.org/ivy/maven", but none for the 'e' namespace. Still, it contains an e:sbtTransformHash element in the info section.

**Comment by eed3si9n** [comment]
@havocp  says running offlineTests on wip/play-232 in Activator can yield

```
[info] [error] (*:update) sbt.ResolveException: download failed: com.jcraft#jsch;0.1.38!jsch.jar
[info] [error] unresolved dependency: org.codehaus.plexus#plexus-component-api;1.0-alpha-16: java.text.ParseException: [[Fatal Error] ivy-1.0-alpha-16.xml.original:11:23: The prefix "e" for element "e:sbtTransformHash" is not bound. in file:/tmp/sbt_4852621/.ivy2/cache/org.codehaus.plexus/plexus-component-api/ivy-1.0-alpha-16.xml.original
```

**Comment by jsuereth** [comment]
This is fixed, but a cache may still have bad ivy files inside of it.

**Comment by jannic** [comment]
Well, I just retried:
- new, clean docker container, debian/sid with openjdk 7
- initially no ~/.ivy2/
- downloaded a fresh copy of sbt 0.13.5 
- created a new project, build.sbt contains only libraryDependencies += "org.apache.geronimo.specs" % "geronimo-jta_1.1_spec" % "1.1.1", and build.properties contains sbt.version=0.13.6-M1. No other files.

After running the 'compile' task, ~/.ivy2/cache/org.apache.geronimo.specs/geronimo-jta_1.1_spec/ivy-1.1.1.xml contains e:sbtTransformHash but no xmlns:e.

So, something still creates invalid xml files.

**Comment by erfangc** [comment]
this is still definitely an issue ... 

my .sbt contains:
libraryDependencies += "org.apache.hadoop" % "hadoop-mapreduce-client-core" % "2.2.0"

clean install of sbt 0.13.7

the cache's ...\org.apache.hadoop\hadoop-mapreduce-client-core\ivy-2.2.0.xml contains: `<e:sbtTransformHash>5719f575b89bf472b6c7168932ed8b3752733254</e:sbtTransformHash>`
without a corresponding `xmlns:e` declaration

which is causing:
`[error] (*:update) sbt.ResolveException: unresolved dependency: org.apache.hadoop#hadoop-mapreduce-client-core;2.2.0: java.text.ParseException: [[Fatal Error] ivy-2.2.0.xml.original:65:23: The prefix "e" for element "e:sbtTransformHash" is not bound. in file:/c:/Temp/.ivy-cache/org.apache.hadoop/hadoop-mapreduce-client-core/ivy-2.2.0.xml.original`

this only happens when the artifact must be resolved from a local filesystem. (many corporation prevent direct access to the maven2 public repository)

## Update

It appears the extra `<e:sbtTransformHash>` was added when sbt resolved the artifact from one of the default Resolvers. For example:

If we run `sbt update` for the first time (with zero-config). The `hadoop-mapreduce-client` artifact is resolved and downloaded to to cache under `~/.ivy2/cache`. Looking inside the cache, the ivy.xml file will contain the `e` tag

**Comment by chasebradford** [comment]
I also get this error on the hadoop-mapreduce-client artifacts.  &lt;e:sbtTransformHash&gt; with no declared extras namespace.

**Comment by chasebradford** [comment]
I've been poking at this quite a bit tonight, and I can't make sense of what I'm seeing.

The converted file has e:sbtTransformHash but not the namespace, even though in addExtra it looks like it's impossible to add one without the other.  If I comment out dmd.addExtraInfo(TransformedHashKey, TransformHash), then the converted file gains the namespace.

I tried adding a System.err.println(dmd) in addExtra.  When addExtraInfo is commented out, the println triggers for the module I'm scrutinizing.  When it's not commented out, it's as if addExtra's never called.

Here's a minimal project that fails for me.  Root fails to resolve, because it doesn't have the Cloudera resolver.  However, it should be able to pull the artifact from cache.  That fails because ivy fails to parse the artifact's xml file.

```
import sbt._
import Keys._

object TestBuild extends Build {
  lazy val Deps = Project("Deps", file("deps")).settings(
    libraryDependencies += "org.apache.hadoop" % "hadoop-mapreduce-client-jobclient" % "2.5.0-cdh5.3.0",
    resolvers += "Cloudera" at "https://repository.cloudera.com/artifactory/cloudera-repos/"
  )

  lazy val root = Project("root", file(".")).dependsOn(Deps)
}
```

**Comment by chasebradford** [comment]
Another update.  hadoop-mapreduce-client-jobclient has the parent pom hadoop-mapreduce-client.  When that pom is processed, the CustomPomParser adds the sbtTransformHash and namespace to it.  Then the ivy2 PomModuleDescriptorParser adds the parent pom's extra info to the -jobclient pom.  That's where it gets the sbtTransformHash.  Finally, when the -jobclient gets transformed, the transformedByThisVersion check sees the inherited tag and skips addExtra.  That leaves the sbtTransformHash but doesn't add the necessary namespace.

**Comment by erfangc** [comment]
thank you Chase that explains why this particular artifact was having issues where as a simpler artifact such as commons-lang3 does not
