### ISSUE TITLE
Ability to disable incremental compiler for CI builds

### ISSUE THREAD

**Issue by purefn** [sbt/sbt#1282]
While looking for a way to improve compile times on our build server, I came across issue #1078, about overhead added by the incremental compiler. Since our build server checks out a fresh copy of the source and builds from scratch each time, it would be nice to be able to disable the incremental compiler completely and not have to pay for something that will not be used.

**Comment by gkossakowski** [comment]
I updated the description of #1078. It turned out that the overhead is much lower and there are no plans for work on that ticket.

Since the overhead is much lower than originally suspected and it would be significant amount of work to introduce a mode where incremental compilation is disabled I don't think we'll work on that.

**Comment by jsuereth** [comment]
So the overhead is ~2-10% for most projects it appears.  I'd still be willing to accept a patch with some mechanism to disable incremental compilation, but for now this is a won't fix.
