### ISSUE TITLE
best practice on using sbtVersion or sbtBinaryVersion

### ISSUE THREAD

**Issue by raymondtay** [sbt/sbt#1337]
Hi sbt developers,

Am running `0.13.5-RC1` right now and was wondering what's the _usual_ practice when it comes to understanding the _exact_ version of the SBT we're running; is it to use `sbtVersion` or `sbtBinaryVersion` ? 

It's a small issue but i wonder why `sbtVersion` is not shown during a autocomplete ? That leads me to think that i should be using `sbtBinaryVersion` which isn't exactly what i'm looking for i.e. `0.13.5-RC1`

Thanks !

**Comment by jsuereth** [comment]
It's not shown because it's global, not defined on the current project.  {.}/_:_/sbtVersion may autocomplete, but I forget the rules.

`sbtVersion` is what you should use.  If you'd like sbtVersion to show up in autocomplete, please open that as a ticket.

Questions about best practice should either go to stack overflow _or_ sbt-dev (depending on whether it hits on sbt core design/development).  Please do not use the issue tracker as a mailing list.

**Comment by fommil** [comment]
btw, you totally failed to recognise that this ticket was number 1337. That deserves some form of party.

**Comment by fommil** [comment]
In fact, I think in order to make up for the delayed celebrations, you should create a party-coloured tag **just** for this ticket. :tada: :confetti_ball: :balloon:
