### ISSUE TITLE
Credentials key. Is there any real reason this needs to be a task rather than a vanilla setting?

### ISSUE THREAD

**Issue by softprops** [sbt/sbt#1370]
I'm asking because I'm [trying my hardest](https://github.com/softprops/bintray-sbt/issues/25) to figure out how I can reference the `credentials` key from a settings key ( `publishTo` ) and am hitting a road block. It [doesn't](https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/Defaults.scala#L96) seem like the [credentials key](https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/Keys.scala#L261) depends on any other setting. Does that fit the bill for it being vanilla setting type?

I understand that, by definition a setting key is a setting without dependencies, but is there a work around for grabbing this kind of value form within a setting. I know you can eval a task but you need a reference to state to do so but `state` is _also_ a task key :/

**Comment by jsuereth** [comment]
It's a task because it reads from a file and does so on demand (So you can add the file during an sbt session).  Settings are only initialized on (re-)loads.   Also, if loading a file fails, you don't want the whole build to crash.

Also, this kind of question is perfect for sbt-dev list, but not really an issue.  If you'd like alternatives for adapting `publishTo`, you can bypass it via `publishConfiguration` I think: https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/Keys.scala#L253

However, will discuss more on the sbt-dev ML if you want.
