### ISSUE TITLE
quit vs. exit - unify the way how to leave any session/tool

### ISSUE THREAD

**Issue by xhudik** [sbt/sbt#1374]
Hi, wouldn't be better to make quitting console and sbt with the same command?
## steps

Now I need
If I want to leave console session:

```
:quit
```

If I want to leave sbt:

```
exit
```
### problem

?
### expectation

I suppose 'exit' and ':exit' would save many errors ...

**Comment by jsuereth** [comment]
this is actually prime for contribution.  A new ":exit" command that does the same thing as "quit" would be nice for unification.

**Comment by som-snytt** [comment]
I settled on ctl-D.  Occasionally, I hit it too many times and lose a terminal window or two.

**Comment by jsuereth** [comment]
ctl-D is actually SUPER annoying, but perhaps more a reality if we fragment
the terminal + the engine (sbt-server).

**Comment by eed3si9n** [comment]
I'm looking at this because we got #1991 from @dwijnand. The original description by @xhudik had quit and exit flipped, so I fixed it. To get out sbt shell you type `exit`, and from Scala REPL you type `:quit` (or just `:q`).

By extending the flip, we probably should also invert @jsuereth's statement above also as:

> A new ":quit" command that does the same thing as "exit" would be nice for unification.

**Comment by dwijnand** [comment]
I looked into doing this in #1991 but `:quit` and `:q` aren't valid command names:

```
java.lang.AssertionError: assertion failed: ':quit' is not a valid command name.
    at scala.Predef$.assert(Predef.scala:179)
    at sbt.SimpleCommand.<init>(Command.scala:17)
    at sbt.Command$.make(Command.scala:33)
    at sbt.Command$.make(Command.scala:32)
    at sbt.BasicCommands$.newAlias(BasicCommands.scala:275)
```

@eed3si9n [recommends](https://github.com/sbt/sbt/pull/1991#issuecomment-97143520) going the other way:

> One way to "solve" this is to define a plugin that does something along the lines of:
> `initialCommands += "\nimport sys.exit"`
> For Scala versions that defines sys.exit. That will allow exit to work on both REPL and sbt shell.

**Comment by dwijnand** [comment]
Being a good traveling task, I created https://github.com/dwijnand/sbt-console-exit, in [all it's glory](https://github.com/dwijnand/sbt-console-exit/blob/v0.1.0/src/main/scala/com/dwijnand/sbtconsoleexit/SbtConsoleExitPlugin.scala).

So.. "solved"?

**Comment by som-snytt** [comment]
Someone complained once (or twice) about the way REPL hijacks $colon. For instance, `::` is an error but `::` is `::.type`. Since they're separating the JLine dependency this week -- I'm not sure what made it urgent -- and there is an interface, it might be interesting if the interface, besides history and completion, handled command dispatch.

You could plug in a reader where shift-enter means execute the line as a command, for instance. Or, I guess you could supply a reader that maps `:q` to exit. I'd like one that handles `:q!`, actually.

**Comment by dwijnand** [comment]
With [sbt-console-exit](https://github.com/dwijnand/sbt-console-exit) installed you can exist both sbt shell and sbt console with `exit`, so closing.

**Comment by dwijnand** [comment]
I'm killing [sbt-console-exit](https://github.com/dwijnand/sbt-console-exit) as you might as well instead of adding:

``` scala
addSbtPlugin("com.dwijnand.sbtconsoleexit" % "sbt-console-exit" % "0.1.0")
```

to `~/.sbt/0.13/plugins/plugins.sbt`, add:

``` scala
initialCommands += "\nimport scala.sys.exit"
```

to `~/.sbt/0.13/console-exit.sbt`
