### ISSUE TITLE
Simpler sonatype

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1429]
Pretty much everybody has something that looks like this in their codebase somewhere:

http://github.com/milessabin/shapeless/blob/master/project/Publishing.scala

it would be really nice if this `Sonatype` trait were a part of `sbt` (one that works for `build.sbt` files), since everybody copys and pastes anyway.

**Comment by Blaisorblade** [comment]
Couldn't this be a plugin?

**Comment by eed3si9n** [comment]
I agree we should improve common use case scenarios like publishing to Sonatype, bintray, and sbt community repo using Opts or plugins if not out of the box. There's actually https://github.com/xerial/sbt-sonatype but I'm not sure if that plugins is designed to reduce boilerplate or just automate release aspect of Sonatype.

Having said that, I'd like this discussion to take place in sbt-dev list, not Issues, because this is where we keep our internal todos, and some people may not read this.

**Comment by fommil** [comment]
I simply copy this to all my projects https://github.com/ensime/ensime-server/blob/master/project/SonatypeSupport.scala
