### ISSUE TITLE
Support wildcard exclusions in Pom parser

### ISSUE THREAD

**Issue by hamnis** [sbt/sbt#1431]
Maven 3.2 supports a new way of excluding everything.

See the [attached](https://github.com/hamnis/maven-wildcard-exclusion-sbt) project for more information.

This means that you may find newer published artifacts which allows exclusions on a more general level.

Sbt does not find the dependencies which have this.

**Comment by mkurz** [comment]
Can this get a higher priority?
IMHO this issue is a bug - not an "enhancement".

We just ran into the limitation of sbt not supporting wildcard exclusions when using Hibernate 5.2.1:
https://hibernate.atlassian.net/browse/HHH-10916
Hibernate has a dependency on `dom4j` which excludes all transitive dependencies:

```
    <dependency>
      <groupId>dom4j</groupId>
      <artifactId>dom4j</artifactId>
      <version>1.6.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>*</artifactId>
          <groupId>*</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```

The problem is that now even `dom4j` itself isn't resolved by sbt and we end up having a `ClassNotFoundException` - because of the missing `dom4j` jar.

**Comment by mkurz** [comment]
Infos:
https://maven.apache.org/docs/3.2.1/release-notes.html#Transitive_dependency_excludes_MNG-2315
https://issues.apache.org/jira/browse/MNG-2315

**Comment by eed3si9n** [comment]
@mkurz Thanks for clearing that up.

**Comment by mkurz** [comment]
@eed3si9n Thanks! Hopefully this get fixed soon...

**Comment by mkurz** [comment]
Is there a chance this will make it in the next sbt version?
Could someone please assign the milestone?

**Comment by eed3si9n** [comment]
I would say this is something we can push till the next sbt 1.0.x milestone, unless there's a support case from a Lightbend customer or we can get the community to contribute the fix.

**Comment by dwijnand** [comment]
Fixed in #2731.

**Comment by mkurz** [comment]
@dwijnand Thank you for fixing this!

**Comment by dwijnand** [comment]
Damn I should've been more explicit in the PR description.

All credit must go to @jtgrabowski for fixing this.

**Comment by mkurz** [comment]
OK so thank you @jtgrabowski for fixing this! :+1: :smile:
