### ISSUE TITLE
review request: sbt-protobuf

### ISSUE THREAD

**Issue by gseitz** [sbt/sbt#144]
Hi Mark,
I was wondering if you could take a look at [sbt-protobuf](https://github.com/gseitz/sbt-protobuf).
[ProtobufPlugin.scala](https://github.com/gseitz/sbt-protobuf/blob/master/src/main/scala/sbtprotobuf/ProtobufPlugin.scala) is all there is, plus there's  a description of all settings  in the [README](https://github.com/gseitz/sbt-protobuf/blob/master/README.md).

I'll be without scalac the next ~8 days, so there's no rush.

Cheers,
  Gerolf

**Comment by harrah** [comment]
1. Because the settings are already scoped by the `protobuf` configuration, you could use the builtin `sourceDirectory` key instead of `protoSource`.  The reuse of builtin keys elsewhere is good.
2. Because you wrap most of your settings in `inConfig(protobufConfig)`, the `in protobufConfig` is implied for those settings and doesn't have to be explicit.  For example, this is sufficient:
   
   ``` scala
   javaSource <<= (sourceManaged in Compile) { _ / "compiled_protobuf" }
   ```
3. There is built-in support for the basic uptodate checking done in sbt-protobuf.  I've not advertised it because it is basic and needs a proper design.  I've added basic documentation for it under "Uptodate checking" on https://github.com/harrah/xsbt/wiki/Common-Tasks/.
4. The documentation is nice and a good model for other plugins.
5. I think it is best to avoid `dependsOn`, especially for tasks under your control.  In this case, perhaps make `includePaths` a `TaskKey` and have `unpackDependencies` produce a tuple (or better, a simple case class) containing both the unpacked files and the base directory.  Then, you can define `includePaths` as:
   
   ``` scala
   includePaths <+= unpackDependencies map { _._2 }
   ```
   
   and be assured that whenever `includePaths` is referenced, the dependencies have been unpacked.  The `dependsOn` wouldn't be necessary.
6. The use of absolute paths when forking a process is good.
7. Why is this line necessary?
   
   ``` scala
   managedSourceDirectories in Compile <+= (javaSource in protobufConfig).identity
   ```
8. Perhaps add a note that `javaSource in protobufConfig` gets deleted on `clean` so that users don't set it to `src/main/java`.
9. You might avoid duplicating `PathFinder(sources) ** "*.proto").get` by defining `sources in protobufConfig <<= ...` and using that.  Related, it should be sufficient to do `(sources ** "*.proto").get` because of an implicit on `Seq[File]` to `PathFinder`.
10. You should be able to replace protoFilter with `"*.proto"`.  The `NameFilter` type expected is the same type as the argument to `**`, for example.

**Comment by gseitz** [comment]
Thanks for the review, Mark.

**Comment by gseitz** [comment]
Mark, I have a couple of questions after working your suggestions into the code:
- ad 2: Is the scope `protobufConfig` only implied for values of the LHS of each setting and I still need to have `in protobufConfig` on the RHS?
- ad 5: Can you elaborate on why `dependsOn` should be avoided?
- ad 7: I think that's an artifact when javaSource was a new key and the files not automatically included in the compilation.

Cheers

**Comment by harrah** [comment]
`inConfig(protobufConfig) ( ... )` puts all keys in `protobufConfig`, both on the left and right side.

As for `dependsOn`, I've been meaning to write that up in more detail.
