### ISSUE TITLE
Support publishing to file repositories specified in ~/.sbt/repositories

### ISSUE THREAD

**Issue by copumpkin** [sbt/sbt#1570]
As far as I can tell, this is impossible right now. I posted a question to SO detailing what I'm doing and how it fails: http://stackoverflow.com/questions/25573489/publishing-an-sbt-artifact-to-the-filesystem-with-resolver-specified-in-sbt

It looks like the `repositories` file parsing happens here:

https://github.com/sbt/sbt/blob/9c442d3aed53bdc89db1ada9d5b204bf02adb339/launch/src/main/scala/xsbt/boot/ConfigurationParser.scala#L188-L212

and I don't think anything that transforms the generated `Repository` values to `Resolver` values ever makes a file-based one, even if the URL scheme starts with `file:/`.

**Comment by copumpkin** [comment]
There's a chance this causes http://stackoverflow.com/questions/25428309/sbt-ivy-failing-to-resolve-wildcard-ivy-dependencies-on-a-filesystem-resolver as well.

**Comment by copumpkin** [comment]
I think the issue arises from [this line](https://github.com/sbt/sbt/blob/b202bd684839c37300dcee07b3eb78f16a0f8d5c/main/src/main/scala/sbt/Defaults.scala#L1658), which unconditionally makes a `Resolver.url` out of an `xsbti.IvyRepository`, even if the URL scheme is file-based. One solution would be to branch on the "protocol" of the URL and call `Resolver.file` when appropriate. I can make a PR for the change if someone knowledgeable agrees that that's how it should change.

**Comment by copumpkin** [comment]
An alternative would be to change `Resolver.url` to do the branching. But then we'd have to change the return type to be more general, since it wouldn't necessarily return a `URLRepository`.

**Comment by jsuereth** [comment]
To be honest, I want to just rip out the whole <insert word here> resolver mechanism of Ivy and redo it, as it's a bit broken to say the least.

HOWEVER, in my rational moments, I'd say the change you suggest to the launcher is the right call.  You _may_ want to also fix this line:  https://github.com/sbt/sbt/blob/b202bd684839c37300dcee07b3eb78f16a0f8d5c/launch/src/main/scala/xsbt/boot/Update.scala#L308-L322
otherwise you could see the likely super-funky scenarios of mismatched ivy repositories between the sbt-launcher-ivy + sbt-ivy.

**Comment by copumpkin** [comment]
I'd support that :smile:

Anyway, I can make the change later today. Is it too late for 0.13.6?

**Comment by copumpkin** [comment]
See #1579 for the associated PR

**Comment by copumpkin** [comment]
The UNC path support I put in there isn't quite right, and crashes, so I think I introduced a bug. I'll investigate, file a new bug, and try to fix it in the next couple of days.
