### ISSUE TITLE
Incremental compilation/dependency analysis broken when using jna

### ISSUE THREAD

**Issue by scroyston** [sbt/sbt#16]
I have a class that uses jna.  It gets recompiled every time, regardless of whether anything has changed.  I tracked it down to a the dependency graph getting "confused".  The problem is some of the jna classes get resolved to the sbt-launcher jna jar:
project/boot/other/net.java.dev.jna/jna/3.2.3/jna-3.2.3.jar

This happens in sbt.Analyze:
for(clazz <- loaded; file <- ErrorHandling.convert(IO.classLocationFile(clazz)).right)

IO.classLocationFile(clazz) returns the boot/other jar for com.sun.jna.Native and some others.

It seems like classLocationFile should only consider the explicit compile classpath...

This is a pretty big blocker for me to move to 0.9.x, since my class happens to be a root dependency for a large project.

**Comment by harrah** [comment]
Thanks for the report and especially for investigating more.  Incremental compilation bugs have high priority.

Analyze is only (supposed to be) used for Java sources.  Can you confirm that you have Java sources that depend on JNA?  If this is the case, I have a fix.

classLocationFile itself accepts an already loaded class.  The problem is the loader being passed into Analyze in the first place.

**Comment by scroyston** [comment]
Thanks for the response!

Yes, it was a java source file that depended on JNA.
