### ISSUE TITLE
Can't pass scalac options for build sources

### ISSUE THREAD

**Issue by duboisf** [sbt/sbt#166]
There is no way to pass options to scala (like -deprecation) for a project's build sources.

The `scalacOptions` TaskKey is for passing options to scalac when compiling the project's sources, not the build sources.

Mark provided a workaround by moving all the .scala files into the plugins folder and adding a build.sbt like so:

``` scala
sbtPlugin := true

scalacOptions += "-deprecation"
```

Still would be nice if we didn't have to move the .scala files into the plugins folder to be able to pass options to scalac to compile our build source files.

**Comment by harrah** [comment]
Explanation: The original commit made it so that options in a `project/plugins/build.sbt` file would apply to the build definitions in `project/` and `*.sbt` files in the project base directory.  While implementing this, I noticed it would be feasible to squash the tree down a bit.  So, I reverted the first commit (but published it for reference) and made it so that `project/` is a proper project.

Implications:
- `project/plugins.sbt` is now allowed instead of `project/plugins/build.sbt`.  `scalacOptions` defined here will be applied to `project/*.scala` files.
- `project/project/` is allowed instead of `project/plugins/project/`.  `project/project/` should be interpreted as "the build definition for the build definition".  It would probably be best to allow an alternate name to convey the default use as plugin definitions.
