### ISSUE TITLE
AutoPlugins cannot add files to the cleanFiles setting

### ISSUE THREAD

**Issue by urbas** [sbt/sbt#1725]
Please find scripted tests that reproduce this bug in [this repository](https://github.com/urbas/bug-sbt-autoplugin-clean/blob/master/README.md). I am using Travis CI to run the scripted bug-reproduction tests (see [![Build Status](https://travis-ci.org/urbas/bug-sbt-autoplugin-clean.svg)](https://travis-ci.org/urbas/bug-sbt-autoplugin-clean)).

**Setup**:
- An auto plugin generates a file. It adds this file to the `cleanFiles` list (see [source code](https://github.com/urbas/bug-sbt-autoplugin-clean/blob/master/src/main/scala/si/urbas/sbt/CleanAutoPluginBug.scala#L22)).
- We add the plugin to the project (see [source code](https://github.com/urbas/bug-sbt-autoplugin-clean/blob/master/src/sbt-test/autoplugin-must-clean/simple/build.sbt#L2))

**Test** (see [test definition](https://github.com/urbas/bug-sbt-autoplugin-clean/blob/master/src/sbt-test/autoplugin-must-clean/simple/test)):
1. We first invoke the plugin's file generation and verify that the file was created.
2. Finally, we invoke `clean` on the project.

**Expected behaviour**:
- The generated file should be deleted.

**Observed behaviour**:
- The file is not deleted.

**Comment by urbas** [comment]
Apologies for pushing, but could anyone take a look whether this is expected behaviour or a bug?

**Comment by eed3si9n** [comment]
Sorry for the delay. I'll look at it now.

**Comment by urbas** [comment]
Great, thanks a lot!

**Comment by eed3si9n** [comment]
Thanks for this interesting exercise. sbt actually is working as expected.
sbt's default values are loaded as auto plugins, and `cleanFiles` are loaded using `sbt.plugins.JvmPlugin`.

Therefore, in order to rewire the `cleanFiles` setting, you need to place your auto plugin after the `sbt.plugins.JvmPlugin`. Add the following to your plugin:

``` scala
  override def requires = plugins.JvmPlugin
```

It should now show cleanFiles as you specified.

**Comment by urbas** [comment]
Apologies for reopening, but this seems rather unexpected. The plugin has nothing to do with the `JvmPlugin`. Shouldn't the `JvmPlugin` use `+=` to modify `cleanFiles` rather than resetting the `cleanFiles` setting completely? This definitely seems like a bug in `JvmPlugin`.

**Comment by ghost** [comment]
Does everything have a dependency on the JvmPlugin? Surely this should be the default. I've seen a number of posts suggesting to add this require, but never understood the significance. 

You've documented a specific way of implementing Autoplugins. This doesnt work for arbitrary reasons. That does **not** sound like the "expected" behaviour.  

@urbas produced a very clear reproducible case. There is no indication in the documentation that JvmPlugin is required or when it is not. Objectively speaking, this is a very poor API design decision, from my point of view appears to be boilerplate for the vast majority of plugins.

**Comment by jsuereth** [comment]
@improbable-dave Let's set aside the boilerplate discussion and talk about the design for a second.

AutoPlugins `requires` is a means of ensuring that the dependencies of some aspect of sbt that your plugin uses is loaded before you settings come.   All settings need an origin.  Your AutoPlugin _could_ be that origin, or it could be one which modifies pre-existing settings.

In the set of plugins I work on (sbt-pgp, sbt-native-packager, sbt-pgp, sbt-git, sbt-site, sbt-pom-reader), only 3 of 20 autoplugins require JvmPlugin.  A majority are either on the IvyPlugin or create their own "universe" of settings.   Additionally, most plugins that I've seen in the wild also have different requires from JvmPlugin, e.g. sbt-web, PlayPlugin etc.    Some may depend on JvmPlugin _and_ others, but setting it to JvmPlugin is just as bad as a default as not having a requirement.

I do think perhaps we must focus on the "requires" aspect in the docs so people see what's there AND appropriately choose an appropriate requires.  What we could do here is actually alter requires to NOT have a default.  i.e. There are some decisions we want plugin authors to make and some we'd like to try to make for them.

I agree that boilerplate is bad.  I'd like to do everything we can to remove it.  However, I also would like Plugin authors to be aware of the requires method and make the appropriate decision per-plugin.

If you'd like to open more actoinable tickets, I think perhaps the following:
- improving the documentation of AutoPlugins to focus on requires
- Debug mode on settings where we alert when a setting from an "external" plugin is overridden by one of the core plugins (CorePlugin/IvyPlugin/JvmPlugin)
- Remove the default completely from AutoPlugin, since most plugins are adapting to something which already exists.

Does this sound ok?

**Comment by ghost** [comment]
I disagree with your reasoning because of the original posters example; it is clearly surprising behaviour.

Given that you have made considerable contribution to SBT and the plugins, I would suggest that maybe you're not coming from the most objective position; I'm sorry if I'm calling your baby ugly, but why is the original posters test wrong? There is nothing to suggest that the JvmPlugin is in use.

I think the actions you have described are reasonable steps and you should open them (or at least the person who decided to close this one).

**Comment by urbas** [comment]
A technical note: should it not cause a dependency exception if you're doing `cleanFiles += ...` but the `cleanFiles` setting has not been initialized with `:=` yet?

So that means that the `cleanFiles` setting is overwritten twice? Once to initialize the setting key and another time after I do `+=`. How can this happen?

**Comment by jsuereth** [comment]
@urbas Yes, it should actually cause a dependency exception.   Our load-optimiser is erasing your setting before we have a chance to discover the issue.  What our engine sees:

```
cleanFiles += ...
... other settings ...
cleanFiles := ...
```

It recognizes a "overwrite" setting and blows away the previous without ever running/remember them BEFORE it initializes/analyzes.

SO, perhaps we can consider that a bug in our over-eager optimiser.

**Comment by urbas** [comment]
This would at least expose the problem and lead the user to search for the source of the `cleanFiles` setting. But to be honest, I did that, and found that `cleanFiles` is in `sbt.Keys` and initialized in `sbt.Defaults`. This made me believe that `cleanFiles` is an "innate" setting and it would never occur to me that an auto plugin would be responsible for it. This really just adds to the fact that there's something fishy here.

**Comment by ghost** [comment]
Some further questions, based on the context of the original test and suggested workaround:
1. Where is JvmPlugin introduced? 
2. If it is added by default, then why is it not a default of AutoPlugin?
3. Why do I need to worry about JvmPlugin to use just clean? Should clean be tightly coupled to Jvm languages? 
4. What else overrides the plugin overrides? Are there any other plugins that are automatically added that we have to worry about?

**Comment by jsuereth** [comment]
1. It's introduced onto the default project constructor.  This is done to retain backward compatibility with older style builds.  
2. Good point.  You're coming closer to persuading me.  I still want plugin authors to find out about the plugin heirarchy quickly, but it couldbe JvmPlugin is a good default given the natureof sbt.
3. This, I'd say, points at a flub in the separation of the core plugins.   clean should probably be part ofthe CorePlugin and extended in the JvmPlugin.  CorePlugin could easily be auto-required as a scaffold of tasks that can be extended.
4. There could be.  Any autoplugin can override settings, as any .sbt file could.  If a plugin is breaking others, it's actually a poorly designed plugin and so far the community has been keen to get the authors to fix such bad behavior so that things work together.    One to be keenly aware of is the PlayPlugin which reworks a good portion of the JvmPlugin for its special mechanism of running.  We're working to ensure that the usual task/setting extensions are respected, but  few of them are shortcuted currently.

**Comment by eed3si9n** [comment]
So, unless the core plugin system improves significantly, we're all ok with making `JvmPlugin` the default right? Given that this feature enables mostly inter-plugin dependencies like sbt-web type scenario, I don't think we'll lose much from doing that.
Could one of you open a new issue for this? I could reuse this case, but I want to preserve how nicely @urbas has framed the issue.

**Comment by urbas** [comment]
@eed3si9n: I am thinking of opening the following issues:
- fix overeager setting key initialization ellision
- move `clean` into `CorePlugin` and make it a default dependency in `AutoPlugins`?
- documentation update that covers default dependencies and core functionality.

@jsuereth: What do you think?

**Comment by eed3si9n** [comment]
Just moving `clean` sounds arbitrary. If we're going to do it, we should figure out what belongs in [this list](https://github.com/sbt/sbt/blob/0.13.7/main/src/main/scala/sbt/plugins/JvmPlugin.scala) and what doesn't (maybe a new sbt-dev thread?):

``` scala
  override lazy val projectSettings: Seq[Setting[_]] = 
    Defaults.runnerSettings ++
    Defaults.paths ++
    Classpaths.jvmPublishSettings ++
    Classpaths.jvmBaseSettings ++
    Defaults.projectTasks ++
    Defaults.packageBase ++
    Defaults.compileBase ++
    Defaults.defaultConfigs
  override lazy val globalSettings: Seq[Setting[_]] =
     Defaults.globalJvmCore
```

**Comment by urbas** [comment]
Indeed, and I am definitely all for figuring it out. For starters, you might want to ask: What is common across JVM and non-JVM builds? But I'm sure you can come up with many more questions like this that will help us answer the problem of what to move into CorePlugin.

**Comment by jsuereth** [comment]
Yeah, i think we should figure out the design/interacton between Core/Ivy/Sbt.  Right now, it's somewhat arbitrary, and indeed Ivy has some bleed-over of scalaVersion thanks to how we cross version.

It'd be good to try to isolate cleaner separation between responsibilities of plugins and code.

**Comment by e-kolpakov** [comment]
Sorry for necro-posting, but was there any follow up on this? I've just banged my head against this issue for about half a day and adding `JvmPlugin` seems to still solve the problem in sbt 1.0.4.

Two questions though:

1. Is this still an expected way to go about it?
2. If so, it might be great to mention it somewhere in SBT docs - I mean something like "in order to override/append builtin keys from plugin, make it depend on JvmPlugin"

**Comment by dwijnand** [comment]
I'm not sure what your code looks like to still hit this, because JvmPlugin is now the default requires in sbt 1+..

**Comment by e-kolpakov** [comment]
@dwijnand Like this: https://gist.github.com/e-kolpakov/856c986453556165401a7cba4d36ffbc

Before adding `JvmPlugin` dependency explicitly, neither generation nor cleaning up didn't work. Initially I've worked it around by appending to `resourceGenerators` and `cleanFiles` in the build.sbt (not the plugin), but than I've found this issue, gave it a try and it worked.

I'm not so sure what am I doing wrong (if anything) or is it an issue in the sbt version I'm using (1.0.4).
