### ISSUE TITLE
Reduce verbosity when resolving artifacts

### ISSUE THREAD

**Issue by huntc** [sbt/sbt#1791]
I was just wondering whether we've ever considered only outputting the following types of message when we cannot locate an artifact locally:

```
       [info] Resolving org.scala-sbt#persist;0.13.5 ...
```

...who would care if this can be resolved quickly? Perhaps we should only output messages like that if the action takes more than, say, 1 second. Taking this approach would vastly reduce the amount of output from sbt.

WDYT?

**Comment by reid-spencer** [comment]
I think that would be helpful. When doing a build with Jenkins, those messages are retained in the output and I end up scrolling through 1000s of them in order to get to the point where the testing output begins. It isn't as much of a concern when doing a build on the terminal because the lines overwrite themselves but it might improve build speed slightly if all that I/O was avoided. At the very least this ought to be put into a verbosity level that is not enabled by default.

**Comment by pauldraper** [comment]
Yes, it's mostly a problem when looking at a log (i.e. not in a console that rewrites lines).

**Comment by eed3si9n** [comment]
There was some Windows ANSI issue that was recently resolved (#1771), but for Macs and Linux the "Resolving.." should overwrite on the spot. With the current way the libraries are resolved, I am not sure if we can generate a log only when 1s has elapsed since downloading the log. We'll take this into account when we re-implement our network API hopefully some time before 1.0.

If you want to turn it off completely, the setting is:

``` scala
ivyLoggingLevel in ThisBuild := UpdateLogging.Quiet
```

**Comment by axel22** [comment]
+1 - even on Linux, for builders like Travis and Drone 90% of output are `Resolving` lines.

And thanks for the setting, been looking for that!

**Comment by axel22** [comment]
Interestingly, this setting didn't change things:

```
2K[info] Resolving org.scala-sbt#sbt;0.13.7 ...
2K[info] Resolving org.scala-sbt#main;0.13.7 ...
2K[info] Resolving org.scala-sbt#actions;0.13.7 ...
...
```

I'm thinking that it should be put into `project/Build.scala`, or also `project/project/Build.scala` when there is a project definition within the project definition itself.

**Comment by axel22** [comment]
It seems that this setting doesn't change anything for me:

```
downloading https://repo1.maven.org/maven2/org/scala-lang/jline/2.10.4/jline-2.10.4.jar ...
    [SUCCESSFUL ] org.scala-lang#jline;2.10.4!jline.jar (184ms)
downloading https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.4/jansi-1.4.jar ...
    [SUCCESSFUL ] org.fusesource.jansi#jansi;1.4!jansi.jar (128ms)
:: retrieving :: org.scala-sbt#boot-scala
    confs: [default]
    5 artifacts copied, 0 already retrieved (24459kB/152ms)
[info] Loading project definition from /tmp/tmpqb8br1cc/project/project
[info] Updating {file:/tmp/tmpqb8br1cc/project/project/}tmpqb8br1cc-build-build...
[info] Resolving org.scala-lang#scala-library;2.10.4 ...
2K[info] Resolving org.scala-sbt#sbt;0.13.7 ...
2K[info] Resolving org.scala-sbt#main;0.13.7 ...
2K[info] Resolving org.scala-sbt#actions;0.13.7 ...
2K[info] Resolving org.scala-sbt#classpath;0.13.7 ...
```

Do you have an example project where the `ivyLoggingLevel` setting is used?

**Comment by jroper** [comment]
I am 100% sure that not one of the millions (a quick calculation reveals that this is a conservative estimate) of resolving messages that have flashed before my eyes over the entire time that I have been using sbt have ever helped me in the slightest.  If there's a resolve error, I see the error message, the resolving info message is not helpful.  If there's a problem with my dependencies, I go to the ivy reports which helps me debug them.  The resolving messages do not contain enough information to be helpful in this case.  I cannot ever remember a time when a resolving message has been useful.  Not once.

But I can tell you that the resolving messages have caused so much pain, mostly with CI, particularly with things like travis that if you turn logging off completely, timeout because you're not logging, or if you leave it on, fail because you logs exceed 10000 lines, 5000 of which are resolving messages.

These messages should be logged at debug, not info.

**Comment by jroper** [comment]
https://github.com/sbt/librarymanagement/pull/51

**Comment by intracer** [comment]
I still hope sbt will provide some progress report so users will not think it's just frozen

**Comment by ocramz** [comment]
What's the progress on this issue? It would vastly improve the developer experience (i.e. critical build errors are buried within these useless messages)

**Comment by ocramz** [comment]
@axel22 I found `ivyLoggingLevel := UpdateLogging.Quiet` in build.sbt to suppress all the `[info] Resolving ..` messages

**Comment by DonMcNamara** [comment]
I'm not an sbt expert, so there might be a better way. I had to add the `ivyLoggingLevel := UpdateLogging.Quiet` line to my build.sbt, _and_ to an sbt file in the `project` sub-directory.

**Comment by eed3si9n** [comment]
Should be fixed by Coursier + super shell.
