### ISSUE TITLE
support external download manager for downloading the artifacts

### ISSUE THREAD

**Issue by He-Pin** [sbt/sbt#1802]
Hi,how about add external downloading manager support for sbt when downloading the artifact from the repo.like `axel` or `aria2`

**Comment by jsuereth** [comment]
We actually need to expose hooks into Ivy so we can effectively do this, but it is in the plans.

**Comment by He-Pin** [comment]
that would be very nice,cause with axel ,we could speed up the downloading

**Comment by He-Pin** [comment]
maybe expose the download hooks,then maybe plugins could implement many effectively way to do the downloading.

**Comment by eed3si9n** [comment]
Likely this won't happen here since we've moved on to using Coursier.
Btw taking over HTTP from Ivy is relatively easy if someone wants to experiment in this area - https://github.com/sbt/librarymanagement/blob/develop/ivy/src/main/scala/sbt/internal/librarymanagement/ivyint/GigahorseUrlHandler.scala

**Comment by He-Pin** [comment]
![image](https://user-images.githubusercontent.com/501740/71031263-fed82d00-214d-11ea-9ac0-c79267a7afee.png)
