### ISSUE TITLE
2.11 Release?

### ISSUE THREAD

**Issue by adamdecaf** [sbt/sbt#1813]
Hey all, I'm trying to build some plugins for 2.11 and running into issues. It looks like there's no 2.11 release of sbt, so you can't compile macros because the existing releases are all build on scala 2.10. Is there a timetable / snapshot / nightly / anything I can use?

I'm seeing these errors 

``` scala
[error] /Users/adam/src/backln/sbt-docker/src/main/scala/sbtdocker/DockerKeys.scala:6: can't expand macros compiled by previous versions of Scala
[error]   val docker = taskKey[ImageId]("Build a Docker image.")
[error]                                 ^
```

That lead me to several SO articles, and this one is just the best answer. (Even if its from August '14) https://stackoverflow.com/questions/23282469/does-sbt-builds-againts-scala-2-11

**Comment by eed3si9n** [comment]
At the moment we don't have timetable / snapshot / nightly / anything that you can use.
One thing you might give it a shot is to use [Fork API](http://www.scala-sbt.org/0.13.7/api/index.html#sbt.Fork$). sbt is able to build Scala 2.11 code using 2.11.5 compiler even though we are based on Scala 2.10. If you mimic what we do for compilation, you might be able to get your stuff working before we release 2.11-based sbt.

**Comment by adamdecaf** [comment]
Hmm, that's too bad. I'll just wait for a proper 2.11 release then.

**Comment by andypetrella** [comment]
Hello,

I actually have the same issue, but the impact is rather important since I'm using SBT to download and inject new dependencies into notebooks (in the [spark-notebook](https://github.com/andypetrella/spark-notebook)).

So the thing is now working very well (even deps on s3 are working) in 2.10, but now I'm stuck with the 2.11 support. Although everything will work (spark repl, scheduling and so forth) only the deps management fails.

So I was wondering if there is a short term plan to have a 0.14 branch with the same 0.13 code bases and features maybe but with cross build enabled?

I know 1.0 is on the way but I guess it may take again some time before it lands, right?

Any other idea is more than welcome :-D.

thanks for reading
andy

**Comment by leobenkel** [comment]
What version of SBT should one use to make a plugin for scala `2.11` ?

**Comment by eatkins** [comment]
@leobenkel there will likely never be support for scala 2.11 sbt plugins. The 0.13.x series is only compatible with scala 2.10.x and the 1.x series is only compatible with scala 2.12.x.

**Comment by leobenkel** [comment]
ok, thanks
