### ISSUE TITLE
setting port for publishing server Credential cause error

### ISSUE THREAD

**Issue by nik-kashi** [sbt/sbt#1829]
setting the port in credential of server:
`credentials += Credentials("Sonatype Nexus Repository Manager", "192.168.2.222:8081", "admin", "SECRET")`

 publish command (activator publish) causes this error :
`[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ 192.168.2.222].`

and after removing port publishing works properly, means:
`credentials += Credentials("Sonatype Nexus Repository Manager", "192.168.2.222", "admin", "SECRET")`

**Comment by jsuereth** [comment]
This is actually by design, currently.  The underlying mechanism doesn't allow differentiating by port.  

Do you have different credentials by port?  We'd have to do some heavy investigation yo see if we can support that use Case.

**Comment by nik-kashi** [comment]
Currently no. but it is possible to exists two repository server in one machine.

In other hand in SBT official documentation, not mentioned that port is not needed (If it is intentionally it should mentioned in docemantation):

http://www.scala-sbt.org/0.13/docs/Publishing.html

And I am spend many time to find that!

**Comment by eed3si9n** [comment]
I've flipped the ordering so https://www.scala-sbt.org/1.x/docs/Publishing.html mentions 

```
realm=My Nexus Repository Manager
host=my.artifact.repo.net
user=admin
password=admin123
```

first. Hopefully this makes it clear enough that the second parameter is supposed to be host.

Otherwise feel free to send a PR to https://github.com/sbt/website/blob/develop/src/reference/02-DetailTopics/03-Dependency-Management/05-Publishing.md.
