### ISSUE TITLE
Support command history search via partial + up-arrow

### ISSUE THREAD

**Issue by sirthias** [sbt/sbt#1833]
It'd be great if the SBT shell mirrored what ZSH does and supported quick history search by allowing me to type a command prefix and searching through the history upon pressing up-arrow.

`!prefixString` is already supported but requires me to remember which command is the last one starting with `prefixString` (not visual verification before running) and doesn't give me a chance to select between several potential alternatives.

**Comment by eed3si9n** [comment]
+1 on this change. If anyone wants to send PR on this, please comment here.

**Comment by kzys** [comment]
Is it still open? Apparently I can search the history by using Ctrl-R, as like zsh.

**Comment by dwijnand** [comment]
The request is for what is referred to in readline as "history-search-backward", not Ctrl-R

**Comment by PanAeon** [comment]
Hi,
looks like jreadline2 already supporting this. According to [The most important command line tip](http://codeinthehole.com/tips/the-most-important-command-line-tip-incremental-history-searching-with-inputrc/) one needs to put the following config in `~/.inputrc`:
```
"\e[A": history-search-backward
"\e[B": history-search-forward
"\e[C": forward-char
"\e[D": backward-char
```
I did that and both bash and sbt started to do quick history search on up arrow.
It's a bit annoying though, that when I put space in front of command then it will not pop up in suggestions, because sbt will not trim leading space when querying history.
@sirthias if this resolves the issue I can put this into documentation either in the Setup-Notes or Running section.

**Comment by sirthias** [comment]
@PanAeon Nice! Your tip does work for me on OSX!
 I think it'd be great if this made it into the documentation!

**Comment by eed3si9n** [comment]
Here's a PR for this - https://github.com/sbt/website/pull/822
