### ISSUE TITLE
[0.13.7] scalac doesn't recognize AutoPlugin as an sbt.Plugins in Build.scala

### ISSUE THREAD

**Issue by kiritsuku** [sbt/sbt#1844]
This repo reproduces the error: https://github.com/sschaef/sbt-autoplugin-test

Executing sbt on the root results in a weird type mismatch, even though the `AutoPlugin` should be recognized as subtype of `sbt.Plugins`.

**Comment by eed3si9n** [comment]
If I believe the timestamp on https://repo.scala-sbt.org/scalasbt/sbt-plugin-snapshots/com.typesafe.sbt/sbt-osgi/scala_2.10/sbt_0.13/0.8.0-SNAPSHOT/jars/ The snapshot has not been updated since 05-Jan-2014 22:07, which matches the date on sbt/sbt-osgi@c6dd29a3fdc16e0789ef2f79e7aeb79d2c455418. At the time auto plugin was not released yet.
