### ISSUE TITLE
SBT is silent on first run looking like it's broken

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt#1954]
We just got the following report on the Play mailing list

> On my end, running the command "activator ui" took 10 minutes, without any indication it was doing anything. To be honest, I tried it a few times before and just closed the console window. But finally, as I was typing this it opened up a new tab in the background. The initial usability of this isn't ideal, especially considering there's no context as to what to expect: That it'll churn as long as it takes without indicators and then at some point open a browser tab. Second run was faster, but still about a 1min wait time.

I've seen this as well. Every time someone joins our company and sets up a new computer we get this report.

If you blast away your ivy repo I'm guessing you'll see this behavior. I think the issue here is that SBT tells you when it's fetching jars for your project, but it probably doesn't tell you when it's fetching jars for your SBT plugins. So on first run, you type `sbt` and it downloads all the play plugins, sbt-web plugins, etc. and it takes a long time and meanwhile the user doesn't know what's happening and why their SBT console isn't coming up. They'll often kill SBT at this point and start it again, which causes it to resume the download, but still look like it's hanging. Folks will often kill it again and just give up at this point

We should really fix this because it's really discouraging to new comers

**Comment by eed3si9n** [comment]
What do you propose as the solution? If it's currently not printing the list of all downloading JARs, I suspect it was quieted in response to people finding it too noisy. We also should confirm that the initial delay is introduced by JAR download.
Maybe we can introduce some ASCII tricks like an in-place progress bar. Thoughts? /cc @jsuereth, @havocp, @jroper

**Comment by havocp** [comment]
We get this report on Activator often. It's especially an issue for asia/pacific due to latency. It definitely confuses people.

I don't know how much control we have over the ivy output, but I think the ideal would probably be to output one line per downloaded artifact with no other noise, and we can do the ANSI codes to overwrite the previous line every time, instead of scrolling it all past. I doubt we can do a real progress bar (because we have no way to know the percent complete). Printing the currently-downloading jar would be more convincing evidence that "it's not stuck," compared to showing some kind of busy-spinner animation.

**Comment by benmccann** [comment]
I think it'd be great to print the jars as they're downloaded and I don't think that it'd be too noisy. We already do that for jars that need to be downloaded because they're dependencies of your sbt project and as far as I know people don't complain about it being too noisy there. I believe that we just don't do it for jars that are required for sbt itself or sbt plugins?

**Comment by eed3si9n** [comment]
@havocp We _might_ be able to suspend all JAR download during Ivy resolution, and download everything in parallel off a final list. Then we do have real progress bar. Another quick fix may be:

``` scala
println("JAR download process initiating... May take hours if you live in Asia or Australia.")
```

**Comment by dwijnand** [comment]
I wonder which artifact source isn't available via a close CDN. I'm pretty sure Sonatype's Maven Central is probably fine, but what about Typesafe's repositories? Another one is bintray for the plugins..

**Comment by jroper** [comment]
Simple solution: I think if sbt (or activator) is doing anything that it knows could take more than 10 seconds, it should say what it's doing, and preferably why.  It doesn't have to say every step, but saying "Downloading SBT 0.13.8 because it wasn't found in the cache..." would be a big help.

Ideal solution:
1. Detect if stdout is a tty
2. If so, go into user feedback mode, which provides more than just carriage return to render lines on top of each other, it should use proper ansi commands to update the screen.
3. In user feedback mode, each time a potentially expensive task is started, some heuristics are used to estimate how much work will be done.  Then, as work is completed, a progress bar progresses.  If the task is dynamic and more work is discovered part way through than was estimated, then the rate of progression as the work is completed slows.
4. In addition to the progress bar, a status line can be updated to say what it's currently doing (downloading meta data for X, downloading jar for X, etc).
5. Afterwards, the status and progress bars are cleared, and logging continue as normal.

If not in user feedback mode, then just a single log message saying what expensive task is about to happen is necessary.

**Comment by lazaridis-com** [comment]
A tiny sentence like:

 `Retrieving Libraries. This can take 5 to 30 minutes (it is done only once after an installation).`

would have kept me (Role: Newcomer) happy - even without a  list of downloads or a progress-bar or an animation.

So, possibly the quick-fix mentioned by @eed3si9n should be applied before the thorough solution suggested by @jroper.

**Comment by havocp** [comment]
The quick 1-line warning would certainly be worth doing in my opinion. I think it can be as quick as 1 minute, all the way to half an hour or more, depending on whether you have dialup in the outback or fast broadband close to the repositories.

**Comment by jroper** [comment]
The biggest killer for me is latency.  I'm on an 80Mb connection now, yesterday I started using sbt 0.13.8 for the first time, took about 5 minutes to resolve/download everything, and that's just sbt, already had scala etc.

**Comment by havocp** [comment]
yeah. insert my rant here about how to design around that problem by checking update results into git. :-) well, I'll spare you :-)

**Comment by lazaridis-com** [comment]
@havocp , this one should really be solved (quick 1-line would  be enough)

**Comment by rtpg** [comment]
So I just had the same sort of issue

```
Getting org.scala-sbt sbt 0.13.9 ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/jars/sbt.jar ...
    [SUCCESSFUL ] org.scala-sbt#sbt;0.13.9!sbt.jar (11245ms)
downloading https://jcenter.bintray.com/org/scala-lang/scala-library/2.10.5/scala-library-2.10.5.jar ...
    [SUCCESSFUL ] org.scala-lang#scala-library;2.10.5!scala-library.jar (44501ms)
```

the interesting thing was that the `downloading` message only appeared _after_ the download finished. So I basically had 5 minutes of `Getting org.scala-sbt sbt 0.13.9...` with no feedback at all

**Comment by pablote** [comment]
Same issue here, it stays on the "Getting org.scala-sbt sbt.." message for several minutes until some feedback starts showing up. Not sure what it's doing, looking at the activity monitor there's very little network activity during that time.

**Comment by intracer** [comment]
+1

**Comment by Vadi** [comment]
In the world of Docker containers, this is really killing. Please fix this.

**Comment by dwijnand** [comment]
In terms of "SBT is silent on first run looking like it's broken", this has been mitigated somewhat by a small change in the messaging.

https://github.com/sbt/launcher/pull/27

**Comment by LeeiFrankJaw** [comment]
What I did to force _sbt_ to show downloading log on first run is the following.

    sbt --debug
