### ISSUE TITLE
SBT don't recompile related java file use final field

### ISSUE THREAD

**Issue by bash99** [sbt/sbt#1967]
how to reproduce: 
#### A.java

``` java
Class A {
   public static final String SCRIPT_1 = "return 1";
}
```
#### B.java

``` java
Class B {
    public static void main(String[] args) {
        System.out.println(A.SCRIPT_1);
    }
}
```
1. change `A.java`'s constant to `"return 2"`; save and recompile.

only A.java is compiled, and run B still output
`"return 1"`;

English is not my native language, so sorry for any mistakes.

**Comment by stuhood** [comment]
This appears to be due to http://stackoverflow.com/questions/3524150/is-it-possible-to-disable-javacs-inlining-of-static-final-variables

**Comment by eed3si9n** [comment]
So the workaround would be to change to 

``` java
Class A {
   public static final String SCRIPT_1 = "return 1".toString();
}
```

**Comment by stuhood** [comment]
@eed3si9n : Yea. I'm going to see whether it is feasible to include the primitive content of the static-final-primitive field in the API of the class, so that this is considered to be an API change.

**Comment by stuhood** [comment]
It looks like it should be possible to do this via the `sbt.classfile.ClassFile` API, which is already used for java compilation.

One question for current SBT committers: would you be opposed to adding usage of that classfile parser to `sbt.ClassToAPI`? It looks like it currently uses only information that is available via reflection, but in this case we'd need to look in (at least) the constant pool.

**Comment by eed3si9n** [comment]
I don't think I'm opposed to the idea of it. Just not sure what the implementation entails, and feasibility of it.

**Comment by stuhood** [comment]
@eed3si9n @jsuereth : Any thoughts on how to represent a final-static field in SourceAPI?

I've gotten the constant value from `sbt.classfile.ClassFile`, and now the change seems to be a matter of exposing the constant as part of the API of the class. The most obvious backwards-compatible approach seems to be to represent it as an `xsbti.api.Singleton`, but it's not immediately obvious what a good unique `xsbti.api.Path` would be for the type. Perhaps a name-mangling of the field?

**Comment by eed3si9n** [comment]
I could be off base, but there's an effort going on around incremental compiler to generalize the notion of dependencies, like #1757, so I'm wondering if we could track relationship between the Java sources without mangling. /cc @Duhemm

**Comment by stuhood** [comment]
@eed3si9n : No, I don't think so: we want field/api-level dependency tracking, and #1757 provides file level tracking.

**Comment by jsuereth** [comment]
@stuhood A few notes:
1. The classfile parser is something we'd like to drop.  We'd also like to drop the "reflection" based extraction in favor of an approach which uses ASM to rip out all the information from the classfile.  AFAIK (and I didn't write the code, was only given a rundown of it), the classfile parser _was_ used in the incremental compiler to grab these constants for analysis.  It could be that code somehow got dropped, or I'm misremembering.
2. As far as how to represent them, I'm not sure how we do it now, but the "least path of resistance" follows from this logic (let me know if you agree):
   - These constants should be encoded as "members" of the class, but with a special notion that they are not "regular" members
   - These constants should be annotated as a [constant type](https://github.com/sbt/sbt/blob/0.13/interface/type#L15-L17) so that we know they are constants
   - I believe these should be annotated as 'public [val](https://github.com/sbt/sbt/blob/0.13/interface/definition#L8)'s, theoretically.  I'm not sure this is enough to track dependencies.

We may need to add a new flag (or subclass) to the API hierarchy that gives you the knowledge you need to know about them in the rest of the logic.   I'm doing a bit more investigation on my end.

**Comment by jsuereth** [comment]
@stuhood Ok, I am right.  Here is where both the reflection reader and classfile parser are used: https://github.com/sbt/sbt/blob/0.13/compile/integration/src/main/scala/sbt/compiler/javac/AnalyzingJavaCompiler.scala#L74-L88

Ideally, we'd like to have _just one of these_.  Since you have to read the classfiles to get the constants, I think this means we'd like to use a legit classfile reader to get all of the API for java classes.

In any case, you may already know, we store the constant pool here: https://github.com/sbt/sbt/blob/0.13/util/classfile/src/main/scala/sbt/classfile/ClassFile.scala#L18

And then this is where the constant pool SHOULD be hitting the extracted API of a class: https://github.com/sbt/sbt/blob/0.13/util/classfile/src/main/scala/sbt/classfile/Analyze.scala#L69

Hopefully that helps you out!  I _think_ we have the right pieces in place, looks like they just weren't full wired together.   I'm also at a loss as to when the "API" stopped getting filled out on the Java side.

**Comment by stuhood** [comment]
Cool... I believe I have something inefficient-but-working. Headed out of town for the rest of the week, but should be able to post something early next week.

**Comment by ericzundel** [comment]
I think a developer just got bitten by this today, we are on sbt 0.13.9.  Is there a release that contains this fix?

**Comment by jvican** [comment]
Should we close this? #2085 was already merged and AFAIK is working on latest Zinc.
