### ISSUE TITLE
run tests in muliple forked JVMs

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1971]
according to http://www.scala-sbt.org/0.12.4/docs/Detailed-Topics/Testing.html it should be possible to specify the number of JVMs to use when forking tests.

However, the following doesn't seem to do anything

``` scala
    concurrentRestrictions in IntegrationTest := Seq(
      Tags.limit(Tags.ForkedTestGroup, 4)
    ),
    fork in IntegrationTest := true,
    testForkedParallel in IntegrationTest := true
```

when I was expecting it to launch 4 JVMs, splitting my tests randomly between the JVMs.

**Comment by eed3si9n** [comment]
In the forking tests section that you quoted http://www.scala-sbt.org/0.13/docs/Testing.html#Forking+tests, it also talks about `testGroupings`, which tells which tests will run together vs run concurrently. Out of the box all test suits are in one grouping.

Here's an example of using 4th letter of the test for grouping. Why 4? Because all of my tests had the first 3 letters the same "sbt." and I'm counting 0-based:

```
> set testGrouping in Test := ((definedTests in Test).value groupBy (_.name(4)) map { case (letter, tests) => new Tests.Group(letter.toString, tests, Tests.SubProcess(Seq("-Dfirst.letter"+letter)))} toSeq)
```

**Comment by fommil** [comment]
I've asked about this on SO and given lots of extra info http://stackoverflow.com/questions/34381893

As far as I can tell, `ForkedTestGroup` is just ignored.

(BTW, in your example, the `ForkOptions` are completely bare... you need the boilerplate like in my example to get anywhere)

**Comment by fommil** [comment]
I can definitely fork tests in separate JVMs (I have my own Group implementation, see https://github.com/ensime/ensime-server/blob/master/project/EnsimeBuild.scala#L115-L141 ) but the parallelism is set by the `limitAll` not the `ForkedTestGroup`. If I set `ForkedTestGroup` to 2 and all to `4` it still seems to run 4 JVMs.

**Comment by fommil** [comment]
I got this working.
