### ISSUE TITLE
withSources() flag incorrectly exports source code

### ISSUE THREAD

**Issue by htmldoug** [sbt/sbt#2001]
The sbt `withSources()` flag incorrectly exposes source code as a classpath dependency of the artifact.
## Steps
1. git clone https://github.com/htmldoug/sbt-withSources-bug1.git
2. sbt publishLocal
3. open ~/.ivy2/local/default/sbt-withsources-bug1_2.10/0.1-SNAPSHOT/poms/sbt-withsources-bug1_2.10.pom
4. observe that sources are exported as classpath dependencies

``` scala
<dependency>
    <groupId>com.typesafe</groupId>
    <artifactId>config</artifactId>
    <version>1.2.1</version>
    <classifier>sources</classifier>
</dependency>
```
## Problems

Using withSources()...

```
libraryDependencies += "com.typesafe" % "config" % "1.2.1" withSources()
```

... causes the sources to be **exported in the pom**.

``` xml
<dependency>
    <groupId>com.typesafe</groupId>
    <artifactId>config</artifactId>
    <version>1.2.1</version>
    <classifier>sources</classifier>
</dependency>
```
1. This behavior is undocumented, surprising, and a security risk. In our play projects, sbt-native-packager happily gobbles up these classpath dependencies and **deploys our source code to our prod servers!** 
2. In downstream dependencies, I've seen sbt evict the classes dependency, e.g. `"com.typesafe" % "config" % "1.2.1"`, in favor of the sources jar! Example not included here (since sources shouldn't be exported in the first place), but I can create one if needed.
## Expectations

From [Download Sources](http://www.scala-sbt.org/0.13/docs/Library-Management.html#Download+Sources):

> To have sbt download the dependency’s sources without using an IDE plugin, add withSources() to the dependency definition.

There is no mention of exposing the source code as a classpath dependency. I expect that this is not the correct behavior.
## Notes

Example here: https://github.com/htmldoug/sbt-withSources-bug1

**Comment by htmldoug** [comment]
I found some [scaladoc](https://github.com/sbt/sbt/blob/0.13/ivy/src/main/scala/sbt/ModuleID.scala#L102-L103) that suggests exporting the sources as a runtime dependency may be intentional, though I can't think of any scenarios where that'd be desired.

**Comment by eed3si9n** [comment]
`libraryDependencies += ...` is for classpath dependencies. My vote would be to keep the current behavior and maybe add some note in the doc about it.

**Comment by jeffmay** [comment]
If we keep the current behavior, then you have to have an IDE to download the sources without adding the source jars to your production servers?

**Comment by eed3si9n** [comment]
@jeffmay I don't know what the usage of downloading the source is, but you can either call `updateClassifiers` directly or use sbt plugins that calls it like ensime-sbt.

**Comment by jeffmay** [comment]
Ah, ok, I just tested out `updateClassifiers` and it works. I didn't know about that option.

**Comment by cunei** [comment]
@eed3si9n, similarly to #2002, the issue is confined to `getScopeAndOptional`, at https://github.com/sbt/sbt/blob/f334d76f70bb6ba2befc38b414f13776d0b119ac/ivy/src/main/scala/sbt/MakePom.scala#L312-L318
In this case, the list of configs passed to it, concerning the source dependency, is simply `sources`, to which `getScopeAndOptional` returns `None`. Indeed that is not the best outcome; the fact that in the pom it becomes a "compile" dependency may lead to troubles. The source jar does not get appended to the classpath in the example given (it doesn't belong there anyway). On the other hand, at least in Maven there doesn't seem to be a better option; my Maven-fu is not that great, but the manual says: "There are 6 scopes available: compile, provided, runtime, test, system, import." https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope
There doesn't seem to be a better scope to use, but I'll defer to @eed3si9n and @jsuereth for a final decision. If the current behavior remains in place, I can write a doc patch.

PS: for completeness:

```
---------------
dependency :
  dependency: com.typesafe#config;1.2.1 {compile=[default(compile)]}
artifact   : DA:config.jar(src) ([sources])
artconfigs : sources
configs    : sources
scope      : None
optional   : false
classifier : Some(sources)
type       : None
---------------
dependency :
  dependency: com.typesafe#config;1.2.1 {compile=[default(compile)]}
artifact   : DA:config.jar(jar) ([*])
artconfigs : *
configs    : compile
scope      : Some(compile)
optional   : false
classifier : None
type       : None
---------------
```

**Comment by htmldoug** [comment]
thanks @cunei and @jsuereth!

**Comment by slustbader** [comment]
Any estimate of when we might expect 0.13.9?
