### ISSUE TITLE
Issue with compiler-interface in scripted tests

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2165]
I was creating a scripted test, one that involves compiling some Scala, and I hit this:

``` scala
sbt.InvalidComponent: Couldn't retrieve default sources: module 'compiler-interface'
```

It's probably related to the change in https://github.com/sbt/sbt/pull/2106.

The workaround, for now, is to add (as was done in https://github.com/sbt/sbt/pull/2106 for `dependency-management/mvn-local`):

``` scala
resolvers += Resolver.file("old-local", file(sys.props("user.home") + "/.ivy2/local"))(Resolver.ivyStylePatterns)
```

**Comment by eed3si9n** [comment]
One of the examples that Dale told me is:

```
scripted dependency-management/cache-classifiers
```

This sort of makes sense since isolates the IvyPath:

``` scala
def localCache = 
    ivyPaths := new IvyPaths(baseDirectory.value, Some((baseDirectory in ThisBuild).value / "ivy" / "cache"))
```

The question is:
1. How are the scripted tests on Travis passing?
2. How should we fix it.

For the solution, one option might be to fix scripted so that it does not depend on user's "local" repository. The current implementation is rather fragile as it depends on `-SNAPSHOT` etc.
A better solution might be to publish required artifacts into a separate local file repository, and automatically add that to the scripted's resolver. We can call it something like `publishAltLocal`.
https://github.com/sbt/sbt-remote-control's integration test implements something like that.
The potential downside of this approach is that it would need to isolate the IvyPath for all scripted tests to take advantage of the fresh alt-local, and people may need to re-download common artifacts every time.

A quick and dirty workaround maybe to add

``` scala
  resolvers += Resolver.file("old-local", file(sys.props("user.home") + "/.ivy2/local"))(Resolver.ivyStylePatterns)
```

like you did with mvn-local tests to all scripted tests with IvyPath isolation.
