### ISSUE TITLE
managed resource available only for freshly cleaned project

### ISSUE THREAD

**Issue by yanns** [sbt/sbt#2168]
## steps

There is a test project that generates "test/inline/category.schema.json" for example.

The test project is in GIT as well: https://github.com/sphereio/json-schema-inliner/tree/master/testProject

This generated resource is available with a freshly cleaned project:

```
cd testProject

▶ sbt clean run
[...]
[info] Running Main
url from test/category.schema.json: file:/Users/yannsimon/projects/json-schema/testProject/target/scala-2.10/classes/test/category.schema.json
url from test/inline/category.schema.json: file:/Users/yannsimon/projects/json-schema/testProject/target/scala-2.10/classes/test/inline/category.schema.json
```

Running again...

```
▶ sbt run
[...]
[info] Running Main
url from test/category.schema.json: file:/Users/yannsimon/projects/json-schema/testProject/target/scala-2.10/classes/test/category.schema.json
url from test/inline/category.schema.json: null
```
## problem

When running again, the managed resource disappears from `testProject/target/scala-2.10/classes/test/inline`
## notes

(cross-post with https://stackoverflow.com/questions/25125063/why-doesnt-a-custom-resourcegenerator-get-executed-upon-compile/25180394#25180394)

I created a SBT AutoPlugin that generates resources: https://github.com/sphereio/json-schema-inliner/

(Thx to [Why doesn't a custom resourceGenerator get executed upon compile?](https://stackoverflow.com/questions/25125063/why-doesnt-a-custom-resourcegenerator-get-executed-upon-compile/25180394#25180394), I could fix my first problem.)

**Comment by yanns** [comment]
I'd be ready to help if somebody can give me some pointers where to look at.

**Comment by eed3si9n** [comment]
Sorry about the inaction on this issue. I was able to reproduce the behavior on my machine.

Could you try turning off your caching behavior to make sure that this is not caused by the plugin changing the last modified date?
https://github.com/sphereio/json-schema-inliner/blob/8af91a0edcddd211525ba7fdf0eb4e4c2d011ce0/src/main/scala/io/sphere/JsonSchemaInliner.scala#L16-L31

Could I suggest you use sbt's caching API, which we use internally for sbt and also plugins like sbt-buildinfo https://github.com/sbt/sbt-buildinfo/blob/d953034cad27ff88913572d7e30d4ae524a54e5b/src/main/scala/sbtbuildinfo/BuildInfo.scala#L36-L41:

``` scala
    val cachedCopyFile =
      inputChanged(cacheDir / "sbtbuildinfo-inputs") { (inChanged, input: HashFileInfo) =>
        if (inChanged || !outFile.exists) {
          IO.copyFile(tempFile, outFile, preserveLastModified = true)
        } // if
      }
```

**Comment by yanns** [comment]
@eed3si9n thanks for the feedback with so many details!
You're right, the caching behavior leads to some situations where the plugin has not told sbt which files are generated.
A very quick fix for this: https://github.com/sphereio/json-schema-inliner/commit/eeb490189781e93c8c6eb15b504a158ce425b653

I'll look at sbt's caching API.
