### ISSUE TITLE
When using MavenResolverPlugin SNAPSHOT jars don't update.

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2176]
In https://github.com/sbt/sbt/pull/2163 I found that my scripted test for my Ivy fix for updated SNAPSHOT srcs/docs fails when using `MavenResolverPlugin`.

In debugging I found out that even binary jars don't get updated.

There are a few of conditions to check:
- My test is using `updateClassifiers`, not `update`
- My test involves using a `MavenRespository` with "localIfCopy" disabled (to allow verifying against the contents of the cache, `maven-cache`)
- My test involves using a file repository, which doesn't contain `maven-metadata.xml`.

**Comment by jsuereth** [comment]
I don't think `localIfCopy` is actually used by maven.

Additionally, you'll need to check the TTL of the maven cache itself.   Most likely this is not set to `0` therefore what you're seeing is expected behavior relative to maven.  We'll have to expose a hook (for testing) where you can invalidate the maven cache.
