### ISSUE TITLE
JUnitXMLReportPlugin in JUnitXmlTestsListener.scala is not adding skipped attribute to the testsuite root element

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#2198]
Hi,

JUnitXML document in testsuite root element could contains skipped="numberofskippedtests" so other plugins can read this info (like jenkins) and get how many skipped tests are.

Looking into the (http://www.scala-sbt.org/release/sxr/sbt/JUnitXmlTestsListener.scala.html) this attribute is not being added
 val result = <testsuite hostname={hostname} name={name}
                           tests={tests + ""} errors={errors + ""} failures={failures + ""}
                           time={(duration/1000.0).toString} >

So, could we add this attribute?

**Comment by eed3si9n** [comment]
Sure. Send us a pull request.

**Comment by ashleymercer** [comment]
I'd like to have a go at picking this up since it's currently causing me pain. A couple of questions:

- should I be working against 0.13 or the 1.0 branch?
- the approach taken by Ant is documented on [this bug report](https://bz.apache.org/bugzilla/show_bug.cgi?id=43969) - I need to read more background but it seems there's some incompatibility between XML reports in Junit 3 and 4. Will report back here once I've worked out what's going on, but in the meantime can we assume Junit 4 compatiblity in sbt (and, presumably, downstream tools?)
- an alternative strategy would be to delegate to the specific test library to handle this. Specs2 and scalatest already both have support for outputting Junit XML so it would remove some duplication - although I might need some help getting this to work correctly, and we'd need to decide what to do if a different (non-specs/non-scalatest) framework is being used

**Comment by eed3si9n** [comment]
Generally our preference for new feature is sbt 1.0 especially if it breaks binary compatibility, but give that it's not out yet, if you want to use the feature sooner you'd have to send us a PR first to 0.13, and then forward port it to 1.0.

**Comment by ashleymercer** [comment]
Pull request against 0.13 above, the change is very small so it should be easy for me to forward-port to 1.0

- junit reports don't distinguish between ignored, skipped and pending tests, so we treat all three as "skipped" in the XML report
- I've opted for the minimal change for now - modifying the existing listener, rather than trying to forward to the correct test library if it's present - to avoid breaking anything
