### ISSUE TITLE
Adding private[this] var in a trait does not force recompilation of sub-classes

### ISSUE THREAD

**Issue by luben** [sbt/sbt#2215]
Hi,

I think this is a recent bug in sbt. If you have a trait `Foo` that is extended by a class `Bar` and you add an `private[this] var` to the `Foo` trait it will not force a recompilation of `Bar`. This is a problem if `Bar` is an Akka actor and I guess in other situations that deal with reflectivy serializing/deserializing objects.

**Comment by Duhemm** [comment]
Thanks @luben! Is the problem that you're reporting similar to what this scripted test is testing ? https://github.com/sbt/sbt/blob/1.0.x/sbt/src/sbt-test/source-dependencies/trait-private-var/test

We've recently fixed this bug in the incremental compiler, but it has not been released in any version of sbt yet. Could you check that it is fixed in the development version of sbt, please?

**Comment by luben** [comment]
Sure, I will test it and report back. Looks it is fixing the same issue I have.

**Comment by Duhemm** [comment]
@luben Is your problem fixed?

**Comment by luben** [comment]
yes, sorry for not coming back
