### ISSUE TITLE
Multiline descriptions are not well shown by the tasks command

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#2218]
(edit: rewritten below https://github.com/sbt/sbt/issues/2218#issuecomment-380487282)

---

I normally use multine description for my settings and tasks, for having good documentation.

With `help myTask`, `inspect myTask` the description is shown ok.
But with `settings` or `tasks`, the formatting is bad:

```
> tasks
...
  myTask                      Line 1
Line 2
Line 3
  publish                     Publishes artifacts to a repository.
  publishLocal                Publishes artifacts to the local Ivy repository.
  publishM2                   Publishes artifacts to the local Maven repository.

...
```

I suggest to keep just the 1st line.

**Comment by eed3si9n** [comment]
+1

**Comment by dwijnand** [comment]
## steps

define a new task or setting:

```scala
val myTask = taskKey[String](
  """Line 1
    |Line 2
    |Line 3
  """.stripMargin.trim
)

myTask := "1"
```

## problem

look up the task/setting with `tasks`/`settings`:

```
> tasks -v
...
  myTask                          Line 1
Line 2
Line 3
  package                         Produces the main artifact, such as a binary jar.  This is typically an alias for the task that actually does the packaging.
  packageBin                      Produces a main artifact, such as a binary jar.
```

## expectation

the formatting isn't that bad, perhaps just keep the 1st line.

## notes

sbt version: 1.1.4

keys with multi-line description aren't that common, but this issue is nicely self-contained for any interested first time contributor.

`tasks` and `settings` are commands in sbt and are defined [here](https://github.com/sbt/sbt/blob/v1.1.4/main/src/main/scala/sbt/Main.scala#L280) and [here](https://github.com/sbt/sbt/blob/v1.1.4/main/src/main/scala/sbt/Main.scala#L286), and [taskStrings](https://github.com/sbt/sbt/blob/v1.1.4/main/src/main/scala/sbt/Main.scala#L359-L361) is where the key description is extracted.

one possible solution is to split the string into lines and use only the first one.

I don't think we have any tests for these two commands, so I think the best way to test it is to manually test by [building sbt from source](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md#instruction-to-build-just-sbt). an alternative is the `sbtOn` custom command, but how to use that is not documented.

if you get stuck on this at all, or if I can help you in any way please feel free to ping me ([@dwijnand](https://github.com/dwijnand)) here or in the [sbt/sbt-contrib](https://gitter.im/sbt/sbt-contrib) Gitter room.

**Comment by ninjalama** [comment]
I will try and look at this :)
