### ISSUE TITLE
Can't download Maven plugin

### ISSUE THREAD

**Issue by pauldraper** [sbt/sbt#2242]
I can't use dependencies that are published as Maven plugins. As far as I can tell, they are resolved and downloaded, but not put on the classpath.

I've tried several.

This example is perhaps the most common Maven plugin:

``` scala
libraryDependencies := Seq(
  "org.apache.maven.plugins" % "maven-compiler-plugin" % "3.3" intransitive()
  // intransitive is not required, but this happens to have a lot of dependencies, so it goes faster
)
```

``` sh
$ sbt 'show dependencyClasspath'
[info] List()
```

**Comment by jsuereth** [comment]
Ok, so this appears to be related to the fact that maven doesn't label these artifacts as `jar` packaging, but `<packaging>maven-plugin</packaging>`.   I think we need to update the Ivy configuration so that maven-plugin is treated as a "jar" out of the box, e.g. see: https://github.com/sbt/sbt/blob/3e5449f02d082c1326da7e6319d70d5b26b84bfd/sbt-maven-resolver/src/main/scala/sbt/mavenint/MavenRepositoryResolver.scala#L46

**Comment by pauldraper** [comment]
@jsuereth, is there a current workaround?

**Comment by pauldraper** [comment]
The workaround is

``` scala
classpathTypes in Compile += "maven-plugin"
```

**Comment by eed3si9n** [comment]
Closing this since there's a workaround.
