### ISSUE TITLE
Launch script for Unix not 'link-safe'

### ISSUE THREAD

**Issue by skyluc** [sbt/sbt#227]
In the Launching Sbt/Unix section of the Setup page, the given bash script is not working if a user creates a soft link to it (ln -s).

```
> mkdir link
cat > sbt <<EOF
java -Xmx512M -jar `dirname $0`/sbt-launch.jar "$@"
EOF
> chmod +x sbt
> ln -s ../sbt link/sbt
> cd link
> ./sbt
Unable to access jarfile ./sbt-launch.jar
```

The following script works in this case (and use 'modern' bash notation).

```
java -Xmx512M -jar $(dirname $(readlink -f $0))/sbt-launch.jar "$@"
```

If you agree with the change, I'll be happy to update the wiki page.

**Comment by jsuereth** [comment]
+1 on this.  We also might want to point people to https://github.com/paulp/sbt-extras for the more advanced start script....

**Comment by harrah** [comment]
Should this be the default script?  If so put it on Setup.  If it is unlikely to be used by most people, put it on Setup Notes.  Setup should be kept relatively basic with more advanced forms on Setup Notes.

**Comment by ngocdaothanh** [comment]
Isn't it readlink -n?
readlink -f does not work on Mac OS Lion.

**Comment by indrajitr** [comment]
Actually BSD readlink doesn't have a -f option. That's why Homebrew's script actually patches bash_completion to replace `readlink -f` with `readlink`. This is a case of one of those subtle variations between GNU coreutils (Linux) and BSD utilities (OS X).

+1 on pointing to sbt-extras though.

Further, @jsuereth, how about considering a _native_ sbt (like sbt.exe)? The case is rather weak for such thing on *nix system though.

**Comment by harrah** [comment]
Superseded by sbt-extras and native packager.
