### ISSUE TITLE
Reading from stdin impossible in forked run

### ISSUE THREAD

**Issue by hajdamak** [sbt/sbt#229]
SBT does not allow application that is executed via forked run to read from standard input: System.in.read()
This prevents starting some types of application in that way. Additionally if you start embedded jetty in your app the only way to stop it is to signal it via CTRL-C. But it also stops SBT.

**Comment by ramnivas** [comment]
I just tried with the current development build (git commit hash: 2f52884df8801e69a1914823358ed2059ba61a59) and reading from stdin still doesn't seem to work. Also, Ctrl+C still appears to exit sbt and not just the program being run.

My build.sbt is pretty simple:

```
name := "fork-console-bug"

version := "1.0"

fork in run := true
```

And the Main class is as follows:

```
package bug

object Main extends App {
    val input = readLine("What's your name: ")
    println("Your name is " + input)
}
```

When I do 'sbt run' (or 'sbt' followed by 'run' in sbt shell), the expected "What's your name: " prompt isn't seen. And when I hit Ctrl+C, sbt exits.

**Comment by harrah** [comment]
Neither is enabled by default.  The ctrl+c is disabled by default because it is experimental.  See:

http://groups.google.com/group/simple-build-tool/browse_thread/thread/a2eb9521a19f34fe/3ce7a88dacdf9bd2#3ce7a88dacdf9bd2

To connect the stdin for the sbt process,

``` scala
connectInput in run := true
```

I had issues with flushing the output from the forked process using the built-in scala.Console.readLine.  I'm not sure where the fault is here.  Also, connecting the input is not enabled by default because it has been difficult to get right in the process API.  I'm not sure if I'm doing something wrong or the java Process implementation is problematic here.  You might see a harmless stack trace after 'run' completes.
