### ISSUE TITLE
Add name shadowing in cross-version support for Scala sources

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2310]
Cross-version support for Scala sources, as implemented in #1799 by @indrajitr and released in 0.13.8, works great when there are 2 versions of Scala (say 2.10 and 2.11) but it requires duplication of code when there are more than 2 versions.

For example, if the supported Scala versions are 2.10, 2.11 and 2.12, but the sources for 2.11 and 2.12 are the same but different to 2.10, then you need to duplicate the files for both 2.11 and 2.12.

An example of such duplication can be seen in https://github.com/milessabin/macro-compat/pull/44.

It would be preferable if the sources for 2.11 and 2.12 were defined under `src/main/scala` and the diverging sources for 2.10 defined under `src/main/scala_2.10` would shadow those files (relative path name shadowing).

**Comment by dwijnand** [comment]
In lieu of this feature, a workaround I've used with success is:

``` scala
Seq(Compile, Test).map { sc =>
  (unmanagedSourceDirectories in sc) ++= {
    (unmanagedSourceDirectories in sc).value.map { dir: File =>
      CrossVersion partialVersion scalaVersion.value match {
        case Some((2, y)) if y == 10 => new File(dir.getPath + "_2.10")
        case Some((2, y)) if y >= 11 => new File(dir.getPath + "_2.11+")
      }
    }
  }
}
```

Thus allowing code to exist in `src/main/scala`, `src/main/scala_2.10` and `src/main/scala_2.11+`.

**Comment by DaniRey** [comment]
The shadowing approach is very appealing, but has one limitation (if I understand it correctly). In case someone wants to provide only limited functionality for older (or newer?!) Scala versions, there is nothing to shadow. 

I for example do not provide certain features, which are based on play-json, when using Scala 2.10, because play-json isn't maintained for 2.10. Therefore certain classes only exist in 2.11 and 2.12.

What do you think about a naming convention, which allows to create a source folder for multiple Scala versions?

To cover the same as you currently do with
`src/main/scala`, `src/main/scala_2.10` and `src/main/scala_2.11+`
in your workaround (which I use as well, thank you for providing it), I would suggest
`src/main/scala`, `src/main/scala-2.10` and `src/main/scala-2.11_12`
This approach would allow to create source folders, such as
 `src/main/scala-2.10_12` or  `src/main/scala-2.11_12_13`

**Comment by dwijnand** [comment]
Those directories are defined as settings, in terms of other settings (like scalaVersion, crossScalaVersions, etc). Not in terms of looking at the filesystem ("Oh there's a `src/main/scala-2.11_12`. I'll add that when I'm using Scala 2.11 or 2.12") and I don't think it should.

**Comment by DaniRey** [comment]
I see. I was not aware that sbt shouldn't look at the filesystem. But after looking at the implementation of https://github.com/sbt/sbt/pull/1799, I see what you mean.
I still think that being able to not provide an implementation for certain Scala versions is a central feature of the current approach.
What do you think about adding the following directories for a 2.11 build,
 `src/main/scala`, `src/main/scala_2.11` , `src/main/scala_2.9+`, `src/main/scala_2.10+`, `src/main/scala_2.11+`

I would prefer this over the shadowing approach, because of two reasons: 
 1. Not implementing a certain feature is possible
 1. It is simple to reason about
 
Here is a sketch of how I would adapt the makeCrossSources function
```
def makeCrossSources(scalaSrcDir: File, javaSrcDir: File, sv: String, cross: Boolean): Seq[File] = {
    if (cross)
      val svm = sv.substring(2).toInt
      (9 to svm).map(v => scalaSrcDir.getParentFile / s"${scalaSrcDir.name}-2.$v+") ++
      Seq(scalaSrcDir.getParentFile / s"${scalaSrcDir.name}-$sv", scalaSrcDir, javaSrcDir)
    else
      Seq(scalaSrcDir, javaSrcDir)
  }
```

**Comment by dwijnand** [comment]
If shadowing were available you could shadow with an empty (or marker) file, e.g.:

**src/main/scala-2.10/foo/PlayJsonSupport.scala**
```scala
// This file is intentionally empty as play-json isn't maintained for 2.10,
// so there is no PlayJsonSupport for 2.10.
```

**Comment by DaniRey** [comment]
Understood. Thanks for the clarification.
Then I am ok with any of the two approaches. 

Shadowing: 
 Pro: slimmer projects, highlight the exception, not implementig a feature forces author to explicitly shadow it (good comments in files)
 Contra: a bit complexer to reason about (and implement?), not implementing a complete feature set needs extensive shadowing

Newer then X:
 Pro: easy to reason about, easy to implement a feature only for certain versions, easy to implement
 Contra: code scattered over more directories than with shadowing, bound to versioning scheme of Scala

**Comment by dwijnand** [comment]
@sjrd seems to have done some source file shadowing: https://github.com/scala-js/scala-js/blob/v0.6.14/project/Build.scala#L920

**Comment by sjrd** [comment]
Yup. And for that matter, even our source file shadowing doesn't scale anymore. Now that we have 4 major versions of Scala to support, for a total of 18 released minor versions + 3 master branches, we have to duplicate quite a few files here and there.

I would like to have "range-based" versioning. But even better, I would like to have diff-based overrides: instead of shadowing entire files, specify `patch` files that should be applied to the "main" line of sources in certain versions.

**Comment by dwijnand** [comment]
Virtual files!
