### ISSUE TITLE
Setup automated timestamped releases of sbt modules

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2376]
For sbt's 1.0 modules:
- https://github.com/sbt/incrementalcompiler
- https://github.com/sbt/util
- https://github.com/sbt/io
- and potentially even https://github.com/sbt/launcher

it would be convenient to automate publishing timestamped releases, especially now as we transition from 0.13 to 1.0.

Personally I'd like this to happen by Travis, on every change to their default branch:

``` bash
script:
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" &&
          "${TRAVIS_BRANCH}" == "master" &&
          $(cat version.sbt) =~ "-SNAPSHOT"
    ]]; then
      sbt ++${TRAVIS_SCALA_VERSION} test publish ;
    else
      sbt ++${TRAVIS_SCALA_VERSION} test ;
    fi
```

If that isn't acceptable we can choose Jenkins and/or nightly releases, etc..

**Comment by dwijnand** [comment]
@eed3si9n For reference here how are we publishing nightlies of sbt 0.13.10-SNAPSHOT?

**Comment by eed3si9n** [comment]
There's a Jenkins job hosted by ci.typesafe.com that runs the following command:

``` sh
mkdir -p ~/.sbt/0.13
mkdir -p ~/.bintray/
cp $BINTRAY_CREDENTIAL_FILE ~/.bintray/.credentials

java -version

SBT_OPT="-Xms512M -Xmx3072M -Xss1M -XX:MaxPermSize=192M -XX:ReservedCodeCacheSize=128m"
/usr/bin/sbt release-nightly

git diff --exit-code --color || { echo "[error] git diff is not clean (see above)"; false; }
```

**Comment by dwijnand** [comment]
Thanks

**Comment by eed3si9n** [comment]
#2638 proposed per-commit publishing, but timestamp might make sense since we need to coordinate multiple repositories.

**Comment by Duhemm** [comment]
What are the advantages and drawbacks of the different approaches (timestamp vs commit-sha)? Isn't the sha more explicit about what a publication contains?

**Comment by eed3si9n** [comment]
The advantage of commit-sha is like you said, is more specific, and we can respond to a specific commit, but the question remains for non-sbt module updates like for Zinc and librarymanagement. Do we pick out the latest from each modules? What if we need to update two repos? Perhaps what we need to do is check in Dbuild configuration that would specify wip branches. Let's say we have that, then the question is what should the version number be called for Zinc updates, for example?

Timestamp on the other hand is simpler because we can line them up and pick out the latest, but we would still run into multi-repo update problem, and there's going to be up-to-24h delay.
