### ISSUE TITLE
Sub project compile error

### ISSUE THREAD

**Issue by sorenmat** [sbt/sbt#25]
If i have a project A with a class A, and a project B with a class B that extends A. And i have the following build files, the build fails.

-- A's build file --
import sbt._
import Keys._
import java.io.File

object MyBuild extends Build {
    lazy val projects = Seq(root)
    lazy val root = Project("A", file("."), settings = Defaults.defaultSettings ++ mySettings)

```
def mySettings = {
    Seq(name := "A", version := "1.0",
        unmanagedSourceDirectories in Compile := Seq(new File("src"))
    )
}
```

}

-- B's build file --
import sbt._
import Keys._
import java.io.File

object MyBuild extends Build {
    lazy val projects = Seq(root)
    lazy val a = RootProject(new File("../A"))
    lazy val root = Project("B", file("."), settings = Defaults.defaultSettings ++ mySettings) aggregate (a) dependsOn (a)

```
def mySettings = {
    Seq(name := "B", version := "1.0",
        unmanagedSourceDirectories in Compile ++= Seq(new File("src"))
    )
}
```

}

-- Compile output --
[info] Set current project to B (in build file:/Users/soren/tmp/sbt/B/)
Compiling:
    src/com/schantz/B.java
[error] /Users/soren/tmp/sbt/B/src/com/schantz/B.java:2: cannot find symbol
[error] symbol: class A
[error] public class B extends A {
[error]                        ^
[error] 1 error
[error] Incomplete tasks (run 'last <task>' for the full log):
[error]   {file:/Users/soren/tmp/sbt/A/}A/compile: javac returned nonzero exit code
[error] Total time: 1 s, completed May 24, 2011 8:04:19 AM
macbookpro:B soren$ 

Project A compiles fine when compile is called in that project.

**Comment by harrah** [comment]
You should only use relative files for defining project base directories.  Base directories get resolved against the project's root, but no other files do.  In the above, both projects have the same src directory because it is resolved against the current working directory.  You can verify this with 'show unmanaged-source-directories'.  Always base files on the baseDirectory setting.

Try one of these equivalent variants:

  unmanagedSourceDirectories in Compile <+= baseDirectory / "src"

  unmanagedSourceDirectories in Compile <+= baseDirectory(_  / "src" )

  unmanagedSourceDirectories in Compile <<= 
    (unmanagedSourceDirectories in Compile, baseDirectory) map {
      (dirs, base) => dirs :+ (base  / "src" )
    }
