### ISSUE TITLE
Add support for defining "compileonly" dependencies

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2503]
It would be nice if it were possible to define compile-time only dependencies, for instance by being defined in the "compileonly" configuration and configured a defined in http://stackoverflow.com/a/21516954/463761

**Comment by dwijnand** [comment]
`compile-internal` might already be this. I've seen it mentioned in the context of macros (mutli-project setup).

**Comment by eed3si9n** [comment]
`compile-internal` is used to encode `provided` and `optional`. See the figure on http://www.scala-sbt.org/0.13/docs/Scopes.html#Scoping+by+the+configuration+axis. Unfortunately, because `test-internal` etc. would depend on `optional` and/or `provided` (`runtime-internal` is a bit special), it can't function as compile-only.

**Comment by solarmosaic-kflorence** [comment]
@dwijnand why was this closed? Is it resolved? it seems like it should be more straightforward to do this than having to stumble upon something like https://github.com/typelevel/cats/pull/1889/files

**Comment by AceHack** [comment]
Yes I'm also confused
