### ISSUE TITLE
Multiple classifiers in pom dependency

### ISSUE THREAD

**Issue by aolshevskiy** [sbt/sbt#257]
In case if project depends on a subproject the dependency tag for the subproject is incorrect:

``` xml
<dependency>
    <groupId>com.github.siasia</groupId>
    <artifactId>maven-plugin_2.9.1</artifactId>
    <version>0.11.1-0.1</version>
    <scope>compile</scope>
    <classifier>sources</classifier>
    <classifier>javadoc</classifier>
</dependency>
```

Multiple classifier tags result the duplicate tag error in Maven.

**Comment by retronym** [comment]
I'm using this as a workaround.

``` scala
   pomPostProcess := {
        import xml._
        Rewrite.rewriter {
          case e: Elem if e.label == "classifier" && e.child.mkString == "sources" => NodeSeq.Empty
        }
      }

import xml.transform.{RewriteRule, RuleTransformer}
import xml._

object Rewrite {

  def rewriter(f: PartialFunction[Node, NodeSeq]): RuleTransformer = new RuleTransformer(rule(f))

  def rule(f: PartialFunction[Node, NodeSeq]): RewriteRule = new RewriteRule {
    override def transform(n: Node) = if (f.isDefinedAt(n)) f(n) else n
  }
}
```

**Comment by aolshevskiy** [comment]
Thanks, Jason. Great that I'm not the only one encountering this.

**Comment by sirthias** [comment]
+1, just tripped over this in [spray](http://spray.cc)

**Comment by aolshevskiy** [comment]
Guys, what would be the best solution for that from your point of view.
Should we remove the whole thing or just leave one first classifier?

I could submit a pull request if you tell me :)

2011/11/16 Mathias <
reply@reply.github.com

**Comment by harrah** [comment]
Not sure what the ultimate solution is as I haven't had time to look at it.  I might just revert the original change for now.

**Comment by indrajitr** [comment]
When generating the pom, we don't get to know which of dependencies are libraryDeps and which of them are projectDeps. We need a way to figure that out. If we can, we can take care of the simpler case of honoring libraryDeps which had classifier as part of the definition (the problem #222 tries to solve).

For projectDeps, let's ignore allowing classifier in pom for now (it's a limitation, but I think most of the time we can live with this for now). For libraryDeps, we should just add the first classifier, if available, but ignore the others.

In general, there is a bit of impedance mismatch between Ivy config and Pom config here. In pom, you cannot have an artifact having multiple classifier. It's one classifier or no classifier. The classifier in turn is used to compose the download url of the artifact. So having the right classifier, if there is one, is crucial.

**Comment by harrah** [comment]
I took a better look at it.  The problem is that the original patch looks at all artifacts in all configurations:

https://github.com/harrah/xsbt/blob/0.11/ivy/MakePom.scala#L143

sbt puts the source and doc artifacts in the "sources" and "javadocs" configurations:

https://github.com/harrah/xsbt/blob/0.11/main/Defaults.scala#L374
https://github.com/harrah/xsbt/blob/0.11/ivy/IvyInterface.scala#L431

We can ignore artifacts in those configurations using a method in DependencyDescriptor similar to getAllDependencyArtifacts but that only gets artifacts in the specified configurations (I'd have to look the name up).

@indrajitr Do you want to do this or should I?

**Comment by indrajitr** [comment]
@harrah, Good pointer. Used `type` instead of configuration.

Also, Instead of fiddling with "src" and "doc" types, filtered on "jar" type instead. For all practical purpose, this should serve the usual use cases (excepting, say, ear, war etc. which either aren't supported in SBT or has limited reason to be added as a dependency).

**Comment by harrah** [comment]
Just the "jar" type doesn't quite work because the type might be "bundle", for example.  The valid types are set in classpathTypes.  (It is just "jar" + "bundle" right now, but it keeps it configurable in one spot.)

**Comment by indrajitr** [comment]
Good point. `classpathTypes` can be added to `MakePomConfiguration` and used in `makePom`.

While at that, should we use this for deriving packaging type as well (instead of an isolated use of [IgnoreTypes](https://github.com/harrah/xsbt/blob/0.11/ivy/MakePom.scala#L117))?

**Comment by harrah** [comment]
That ignore types usage is different, though, and I think it is correct as a blacklist.  It is legitimate for a user to say 'war' as the packaging, for example.

**Comment by softprops** [comment]
Damn, I'm glad I'm not the only one. I just ran into this same issue. I should check the list first next time. I ended up carefully publishing one version then changing the dependent version's dependsOn(...) to a library dependency to ensure the jars are pulled

**Comment by indrajitr** [comment]
@softprops Try out the snapshot at your convenience -- hopefully this has been sorted out now.
