### ISSUE TITLE
ClassNotFoundException after renaming class with duplicate name

### ISSUE THREAD

**Issue by waywardmonkeys** [sbt/sbt#260]
This is my own fault, but I'm not sure if sbt could do a better job of dealing with it.
1. I have a file `ATest.scala`. It contains class `ATest`.
2. I  make a copy to `BTest.scala` and make some changes, but _forget_ to rename the class to `BTest`.
3. I run `test`
4. I see that only my new tests run and the old ones do not. I realize that I forgot to rename the class.
5. I rename the class to `BTest` and build and run `test`.
6. I now get an error:

```
[error] Could not run test com.acme.ATest: java.lang.ClassNotFoundException: com.acme.ATest
```

The obvious fix was to just go and touch `ATest.scala` to get around this.

**Comment by harrah** [comment]
Well, I would say this is tough in general.  What ends up happening is sbt thinks two different sources own the same class file.  Unless I'm forgetting something, sbt might be able to detect this specific case and trigger a recompilation that would detect the duplicate names.

The actual error is because when you rename the second ATest to BTest, sbt deletes the class files before recompilation (correctly) and the original ATest is left hanging (incorrectly).  'test' believes 'compile' when it says that ATest exists and is compiled, but 'compile' is obvious lying here.
