### ISSUE TITLE
Maven Version Range Sets in Transitives Do Not Work

### ISSUE THREAD

**Issue by jamesward** [sbt/sbt#2647]
## steps

Specify a dependency which contains a transitive dependency using a Maven Version Range Set, like:

```
libraryDependencies += "org.webjars.npm" % "glob" % "6.0.1"
```
## problem

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.webjars.npm#minimatch;[2,3),[3,4): not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```
## expectation

This works fine in Maven.
## notes

This should work according to: https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html

**Comment by joan38** [comment]
Hi this issue seems to backfire. Basically whenever we use `scalajs-react` we need to add a workaround:
```
dependencyOverrides += "org.webjars.npm" % "js-tokens" % "3.0.2"
```
See: https://github.com/webjars/webjars/issues/1789

I don't know what is the easiest fix but just wanted to add that this sound quiet important at least from the scalajs-react user point of view.

**Comment by eed3si9n** [comment]
Works using sbt 1.3.0-RC3, which uses Coursier internally.
