### ISSUE TITLE
Consider a "no build config found, are you in the right directory?" warning at startup

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#2668]
## problem

When SBT is started in a directory without `*.sbt` or `./project/*.scala`, SBT will soldier on, using defaults and config from the home directory.

The SBT-extras launcher script issues a error in this case, [requiring `-sbt-create` to continue](https://github.com/paulp/sbt-extras/blob/e428bbdb514e1ffe245010b3c4f69e9dfa4bbdb3/sbt#L311). I think this warning is useful enough to move into SBT itself.

A common way people make this mistake is to start SBT in a subdirectory of the project, rather than in the root.
## expectation

SBT's official launcher script, or SBT's startup itself, could issue a warning if no project-specific config was found. This could be augmented with a search of the parent directories to give a "did you mean `cd ../..; sbt`?"
## notes

Inspired by this new user experience https://gitter.im/scala/scala?at=5784992359cfbd4c5e8414a1

**Comment by dwijnand** [comment]
I agree. I also created https://github.com/sbt/sbt/issues/2669 as a related issue.

**Comment by soc** [comment]
Wasn't one of the big talking points of SBT that one could start it with zero configuration and have it work? (Probably even more important in relation to #2669.)

**Comment by dwijnand** [comment]
Was it? I think it's a good feature, but not a blocker for 1.0.0, and should be carefully weighed against this and #2669's use case.

**Comment by eed3si9n** [comment]
> Wasn't one of the big talking points of SBT that one could start it with zero configuration and have it work? 

Yes. When Mark first demo'ed sbt 0.9 I remember him starting up sbt without any configuration and interactively adding settings via `set name := "hello"` and `session save`. When Josh or I give intro to sbt talks, we also do something similar to showcase that you can use sbt in its default state for a while.

Displaying a warning I don't think necessarily conflicts with sbt being functional without any scripts.

**Comment by soc** [comment]
@eed3si9n In #2669 more than a warning is considered.

**Comment by eed3si9n** [comment]
Coming back to this issue since it's part of the sbt 1.0.0 milestone...

In how many ever years I've been using sbt (since sbt 0.7.7) I don't think I've ever started a build by launching sbt with zero configurations, and started typing `set` commands into the shell and used `session save` to save to `build.sbt`. I don't think that use case never took off, and sbt 0.13 introducing multi-project build and auto plugins more or less killed it.

I see the direction proposed by sbt-extras and Jason to be more beneficial to the actual users of sbt.

Here's what I suggest we do:
- If `sbt new` command is called, don't issue warning.
- Otherwise, if no build files are found issue warning. Give the user an option to run `sbt new sbt/hello.g8` or quit.
- When the build starts up, and if there are build files but no `project/build.properties`, display warning that `project/build.properties` is missing and create one.

**Comment by dwijnand** [comment]
Shall we close #754 in favour of this (or vice versa), or is it distinct?

**Comment by eed3si9n** [comment]
I'd say close #754 when the PR is merged.

**Comment by dwijnand** [comment]
I agree to the rest, but for that last step I would prefer prompting the user instead of creating and warning.

Also I don't think this change is breaking, so we could ship it in 0.13 if someone contributed it.

**Comment by dwijnand** [comment]
So even though I've read and commented on this issue a number of times, I apparently did it without ever switching my brain off.

* #754 is about `project/build.properties`, and warning or creating it if it's absent.
* #2668 (this issue) is about warning if no `*.sbt` or `./project/*.scala` files are found

In my opinion, we should resolve #754, and doing so would satisfy the underlying use case here.

**Comment by dwijnand** [comment]
WRT to this issue of sbt 0.13.15 you get startup warning, in sbt 0.13.16 it'll look like this:

![image](https://cloud.githubusercontent.com/assets/344610/25539249/34cee046-2c3e-11e7-8d62-b66baf5ca4bf.png)
