### ISSUE TITLE
test:publish disappeared in 0.13.12

### ISSUE THREAD

**Issue by laughedelic** [sbt/sbt#2696]
## steps

Minimal project:
- `project/build.properties`:
  
  ```
  sbt.version=0.13.12
  ```
- `build.sbt`:
  
  ```
  name := "foo"
  ```
## problem

In the sbt console:

```
> inspect test:publish
[info] No entry for key.
[info] Description:
[info]  Publishes artifacts to a repository.
[info] Delegates:
[info]  {.}/test:publish
[info]  {.}/runtime:publish
[info]  {.}/compile:publish
[info]  {.}/*:publish
[info]  */test:publish
[info]  */runtime:publish
[info]  */compile:publish
[info]  */*:publish
[info] Related:
[info]  *:publish
```

`test:publish` is undefined.
## expectation

If I change sbt version in `project/build.properties` to 0.13.11, I see

```
> inspect test:publish
[info] Task: Unit
[info] Description:
[info]  Publishes artifacts to a repository.
[info] Provided by:
[info]  {file:/Users/laughedelic/dev/foo/}foo/*:publish
[info] Defined at:
[info]  (sbt.Classpaths) Defaults.scala:1097
[info] Delegates:
[info]  test:publish
[info]  runtime:publish
[info]  compile:publish
[info]  *:publish
[info]  {.}/test:publish
[info]  {.}/runtime:publish
[info]  {.}/compile:publish
[info]  {.}/*:publish
[info]  */test:publish
[info]  */runtime:publish
[info]  */compile:publish
[info]  */*:publish
[info] Related:
[info]  *:publish
```
## notes

I don't know if it's supposed to be like that, but I don't see any mentions of this in 0.13.12 release notes and I would like to know how to get `test:publish` task back (with all related settings).

**Comment by eed3si9n** [comment]
This is kind of interesting because 0.13.12 is correct in that there's no such thing as `test:publish`. As you can see it was provided by `*:publish`, so unlike what you might have expected `test:publish` even if it responded would've behaved like a normal `publish`.

I'm not sure which of the changes in https://github.com/sbt/sbt/releases/tag/v0.13.12 (https://github.com/sbt/sbt/compare/v0.13.11...v0.13.12) is causing this, but I don't think it was intentional. #2469 maybe? `test:publish` happened to be behaving more correctly (IMO), but I'm not sure if it could have negative impact on some other places by not delegating `{foo}/*:x` to `{foo}/test:x`.

/cc @Duhemm

**Comment by Duhemm** [comment]
Indeed #2469 unintentionally changed the behavior.

Prior to #2469, sbt considered only the project keys in `scopedKeyFull`, and not the keys defined at the build level. #2469 changed `scopedKeyFull` so that it returns the results for the build level keys and then the project level keys. Swapping the results (project and then build level) solves this issue in particular, but that's probably not the right solution.

My intuition is that the parser for build level keys fails immediately and so the second parser is skipped (in `select`). I'll look into it as soon as I get some more time.

Note that `test:p<tab>` doesn't get autocompleted in sbt 0.13.11.

**Comment by laughedelic** [comment]
OK, I see that `test:publish` wouldn't work the way I wanted anyway (although I think I used it some time agon...). 
So is it possible to define a custom config scope with the `publish` task and choose which artifacts will be published in it?

**Comment by eed3si9n** [comment]
> So is it possible to define a custom config scope with the publish task and choose which artifacts will be published in it?

Everything is just code, so it's probably possible, but not sure how easy/natural it would be.

**Comment by eed3si9n** [comment]
Closing this for now.
