### ISSUE TITLE
Conflict with internal SBT dependencies

### ISSUE THREAD

**Issue by nartamonov** [sbt/sbt#2796]
I wrote SBT plugin which _must_ use Jsch version 0.1.54. So in `project/plugins.sbt` I have:

``` scala
libraryDependencies ++= Seq(
  "com.jcraft" % "jsch" % "0.1.54"
)
```

Since SBT also have internal dependency on Jsch version 0.1.46, plugin _actually_ uses 0.1.46. How can I fix this?

I've tried `dependencyOverrides` but with no luck.

**Comment by hvesalai** [comment]
I'm having the same problem. @nartamonov I think the best thing would be for @harrah to bump the jsch version to be the latest and establish a process of updating it to follow latest version. It's not good that security-related libs are lacking behind.

**Comment by hvesalai** [comment]
See also #403

**Comment by thesamet** [comment]
ScalaPB (via sbt-protoc) suffers from the same problem. [sbt-protc](https://github.com/thesamet/sbt-protoc) depends on protobuf-java (through a package called protoc-bridge). SBT also depends on an old version of protobuf-java. As a result, sbt-protoc/protoc-bridge can't be upgraded to recent versions of protobuf-java due to binary incompatibility.

I could solve it by providing a shaded version of protobuf-java with protoc-bridge and ask authors of code generators to migrate to my shaded version, but that seems like it will cause other problems (due to more things need to be ported to the shaded version)

Are there other options? What is the path forward here?

**Comment by eed3si9n** [comment]
This is probably a won't fix situation, but I did write https://eed3si9n.com/sbt-sidedish/ a while back as a workaround.
