### ISSUE TITLE
Name the dependency that has different Scala version

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#28]
I got the following error with SBT 0.9.9 (without the commit that upgraded the Scala version to 2.9.0-1):

"java.lang.RuntimeException: Different Scala version specified in dependency (2.8.1) than in project (2.9.0-1)"

It would be helpful to know the name of the problematic dependency. :)

Also, in order to get more detail, there's the message:

"Incomplete tasks (run 'last <task>' for the full log)"

When I do "last test:compile", I get no output. Am I doing something wrong or is that also a bug? If so, I can file a separate one.

**Comment by ijuma** [comment]
"When I do "last test:compile", I get no output. Am I doing something wrong or is that also a bug? If so, I can file a separate one."

I filed issue #29 for this. It's because the task with the error is "update" which was invoked by "test:compile".

**Comment by ijuma** [comment]
I could not work out what was causing this, so after changing the sbt code to include information about the module, it turns out that it was my root project. It seems like scala-library 2.8.1 was added to it by default. This seems like a recent change and an unexpected one since my root project is meant to be simply a container to the various subprojects.

**Comment by harrah** [comment]
The fix prints the actual Scala artifact causing the problem.  Normally this would happen when the user explicitly declares a dependency on an org.scala-lang artifact with a different version number than scalaVersion.

Here, the version number being checked against was pulled from too high of a scope (global instead of project), so it was checking against the wrong version number.  That is now fixed also.

It was indeed a recent change that scala-library was added as a dependency automatically.  This was not the problem directly, but it exposed the above issue.

**Comment by ijuma** [comment]
Thanks, I have verified that your fix solves the issue.
