### ISSUE TITLE
SBT console-project Command Fails if Build Specifies Custom Init Commands

### ISSUE THREAD

**Issue by djspiewak** [sbt/sbt#286]
The `console-project` task doesn't work for builds that have specified initial commands for the `console` task (using the `initialCommands in console` incantation in their `build.sbt`).  If those initial commands reference classes defined by the sources within the project (rather than dependencies), those commands will fail.  Note that this breaks ENSIME for all such projects.

**Comment by gseitz** [comment]
The same holds true for `console-quick`.

**Comment by harrah** [comment]
Can't reproduce with `console-project`.

As for `console-quick`, it delegates to `console` for everything except the classpath, where it uses `dependencyClasspath` instead of `fullClasspath`.  So, if you refer to project sources, you would want separate initialCommands configurations:

``` scala
initialCommands in console := "..."

initialCommands in consoleQuick := "..."
```

`consoleProject` isn't related to `console` or `consoleQuick`, however, so it shouldn't be affected by either of their `initialCommands` settings.

See `inspect initial-commands(for console-quick)` and `inspect initial-commands(for console-project)`

**Comment by djspiewak** [comment]
It appears this issue only surfaces if you have used `initialCommands :=` rather than `initialCommands in console :=`.  I would prefer to see SBT warn on something like this, but it's good to find a resolution for this problem.
