### ISSUE TITLE
autoScalaLibrary := false is ignored

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2867]
From https://github.com/xeno-by/eden/commit/e5c1d1a5a8511cc3998099b27c46c5e9edd33e3b#commitcomment-20183004

It would appear that something in sbt 0.13.12 makes sbt "disregards the option `autoScalaLibrary := false`".

Further investigation is required. @liufengyun would you willing to try and provide a minimised reproduction of the issue you saw?

**Comment by liufengyun** [comment]
The set up I've is as follows. It works fine with `0.13.11`, but fails to resolve dependencies under `0.13.13`.

```Scala
lazy val dottyVersion = "0.1.2-SNAPSHOT"

lazy val common = Seq(
  resolvers ++= Seq(
    Resolver.bintrayIvyRepo("scalameta", "maven"),
    Resolver.sonatypeRepo("snapshots")
  )
)

lazy val macrosSetting = Seq(
  scalaVersion := dottyVersion,
  scalaOrganization := "me.fengy",
  scalaBinaryVersion := "2.11",

  autoScalaLibrary := false,

  libraryDependencies ++= Seq(
    "ch.epfl.lamp" % "scala-library_2.11" % "0.1-SNAPSHOT",
    "me.fengy" % "dotty_2.11" % dottyVersion % "scala-tool"
  )
) ++ common


lazy val macros = (project in file(".")).settings(macrosSetting: _*)
```

Steps to reproduce:

1. Put the code above in `build.sbt` in an empty folder `test`
2. Create a file `project/build.properties` under `test` with the following content:
```
sbt.version=0.13.11
```
3. Run `sbt compile` under `test`

**Comment by smarter** [comment]
I think what's actually going on is that `ch.epfl.lamp % dotty_2.11 % 0.1-SNAPSHOT` depends on `org.scala-lang % scala-library % 2.11.5`, but sbt decides to rewrite that dependency to `ch.epfl.lamp % scala-library % 0.1-SNAPSHOT` because of `overrideScalaVersion`, you can workaround it by adding:
```scala
ivyScala ~= (_ map (_ copy (overrideScalaVersion = false)))
```
to your build, this is effectively required for every dotty-compiled project that uses sbt 0.13.13, see https://github.com/sbt/sbt/issues/2896

**Comment by liufengyun** [comment]
Thanks for the tip @smarter 👍
