### ISSUE TITLE
Can I set scalaVersion to latest in build.sbt?

### ISSUE THREAD

**Issue by joeky888** [sbt/sbt#2878]
Can I set something like

`scalaVersion := "latest"`

instead of `scalaVersion := "2.11.8"` in build.sbt?

thanks.

**Comment by eed3si9n** [comment]
The sbt issue tracker is not a support system. Please see [how can I get help?](http://www.scala-sbt.org/community.html#how-can-I-get-help)

### note

Technically speaking it's possible to put dynamic revision as `scalaVersion`, but I would not recommend it since all sorts of things depends on `scalaVersion` being a normal version number.

```
import Dependencies._

lazy val root = (project in file(".")).
  settings(
    inThisBuild(List(
      organization := "com.example",
      scalaVersion := "latest.integration",
      scalaBinaryVersion := "2.12"
    )),
    name := "Hello",
    libraryDependencies += scalaTest % Test
  )
```
