### ISSUE TITLE
To adopt sbt-extras or not

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2889]
One of frequently asked questions is the adoption of sbt-extras, so I'm going to create an issue here.

[Historically (until sbt 0.12.1, October 2012)](https://github.com/harrah/xsbt/wiki/Getting-Started-Setup/aac905288c9d169baffe5892f418a893a860f6e2) sbt did not ship launcher scripts. The installation instruction used to say:

> Create a script to run the jar, by placing this in a file called sbt in your ~/bin directory:
>
>     java -Xmx512M -jar `dirname $0`/sbt-launch.jar "$@"

Pre-2012, we used to hand roll our own launcher script. Given that many of the Scala users used OS X and Linux, this vacuum was filled in by sbt-extras "the rebel cut".

But now that 2016 is almost over, and we have an official bash and batch script maintained by us, I think it's better to recommend the official cut, and when appropriate, include script-level features to documentation as well.

The major reason for sticking with the official script is Windows parity. Some people need Windows support (including Lightbend customers), and we would like to maintain feature parity when possible.

Another reason is control / design decisions. We now recognize launcher scripts to be an integral part of sbt, so the sbt team would need to merge patches when necessary. sbt-extras as I understand it would `curl` launcher JAR per sbt versions. This probably made sense when there was no compatiblity between the launchers. sbt 0.13.x kept the launcher compatibility, and we'd maintain it for sbt 1.0.x as well. To be fair, `curl`ing might still be useful in some situation because we do update `launchconfig`, but it might not be good in a firewalled environment, so there's a tradeoff.

In general though, given Windows parity, I'd be happy to discuss enhancements to the launcher script. See for example https://github.com/sbt/sbt-launcher-package/pull/111.

**Comment by evacchi** [comment]
one thing that people often mention about sbt-extras is that it does not start if the directory does not "appears" to be an actual project. This is IMO is one of those misfeatures of SBT that sounds good when you're writing a "hello world" tutorial, but that tend to bite you otherwise.

Example: you `cd..`, then type `sbt`, `package` and the build completes "succesfully" when it hasn't actually built anything (wrong dir). This has bitten me a few times especially in CI envs.

sbt-extras default behavior is to fail immediately

**Comment by dwijnand** [comment]
@evacchi I agree, and it should be handled by sbt itself (well, the scala launcher part: https://github.com/sbt/launcher).

Tracked in https://github.com/sbt/sbt/issues/2668 and https://github.com/sbt/sbt/issues/754.

**Comment by milessabin** [comment]
FWIW, now that the vanilla launcher supports `.jvmopts` I've stopped using sbt-extras.

**Comment by SethTisue** [comment]
I stopped using sbt-extras aaaaages ago now and haven't missed it.

**Comment by SethTisue** [comment]
as far as I know, this is the only ticket-of-record we have about the status of sbt-extras.

this came up again recently at https://github.com/olafurpg/setup-scala/pull/43 and https://github.com/scala/scala-dev/pull/781, both of which seek to standardize on `sbt` as always referring to the default launch script

this situation has been playing out for years now and there's been a lot of other discussion in a variety of online and offline venues. we haven't really done the work of collecting that discussion in one place. but in short:

it's harmful to the community to have different scripts floating around that are called `sbt` but have different behavior. it's fine for alternate scripts to exist as long as they have unique names so you know what you're getting.

there doesn't seem to be much if any reason for sbt-extras to be the community's de facto default launch script anymore, as it was years ago. regardless, if there are particular aspects of sbt-extras that somebody missed, users remain free to use sbt-extras, and they are also free to submit pull requests that improve the default script

I sort of boiled over about this issue recently after being bitten by https://github.com/dwijnand/sbt-extras/issues/326 for about the 20th time, and also by watching tons of repos be bitten by https://github.com/olafurpg/setup-scala/issues/35

(I hope this goes without saying, but it's absolutely nothing against Paul for creating sbt-extras at a time (a long-ago time) when it was really and truly needed, or against Dale for doing the community a real service of taking over maintenance of it)

**Comment by sideeffffect** [comment]
One nice thing that `sbt-extras` enables is specifying the repo to download the launcher JAR from. (This feature is particularly important for enterprise customers.) It is possible to do it via
 * _command line switch_ (`-sbt-launch-repo`)
 * _configuration file_ (`.sbtxopts`) that contains the commandline switches
 * _environment variable_ (`SBTX_OPTS`) that contains the commandline switches

(I used the `.sbtxopts` way and it worked great for me.)

The official sbt launch script enables this only via _environment variable_ (`SBT_LAUNCH_REPO`). Would the sbt maintainers be open to a PR that enables specifying the launcher repo in a file (that can be versioned in git along with the Scala source code) ?

One way would be to use the switch `-sbt-launch-repo` and have the script read it from `.sbtopts` and also amend sbt proper to ignore the switch (because it doesn't need it anymore) when reading `.sbtopts`.
