### ISSUE TITLE
test:dependencyClasspath ordering question

### ISSUE THREAD

**Issue by clemper** [sbt/sbt#2904]
I have a question regarding the test dependencyClasspath. Apparently if you depend on a subproject using "test->test", the test classpath has the test-classes come before classes for the project, but classes comes before test-classes for all dependent subprojects.  Is this intended behavior, and if so, why?  I cannot find any reference to this behavior in the SBT docs.   This behavior makes it very difficult to share test configuration across projects.  I am using SBT 0.13.12 and Scala 2.11. Thanks.

**Comment by eed3si9n** [comment]
> Is this intended behavior, and if so, why? I cannot find any reference to this behavior in the SBT docs.

I think it's not documented because it's underspecified and whatever you're seeing is the result of the implementation. So in that sense, it's likely working as expected in the sense the there's no expectation at the detail you're describing in terms of test-classes vs classes.

> This behavior makes it very difficult to share test configuration across projects.

You lost me here. Are you redefining classes with the same name across different subprojects? Do you have examples of what you're trying to do?

**Comment by clemper** [comment]
@eed3si9n thanks for your response.  We are using the typesafe Config library, where the resolution of the configuration settings is dependent on the order that reference.conf and/or application.conf are found on the classpath.  That means if we have a common component that is used across a number of subprojects, then we have to copy the test configuration to every subproject.   This is possibly fine for a single case, but it gets unwieldy and difficult to manage with many shared components.   If sbt was consistent with the order of the classpath, then this would be relatively trivial (i.e. it would "just work").  My expectation was definitely that test-classes for a project or subproject should always come before classes based on my experience using Maven.

**Comment by jalaziz** [comment]
We hit this recently.

I thought `test` dependencies would be ordered first in the classpath only to recently find out they're not. We were expecting that to be the case so we can disable things like remote logging and monitoring in our "core" project through config without having to disable them in each and every project that depends on "core".

The current behavior is really confusing because `test-classes` is placed before `classes` in the classpath for the current project being tested. Should that be true for all test dependencies as well?

**Comment by eatkins** [comment]
@jalaziz `test-classes` is not a part of the test dependency classpath but `classes` is. The project classpath, in this case `test-classes` always appears before the dependency classpath. I don't think sbt has ever tried to specify the order of jars in the classpath. My suggestion would be to override `Test / dependencyClasspath` by re-sorting it. For example,
```scala
Test / dependencyClasspath ~= { cp => cp.sortBy(f => f.data.getName ) }
```
would resort the classpath by the file name of each jar or class directory.

**Comment by eed3si9n** [comment]
I don't think we would try to distinguish between Test-configuraiton derived JARs vs Compile-configuration derived JARs. Maybe it's potentially possible, but from sbt's perspective we use whatever the underlying dependency resolver gives us be it Ivy or Coursier.

**Comment by jalaziz** [comment]
To clarify, here's the full classpath:

```
[info] * Attributed(/Users/jalaziz/Development/foo/server/scala-client-api/target/test-classes)
[info] * Attributed(/Users/jalaziz/Development/foo/server/scala-client-api/target/classes)
[info] * Attributed(/Users/jalaziz/Development/foo/server/common/target/classes)
[info] * Attributed(/Users/jalaziz/Development/foo/server/common-server/target/classes)
[info] * Attributed(/Users/jalaziz/Development/foo/server/core/target/classes)
[info] * Attributed(/Users/jalaziz/Development/foo/server/core/target/test-classes)
```

`scala-client-api` depends on `core` with `compile->compile;test->test`. However, notice how `core/target/test-classes` comes _after_ the `core/target/classes`?

@eed3si9n are you saying that it is Coursier or Ivy that determines this order?

> The project classpath, in this case test-classes always appears before the dependency classpath

@eatkins apologies if I used the wrong terminology. The case I'm describing is hopefully illustrated above. The issue is that `test-classes` is ordered after `classes` for projects that the current project depends on. It is ordered correctly for the current project though.

**Comment by jalaziz** [comment]
Just an update, reordering the classpath worked.

Here's what I ended up doing:
```scala
Test / dependencyClasspath ~= fixTestClasspath
```
```scala
protected def fixTestClasspath(cp: Seq[Attributed[File]]): Seq[Attributed[File]] = {
    val testClasspaths = cp.filter(c ⇒ c.data.getName == "test-classes").map(c ⇒ c.data.getParent → c).toMap
    val addedTestClasspaths = mutable.Set.empty[Attributed[File]]
    val reorderedClasspath = mutable.Buffer[Attributed[File]]()
    cp.foreach({
      case c if c.data.getName == "classes" && testClasspaths.get(c.data.getParent).isDefined ⇒
        val testClasspath = testClasspaths(c.data.getParent)
        if (!addedTestClasspaths(testClasspath)) {
          reorderedClasspath += testClasspath
          addedTestClasspaths += testClasspath
        }
        reorderedClasspath += c
      case c if c.data.getName == "test-classes" ⇒
        if (!addedTestClasspaths(c)) {
          reorderedClasspath += c
          addedTestClasspaths += c
        }
      case c ⇒ reorderedClasspath += c
    })

    reorderedClasspath
  }
```

It's a bit more complicated because I wanted to ensure order is preserved except for reordering `test-classes` paths.
