### ISSUE TITLE
Spelling error in API

### ISSUE THREAD

**Issue by waywardmonkeys** [sbt/sbt#293]
This is pretty nitpicky, but I noticed it when fixing a spelling error in our code ...

`descendents` should be `descendants` so, that means that stuff like `descendentsExcept` and associated comments are not spelled correctly.

**Comment by indrajitr** [comment]
Turns out `descendent` is grammatically valid. Although `descendant` has _engulfed_ `descendent` :) At least that's what [Grammarist say](http://www.grammarist.com/usage/descendant-descendent/).

@waywardmonkeys, if you feel strongly about this and @harrah wants (to comply with earthly conventions, if not anything :)), we can deprecate all the `descendent` related methods in favor of the newer ones.

**Comment by waywardmonkeys** [comment]
There's only one actually. :) And one or two sources claim `descendent` is valid, but I think they're just covering their own inadequacies.  Most stuff says it is `descendant` :)

**Comment by harrah** [comment]
My dictionary happens to be one of those sources.  Oh well.  A patch is welcome.
