### ISSUE TITLE
SBT installation in Ubuntu 16.04 use experimental OpenJDK 9 version which fail to download SBT

### ISSUE THREAD

**Issue by guizmaii** [sbt/sbt#2931]
## steps

- Launch a virgin Ubuntu 16.04 machine
- Follow the installation instructions here : http://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Linux.html which are:
```
echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
sudo apt-get update
sudo apt-get install sbt
```

- In a SBT project, run any SBT command. It'll download the SBT version defined in `project/build.properties`. Here the version was 0.13.13

## problem

`sudo apt-get install sbt` will install `openjdk-9-jre-headless` which is an experimental version.
Because of that, the last step described above will fail with something like that:
```
https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/compiler-interface/0.13.8/jars/compiler-interface-bin.jar
[FAILED ] org.scala-sbt#precompiled-2_8_2;0.13.8!compiler-interface-bin.jar: sun.security.validator.ValidatorException: No trusted certificate found (1658ms)
```
(Error example come from here: https://medium.com/@henricook/solution-to-sun-security-validator-validatorexception-e300dd7dba70#.u72cvwdqe)

## expectation

As describe in the blog post mentioned above, `sudo apt-get install sbt` should use `openjdk-8-jre-headless` instead of `openjdk-9-jre-headless`

**Comment by eed3si9n** [comment]
Our `debianPackageDependencies` says:

```scala
    debianPackageDependencies in Debian ++= Seq("java6-runtime-headless", "bash (>= 2.05a-11)"),
```

Intuitively one might think `"java6-runtime-headless"` means JRE6. But it turns out it's actually a virtual package (http://packages.ubuntu.com/hu/xenial/java6-runtime-headless, https://packages.debian.org/sid/java6-runtime-headless).
I am going to change to `openjdk-8-jdk`.

**Comment by dvic** [comment]
Has this one been released? (I'm still experiencing the issue with the docker image `ubuntu:xenial`)

**Comment by Locke** [comment]
> Has this one been released?

It has been with 0.13.15 which is why I discovered this issue / the change.

I'm using Debian and I'm not using OpenJDK, but Oracles Java provided by webupd8team (`oracle-java8-installer`, which provides java8-runtime-headless). As sbt now explicitly depends on `openjdk-8-jdk` I'm forced to install OpenJDK although I already have another java installed.

@eed3si9n Is it possible to relax the dependency to allow other runtimes too? afaik it should be `Depends: openjdk-8-jdk | java8-runtime-headless, bash (>= 3.2)` to install `openjdk-8-jdk` by default and alternatively allow `java8-runtime-headless`. However it seems that `debianPackageDependencies` is a `SettingKey[Seq[String]]` (and `PackageMetaData` having `depends: Seq[String]`) so it can't include lists of alternative package names.

**Comment by eed3si9n** [comment]
@Locke There's a new issue on this https://github.com/sbt/sbt/issues/3105. Please comment there.
