### ISSUE TITLE
SBT dependsOn AutoPlugin

### ISSUE THREAD

**Issue by joan38** [sbt/sbt#2971]
When I do `sbt compile` it doesn't print `Hello`:

```
// build.sbt
enablePlugins(Hello)
```
```
// project/Hello.scala
import sbt._
import sbt.Keys._

object Hello extends AutoPlugin {

  object autoImport extends AnyRef {
    lazy val hello = taskKey[Unit]("Says hello")
  }
  import autoImport._

  override val projectSettings = Seq(
    hello := {
      streams.value.log.info("Hello")
    },
    compile in Compile := (compile in Compile).dependsOn(hello).value
  )
```

See the related question on StackOverflow:
http://stackoverflow.com/questions/41283129/sbt-dependson-autoplugin

Cheers

**Comment by dwijnand** [comment]
Hi @joan38, please note the "How can I get help" topic on the website: http://www.scala-sbt.org/community.html#how-can-I-get-help

The problem is that you're defining `compile in Compile` which then gets over-written by JvmPlugin. To do what you want you need to make your AutoPlugin require the JvmPlugin:

```scala
object Hello extends AutoPlugin {
  override def requires = plugins.JvmPlugin

  // etc
}
```

**Comment by joan38** [comment]
Thanks @dwijnand, it works!
Sorry, I really thought that it was a bug but still posted on StackOverflow without success.

**Comment by dwijnand** [comment]
Can you link to the Stack Overlfow question?

I personally spend more time in the [sbt/sbt](gitter.im/sbt/sbt) gitter room than on the Stack Overflow sbt questions.
