### ISSUE TITLE
Consider releasing sbt 1+ cross-built

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#3009]
.. which means even the plugins are cross-built.

This would mean that when we ship sbt 1.0.0 on Scala 2.12.x, when 2.13 comes out we can:

* release sbt cross-built to 2.13, and
* plugin authors can release cross-built to 2.13

(and again for 2.14, etc)

There are pros and cons to this decision.

@olafurpg has spoken about this. Here's he and @sjrd discussing the topic:

https://www.reddit.com/r/scala/comments/5yvgrw/sbt_01314rc1/deuelyl/

**Comment by eed3si9n** [comment]
Due to (commercial) maintenance, bincompat, I think we should promise *less*, not more - 
https://www.slideshare.net/EugeneYokota/the-state-of-sbt-013-sbt-server-and-sbt-10-scalasphere-ver#31

**Comment by olafurpg** [comment]
To clarify my reddit comments, I would be delighted to get sbt 0.14/1.0 on 2.12 alone (no cross-building). My only wish is to be able to write sbt plugins using a modern Scala version sometime in the near future (~2017).

**Comment by ekrich** [comment]
I think it is perfectly fine to have a set version like sbt 1.0 series, Scala 2.12, Java 8 and if Java 9 doesn't break things then add that support. When Scala 2.13 comes out then have a new sbt series. The current 0.13 series with 2.10 plugins can just slowly go away. If commercial support dictates 0.13 until End Of Life (EOL) then only fix bugs or back port things that make sense. You should support the mainline version, new version, and EOLed version. Doing cross compiling across 2.10 and 2.11 reminds me of C pre-processor stuff where you keep adding code to support different platforms and sometimes versions. To support APIs that differ ends up wasting a ton of time for the benefit of whom? People need to upgrade code and fairly reasonable options of versions and support that lasts long enough is fine. Java made people lazy by being so backward compatible that nobody upgraded but in the end the systems and the businesses lost out by inaction. Finally Java says they will really remove deprecated code. Everyone benefits from progress that improvements and upgrades give.

**Comment by eed3si9n** [comment]
Neither Java nor sbt exist in a vacuum. They both act as harness around culture and ecosystem of libraries, plugins, and tooling. Long term binary compatibility allows both companies and hobbyists to invest time to build plugin on top of sbt. One of the reasons we are having this conversation is because some libraries are no longer available on 2.10. If we keep bifurcating sbt platform, we'll have *more* of these problem not less. Like I can run Play X.Y but not do Scalafmt or vice versa.
We will have sbt 1.0 built against 2.12 in 2017 (and a milestone soon).

Given that preliminary even with sbt 0.13 we were able to add preliminary JDK 9 support, I'm optimistic that sbt 1.0 can evolve together with Scala 2.12.x for a while.

**Comment by jvican** [comment]
This discussion seems settled. Given the roadmap of sbt 1.0 and its imminent release, I suggest to close this issue.
