### ISSUE TITLE
make scmInfo a required field for open source projects

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#3027]
## steps

publish an open source project without scmInfo

## problem

its hard to find the source

## expectation

every open source project must have a scmInfo tag

## notes

scaladex has to keep track of the lost & found: https://github.com/scalacenter/scaladex-contrib/blob/master/claims.json

**Comment by eed3si9n** [comment]
I don't know if a build tool should enforce these kinds of rules. How would I know if something is OSS and if something is even published publicly. If it's mostly for sbt plugins, would it make sense to enforce this at sbt-bintray instead?

**Comment by MasseGuillaume** [comment]
I think the build tool should guide the user. It's true that in this case it's mostly Bintray not enforcing VCS tags. Sonatype does the validation manually.

**Comment by MasseGuillaume** [comment]
`openSource := true`

Should be set by default since the publish task publish source by default.

**Comment by eed3si9n** [comment]
`publishTo` could point to a corporate repository that has nothing to do with open source, which is a licensing matter.

**Comment by MasseGuillaume** [comment]
good point :)

**Comment by dwijnand** [comment]
Given sbt is OSS (BSD 3 clause) I'm happy to make it opinionated that the software it builds is OSS by default. And there would be an obvious way to opt-out of that (`:= None` or `:= false` or similarly simple).

**Comment by eed3si9n** [comment]
Why solve it at this layer if Sonatype already checks for this, and we can tackle it at sbt-bintray?

**Comment by dwijnand** [comment]
I'm thinking perhaps it would be good to fail early, at the core. Instead of the status quo where we fail after having delivered incomplete metadata.

**Comment by eed3si9n** [comment]
Not sure what you mean. If we implemented it, we'd put check on deliver task or something like that, right? How would that be any different in a plugin?

**Comment by cunei** [comment]
As one of my professors used to say, correctness is strictly a function of the specification. One might want to build an scmInfo-less project in order to test whether a certain repository system handles it correctly, for instance, or for all sorts of debugging or development reasons.
If I want to build a project without scmInfo, the build tool must be there to build what I ask for, not to impose rules on me. You may wish to issue a warning, at best, but I disagree the field must be made mandatory. You can always push enforcement to other layers, if you so wish.

**Comment by jvican** [comment]
I think this should not be required, and I would propose to close it. We already have too many open issues in sbt :smile:.

**Comment by eed3si9n** [comment]
closing.

**Comment by MasseGuillaume** [comment]
Why are we closing this issue? It's a real problem and this is backing it https://github.com/scalacenter/scaladex-contrib/blob/master/claims.json

I spent more than 40 hours finding those repo. Can we reopen? Maybe with another name in the description?

**Comment by jvican** [comment]
I'm sorry @MasseGuillaume, I didn't intend to stand in your way. The reason I proposed to close is because the title of the issue suggests to make scmInfo mandatory for all sbt builds which is clearly not possible for the aforementioned reasons.
  
I don't doubt there's a real motivation behind this issue. Perhaps we can open a new issue proposing an alternative solution to it?
