### ISSUE TITLE
`--error` does not suppress new batch mode warning in 0.13.15

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#3091]
```text
% sbt --error compile
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
```

this regresses on #840

**Comment by SethTisue** [comment]
also

```text
% sbt --error
WARN: No sbt.version set in project/build.properties, base directory: /Users/tisue/tmp/unused
```

**Comment by dwijnand** [comment]
The primary reason this is happening is because I'm trying to do it as early as possible, when there is a clear distinction between sbt.xMain, and sbt.ScriptMain or sbt.ConsoleMain - ironically exactly for scripting reasons.

I think I can rework this to appease both use cases, but I wonder: @SethTisue what's the severity in your mind of this regression?

**Comment by jvican** [comment]
Is it possible to disable this warning @dwijnand?
  
For instance, I use sbt for scripting intensively. I think that this warning is good when the user types sbt, but I'd like to remove it when I'm programmatically controlling sbt.

**Comment by dwijnand** [comment]
By invoke sbt in non-interactive (aka batch) mode.

The easiest way is by appending `< /dev/null`, e.g:

```bash
sbt compile < /dev/null
```

Or in **sbt-extras** by passing `-batch`, e.g:

```bash
sbt -batch compile
```

I'm happy to revise the implementation to strike a better balance.

**Comment by jvican** [comment]
Thanks for the pointers.
  
It would be interesting to have something like `--script` in the official sbt. To the best of my understanding, it would have the same behaviour as `-batch` but I think the naming is clearer.

**Comment by dwijnand** [comment]
The concept of "script" already refers to http://www.scala-sbt.org/0.13/docs/Scripts.html (and its sbt.ScriptMain), which is not what you're after when you say "script".. :-/

**Comment by jvican** [comment]
It's a pity that sbt is using that definition of 'script' when the widely used notion of scripting is substantially different (for example, bash scripts).
  
In any case, `--batch` sounds good. Another alternative would be `--one-shot`.

**Comment by dwijnand** [comment]
The nomenclature looks consistent to me: a bash script is a script that bash interprets and an sbt script is a script that sbt interprets (using ScriptMain).

I'd be happy to port `-batch` to the sbt-launcher-package scripts. Note that `--batch` is complicated at the moment due to the history of and migration needed for `--`... https://github.com/sbt/sbt/pull/2741.

**Comment by jvican** [comment]
> The nomenclature looks consistent to me: a bash script is a script that bash interprets and an sbt script is a script that sbt interprets (using ScriptMain).
  
You're right.
  
> I'd be happy to port -batch to the sbt-launcher-package scripts. Note that --batch is complicated at the moment due to the history of and migration needed for --... #2741.
  
I would like to see this supported by default, so 👍 .

**Comment by eed3si9n** [comment]
If we implement the `project/build.properties` warning as one of the commands, we might be able to place it after the early commands.

**Comment by dwijnand** [comment]
Indeed that was my idea. I'm just not sure what priority to give this regression - i.e if it should be worked on now.

**Comment by eed3si9n** [comment]
We can schedule it for next 0.13.x release, but I don't think it's high priority enough to disrupt the current iteration.

**Comment by jastice** [comment]
`sbt new` also triggers the warning

**Comment by sarahgerweck** [comment]
This _really_ shouldn't be a warning: it shows up even in things like `sbt run`. Can we please get a setting that we can put in `build.properties` and in our `~/.sbt` to permanently disable this?

I personally think this was an ill-advised feature. You do this in the docs, not as nagware. I already have a mother, I don't need my build system to scold me—especially if its message is that I'm supposed to change my workflow and keep a JVM around permanently. Tools are supposed to make my life easier, not the other way around.

**Comment by jeffrey-aguilera** [comment]
Agree 100% with @sarahgerweck.  This warning is just plain annoying and not very reliable.

**Comment by eed3si9n** [comment]
Due to JIT (and startup time of sbt itself too I assume), there's a significant difference in compiler performance if you keep the sbt shell around, so I think it warrants displaying a message to let people know that running batch mode is slower. 
See https://twitter.com/eed3si9n/status/837585213563801600

Here are the some changes I suggest:

- The message should be reduced to `[info]` level since it literally is an information, not something that could break correctness.
- Respect the log level.
- It should only be displayed on passing a single `compile` as argument.
- Reduce the message to a single line, for example `[info] Compiling in batch mode is slower than from interactive shell.`
- Provide a globally scoped setting to opt out.

**Comment by koertkuipers** [comment]
i too find this new batch mode warning annoying. not so much the warning itself (i can live with the extra text) but the fact that by accident hitting [ENTER] puts me in interactive mode. this makes batch/scripting usage more difficult as others have mentioned before me.

**Comment by dwijnand** [comment]
@koertkuipers thanks for your feedback. I've opened https://github.com/sbt/sbt/pull/3153 to remove the [ENTER] feature, targeting sbt 0.13.16.
