### ISSUE TITLE
0.13.15 switched to OpenJDK 8, causing problems installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by vincentwoo** [sbt/sbt#3105]
Previously in 0.13.13, the apt repo for sbt enforced the Java requirement of `java6-runtime-headless`. In the 0.13.15 release, the dependency specified is now `openjdk-8-jdk`. There isn't a great story for installing OpenJDK 8 on Ubuntu 14.04: https://askubuntu.com/questions/464755/how-to-install-openjdk-8-on-14-04-lts.

Was this an intentional change? I didn't see it in the notes.

**Comment by eed3si9n** [comment]
Yes. This was an intentional change that we made for sbt 0.13.15.
Since Scala 2.12.x requires JDK 8 and JDK 6 is EOL I figured this was a good time to add to change the launcher (https://github.com/sbt/sbt-launcher-package/pull/139). Interestingly, on the RPM side it caused enough problem to CentOS that we ultimately decided to remove JDK requirements altogether yesterday (https://github.com/sbt/sbt-launcher-package/pull/153).

Maybe for 0.13.x series, we need to roll back to `java6-runtime-headless`.

**Comment by vincentwoo** [comment]
I think removing the JDK requirements altogether is good. My app uses Oracle's Java.

**Comment by Locke** [comment]
> I think removing the JDK requirements altogether is good.

My intuition tells me that the removal of the dependency shouldn't be done (if there is a feasible alternative) as it a) might confuse new users who can't launch their freshly installed sbt as they have to manually install java and b) affects migrating users from 0.13.x to 1.0 who might have an incompatible java version for scala 2.12.x and won't see the conflict right at the installation time.

(There is also c): it violates the Debian Policy Manual to not-specify dependencies, which would make it even harder to ship sbt with Debian, but that's possibly another discussion.)

> Maybe for 0.13.x series, we need to roll back to `java6-runtime-headless`.

As `openjdk-9-jre-headless` provides `java6-runtime-headless` it would be installed in newer Ubuntu releases and we would have #2931 back - the change from `java6-runtime-headless` to `openjdk-8-jdk` was made to avoid the installation of Java 9...

As Debian (and therefore Ubuntu) has the concept of alternative dependencies I suggest to depend on `openjdk-8-jdk` (as recommended option) and alternatively depend on `java6-runtime-headless` (to allow other Java versions / variants, e.g. Oracle's Java or Java 6/7). For the 1.x series it then should be  changed to `java8-runtime-headless` instead of `java6-runtime-headless`.

I didn't try it out, but the new `debianPackageDependencies` should be `Seq("openjdk-8-jdk | java6-runtime-headless", "bash (>= 3.2)")`. (I'm using the | separator directly as sbt-native-packager has no support for Debians alternatives)

**Comment by eed3si9n** [comment]
sbt relies on having a locally installed Java compiler, so it should be a JDK if we depend on anything.

**Comment by toby5box** [comment]
I'm also hit by this change. Previously I was using `openjdk-8-jdk-headless` as JDK, but the .15 deb won't install against it. (I'm starting from the Docker image for `jessie-backports`.)

**Comment by eed3si9n** [comment]
Unless someone can provide me a definitive guide on how to depend on JDK without messing up Trusty etc. I think I'll go with removing the requirements.

**Comment by eed3si9n** [comment]
See also https://github.com/sbt/sbt/issues/2931:

> Intuitively one might think "java6-runtime-headless" means JRE6. But it turns out it's actually a virtual package (http://packages.ubuntu.com/hu/xenial/java6-runtime-headless, https://packages.debian.org/sid/java6-runtime-headless).

**Comment by cchepelov** [comment]
How about simply Recommend'ing that? or maybe a Depends: java8-sdk-headless (which default-jdk-headless provides which in turn pulls in openjdk8 unless some other implementation Provides java8-sdk-headless?)  
    #untested just pulled from APT metadata on a stretch laptop

**Comment by eed3si9n** [comment]
http://packages.ubuntu.com/hu/xenial/java8-sdk-headless lists openjdk-9-jdk-headless.

**Comment by eed3si9n** [comment]
So you either already have your favorite JDK (including that from Oracle) or sbt will pull in something we don't currently support very well.

**Comment by fommil** [comment]
a temporary workaround is to use `sbt-extras`. And use `jenv` to manage java versions.

**Comment by cchepelov** [comment]
ouch, yes, java9 would be pushing it I guess

**Comment by eed3si9n** [comment]
ok. I published 0.13.15.2. Hope this works.
