### ISSUE TITLE
`skip in publish`

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3136]
I propose that we implement a flag named `skip in publish` to mark a subproject as non-publishing.

## steps

```scala
skip in publish := true
```

## expectation

`publish`, `publishLocal`, and `publishSigned` will opt out of publishing action.

## note

This allows me to install sbt-pgp plugin as a global plugin, but still opt out of publishing.

**Comment by olafurpg** [comment]
Note. This would also be useful for sbt plugins that use synthetic projects.

**Comment by dwijnand** [comment]
How is this different to `publishArtifact`?

**Comment by jvican** [comment]
> How is this different to publishArtifact?
  
Same question. I've been using `publishArtifact` quite a lot to denote that something should not be published, and I'm using that to skip the execution of publishing tasks in sbt-release-early.
  
The following [SO thread](http://stackoverflow.com/questions/8786708/how-to-disable-package-and-publish-tasks-for-root-aggregate-module-in-multi-modu/37072580#37072580) mentions a misbehaviour of `publishArtifact`: "while this works it still creates and delivers ivy.xml files (at least when doing a publish-local)". This may be a difference @dwijnand.
  
I think it would be great to make the use of this option standard and suggest avoiding to disable publish tasks via `publish := {}`.
  
However, I'd like to note that I believe `publishArtifact` is not a great name for this. I prefer `skip in publish`, especially because the "skip" setting already exists. If you decide to go this route, I can provide a rewrite for it in the sbt migration rewrites. But this would force us to define what `publishArtifact` means and what we use it for. It's not clear if the misbehaviour I mentioned before is an issue until we define what `publishArtifact` is supposed to do.

**Comment by eed3si9n** [comment]
See http://www.scala-sbt.org/0.13/docs/Artifacts.html for how `publishArtifact` is used.
It's used as a flag along with configuration and task scoping to denote certain artifacts are published.

```scala
// enable publishing the jar produced by `test:package`
publishArtifact in (Test, packageBin) := true

// enable publishing the test API jar
publishArtifact in (Test, packageDoc) := true
```

Changing `publishArtifact := false` at the subproject scoping simply means by default you don't want to publish something, but its power will be nullified the moment there are more scoped setting gets introduced.

That's why today we need to do `publish := (), publishSigned := ()` etc..

```
skip in publish := true
```

would carry a clear semantics that the entire operation of publishing should be skipped.

**Comment by jvican** [comment]
> would carry a clear semantics that the entire operation of publishing should be skipped.
  
I feel that if we go this route, we should have a rewrite to replace:
```
publishArtifact := false
publish := ()
publishSigned := ()
```
 
by `skip in publish := true`.
  
Therefore simplifying the whole machinery necessary to disable publishing in projects.

**Comment by dwijnand** [comment]
> but its power will be nullified the moment there are more scoped setting gets introduced

I don't understand what this means.

**Comment by eed3si9n** [comment]
```
publishArtifact := false,
publishArtifact in (Compile, packageBin) := true
```

then when the publisher looks for `publishArtifact in (Compile, packageBin)`, it'll evaluate to `true` regardless of the subproject-scoped value of `publishArtifact` says.

**Comment by dwijnand** [comment]
That looks fine to me.

We already suffer from "in compile in Compile in COMPILE". I don't think we should add a `skip in publish := true` when we already have a very similar `publishArtifact := false`.

**Comment by jvican** [comment]
If `publishArtifact` should stop any artifact from being published (and the misbehaviour i've mentioned before is indeed a misbehaviour and ivy files should not be created), I believe that we should reuse it to skip publishing.
  
The case where `publishArtifact` gets redefined after all the settings have been applied is a configuration issue that deserves a fix at the root of the problem.
  
However, in my opinion, we should also have `skip in publish` just to be consistent with `skip in update` and `skip in compile`. This would make disabling artifact publication intuitive, and have different ways to do the same thing.

**Comment by eed3si9n** [comment]
Another benefit of `skip in publish` is that it can be introduced into 0.13 safely.

**Comment by dwijnand** [comment]
Also I'd say it's unintuitive that `skip in publish` doesn't just affect `publish` but also `publishLocal`, `publishSigned` etc.

@jvican WRT that ivy files issue I hope to have a chance to merge `publish` and `deliver` into just `publish` - see https://github.com/sbt/sbt/issues/2088#issuecomment-249866091.

**Comment by eed3si9n** [comment]
> If `publishArtifact` should stop any artifact from being published (and the misbehaviour i've mentioned before is indeed a misbehaviour and ivy files should not be created), I believe that we should reuse it to skip publishing.

Using the Ivy / sbt 0.13 semantics of the term _artifact_, `publisArtifact := false` publishing `ivy.xml` I think is by design, not a bug. This is because artifacts are just files associated with modules in Ivy, but `ivy.xml` (called "module descriptor" by [Ivy](http://ant.apache.org/ivy/history/latest-milestone/terminology.html#module)) is considered to be part of the module itself, which can denote dependencies etc.

**Comment by jvican** [comment]
> Also I'd say it's unintuitive that skip in publish doesn't just affect publish but also publishLocal, publishSigned etc.
  
This is true for any task that depends on another task that is a no-op, right? If `publishLocal` wouldn't depend on `publish`, this wouldn't happen. I think this is fine :smile:. In the case of `skip in compile`, if you have a custom task `compileRemotely` that depends on a skipped `compile`, you would expect `compileRemotely` to do nothing.
  
> @jvican WRT that ivy files issue I hope to have a chance to merge publish and deliver into just publish - see #2088 (comment).
  
Looking forward to it.
  
> In the Ivy / sbt 0.13 semantics of the word artifact,
  
Yes, this is why i suggested that we should define `publishArtifact`. To me, this is a good point, but I believe that such small difference in comparison with `skip in publish` should not exist. It's not worth it to keep `publishArtifact` around anymore -- we may consider just deprecating it (and providing a rewrite for it).
  
As a side point, if ivy metadata is considered to be part of the module itself and not a part of `publish`, `skip in publish` should behave in the same way as `publishArtifact` does now. Otherwise, the semantics of `skip in publish` are not "skip only the publish action" but "skip the publish action and all the tasks that depend on it".

**Comment by eed3si9n** [comment]
In Ivy (and in sbt 0.13 by extension), a module consists of descriptor (which denotes dependencies, configurations, and list of artifacts) and artifacts (actual files). `publish` means publish the module, which results to publishing both the descriptor and the artifacts. From the sbt's point of view, if you don't want things published, `publish` should not be called at all.

Since it's convenient to aggregate across subprojects and publish all of them at once, I'm now proposing a skipping mechanism.

In sbt 1.0, I'm open to tweaking these closer to whatever the notion Maven uses or what people might expect a module publishing should look like.

**Comment by eed3si9n** [comment]
Fixed by https://github.com/sbt/sbt/pull/3380

**Comment by benhutchison** [comment]
Just lost 2 hours to "sbt>publishSigned... error .. grrrr" to eventually realise it is this issue! 

Advice on the web is still saying `publishArtifact := false` to disable publishing, but with that setting I was seeing a scala.js crossBuild erroring with `root/*:publishSignedConfiguration) Repository for publishing is not specified`.

Have updated [Stackoverflow advice]()

Mentioning how *not* to publish a project would be appreciated in the core [publishing docs](http://www.scala-sbt.org/1.x/docs/Publishing.html)

**Comment by fommil** [comment]
also just lost 2 hours figuring out why I was getting these exceptions

```
[error] java.io.IOException: destination file exists and overwrite == false
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:75)
```

with no information about **which** file was failing, I might add, despite https://github.com/sbt/sbt/issues/3431 being closed.
