### ISSUE TITLE
Unit tests are not deterministic

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3170]
Unit tests are not deterministic. There are race conditions that make some test cases fail from time to time. For instance, running `;safeUnitTests;otherUnitTests` produced the following spurious error locally:
```
[info] SessionSettings  should
[info] ! Be identical for empty map 
[error]    MessageOnlyException: : [/data/rw/code/scala/sbt/main/target/scala-2.12/test-classes/session-settings/2.sbt.txt]:12: Pattern matching in val statements is not supported  (file:1)
```
  
We should find a solution to this.

**Comment by jvican** [comment]
An example in our CI: https://travis-ci.org/sbt/sbt/jobs/228286717#L2000.

**Comment by eed3si9n** [comment]
@cunei found that parsing was not thread safe (https://github.com/sbt/sbt/pull/3743) since apparently thread-safety can be opted in. We tried to opt-in in https://github.com/sbt/sbt/pull/3776, but we still saw errors, so went back to `synchronized` in https://github.com/sbt/sbt/pull/3802.

I'm hoping that was the main cause of non-deterministic failures, so I am going to close this for now.
