### ISSUE TITLE
HTML markup in pdf

### ISSUE THREAD

**Issue by janekdb** [sbt/sbt#3195]
(See the guidelines for contributing, linked above)

## steps

Read sbt PDF for 0.13.15

## problem

HTML tags are seen

```
<td><tt>clean</tt></td>
<td>Deletes all generated files (in the <tt>target</tt> directory).</td>

```
## expectation

Formatted text instead of tagged text.

**Comment by eed3si9n** [comment]
Hmm.. I'm currently using Pandoc to convert markdown to PDF.

https://daringfireball.net/projects/markdown/syntax says:

> For any markup that is not covered by Markdown’s syntax, you simply use HTML itself. There’s no need to preface it or delimit it to indicate that you’re switching from Markdown to HTML; you just use the tags.

So using HTML is legal in Markdown syntax.

**Comment by lihaoyi** [comment]
It seems the correct thing to do, if you want to use Pandoc to convert Markdown to PDF, would be to avoid using HTML tags and stick to the things that Pandoc's MD-to-PDF supports. For example `-` lists and `**bold**` instead of `<td>`/`<tt>` tags.

Another alternative would be to stop using MD-to-PDF, and instead use MD-to-HTML and Save-as-PDF in Chrome to generate correct PDFs

In the end, Pandoc's MD-to-PDF is just a few bits on disk. Can't blame Pandoc for generating borked PDFs, since in the end it's a human that chooses to use Pandoc and decides whether or not the output is satisfactory 😛

**Comment by eed3si9n** [comment]
Looks like Pandoc has fixed itself. https://www.scala-sbt.org/1.x/docs/sbt-reference.pdf looks ok.
