### ISSUE TITLE
javac warnings are truncated / swallowed

### ISSUE THREAD

**Issue by mpollmeier** [sbt/sbt#3207]
I setup a mini repo that demonstrates this bug: https://github.com/mpollmeier/sbt-swallows-javac-warnings

Here's how you can reproduce it:

```
git clone git@github.com:mpollmeier/sbt-swallows-javac-warnings.git
cd sbt-swallows-javac-warnings
sbt clean compile
...
[info] Compiling 2 Java sources to /home/mp/Projects/sbt-swallows-javac-warnings/target/scala-2.12/classes...
[warn]  annotations.CustomAnnotation
[error] warnings found and -Werror specified
[error] (compile:compileIncremental) javac returned nonzero exit code
```

Problem: it truncates / swallows the javac warning details. Here is the same with javac:

```
javac -cp log4j-core-2.8.jar -Xlint:all -Werror src/main/java/annotations/*.java
...
warning: No processor claimed any of these annotations: annotations.CustomAnnotation
error: warnings found and -Werror specified
1 error
1 warning
```

**Comment by jvican** [comment]
Hey @mpollmeier, I have experienced the same issue with javac, but with errors rather than warnings. In my case, sbt was not showing me any javac errors, only the "javac returned nonzero exit code".
  
I don't know what may be going on here. Which JVM are you using? Ideally this is just a problem of the loggers, but could be a bad handling of java tools from the Zinc side. We need to check if this is still happening in sbt 1.0 (/cc @eed3si9n).

**Comment by jvican** [comment]
I've reproduced this with latest Zinc 1.0. Thank you very much for that github repository. It's a blessing to be able to reproduce these kind of errors.
  
I'll look into it at some point before official sbt 1.0.

**Comment by mpollmeier** [comment]
Thanks for confirming! I'm on `openjdk version "1.8.0_121"`

**Comment by hubertp** [comment]
This bug can be closed, it seems to have been fixed in `zinc` some time ago.

**Comment by mpollmeier** [comment]
Correct, I tested with sbt 1.2.8 and it's fixed.

**Comment by sandip-bhosale** [comment]
`[]() 

`
