### ISSUE TITLE
Logger does not use success

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3213]
## steps
Define inside a task:

```scala
streams.value.log.success("Wrote the classpath for the macro neg test suite.")
```

## problem
Sbt shows:
```
[info] Wrote the classpath for the macro neg test suite.
```

## expectation

```
[success] Wrote the classpath for the macro neg test suite.
```
  
Success should be colored.

**Comment by jvican** [comment]
An even simpler case:
```
[info] Total time: 7 s, completed May 24, 2017 12:12:35 PM
```

**Comment by dwijnand** [comment]
Is this in sbt 1 and would you say it's a regression in behaviour?

**Comment by jvican** [comment]
Yes, I think so.

**Comment by jvican** [comment]
Wasn't this fixed @dwijnand ? A spree attendee is having a look at this.

**Comment by dwijnand** [comment]
No it's not.

**Comment by Krever** [comment]
Based on what I have found out: this happens because `sbt.internal.util.ManagedLogger` is used and it is simply delegating the `success` to `org.apache.logging.log4j.Logger` which does not expose anything like `success`.  

Sadly I don't have enough knowledge to implement the solution. Either some other implementation of `Logger` should be used(instead of `ManagedLogger`) or some other backend then `log4j`.

**Comment by dwijnand** [comment]
I spoke to @eed3si9n about this at some point, and he suggested (IIRC) an implementation based on  using some marker text (I suppose something like a `"[success] "` prefix to the message) to encode that the message is intended to be a "success" message.
