### ISSUE TITLE
Make `cancelable in Global := true` the default?

### ISSUE THREAD

**Issue by smarter** [sbt/sbt#3252]
As far as I can tell, everyone loves this feature, so why not make it the default? The only reason I can think of is that it doesn't seem to work with `compile` (the shell says "Cancelling execution...", but nothing is canceled until the compilation completed, and you're stuck). I see two solutions to that:
1. Make compilation interruptible. There is no fundamental reason that this cannot be done.
2. Make `Ctrl+D` or some other shortcut (`Ctrl+C Ctrl+C` ?) quit sbt at any point, just like `Ctrl+C` does when `cancelable` is false.

**Comment by lihaoyi** [comment]
FWIW, with a bit of work you can make *anything* interruptable, as is done here 

https://github.com/lihaoyi/Ammonite/blob/master/amm/repl/src/main/scala/ammonite/repl/Signaller.scala
https://github.com/lihaoyi/Ammonite/blob/master/amm/repl/src/main/scala/ammonite/repl/Repl.scala#L154-L161

Yes, it uses deprecated `Thread#stop`, which may leave your JVM in a borked state, etc. etc. etc.

However, in practice it only leaves your JVM in a borked state on the rare occasion you manage to interrupt the JVM while in the middle of classloading, which is in practice rare (1% of the time? Less). Any application-level mutable-state should get cleaned up by `finally` blocks; otherwise it would be just as susceptible to being borked by any random NPE or other exception.

Furthermore, when Thread#stop *does* leave the JVM in the borked state, you restart the JVM. This is exactly the same as you would have to do already, *every single time*. So it's a 1% no-difference, 99% strict-improvement.

Ammonite has been using this for 2 years now, and in practice it works really well. Not saying this path is definitely the way forward, but I think it deserves some consideration

**Comment by retronym** [comment]
SBT implements cancellation by shutting down an executor service, which interrupts running threads. Workloads need to periodically check if they are interrupted, and ensure that `InterruptedException` or `java.nio.channels.ClosedByInterruptException` thrown by library code end aren't swallowed, but cancel the workload immediately. I've implemented this for Scalac 2.13.x in scala/scala#6479.

I've also modified SBT to avoid printing a `RejectedExecutionExceptin` stack trace after cancellation (#4058 ), which is another reason to take the "beta" label of cancellation.

I don't think we should call `Thread.stop`.

Before changing the default to true, we should test how forked tests behave. Which process actually receives the signal? If it is the forked process, does it actually have a signal handler to convert this to a thread pool shutdown? If it is the SBT process, should we send a message to the forked test process via the socket protocol to do as much?

**Comment by djspiewak** [comment]
Adding my two cents…

I've had issues with `cancelable in Global := true` specifically in two areas: concurrency frameworks, and unit test frameworks (e.g. specs2).  I haven't tried recently; specs2 may no longer have these issues. Basically what I was seeing was that the `InterruptedException` would get caught by some other exception handling mechanism, which would then convert it into some sort of higher semantic failure.  In the case of specs2, that failure was reflected in a failed test (while the rest of the specification would continue executing). In the case of concurrency frameworks (at the time, scalaz-stream), it was a bit non-deterministic, but often it would hit a failure recovery mechanism in the application I was running, which would in turn just spin itself back up again.

This all resulted in an experience which was practically unusuable, since it made it impossible (short of `kill -9`) to actually stop `test` or `run` tasks in SBT on that project.

**Comment by eed3si9n** [comment]
@djspiewak Were your `test` and `run` forked?

**Comment by djspiewak** [comment]
@eed3si9n I know the `run` was. I'm assuming `test` was as well, but I can't remember. The last time I experimented with this was like, in 2014.

**Comment by eed3si9n** [comment]
Here's how typing Ctrl+C during forked test looks like for ScalaTest:

```
sbt:Hello> test
[info] Compiling 1 Scala source to /private/tmp/foobuild/scala-seed-project/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 1 Scala source to /private/tmp/foobuild/scala-seed-project/target/scala-2.12/test-classes ...
[info] Done compiling.
[info] HelloSpec:
[info] The Hello object
hello
hello
hello
^C
[warn] Canceling execution...
[error] Total time: 8 s, completed Jun 12, 2018 11:10:47 PM
sbt:Hello> Exception in thread "Thread-16" java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2958)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1538)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:818)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:807)
	at java.lang.Thread.run(Thread.java:748)
```

1. https://github.com/sbt/sbt/blob/v1.1.6/main/src/main/scala/sbt/EvaluateTask.scala#L367-L375
2. https://github.com/sbt/sbt/blob/v1.1.6/tasks/src/main/scala/sbt/ConcurrentRestrictions.scala#L131 (calls `shutdownNow` on executor)
3. Inside the forked test task (on local sbt side) https://github.com/sbt/sbt/blob/v1.1.6/main-actions/src/main/scala/sbt/ForkTests.scala, finally clause probably shutsdown the listener socket, hanging up the phone.
4. ForkMain app probably is still running until it tries to talk to the socket, and then shutsdown?

It might be an improvement to hold on to `scala.sys.process.Process` here https://github.com/sbt/sbt/blob/v1.1.6/main-actions/src/main/scala/sbt/ForkTests.scala#L125, and explicitly call `destroy()` on it.

**Comment by toshetah** [comment]
According to this [issue](https://github.com/sbt/sbt/pull/4059), this was fixed in 1.2.0, while this issue has the milestone 1.3.0 .
Which one is the correct one?

**Comment by eed3si9n** [comment]
@toshetah https://github.com/sbt/sbt/pull/4059 did not land. https://github.com/sbt/sbt/pull/4630 is the one that got merged.

**Comment by cbrunnkvist** [comment]
As of Q1 2021, SBT and/or Play are still "broken" out of the box: `(Server started, use Enter to stop and go back to the console...)` is a lie 😉 when you `sbt run` the development server. 

- **Enter** does nothing
- **Ctrl-C** causes two stacktraces, one about "Failed to disable echo", the second from sbt.util.LogExchange.logger ("No Log4j 2 configuration file found"), then exits with _"Application started"_ (eh, you just _exited_, dude come on?)
- **Ctrl-D** (which I think not everybody knows is interpreted as "EOF") actually does result in a proper _"Starting synchronous coordinated shutdown with ServerStoppedReason reason"_

This is probably mostly a Play Framework issue at this point (related to https://github.com/playframework/playframework/issues/10027, https://github.com/playframework/playframework/issues/9043 and possibly more?) but many Google searches seem to lead to this ticket instead, thus I'm linking these issues together here.

**Comment by mkurz** [comment]
@cbrunnkvist https://github.com/playframework/playframework/issues/9043 has just been fixed (by me).

> As of Q1 2021, SBT and/or Play are still "broken" out of the box: `(Server started, use Enter to stop and go back to the console...)` is a lie  when you `sbt run` the development server.

> * **Enter** does nothing

Works for me.

> * **Ctrl-C** causes two stacktraces, one about "Failed to disable echo", the second from sbt.util.LogExchange.logger ("No Log4j 2 configuration file found"), then exits with _"Application started"_ (eh, you just _exited_, dude come on?)

That got fixed by https://github.com/playframework/playframework/issues/9043 and will ship with Play 2.8.8.


> * **Ctrl-D** (which I think not everybody knows is interpreted as "EOF") actually does result in a proper _"Starting synchronous coordinated shutdown with ServerStoppedReason reason"_

Will also work better in Play 2.8.8.

Currently Play does not yet support sbt 1.4.x - support will also come with Play 2.8.8 so stay tuned.

**Comment by cbrunnkvist** [comment]
> Enter does nothing
> Works for me.

@mkurz I believe that it might work when you lauch `run` from in interactive sbt shell, but not when you launch directly with `sbt run` from the command line (note: tested on macOS only).
