### ISSUE TITLE
Reconsider failing `.value` inside lambda expression

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3266]
## steps

```scala
    test in Test := {
      List(1, 2, 3) foreach { x =>
        streams.value.log.info(s"foo $x")
      }
      (test in Test).value
    }
```

## problem

```
build.sbt:17: error: The evaluation of `streams` inside an anonymous function is prohibited.

Problem: Task invocations inside anonymous functions are evaluated independently of whether the anonymous function is invoked or not.

Solution:
  1. Make `streams` evaluation explicit outside of the function body if you don't care about its evaluation.
  2. Use a dynamic task to evaluate `streams` and pass that value as a parameter to an anonymous function.

        streams.value.log.info(s"foo $x")
        ^
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
```

## expectation

The task does exactly what I want it to do. It should work without warnings or error.

## notes

In general, an error (or even a warning) should be displayed when we are 90% certain that the build is doing something against what the user has intended. In this case, I don't think it is.

Ref https://github.com/lucidsoftware/neo-sbt-scalafmt/pull/11, https://github.com/sbt/sbt/pull/3216/commits/ca3acc4e52668c77a1f2dfa0cc247a45936cf7bd

/cc @jvican

**Comment by pauldraper** [comment]
I am perhaps one of the few people that appreciated/preferred the non-macro `<<=` because it was clear what was happening.

```scala
(taskA, taskB, taskB).map { (a, b, c) => ... }
``` 

But macro `:=` is certainly more succient, and I can see why sbt switched.

Now it seems sbt is still using macros, but effectively going back to the previous approach.

```scala
val a = taskA.value
val b = taskB.value
val c = taskC.value
...
```

I understand the reasons, but I don't agree. If I wanted to explicit about evaluation, I'd use `<<=`.

At the minimum, I suggest at least making this optional.

**Comment by jrudolph** [comment]
IMO the whole linter should be removed not only for this particular case but for the others as well. In the default case the macro expansion does the right thing of evaluating the task every time. I guess that's somewhat surprising for new users but it's a consequence of the system (and the same as before with the manual syntax). In the case where you want the dynamic behavior you can still use the `dynamicTask`` workaround.

**Comment by mkurz** [comment]
+1 please fix this

**Comment by eed3si9n** [comment]
Maybe an import statement like language flag thing?

```scala
import sbt.dsl.taskInLambda
```

**Comment by dwijnand** [comment]
Personally I'd want it to disable all linting, not just for lambdas - also if's etc:

```scala
import sbt.dsl.power
```

**Comment by Lymia** [comment]
+1

Please fix this. I just encountered this as I am converting an old plugin of mine from 0.13.x

It clutters build scripts with useless vals if you want to do any kind of abstraction, especially since the closures I have `.value` in are executed unconditionally by the function they are passed to anyway. I thought switching to `.value` over `(a, b, c) map { ... }` was exactly to reduce the kind of clutter this change causes.

It's been a year.
