### ISSUE TITLE
Why sbt can't resolve missing dependencies while maven can?

### ISSUE THREAD

**Issue by s101d1** [sbt/sbt#3311]
sbt version: 0.13.15

I can't resolve some dependencies with this build.sbt:

```
scalaVersion := "2.11.11"

libraryDependencies ++= Seq(
  "org.opentripplanner" % "otp" % "1.1.0"
)
```

It complained about `module not found: com.conveyal#jackson2-geojson;0.8`.

From the repository url on mvnrepository.com:
https://mvnrepository.com/artifact/org.opentripplanner/otp/1.1.0

If you look at the "Compile Dependencies" section, it seems the resolve failed because `com.conveyal » jackson2-geojson (0.8)` library (and some other libraries too) doesn't exist in the repository anymore.

However, with same configuration maven can resolve those missing libraries without issue:

```
    <dependencies>
        <dependency>
            <groupId>org.opentripplanner</groupId>
            <artifactId>otp</artifactId>
            <version>1.1.0</version>
        </dependency>
    </dependencies>
```

Anyone can explain what happened? How could I achieve same thing with sbt?

**Comment by jvican** [comment]
What are your resolvers?
  
Please, run `inspect resolvers` and `show resolvers` inside the sbt shell.

**Comment by s101d1** [comment]
I don't set resolvers at all. Same case with the maven too.

```
> inspect resolvers
[info] Setting: scala.collection.Seq[sbt.Resolver] = List()
[info] Description:
[info]  The user-defined additional resolvers for automatically managed dependencies.
[info] Provided by:
[info]  */*:resolvers
[info] Defined at:
[info]  (sbt.Classpaths) Defaults.scala:1159
[info] Reverse dependencies:
[info]  *:externalResolvers
[info] Delegates:
[info]  *:resolvers
[info]  {.}/*:resolvers
[info]  */*:resolvers
[info] Related:
[info]  */*:resolvers
> show resolvers
[info] *
>
```

**Comment by dwijnand** [comment]
Apparently otp on Maven Central depends on artefacts that aren't on Maven Central, which I thought was something that Sonatype enforced.

sbt is failing because there is nothing at http://repo1.maven.org/maven2/com/conveyal/jackson2-geojson/0.8/jackson2-geojson-0.8.pom

Somehow Maven works because something tells it to fetch it from https://maven.conveyal.com/com/conveyal/jackson2-geojson/0.8/jackson2-geojson-0.8.pom.

I wonder if this is a change in Maven Central that sbt should support, or an error on Sonatype's behalf..

**Comment by damache** [comment]
is the work around for this to install with mvn and not depend on sbt?

**Comment by eed3si9n** [comment]
I am closing this since adding a resolver would work?
