### ISSUE TITLE
stuck at “Getting org.scala-sbt sbt ..."

### ISSUE THREAD

**Issue by zenglian** [sbt/sbt#3423]
Please google "stuck at “Getting org.scala-sbt sbt ..."" to see the problem. This is an old issue. It's widely complained.

Current CDN is fast in US and many other regions but not the case for some other regions...extremely slow or inaccessible at all for them.

I'm not quite sure which CDN is the best, but for me most sites' downloading speed is normal except sbt. Please try some free online tools for testing download speed all over the world.

**Comment by eed3si9n** [comment]
Which version of sbt, package, and OS are we talking about here?
If it's Debian or RPM, it's because the installer hits Maven Central.

**Comment by zenglian** [comment]
The problem is actually with **region** (and maybe ISP), not related to version and OS (thus with all versions and OSes...).   
My region is mainland China.   
I set some local mirror (aliyun) in `repositories` file, but seems it's not respected for some packages.

**Comment by eed3si9n** [comment]
There are many parameters that the version does affect.

### offline installer (0.13.15+)

Because starting sbt 0.13.15 some installers contain all the JAR files in the zip. Then it's just the matter of having the zip file close enough to mainland China.

### Maven Central vs repo.scala-sbt.org

Another major difference between 0.13.x and 1.x is that 0.13.x was serving artifacts that goes through `https://repo.scala-sbt.org` hosted in US East, that probably added a lot of latency.

**Comment by zenglian** [comment]
All I tried is 0.13.x. I did not know there 1.x yet.  On http://www.scala-sbt.org/, the latest it 0.13.16.

**Comment by eed3si9n** [comment]
sbt 1.0.0 is released today 😄 
try it out and see if your situation improves  - http://developer.lightbend.com/blog/2017-08-11-sbt-1-0-0/

**Comment by He-Pin** [comment]
If we are serving the artifacts on maven center,then it would be much faster.

**Comment by He-Pin** [comment]
I mean for mainland China, GFW does that to us.

**Comment by eed3si9n** [comment]
Closing this for now since sbt 1 is served from Maven Central.

**Comment by SunicYosen** [comment]
Why "Getting org.scala-sbt sbt xxx" is needed?
I have installed sbt 1.x.x by 'sudo apt install sbt', with version 1.2.6
Thanks a lot!
