### ISSUE TITLE
sbt-maven-resolver no longer available in 1.0.x

### ISSUE THREAD

**Issue by dpratt** [sbt/sbt#3486]
(See the guidelines for contributing, linked above)

## steps

Add the maven resolver plugin to any project by putting 

```
addMavenResolverPlugin
```

in project/plugins.sbt

## problem

The project can't be loaded due to the fact that org.scala-sbt:sbt-maven-resolver:1.0.0 cannot be resolved.

## notes

I don't know if this plugin is supported in the 1.0.x series, but the settings hook function is still available in the global API. I propose that it should be either removed, or replaced with an implementation that just logs the fact that the plugin is not available/compatible with 1.0.x

sbt version: *insert sbt version*

**Comment by dwijnand** [comment]
sbt-maven-resolver was lifted and shifted to https://github.com/sbt/sbt-maven-resolver, but hasn't gotten any attention (love) since.. much like `addMavenResolverPlugin`..

**Comment by slandelle** [comment]
Then, why not drop it, or make it noop with a warning log? At least mention in the migration guide `addMavenResolverPlugin` doesn't currently work.

It took me a desk head bangings to figure out why I got this "org.scala-sbt#sbt-maven-resolver;1.0.2: not found" error.

Please tell me how I can help.

**Comment by dwijnand** [comment]
It slipped through the cracks.

A straightforward PR that deprecates `addMavenResolverPlugin` and (if possible) prints some kind of warning on use would most probably be merged quickly.

**Comment by slandelle** [comment]
I'm not familiar with sbt sources yet, but I'll give it a try.

**Comment by slandelle** [comment]
@dwijnand I can't manage to print a warning. How do you grab a logger in a Settings (not in a Task)?

**Comment by dwijnand** [comment]
Use `sLog.value` instead.

**Comment by slandelle** [comment]
Thanks!

**Comment by slandelle** [comment]
See #3781

**Comment by jgonian** [comment]
I discovered `addMavenResolverPlugin` and `sbt-maven-resolver` in the SBT documentation while I was trying to overcome multiple integration issues between SBT and Maven during our company's migration to SBT.

For example, this is the only available way to have libraries released truly in Maven style, including updating the `maven-metadata.xml` file that many plugins are depending upon.

When I read the documentation (http://www.scala-sbt.org/1.0/docs/Combined+Pages.html#Maven+resolver+plugin and #1793) I still think that this is a useful plugin and removing it without putting a better integration with Maven in place, feels like a huge step backwards. 
 
@dwijnand, wouldn't it make more sense to port it to SBT 1.0 instead of deprecating it in #3781?

**Comment by slandelle** [comment]
@jgonian @dwijnand Actually, I have just closed #3781. I had lost track but finally realized that without `addMavenResolverPlugin`, I'm indeed unable to properly publish snapshots on Sonatype: artifacts are not properly renamed (should be timestamp instead of snapshot) and metadata are not updated :(

**Comment by jgonian** [comment]
Given that sbt-maven-resolver plugin is internally using Eclipse Aether, which is the same library as Maven itself uses, I'm wondering why SBT doesn't use it by default when users set `publishMavenStyle := true`.

I believe this would reduce the maintenance overhead for both sbt maintainers and sbt users.

**Comment by airlsyn** [comment]
any progress for this ?

**Comment by eed3si9n** [comment]
Bringing Maven resolution into sbt has gotten no priority from sbt core maintainers in the last several years.

In theory it shouldn't be too difficult to resurrect https://github.com/sbt/sbt-maven-resolver/ but community and we have mostly focused their attention on bringing Coursier up to speed. I'm going to close this issue, but feel free to send PR on https://github.com/sbt/sbt-maven-resolver/.

**Comment by airlsyn** [comment]
with some fix (https://github.com/sbt/sbt-maven-resolver/pull/5), sbt-maven-resolver  works again(tested on sbt1.3.8, sbt.1.3.10) @eed3si9n

**Comment by eed3si9n** [comment]
Thanks to @ericxsun sbt-maven-resolver is back again - https://github.com/sbt/sbt-maven-resolver

**Comment by TonioGela** [comment]
The last referenced issue in this discussion was closed without releasing the plugin 👆
