### ISSUE TITLE
scripted should not be enabled by default

### ISSUE THREAD

**Issue by alexarchambault** [sbt/sbt#3514]
## steps

Start from a simple project:
```
$ cat project/build.properties
sbt.version=1.0.1

$ cat project/plugins.sbt
libraryDependencies += "org.scala-sbt" %% "scripted-plugin" % sbtVersion.value

$ cat build.sbt
scalaVersion := "2.11.11"
```

Run:
```
$ sbt update
…
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scala-sbt:scripted-sbt_2.11:1.0.1 ((sbt.ScriptedPlugin.projectSettings) ScriptedPlugin.scala#L39)
[warn] 		  +- default:coursier-sbt-1-0_2.11:0.1-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-sbt#scripted-sbt_2.11;1.0.1: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
…
[error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-sbt#scripted-sbt_2.11;1.0.1: not found
[error] Total time: 7 s, completed 11 sept. 2017 19:10:37
```

## problem

updates don't work if scala version is set to 2.11.x.

## expectation

updates should work, the scripted plugin should not be enabled by default. It should require `enablePlugins(ScriptedPlugin)`

## notes

sbt version: 1.0.1

**Comment by jvican** [comment]
Related https://github.com/sbt/sbt/issues/3538 :smile:.

**Comment by bantonsson** [comment]
The `ScriptedPlugin` now being an _aggressive_ `AutoPlugin` is stopping us from upgrading our build to sbt 1.0.x. Is there a workaround for this? I only need the scripted plugin for 2 out of roughly 100 projects, but now it gets added everywhere.

**Comment by jvican** [comment]
@bantonsson Adding `.disablePlugins(ScriptedPlugin)` to 98 of all your projects would do it! 😄

**Comment by bantonsson** [comment]
@jvican That was the workaround I was afraid of 😉

**Comment by pvlugter** [comment]
👍 for turning off the auto-trigger again

**Comment by bantonsson** [comment]
Could we please get the old behaviour back for sbt 1.1.x?

**Comment by JoeNunnelley** [comment]
I am having this issue with scala 2.11.6 and sbt version 1.1.5  I've updated a plugin from using sbt 0.13.8 to use 1.1.5 (also tried 1.1.2) and resolved all the failing dependencies that unearthed. All expect one. It appears this issue is still alive.  Here is my output from `sbt update`  

```[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-sbt#scripted-plugin;1.1.5: not found```  Is there a resolution to this in the works?

the build.sbt for the projec contains this : 

```sbtPlugin := true$
$
// if you update this list of repos remember to update project/plugins.sbt too.$
libraryDependencies += ("org.scala-sbt" % "scripted-plugin" % sbtVersion.value).$
  exclude("org.scala-sbt", "precompiled-2_8_2").$
  exclude("org.scala-sbt", "precompiled-2_9_2").$
  exclude("org.scala-sbt", "precompiled-2_9_3")$```

**Comment by bantonsson** [comment]
Hi @JoeNunnelley 

The unresolved message you are getting is because the scripted-plugin should now be added with a `%%` for cross compiled like this `libraryDependencies += "org.scala-sbt" %% "scripted-plugin" % sbtVersion.value`. I'm not sure why the scripted plugin is in the `build.sbt` file and not in the `project/plugins.sbt` file, but maybe your `build.sbt` is for a plugin that depends on the scripted plugin?

The other thing that this ticket is about is that the scripted plugin is now an auto plugin and will be automatically added to all projects in a multi project build, so that you need to add `.disablePlugins(ScriptedPlugin)` to all projects that don't use it.

**Comment by BFMarks** [comment]
Thanks @bantonsson !
