### ISSUE TITLE
Time lag before file watch (triggered execution) detects changes on Mac

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3527]
There's been a number of reports on Gitter around this topic. For example:

@fsvehla wrote [Aug 31 03:52](https://gitter.im/sbt/sbt?at=59a7c02781cd9a5d7e9d3e98):

> SBT takes a long time (3, 4 seconds) to notice source code changes changes — with and without changing pollInterval, how can I start to debug this?
I’ve switched to having the sources watched by Guard and type 'testQuick' into the SBT console with tmux, but that’s not a real solution. I’m on macOS in case there are some OS differences with the new NIO watchers
>
> Yes, I’m on 1.0.1

This is a known issue since we don't have native NIO support for macOS. It would be good if someone could write something up that is licensed under Apache v2.

**Comment by eed3si9n** [comment]
Maybe we switch internally to use https://github.com/takari/directory-watcher?

/cc @Duhemm

**Comment by tpolecat** [comment]
Yeah for me it's taking about 10x longer to see file changes. I'm on sbt 1.0.2 and MacOS.

**Comment by jastice** [comment]
intellij-community contains some C code for mac and linux for this purpose which is apache licensed:

https://github.com/JetBrains/intellij-community/tree/master/native/fsNotifier

**Comment by spockz** [comment]
It would be nice if we could get a jar that loads a native solution so that `FileSystem.newWatchService()` returns an optimised one. I'm not sure whether the lib is that pluggable though.

**Comment by AtkinsChang** [comment]
I try to write some in JNI with same interface. 
https://github.com/AtkinsChang/watch-service

Custom `FileSystem.newWatchService()` is pluggable.
Java is able to config default filesystem class with property `java.nio.file.spi.DefaultFileSystemProvider`.
But if you want to extends` MacOSXFileSystem`, the library should be load in bootclasspath with rt.jar. Otherwise you need to write your own `FileSystem`.
http://docs.oracle.com/javase/8/docs/technotes/guides/io/fsp/filesystemprovider.html

**Comment by RatanRSur** [comment]
seeing the same on arch linux, sbt 1.0.0

**Comment by alissapajer** [comment]
Also seeing the same on ubuntu 16.04, sbt 1.0.0.

**Comment by djspiewak** [comment]
With quasar and SBT 1.0.2, it takes about 7 seconds to see file changes in the default configuration, and about 16 seconds to see file changes with `set every sourcesInBase := false` (which is required to avoid constantly hitting #3502).  This is on macOS 10.13 with APFS.

**Comment by gkossakowski** [comment]
Former FB people here at Stripe say good things about watchman. Maybe implementing a client to https://facebook.github.io/watchman/docs/socket-interface.html would be a good idea?

The benefit of watchman is that it's battle-tested on code bases of the size orders of magnitude larger than what sbt users run into.

**Comment by eed3si9n** [comment]
If we go the watchman route, here's a client written in Java - https://github.com/facebook/buck/blob/v2017.09.04.02/src/com/facebook/buck/io/Watchman.java

**Comment by jvican** [comment]
I think @Duhemm already had a look at Watchman (I think I recommended it), but there was some technical reason why he didn't go for it. Maybe he could expand.

**Comment by ScalaWilliam** [comment]
Experiencing this problem too. Forces me to downgrade to 0.13.16 for TDD tasks.

**Comment by eed3si9n** [comment]
Maybe as a short-term solution, it would be good to tune the polling just so we could be on par with 0.13 if possible.

**Comment by mdedetrich** [comment]
@eed3si9n Possibly dumb question, but does this help the situation with MacOsx/Linux https://stackoverflow.com/a/18362404 ?

There is also https://github.com/gjoseph/barbarywatchservice

**Comment by dwijnand** [comment]
Interesting find @mdedetrich, thank you! Given the caveats about private package/JVM-specific we'd have to provide opt-in or opt-out options for users, but I think that's a viable way forward. At least to experiment with.

**Comment by gmethvin** [comment]
We've had this same problem in Play, which has always rolled its own solution to do file watching, instead of using sbt's. In the past we've used JNotify to handle OS X but I've been working on a replacement that is Apache 2 licensed: https://github.com/gmethvin/directory-watcher. This is actually used in Play 2.6.6+ but currently only for sbt 1 users. We've encountered and fixed a few bugs after launching it but overall it seems to be working for most people.

Unfortunately BarbaryWatchService does not have a clear license and it seems like it might depend on some GPL stuff: https://github.com/gjoseph/BarbaryWatchService/issues/6. Since the author of that library isn't confident enough to actually put a license on there, I think it's best to avoid that library entirely.

directory-watcher includes a separate JNA implementation of the WatchService for OS X, which I think may be able to be dropped in as a replacement in sbt, though I haven't tried it. It differs slightly in that it watches the directory recursively by default instead of just direct descendants of the watched directory.

I'm open to ideas and contributions on directory-watcher. I'm also open to the idea of changing the API. I'd like to keep it as a pure Java library, though, since this is an issue that affects everyone on the JVM and don't want to discourage Java users from using or contributing to it.

**Comment by mdedetrich** [comment]
> I'm open to ideas and contributions on directory-watcher. I'm also open to the idea of changing the API. I'd like to keep it as a pure Java library, though, since this is an issue that affects everyone on the JVM and don't want to discourage Java users from using or contributing to it.

I don't think this is realistically possible if you actually want to provide a file watcher service with good performance. It seems like other solutions from other companies (Intellij, Facebook) have custom rolled solutions which are coded in C/C++.

I mean that this is kind of the issue, its deficient in JDK and to do this stuff properly you have to interact with the lower level platform

**Comment by stringbean** [comment]
> I don't think this is realistically possible if you actually want to provide a file watcher service with good performance. It seems like other solutions from other companies (Intellij, Facebook) have custom rolled solutions which are coded in C/C++.
>
> I mean that this is kind of the issue, its deficient in JDK and to do this stuff properly you have to interact with the lower level platform

@gmethvin's library uses JNA to interact with the native filesystem events API so it is 'pure java' but still benefits from native events.

After a quick look at the different solutions this seems a good one to start with.

**Comment by mdedetrich** [comment]
> @gmethvin's library uses JNA to interact with the native filesystem events API so it is 'pure java' but still benefits from native events.

I guess this is nitpicking but its not really pure Java then (pure Java implies no JNA). I mean to interact with C/native events then yo need JNA/JNI

**Comment by gmethvin** [comment]
By pure Java I meant that the entire library is Java code. No scala code, no custom native libraries, etc. JNA is about the closest thing we can get to pure since we need some way to access functionality that's not implemented in the JVM.

**Comment by megri** [comment]
I did some tests using https://github.com/gjoseph/BarbaryWatchService. It's closely modelled after the Java API and feels pretty pluggable. I'll see if I can make a sbt-plugin POC

**Comment by megri** [comment]
If you want, feel free to experiment with/copy this plugin: https://github.com/megri/macos-watcher

**Comment by AtkinsChang** [comment]
I suggest to use JNI version that you don't need to have a fat JNA jar in dependency.
And the https://github.com/gjoseph/BarbaryWatchService use one watch per thread.
The macOS api support event callback(event multiplexing) that you need not to create a jvm thread waiting for it per watch.

**Comment by gmethvin** [comment]
If you want JNI you can use [JNotify](http://jnotify.sourceforge.net/). The downside is that you have to make the native library available to sbt somehow, so you have to do something like this: https://github.com/playframework/play-file-watch/blob/1.1.5/src/main/scala/play/dev/filewatch/JNotifyFileWatchService.scala#L84. The other downside is it's LGPL, which is probably fine for most people but might be a concern in some enterprise environments.

**Comment by eed3si9n** [comment]
Hopefully this is fixed in #4071 / [sbt/io#138](https://github.com/sbt/io/pull/138) as we adopted @eatkins's MacOSXWatchService from [CloseWatch][closewatch]. Credit also goes to @gmethvin and Takari's directory-watcher implementations.
This will be released in 1.1.3.

  [closewatch]: https://github.com/swoval/swoval/tree/master/plugin
