### ISSUE TITLE
Add scripted as library dependency for builds of sbt plugins

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3538]
## problem
Sbt plugins have only one way of being tested: scripted. Scripted is used by almost any sbt plugin in the world. Yet, every sbt plugin has to bring the scripted plugin dependency manually.
  
Shortcomings:
1. Users need to get the scripted library from the docs every time they create a new plugin:
`libraryDependencies += { "org.scala-sbt" % "scripted-plugin" % sbtVersion.value }`.
2. Users need to reload their build once the dependency has been added.

## expectation
It would be nice if `scripted` is added automatically for those builds for which `sbtPlugin := true`. I'm proposing to internalize the scripted plugin inside the sbt repo in a similar way `IvyPlugin` and others are.
  
My goal with this is to make it easier for devs to define sbt plugins. Those builds that already specify the scripted library dependency will use the specified plugin instead of the "internalized" one.
  
I cannot think of any reason why this hasn't been done before, but I believe it's a good moment to do it.

**Comment by eed3si9n** [comment]
This is an interesting idea.
To do this we might need to define `SbtPlugin` plugin that will pull in both scripted and `sbtPlugin := true`.

**Comment by dwijnand** [comment]
I'm for this idea, btw.

**Comment by dwijnand** [comment]
If we make changes to scripted we should keep https://github.com/sbt/sbt/issues/3514 in mind too.

**Comment by eed3si9n** [comment]
Note we'd essentially duplicate scripted plugin inside the SbtPlugin plugin, because we can't dynamically add dependencies to metabuild.

**Comment by jvican** [comment]
I was thinking of porting my improvements from the scripted sbt suite to the scripted plugin (to get batch and parallel execution). If you say that this requires us to port the scripted plugin inside the `SbtPlugin` plugin, I can do both changes at once.
  
If you like this approach, let me know and I'll open a PR.

**Comment by sjrd** [comment]
> Sbt plugins have only one way of being tested: scripted.

This is simply not true. I have a totally different way of testing sbt plugins, which results in much faster turnarounds, because it does not need to reload a new sbt instance for every single test. The idea is to have the build include the sources of the sbt plugin it defines, and have projects in the build itself that test the sbt plugin.

See for example how it's done in sbt-dynscalajs:
* [Source in the sbt plugin into the build](https://github.com/sjrd/sbt-dynscalajs/blob/b61fd2d3704faa29b3440729a58ae3044ed84a50/project/build.sbt#L15-L16)
* [Define a test project using the plugin right inside the build](https://github.com/sjrd/sbt-dynscalajs/blob/b61fd2d3704faa29b3440729a58ae3044ed84a50/build.sbt#L58-L65)

Please don't add non-essential dependencies to sbt plugins.

Also, who knows, maybe one day someone will come up with another way to test sbt plugins, which would compete with scripted. In that case, the extra dependency would be even more annoying. Consider that automatically depending on scripted is similar to automatically depending on ScalaTest for regular Scala projects. No one wants that.

**Comment by eed3si9n** [comment]
@sjrd I implemented https://github.com/sbt/sbt/pull/3875 as an AutoPlugin that enables both scripted and `sbtPlugin := true`. I'd advertise that as a way for creating plugins once it's released, but it won't necessarily add dependency to plugins.
