### ISSUE TITLE
Investigate scripted tests/fork-parallel 

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3545]
```
[error] x tests / fork-parallel 
[error]  Cause of test exception: {line 2}  Command succeeded but failure was expected
```

**Comment by cunei** [comment]
@dwijnand, can you please point me to a failed test? I am trying to reproduce, but all seems to work for me with current 1.1.x head.

**Comment by cunei** [comment]
is it possible that you have seen https://github.com/sbt/sbt/pull/3802 ?

**Comment by dwijnand** [comment]
@eed3si9n mentioned failures at https://github.com/sbt/sbt/pull/3816#discussion_r157337712.

Yes I saw #3802.

**Comment by cunei** [comment]
OK, I found this travis run:
https://travis-ci.org/sbt/sbt/jobs/317262269
In its log there is a failed `tests/fork-parallel`. The log refers to sbt's commit 4cae6895. The commit log is here:
https://github.com/sbt/sbt/commits/4cae6895680000bacc6aeab0cc8990a5148d5338
The list of commits includes the fix in #3802, meaning that `templateStats()` is synchronized. So, there is definitely still an issue lingering somewhere. However, I spent quite a bit of time trying to get the failure on my machine, with no luck. To make things more complicated the commit above is an unreferenced commit in GitHub, meaning that it is not attached to any branch or tag; probably a `push -f` left it dangling. It turns out that there is no simple way to fetch or to reconnect a dangling commit left in GitHub, so it's difficult to fetch the same commit locally. Related commits, locally, show success for `tests/fork-parallel`.
What I am trying now is using the GitHub API to create, via REST calls, a new remote branch attached to the dangling commit inside GitHub; that seems to be the only way to retrieve the commit, so that I can test it again using Travis. WIP.

**Comment by eed3si9n** [comment]
What I originally had was the content of #3789 + https://github.com/sbt/sbt/pull/3816/commits/40b86ae41265c49e6e52fa2ac043413be82bd0cc, which failed the `tests/fork-parallel` test.

**Comment by cunei** [comment]
I retrieved the branch, and restarted Travis: it failed at the very same spot again:
https://travis-ci.org/sbt/sbt/jobs/319252979
Yet, it works on my machine.

**Comment by cunei** [comment]
Gotcha! The Travis test uses a VM that has less than four cores. The `tests/fork-parallel`, because of how it is written, will always report success when run on less than four cores, rather than failing in one of the two cases as expected. To reproduce, pretending that only two cores are available:
```
taskset 0x00000003 sbt 'scripted tests/fork-parallel'
```
So it's really just the test that needs fixing @eed3si9n, @dwijnand

**Comment by eed3si9n** [comment]
nice. I am ok with keeping the text commented out with your explanation in the comment then.
