### ISSUE TITLE
vim :quit

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3599]
## steps

1. `:q` or `:quit`

## expectation

It should exit sbt, like we already can in Scala REPL and editors.

## notes

`:q` is not a valid command in sbt 1.1 or 0.13, so there should be no ambiguity.

**Comment by eed3si9n** [comment]
Duplicate of #1374

**Comment by eed3si9n** [comment]
This is a concern:

> @ekrich Not only would I buy and wear a `:q` t-shirt, I'd sell them to my vimmer friends. RIght now I'm wearing boxer briefs with I `:quit` stitched in the elastic. On a serious note, REPL is undergoing a revamp for 2.13, and one idea could be to discard the colon syntax in favor of ordinary invocations. I'd be in favor of colon syntax for an ed editor backed by a language server, however.

**Comment by nafg** [comment]
Personally I don't get the point. The REPL needs `:` to escape commands from being interpreted. SBT doesn't. (The REPL _could_ do what ammonite does and have scala functions imported that interact with the REPL itself, but it doesn't.)

Are we going to advocate that bash also support `:q`?

**Comment by eed3si9n** [comment]
I think it would be nice to have a common command to quit between REPL and sbt shell. There used to be `exit`, but that no longer works on Scala. It may not be the most common things people type in, but eventually everyone needs to quit out.

**Comment by dwijnand** [comment]
Ctrl-D is the common way, and it'll even work for you to quit bash.

An alternative is `initialCommands += "import scala.sys.exit"`, then you can use `exit` in both the shell and the REPL.

I don't think we should add more ways to achieve the same thing.

**Comment by ekrich** [comment]
I look at this from an outsider experience. Not everyone has the same level of experience and anything to make the entry to Scala and sbt easier and make the tools more uniform I think is helpful. Also, since they are considering changes to the REPL in 2.13 then it would be nice to keep this in mind. With sbt you can create aliases which means you can do the following.
```
alias c = compile
alias :c = compile (won't work)
alias exit = compile (does nothing but silent)
alias q = exit (q now exits sbt)
```
So I guess `exit` has some exalted status like Unix exit command or exit in shell but then history is retrieved  different than in shell so I'm not really sure of the design decisions.

The Java REPL too uses `:help` for help and `:hist` for history and `:quit` to quit.
http://www.javarepl.com/term.html

Haskell REPL also uses `:help` and `:quit`. They also allow you to set an editor and `:edit` which might be nice for those VIM users that need `:q` t-shirts.

Python REPL uses `help()` which brings you to a `help>` prompt.

I'm sure there could be some room for improvement one way or the other.

**Comment by dwijnand** [comment]
we should close this.

**Comment by eed3si9n** [comment]
I will try to make this a plugin first then.

**Comment by dwijnand** [comment]
note: https://github.com/sbt/sbt/pull/1991#issuecomment-97140366

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-vimquit

**Comment by ekrich** [comment]
@eed3si9n I don't know what to say other than you can make a `sbt` plugin for anything if you know what you are doing.

**Comment by ktoso** [comment]
That'd be lovely, I even have :q and :wq set up in my shell for convenience rather than "exit" :)

**Comment by FDiskas** [comment]
So strange :D

![image](https://user-images.githubusercontent.com/468006/98389812-3cdb8980-205d-11eb-9b75-7f7000ce7c29.png)
