### ISSUE TITLE
[vs-code_scala-sbt-plugin] Not such file or directory : active json

### ISSUE THREAD

**Issue by wilmer-daza** [sbt/sbt#3624]
(See the guidelines for contributing, linked above)

## steps
1. Install the scala sbt extension for VS CODE
2. Open the vs code editor

## problem
1. Here you have the problem:

```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/wilmer/Projects-git/poc-colis360/project/target/active.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at discoverUrl (/home/wilmer/.vscode/extensions/lightbend.vscode-sbt-scala-0.0.2/server/server.js:24:34)
    at Object.<anonymous> (/home/wilmer/.vscode/extensions/lightbend.vscode-sbt-scala-0.0.2/server/server.js:6:9)
    at Object.<anonymous> (/home/wilmer/.vscode/extensions/lightbend.vscode-sbt-scala-0.0.2/server/server.js:28:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
[Info  - 3:04:55 PM] Connection to server got closed. Server will restart.
```

## notes

sbt version: *insert sbt version*

**Comment by eed3si9n** [comment]
Which version are you using? LSP is only available in sbt 1.1.0-M1.

**Comment by wilmer-daza** [comment]
You mean the sbt version within my project/build.properties or the sbt version within my environment?

**Comment by dwijnand** [comment]
The sbt version in project/build.properties.

**Comment by wilmer-daza** [comment]
I just changed my sbt version to 1.1.0-M1 and still I got the same error (off course I did execute "sbt compile" on my project)


Error: ENOENT: no such file or directory, open '/home/wilmer/test/scala-test/project/target/active.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at discoverUrl (/home/wilmer/.vscode/extensions/lightbend.vscode-sbt-scala-0.0.2/server/server.js:24:34)
    at Object.<anonymous> (/home/wilmer/.vscode/extensions/lightbend.vscode-sbt-scala-0.0.2/server/server.js:6:9)
    at Object.<anonymous> (/home/wilmer/.vscode/extensions/lightbend.vscode-sbt-scala-0.0.2/server/server.js:28:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
[Info  - 2:57:00 PM] Connection to server got closed. Server will restart.
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

**Comment by wilmer-daza** [comment]
Sorry guys, I now understand what happened. That "activate.json" is created at the execution of sbt, if I stop the sbt console then this file is destroyed, that means that, if I want my sbt plugin to work I should execute sbt on my project, that's completely inconvenient and not practical at all. I also tried to look for and option to be disabled within the conf (so that It will not try to start and/or connect to the server) but I didn't find anything.

**Comment by laughedelic** [comment]
@wilmer-daza yes, this whole sbt server interaction is experimental for now, so you have to launch the sbt server manually. See https://github.com/sbt/sbt/issues/3508#issuecomment-331877593.

**Comment by corazza** [comment]
Any news on this issue? It's really annoying that I always have to set up a manual sbt instance to run before launching VS Code

**Comment by cornytrace** [comment]
@corazza Agreed

**Comment by eed3si9n** [comment]
Launching a sbt instance can't be too difficult, but at that point you won't be able to interact with it via the terminal. Do you folks not need to interact with sbt shell when you code using VS Code?

**Comment by laughedelic** [comment]
> Launching a sbt instance can't be too difficult, but at that point you won't be able to interact with it via the terminal.

Why? When I launch sbt and connect to the server, I still can use the shell. It gets spammed with some extra logging, but it still works as a shell.

> Do you folks not need to interact with sbt shell when you code using VS Code?

I think what most people want from this integration is just to get the compilation errors in the editor. Using sbt shell (for other things) is kind of orthogonal to it. Also, if I get it right, the idea of auto-launching server implies that it's irrelevant who launched it first (user or editor) because then any other client will connect to an already running server. Is this understanding correct?

**Comment by eed3si9n** [comment]
> > Launching a sbt instance can't be too difficult, but at that point you won't be able to interact with it via the terminal.
>
> Why? When I launch sbt and connect to the server, I still can use the shell. It gets spammed with some extra logging, but it still works as a shell.

You can interact with the server-running sbt because we run it from a terminal like Zsh and Bash, so I wrote that if you just start the server process there's no stdin/io associated with it. But, come to think of it, VS Code does come with a terminal emulator so that might be an option someone could pursue.

> Also, if I get it right, the idea of auto-launching server implies that it's irrelevant who launched it first (user or editor) because then any other client will connect to an already running server. Is this understanding correct?

Ideally, we can attach any client to the server and it would work like you just launched `sbt`. I wish we were there, but there are a bunch of commands that is not virtualized like `run` and `console`. They will require you to interact directly with the original sbt process for now.
But this is not all-or-nothing either. We could start with beta client that does half of the stuff, and it could still be useful.

**Comment by laughedelic** [comment]
> But this is not all-or-nothing either. We could start with beta client that does half of the stuff, and it could still be useful.

Totally agree.
