### ISSUE TITLE
projectSettings in build.sbt

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#3716]
Currently the only way to correctly define a setting that applies to all projects is to use an `AutoPlugin` and place it in the `projectSettings`.

However, most developers use the (broken) approach of defining a `val commonSettings` in their `build.sbt` and manually applying it to all project. Unfortunately a) they inevitably forget one project b) they almost always forget about the root project.

It would be useful to be able to have a construct with semantics similar to `inThisBuild`, e.g. `inEachProject`.

**Comment by eed3si9n** [comment]
At first I was a bit concerned about adding another DSL, but after giving it a bit more thought this might be more useful than `inThisBuild(...)` or trying to fix the scoping rules around it.
As a replacement of `commonSettings` pattern, I'd imagine the ordering of `inEachProject(...)`-derived settings to be placed after all the autoplugin-based settings, and before `.settings(...)`.
The ordering starts to matter when you rewire an existing key:

```scala
lazy val root = (project in file("."))
  .inEachProject(
    test in Test := { println("done") }
  )
```

**Comment by dwijnand** [comment]
We should stop adding more and more hacks (and then documenting them, and answering questions about them, and otherwise teaching people about their existence and drawbacks) to avoid the fundamental scoping issue and actually fix the scoping issue.

It shouldn't be necessary for every single project to have the same collection of settings defined for it, it also slows down loading (and reloading, or tweaking session settings with `set`) as well as wasting memory.

**Comment by fommil** [comment]
That sounds like an sbt 2.0 fix, what about sbt 1.0?

**Comment by dwijnand** [comment]
For sbt 1 you can choose which workaround you prefer. Remember to add `commonSettings`, define a helper method that creates the `Project` value and adds `commonSettings`, or use a local AutoPlugin's `projectSettings`. Oh and trial-and-error your way to defining some of the settings `in ThisBuild` scope instead of project scope.

**Comment by fommil** [comment]
I personally use `projectSettings` in an autoplugin, but I feel that leaving the confines of the `build.sbt` is beyond the vast majority of typical scala developers.
