### ISSUE TITLE
sbt/exec should send respond to request

### ISSUE THREAD

**Issue by olafurpg** [sbt/sbt#3863]
## steps
Send `sbt/exec` command following the steps described in https://developer.lightbend.com/blog/2017-11-30-sbt-1-1-0-RC1-sbt-server/?final?final 

## problem

The sbt server never responds to request number 2.
```
Content-Length: 93^M
^M
{ "jsonrpc": "2.0", "id": 2, "method": "sbt/exec", "params": { "commandLine": "compile" } }^M

```
According to the json rpc specification, every request should have a response. By not responding the request, the client will keep an open request hanging forever.

## expectation

On command success, I expected to receive some response once the command completes execution
```
{ "jsonrpc": "2.0", "id": 2, "result": null }
```
On command failure, I expected an error object with a "Server error" code. Sbt should maybe define the categories of errors it can respond with and document which codes it returns with their meanings.

## notes

sbt version: 1.1.0

**Comment by BastienClement** [comment]
I'm trying to use sbt server as a way to speed up a Jenkins pipeline that need to repetitively invoke sbt commands. A python script is called instead of sbt and forwards the command over the server socket. This script need to wait until the command is done and then exit with the appropriate code to indicate either a success or a failure.

The fact that there is no response to `sbt/exec` messages is a major pain. I'm currently using the `window/logMessage` (`Processing` / `Done`) messages to find out whether the command finished and use the presence of `type: 2` (error severity) messages as an indicator of failure, otherwise I assume a success.

This is mostly working, though a bit hackish. The whole system would be a lot more robust with an appropriate response from the server. I believe that this response should at least include whether the execution was successful or failed. This information is displayed by sbt as a `[success]` / `[error]` line, even for commands received from the server.

On the other hand, the speed gain is massive. I don't know if sbt server was ever intended as a way to script the shell instead of integrating with IDEs, but this is working wonderfully!

**Comment by eed3si9n** [comment]
@galedric That sounds awesome. Could you please blog/opensource your stuff?

**Comment by laughedelic** [comment]
I think this was fixed in https://github.com/sbt/sbt/pull/3991

**Comment by dwijnand** [comment]
I think so too.
