### ISSUE TITLE
sbt 1 triggered execution (file watch, ~, tilde) epic

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3868]
This is an epic issue to track various triggered execution (file watch, ~, tilde) related issues.
**If you're having issues with triggered execution and you do not see it here, please open a new issue.**

- watchSources is redundant and not precise #3718
- Incremental compiler crashes because of open file handles #3497
- watchSources should watch the entire directory #3369
- <s>~ is not triggering for files saved in IDEA #3819</s>
- <s>Deleted files do not trigger ~ #3845</s>
- <s>sbt 1.1.0 watch (~) thread leak causing high cpu use #3860</s>

## compile loops forever

There are several issues and fixes that are related to `~ compile` causing sbt to `compile` in loop forever.

- <s>Recompiles even if there is no changes #3501</s>
- <s>sbt 1.0.2 ~compile loops forever with source generator #3565 </s>
- The above issues are believed to be fixed by [1.0.x] Track sources in base directory non-recursively #3634 included in 1.0.3.

There's been report that `~run` still loops using Play. Here's an issue I created to debug this:

- triggered execution (file watch) should print debug log of the changed files #3869

## File watch on macOS

- Time lag before file watch (triggered execution) detects changes on Mac #3527

<s>Try https://github.com/swoval/MacOSXWatchService. This uses https://github.com/gmethvin/directory-watcher, an Apache v2 licensed file watching.</s>

MacOSXWatchService is now called Close Watch (https://github.com/swoval/swoval/blob/master/plugin/README.md), and has its own watching implementation.

## Alternative watch mode (sbt 1.0.3 and later)

The new `sbt.watch.mode` JVM flag has been added with the following supported values:

- `polling`: (default for macOS) poll the filesystem for changes (mechanism used in sbt 0.13).
- `nio` (default for other platforms): use the NIO based WatchService.

If you are experiencing long delays on a non-macOS machine then try adding `-Dsbt.watch.mode=polling` to your sbt options.

https://github.com/sbt/sbt/pull/3597

**Comment by eatkins** [comment]
I have a few clarifying comments:
1) MacOSXWatchService no longer uses directory-watcher but is still Apache v2 at the moment. I wrote all of the code and would be happy to downgrade to a more permissive license if that would be useful for the community.
2) Out of the box, MacOSXWatchService completely replaces the ~ command with a different implementation. In my experience it doesn't suffer from #3497, #3819, #3845 or #3860 
3) It works with linux and (theoretically) windows so it may be beneficial for those users suffering from the issues mentioned in (2).

**Comment by eed3si9n** [comment]
@eatkins I would love to merge Close Watch into sbt, and fix all this. Would you mind sending in a PR for this?

**Comment by eatkins** [comment]
@eed3si9n I'd love to get it merged into mainline sbt. Before I proceed, I am curious exactly what you're looking for. CloseWatch completely overhauls how sbt interacts with the file system both in triggered execution and when fetching the source file lists by adding a global file system cache. For large repos O(5000) files, this can reduce the start up time of the compile task by O(1 second) because it's expensive to list all the files on disk. Moreover, I completely re-implemented the Continuously.continuous method and eschewed the default sbt.WatchService entirely. Combined, these are some pretty large changes that I fear may get stuck in review for a while (and possibly not accepted), but that I think would improve sbt for everyone.

With that said, it would be straightforward to add the sbt.WatchService that uses my apple file system library to receive events without introducing the file cache/continuous re-implementation so the out of the box experience for mac users would be acceptable. I would be a bit bummed to do this, but I also don't want to prepare a large PR if it's just going to be rejected.

**Comment by eed3si9n** [comment]
@eatkins Thanks for the comment!

> Before I proceed, I am curious exactly what you're looking for.

I want the pain to stop.

> CloseWatch completely overhauls how sbt interacts with the file system both in triggered execution and when fetching the source file lists by adding a global file system cache. For large repos O(5000) files, this can reduce the start up time of the compile task by O(1 second) because it's expensive to list all the files on disk. 

That sounds good to me. @dwijnand?

> Moreover, I completely re-implemented the Continuously.continuous method and eschewed the default sbt.WatchService entirely.

I am ok with that. 

> With that said, it would be straightforward to add the sbt.WatchService that uses my apple file system library to receive events without introducing the file cache/continuous re-implementation so the out of the box experience for mac users would be acceptable.

We have 1.x branch (targeting 1.2.0 comes out in months) and 1.1.x branch (comes out in days or weeks). For 1.1.x branch, I would prefer conservative patch.

**Comment by eatkins** [comment]
Ok. I'm finishing up a back port of CloseWatch to sbt 0.13. Hopefully within a few days, I'll start pushing some PRs to sbt.io and sbt.

**Comment by eed3si9n** [comment]
@eatkins Ping. Any status on `~`?

**Comment by eatkins** [comment]
Funny timing. I just wrapped up my other projects:
https://github.com/sbt/sbt/pull/4052
https://github.com/sbt/io/pull/138

**Comment by eatkins** [comment]
See https://github.com/sbt/sbt/pull/4096
https://github.com/sbt/io/pull/142

**Comment by aryairani** [comment]
Is there a released version that implements this? Thanks.

**Comment by francisdb** [comment]
Still find it sometimes not detecting code changes on `1.1.6`

**Comment by eatkins** [comment]
@francisdb can you provide more details? Do you have a straightforward sbt build or is there anything non-standard with the layout? Are there any symlinks for source files or directories?

**Comment by francisdb** [comment]
Huge project with 20+ subprojects, not easy to reproduce, is there a way to get logs from the watcher?

**Comment by aryairani** [comment]
I'm using 1.1.6 and haven't been able to trigger a custom watched directory either.  Also happy to provide logs.

**Comment by eatkins** [comment]
Unfortunately, logs are not available at the moment due to https://github.com/sbt/sbt/issues/4097. I am thinking about how to work around that bug, but any change won't be available until the next sbt release at the earliest*. I am actively working on improving the directory watching, but most of it is out of band work on the close watch plugin that I hope to complete and integrate into sbt soonish.

* If by some chance either of you are willing to build your own sbt, logging could be enabled by replacing `log.debug` with `println` at this line: https://github.com/sbt/sbt/blob/1.x/main-command/src/main/scala/sbt/Watched.scala#L111

**Comment by aryairani** [comment]
@eatkins I built `sbt` from `master` but don't know how to run it :)
edit: I replaced log.debug with println at Watched.scala#L111, then `sbt publishLocal` and then `java -jar <sbt-dir>/launch/target/sbt-launch.jar` in my project dir.  But no change and no obvious logging output.

**Comment by eed3si9n** [comment]
@aryairani Start sbt with `sbt -Dsbt.version=1.2.0-SNAPSHOT`, and then run `reboot dev` once to clear the boot directory.

**Comment by eed3si9n** [comment]
I'm retiring this epic, and going to use the label area/watch instead. Feel free to either continue the conversation here, or open a new issue.

**Comment by alex-piccione-spin** [comment]
I installed sbt 1.1.6 on Windows.
I followed the instruction on https://www.scala-sbt.org/1.x/docs/sbt-by-example.html .
I have an empty build.sbt file.
I have project/src/main/scala/example/Hello.scala file with a simple Hello class.
`compile`  works.
`~compile` does not work: file changes does not trigger the command.

**Comment by OlegYch** [comment]
@alex-piccione do you mean `project/src/main/scala/example/Hello.scala` or `src/main/scala/example/Hello.scala` ?

**Comment by alex-piccione-spin** [comment]
The documentation it says 

> From a different shell or in your file manager create in the project directory the following nested directories: src/main/scala/example. 

I created the Hello.scala there.
compile works, so I thought it was ok.

I put the _src_ folder at the same level of the project folder and it works !
thanks

**Comment by OlegYch** [comment]
yeah the wording could be clearer
