### ISSUE TITLE
SBT 1.1.0 Ignore ivy resolvers

### ISSUE THREAD

**Issue by yaniveliash** [sbt/sbt#3905]
## steps
1. Setup private nexus repository based on SBT recommendation (separate repositories for maven and ivy)
2. Configure repositories file in your .sbt directory with the ivy scheme
3. Configure credentials for your private nexus repository
4. Try to build your project (in my case with sbt-assembly)

## problem
SBT resolve all the ivy dependencies from typesafe and not from my repositories file.
In my specific case: sbt-assembly
while maven resolve OK from my nexus private repository where my nexus proxy and cache those artifacts

## expectation
When adding -Dsbt.override.build.repos=true (and without with there are not resolvers inside the build.sbt file) I expect that ALL the resolving will got based on my repositories file and will have zero attempt
to the public repositories

## notes
When I've added in my IPTABLES a DROP rule to the load balancer that provide typesafe repositories
After a few minutes (probably a timeout) SBT went to my nexus private repository and actually resolved my required ivy dependencies thru the system.

sbt version: 1.1.0

**Comment by jugalps** [comment]
I am facing the same issue. Is there any other way instead of adding a DROP rule to IPTABLES?

**Comment by onmomo** [comment]
This is also preventing us to upgrade.

**Comment by jugalps** [comment]
@onmomo @geostant - I managed to get it working eventually by creating a `.jvmopts` file in the project root directory with the following option and having a custom `repositories` file in `.sbt` directory:
```
-Dsbt.override.build.repos=true
``` 
After I provide this file, I see that the custom repositories file is picked up correctly by SBT without referencing builtin ivy resolvers and I am able to resolve all the dependencies without any issue.

**Comment by onmomo** [comment]
@jugalps thanks a lot, this fixed it for me on the AWS Linux AMI. The fix is not required for my local machine (macos) or ubuntu, though. 
sbt 1.1.2, openjdk 8 / oracle jdk 8

Found another workaround:
If sbt is launched as this `sbt -Dsbt.repository.config=project/proxy-repositories compile` it will pick up the file `proxy-repositories` and will resolve via corporate artifactory. No modifications in the ~/.sbt directory nor a .jvmopts is required in this case.
Seems like the -Dsbt.repository.config in the .sbtopts file in the project root is ignored for some reason in this specific environment (AWS Linux AMI)
```
cat .sbtopts 
-J-Xmx1G
-Dsbt.boot.credentials=${HOME}/.ivy2/.credentials
-Dsbt.repository.config=project/proxy-repositories
-Dsbt.override.build.repos=true
```
