### ISSUE TITLE
JSch too old

### ISSUE THREAD

**Issue by ryandbair** [sbt/sbt#3976]
SBT currently includes JSch 0.1.46, transitively through Ivy. This version does not support any key exchange algorithms considered secure these days. More specifically, none of the algorithms are supported by GitHub any longer. 

sbt version: 1.1.1

This may require updating Ivy: #1920

**Comment by eed3si9n** [comment]
I'd be open for either trying to backport JSch bumping to our Ivy fork, or applying our patches on top of the latest Ivy.

**Comment by hansharhoff** [comment]
Are there any available workarounds for sbt to be able to connect to github?

Currently a fresh install on Windows (8.1) fails at the first step of the tutorials: https://www.scala-sbt.org/1.x/docs/Hello.html

For reference it fails with Algorithm Negatiation Fail
because of:
https://github.com/is/jsch/issues/2 https://developer.github.com/changes/2018-02-01-weak-crypto-removal-notice/

**Comment by hansharhoff** [comment]
Workaround is to manually download the  https://github.com/scala/scala-seed.g8/tree/2.12.x/src/main/g8 folder and use that as your starting point for a project.

**Comment by dwijnand** [comment]
fix merged in https://github.com/sbt/librarymanagement/pull/217

**Comment by dwijnand** [comment]
fixed via https://github.com/sbt/sbt/pull/4031
