### ISSUE TITLE
brew sbt formula using URL shortener, corporate network issues

### ISSUE THREAD

**Issue by bkrodgers** [sbt/sbt#4165]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

brew upgrade sbt
==> Downloading https://piccolo.link/sbt-1.1.5.tgz
==> Downloading from http://internal-proxy-ip/cgi-bin/blockpage.cgi?ws-session=session-id

## problem

I'm having a problem upgrading sbt through brew. It looks like the sbt formula (https://github.com/Homebrew/homebrew-core/blob/master/Formula/sbt.rb) is using a URL shortener link of https://piccolo.link/sbt-1.1.5.tgz to download.

Unfortunately, our corporate network has blocked this URL shortener. Forcepoint has it categorized as "Elevated Exposure." While I can put in a request to get this recategorized or whitelisted (which may or may not be approved), is it really necessary to use a URL shortener within a brew formula? I believe this categorization is done by Forcepoint, not our security office, so this issue will affect others who are behind Forcepoint if they have this category blocked.  

## expectation

A normal brew upgrade

## notes

I did submit this issue on homebrew-core as well, but as I think about it perhaps it needs to be addressed here.  https://github.com/Homebrew/homebrew-core/issues/27912

sbt version: N/A, can't install

**Comment by cunei** [comment]
Hello @bkrodgers,
We are using a URL shortener because our CDN does not offer precise per-file download statistics. The shortener simply keeps track of the number of times each release is downloaded, which is very useful for us to guide development and to assess interest in new features.
It is not clear to us why Forcepoint should categorize the site as high-risk; my guess is that it is a default rule-based assessment for any previously unknown new site that uses shortener software. This site is based on the open-source Polr shortener, and probably Forcepoint just marks them all as suspicious by default.
The best approach would be to ask them to whitelist the site, if at all possible. Kindly let us know how we can assist you with this process.

**Comment by dwijnand** [comment]
Perhaps adding an alternative ("mirror" in homebrew terms, I think) URL to the formula would be a good idea for a few reasons.

**Comment by cunei** [comment]
Homebrew switched to the dereferenced URL, so those installs will not be accounted for in our download stats (nor will whose who obtain the distribution via GitHub, incidentally). See: https://github.com/Homebrew/homebrew-core/pull/27787
/fyi @eed3si9n

**Comment by dwijnand** [comment]
It wasn't merged though.

**Comment by cunei** [comment]
Right, I didn't notice

**Comment by cunei** [comment]
Yep, apparently Forcepoint identified the site type from fixed urls like "http://piccolo.link/about-polr". A report is available at: https://csi.websense.com/Report/Index/f77dc8df-5f54-4548-805f-a8e2003c21d0

**Comment by eed3si9n** [comment]
As @cunei mentioned, we use the shortener to track the download statistics, which is a important metrics to the sbt project and to companies that back it. We are currently looking into if it's possible for us to use some more normal looking domain name (like something.scala-sbt.org). Thanks for your patience.

**Comment by ethomas2** [comment]
Just wanted to +1 this issue. I also can't brew install sbt due to corporate firewall issues.

For what it's worth, the solution that i'm considering going with is to bypass the short url by creating our own internal brew formula that uses the direct link (like what was done here https://github.com/Homebrew/homebrew-core/pull/27787). That's probably the path of least resistance for me.

I realize it's not your fault that the short-url is getting blocked, but if other companies are also bypassing the short-url then you might already have a significant number of users that aren't accounted for in your download statistics.

**Comment by ChristianKienle** [comment]
+1 from me as well. Ran into the exact same issue.

**Comment by seoh** [comment]
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/2159453/45588145-d5c55d00-b94a-11e8-85be-c09ffbb31e73.png">

Sometimes shorten link goes wrong. it was just temporarily issue and works well after a few minutes, but I think it should be logged.

**Comment by mrveera** [comment]
I have tried using multiple networks still not able access below link
 https://piccolo.link/sbt-1.2.3.tgz

**Comment by cunei** [comment]
Concerning the brew sbt formula, and the issues with corporate firewalls, the piccolo.link website now seems to be whitelisted on Forcepoint/WebSense, and therefore should work fine now. At least, the WebSense site reports "No threat detected", at this time.

Regarding the recent download issues, the provider for piccolo.link identified and fixed a load balancing issue, so all should be back to normal. Additional details at: https://github.com/sbt/sbt/issues/4413#issuecomment-428305970

Since WebSense no longer identifies the shortener as malicious, this ticket can be closed now; please let us know if you still encounter difficulties with Forcepoint.
