### ISSUE TITLE
A lack of API documentation

### ISSUE THREAD

**Issue by huntc** [sbt/sbt#4195]
I find that when contributing to projects, it is important to understand the rationale for public types and methods. The absence of such means that it is hard to navigate through a project and learn what does what. A case in point presently is learning how library resolution takes place so that I can leverage it within my build. It is *hard* to understand sbt and its organization and this probably inhibits contributions.

Another example - see https://www.scala-sbt.org/1.0.0/api/sbt/Keys%24.html - not a single line of documentation explaining each key...

I realize that the code base is quite mature, but perhaps all future pull requests should put this right and ensure that new public types and methods have sufficient rationale explaining their existence.

WDYT?

**Comment by eed3si9n** [comment]
I agree that having some Scaladoc might help, but I am not 100% sure if that would explain the overall organization of the sbt code base, or how library management works.
Keys are not explained in Scaladoc because we have `sbt help` instead.

What's the success criteria of this issue? Changing the coding guideline? https://github.com/sbt/website/blob/1.x/src/reference/90-Developers-Guide/02-Coding-Guideline/00.md

**Comment by huntc** [comment]
Yes, changing the coding guidelines would suffice for me. Want me to have a stab at that?

**Comment by eed3si9n** [comment]
@huntc Yes, plz.

**Comment by eed3si9n** [comment]
Closing this.
