### ISSUE TITLE
Ctrl + C is not propagated to forked test

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4197]
This is part of `Glocal / cancelable` epic.

See https://github.com/sbt/sbt/issues/3252#issuecomment-396813096

## steps

```scala
import Dependencies._

Global / cancelable := true
ThisBuild / organization := "com.example"
ThisBuild / scalaVersion := "2.12.6"
ThisBuild / version      := "0.1.0-SNAPSHOT"

lazy val root = (project in file(".")).
  settings(
    name := "Hello",
    Compile / fork := true,
    Test / fork := true,
    libraryDependencies += scalaTest % Test
  )
```

1. Run some long running test.

```scala
package example

import org.scalatest._

class HelloSpec extends FlatSpec with Matchers {
  "The Hello object" should "say hello" in {
    Hello.loop shouldEqual "hello"
  }
}

object Hello extends App {
  def loop: Unit = {
    println("hello")
    Thread.sleep(1000)
    loop
  }
}
```

2. Type in Ctrl + C into the shell.

## problem

```
sbt:Hello> Exception in thread "Thread-16" java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2958)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1538)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:818)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:807)
	at java.lang.Thread.run(Thread.java:748)
```

## expectation

Test shutsdown cleanly.

## notes

It might be an improvement to hold on to scala.sys.process.Process here https://github.com/sbt/sbt/blob/v1.1.6/main-actions/src/main/scala/sbt/ForkTests.scala#L125, and explicitly call destroy() on it.

**Comment by driquelme** [comment]
@eed3si9n  ~~This might be a Scalatest issue.~~
What seems to be happening is that Scalatest spawns it's own server thread to listen for incoming events from the remote jvm tasks. 
https://github.com/scalatest/scalatest/blob/3.0.x-for-scala-2.12.x/scalatest/src/main/scala/org/scalatest/tools/Framework.scala#L849

The crash happens when Ctrl-C causes the remote jvm to close the client socket. Prior to this, Scalatest's server thread is blocked waiting for an object event to be read. When the client socket is closed it's output stream is flushed with zero bytes, causing the server's ObjectInputStream to throw a java.io.EOFException here:
https://github.com/scalatest/scalatest/blob/3.0.x-for-scala-2.12.x/scalatest/src/main/scala/org/scalatest/tools/Framework.scala#L790

We could add a ShutdownHook to ForkMain to get a chance to signal the `Runner` that it's about to get killed, ~~but I don't see any methods in `sbt.testing.Framework` that would allow this~~, `sbt.testing.Runner.done` could be used to signal that we are done.
~~On the other hand, Scalatest's framework implementation could add it's own shutdown handler and send the appropriate object event to it's server before termination happens.~~

Related issue in Scalatest:
https://github.com/scalatest/scalatest/issues/770

**Comment by eed3si9n** [comment]
@driquelme Thanks for the detective work. Do you think it would still make sense to call `process.destroy()`? Or is the remote JVM automatically shutdown by someone?

**Comment by driquelme** [comment]
@eed3si9n  The child process is receiving the CTRL-C and shutting down, at least on my mac. It should be the same in any POSIX OS. Not sure about windows though.
I also noticed that the Scalatest's server thread, which runs in the mothership jvm, blocks on IO so it doesn't get terminated, this is what ultimately causes the original exception.
I don't think calling `process.destroy` is going to be of much help with this issue.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4226
