### ISSUE TITLE
Maven dependencies with 'provided' scope should not pull in transitive deps

### ISSUE THREAD

**Issue by jkodumal** [sbt/sbt#42]
As stated in the Maven documentation, dependencies declared in pom.xml with 'provided' scope should be intransitive. There's a reproducer available here : https://github.com/jkodumal/Sbt-Maven-Reproducer

When the issue is addressed, 'sbt update' should no longer attempt to pull in a dependency on ejb 3.0 (which can't be resolved).

**Comment by ijuma** [comment]
Out of curiosity, what is the reasoning for the revert?

**Comment by harrah** [comment]
1) Ivy has intransitive(), making it easy to go from transitive->intransitive for a specific dependency.  It is not possible to declare a dependency in an intransitive configuration to be transitive.
2) It is a better default for Provided to be transitive for Scala because scalac often requires indirect dependencies on the classpath

This was especially apparent to me when declaring sbt as provided for sbt plugins.  I will probably make it easier to have Provided be intransitive (like providedTransitive := false), but something like this should work now:

```
ivyConfigurations ~= { _.map { case Provided => Provided.intransitive(); case x => x } }
```

(Provided might not be a stable identifier in 0.10.0, but it should be in .1)

**Comment by ijuma** [comment]
Thanks for the explanation.

**Comment by harrah** [comment]
I thought I would make it easier to change Provided to be intransitive with the commit referenced here.  The previously mentioned `ivyConfigurations` line can now be:

```
ivyConfigurations ~= overrideConfigs(Provided.intransitive)
```

However, in the process, I discovered that making Provided intransitive (as done in the original, reverted fix as well) doesn't seem to work as I would have expected.  The 'provided' configuration itself doesn't have transitive dependencies.  However, the 'compile-internal' configuration, which extends 'provided', 'optional', and 'compile', does.

It appears that the best solution is still to explicitly call intransitive() for each dependency, sorry.
