### ISSUE TITLE
fgRun feature

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4206]
## steps

1. `fgRun`.

## expectation

Works like `run` in sbt 0.13.

**Comment by lecogiteur** [comment]
This what is happened for me when I do `sbt run`.

in sbt 0.13 or 1.0:

```
 - src
 - target
      |- scala2_xxx
              |- classes
              |- resolution-cache/ 
```
When run my app with sbt, it's based on classes directory


In 1.1.x 
```
 - src
 - target
      |- scala2_xx
              |- classes
              |- resolution-cache/ 
              |- my-app_2.12-0.1.0-SNAPSHOT.jar
```
When run my app with sbt, it's based on jar.

I have no modification in my build.sbt (just sbt version).

How to configure sbt in order to keep the same behaviour than 0.13 (or 1.0)
