### ISSUE TITLE
clearer error for submodule scalaVersion mismatch

### ISSUE THREAD

**Issue by truher** [sbt/sbt#438]
see [stackoverflow](http://stackoverflow.com/questions/10391229/sbt-git-dependency-produces-error-if-scalaversions-different/) for details.  if a parent project's scalaVersion is different from a child's scalaVersion, you get an opaque, fatal, error.

**Comment by harrah** [comment]
Thanks for following up.  This is fixed on the 0.13 branch and will be backported for 0.12.0.

**Comment by truher** [comment]
rock on.

**Comment by Blaisorblade** [comment]
I experienced a different variation of this bug: subprojects should IMO default to the same scala version as their parent project, since otherwise the subproject cannot be used in the parent project; however they don't and use a fixed default. When I changed the root project's Scala version from 2.9.1 to 2.9.2, I ran into the same unhelpful error.*
If you think that subprojects should not always, or not by default, inherit the scalaVersion from their parent, it should be at least possible to choose explicitly this setting with `scalaVersion := inherit` or `scalaVersionInherit := true`. It sounds overkill though: a subproject should inherit the parent's scalaVersion unless the subproject overrides it explicitly.

Should I open a separate issue?
- I guess SBT defaults to 2.9.1 because it's SBT 0.11.3 compiled with Scala 2.9.1.

**Comment by harrah** [comment]
Dependencies were separated into three categories in 0.10.x from just one in 0.7 and earlier.  Those three are aggregation, classpath, and delegation dependencies.  An aggregation dependency only implies that executing a task on one project will also execute it on the aggregated projects.  A classpath dependency only implies that a project uses the products of another project.  The final dependency specifies that one project will delegate to another for undefined settings.

I don't think delegation dependencies have really gotten much use because it is often simpler to just define a setting in the ThisBuild scope, for example, or to use normal Scala abstractions to define a setting for all projects (such as having a commonSettings `Seq[Setting[_]]` that gets appended to the settings for all projects).

**Comment by Blaisorblade** [comment]
I finally took a serious look at your tip. You propose to have `scalaVersion in ThisBuild := "2.10.0-M5"` in the main build.sbt. That worked perfectly, thanks!

I still slightly prefer that to be the default, but I think it's much more important to document this trick - when reading the page on scopes, it's not clear at all what `ThisBuild` means, much less how important this is. So, I took a stab at documenting this in the [wiki page on multiple projects](https://github.com/harrah/xsbt/wiki/Getting-Started-Multi-Project) with this specific example. It was a quick attempt, but still better than nothing.

I'm a bit worried about the exact terminology, and a bit more worried about the fact that one more example would help. An example of your suggestion to use `Seq[Setting[_]]` would also maybe be useful. Anyway, I'd recommend to take a quick look to fix my mistakes there.
