### ISSUE TITLE
SemanticSelector("=2.13") doesn't matches "2.13.0-M5"

### ISSUE THREAD

**Issue by kxbmap** [sbt/sbt#4422]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
```scala
scala> import sbt._
import sbt._

scala> val sem = SemanticSelector("=2.13")
sem: sbt.librarymanagement.SemanticSelector = >=2.13 <=2.13

scala> sem.matches(VersionNumber("2.13.0"))
res0: Boolean = true

scala> sem.matches(VersionNumber("2.13.0-M5"))
res1: Boolean = false
```

## problem

Scaladoc of SemanticSelector says:

> Metadata and pre-release of VersionNumber are ignored.
> So `1.0.0` matches any versions that have `1.0.0` as normal version with any pre-release version
> or any metadata like `1.0.0-alpha`, `1.0.0+metadata`.

But actually they are not ignored.

## expectation

Ignore pre-release section, or fix Scaladoc.

## notes

sbt version: 1.2.4

**Comment by eed3si9n** [comment]
@tanishiking Would you like to take a look at this?

**Comment by tanishiking** [comment]
@kxbmap Ah, sorry the part of scaladoc is not correct... I'll fix the document and add some explanation. Thank you for reporting.
In order to match pre-release versions, we need to explicitly specify the pre-release identifiers. For example: ">=2.13.0-M1".

---

In `SemanticVersionSelector`, the order of semantic versions basically follows the rule specified in https://semver.org/#spec-item-11

> When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version.
> Example: 1.0.0-alpha < 1.0.0.
> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows:
> identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order.
> Numeric identifiers always have lower precedence than non-numeric identifiers.
> A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal.
> Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

(The difference from the original specification is that `SemanticVersionSelector` separates the pre-rerease identifiers by "hyphen" instead of "dot")

And as scaladoc says, `=2.13` is equivalent to `>=2.13.0 <2.14.0`.
Therefore, `=2.13` doesn't matches 2.13's pre-release versions like "2.13.0-M5" because "2.13.0" is larger than "2.13.0-M5" in terms of semantic versioning.
