### ISSUE TITLE
Provide a way to specify test report name

### ISSUE THREAD

**Issue by ignasi35** [sbt/sbt#4451]
Test reports are generated using two different filenames for specific report processors to read. 

Some processors may pick both file formats reporting twice as many tests. It'd be good to make the reporting tunable so users may choose one output format or the other

_Originally posted by @yanns in https://github.com/sbt/sbt/pull/4343#issuecomment-428160480_

**Comment by eed3si9n** [comment]
For context #4343 says

> Fixes #3150 by duplicating the reports generated so given a test `com.example.MyTest.java` the following will be created:
>
> - `com.example.MyTest.xml`
> - `TEST-com.example.MyTest.xml`

**Comment by eed3si9n** [comment]
To potential contributor, the relevant files are:
- testing/src/main/scala/sbt/JUnitXmlTestsListener.scala changed in https://github.com/sbt/sbt/pull/4343/files
- and https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/internal/SysProp.scala if we use system properties as flag

For example we can provide `-Dsbt.testing.legacyreport=true` to produce legacy report, but otherwise just use the new `TEST-*` file name.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/5350 by @mrArkwright

**Comment by francisdb** [comment]
this seems to have caused duplicate test reporting when using the play plugin
https://github.com/playframework/playframework/issues/10000
