### ISSUE TITLE
Port property-based tests from ScalaCheck to Hedgehog

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#4523]
https://github.com/hedgehogqa/scala-hedgehog looks great, possibly better than ScalaCheck.

So for a number of reasons I think the property-based tests in sbt could be ported.

**Comment by eed3si9n** [comment]
The idea of better shrinkage sounds interesting, but it's not like we are suffering in that area, so this seems like a nice to have. 

- The surface DSL looks slightly more verbose than ScalaCheck if you see the migration guide (https://github.com/hedgehogqa/scala-hedgehog/blob/master/doc/migration-scalacheck.md#hedgehog)
- There's a huge difference with ScalaCheck for number of commits and contributors, so that's a risk as well.

**Comment by dwijnand** [comment]
> The idea of better shrinkage sounds interesting, but it's not like we are suffering in that area

I think https://github.com/sbt/sbt/issues/3893 would've been obvious if it were built using Hedgehog's system rather than ScalaCheck's broken system.  Btw ScalaCheck took QuickChecks broken system and made it worst too (by picking the implicit Shrink when given a specific, non-implicit Gen).

> this seems like a nice to have.

It's a nice-to-have for sure.

> * The surface DSL looks slightly more verbose than ScalaCheck if you see the migration guide

Yeah, that's because it forces you to make explicit, conscientious decisions instead of not understanding the choice

> * There's a huge difference with ScalaCheck for number of commits and contributors, so that's a risk as well.

True, but then (a) ScalaCheck is an ancient library, and (b) ScalaCheck isn't maintained anymore, outside of rebuilds.

Anyways, I would file it under "weekend project" or "hackathon".

**Comment by charleso** [comment]
Hi, I'm the maintainer of Scala Hedgehog.

Just as a (delayed) follow-up to @dwijnand suggestion. I had a quick stab at converting `ParseKey` to hedgehog way back in February, which only took 2 hours or so. Fortunately and unfortunately it exposed a few memory/performance issues which I was a little embarrassed about and have taken me quite a while to get around to fixing.

If you're interested here is my branch:

https://github.com/sbt/sbt/compare/develop...charleso:hedgehog

I reverted the fix for #3893 and run (with `test:run`) and eventually hit the error below (see link). Please note in the above branch *I have removed all of the custom-shrinking*. I'm curious if the final result is shrunk enough to have been immediately useful at the time or not?

That said, in no way am I advocating for hedgehog. I actually agree with @eed3si9n about the risk, I'm on the only real contributor (on the scala version) so I wouldn't want to leave SBT or the community hanging. That said I hope people might find it interesting/useful and for scala-hedgehog to potentially pick up some slightly less critical users/projects.

That was fun and (very) beneficial for me. Please let me know if you have any questions or want to chat.

**Comment by charleso** [comment]
I'm running it a few more times, just to see what it picks up. I won't spam this thread though, I've created a public gist:

https://gist.github.com/charleso/9b902ea52ac0a59c79ce005a96899988

**Comment by eed3si9n** [comment]
If either @dwijnand or @charleso wants to try hedgehog with the notorious ParseKey, we can give it a go. (It might get stuck on PR queue until we fix the parse key itself if the test correctly fails)

**Comment by charleso** [comment]
@eed3si9n would be happy to! Although is that any different/extra than that I already spiked/tested on my branch above? Sorry if I'm missing something obvious.

**Comment by eed3si9n** [comment]
> would be happy to! 

awesome.

> Although is that any different/extra than that I already spiked/tested on my branch above? Sorry if I'm missing something obvious.

No. I guess I can bump to the latest hedgehog-sbt, and see if it succeeds locally.

**Comment by eed3si9n** [comment]
I wanted to bump the example count from 100 to 10000 so added the following:

```scala
  def propertyN(name: String, result: => Property, n: Int): Test =
    Test(name, result)
      .config(_.copy(testLimit = SuccessCount(n), shrinkLimit = ShrinkLimit(n * 10)))
```

It worked for 1000, but when it's 10000 it failed without any hints of what happened.

```
[error] Error: Total 1, Failed 0, Errors 1, Passed 0
[error] Error during tests:
[error] 	sbt.ParseKey
[error] (mainProj / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 11 s, completed Sep 27, 2019 4:35:18 PM
```

**Comment by eed3si9n** [comment]
Here's my branch - https://github.com/sbt/sbt/compare/develop...eed3si9n:wip/hedgehog?expand=1

**Comment by charleso** [comment]
@eed3si9n Hmm, that's not good at all. :( Investigating now. Thanks for the branch.

**Comment by charleso** [comment]
@eed3si9n I'm going to have to head out (this morning my time), but there is an error in the actual `Gen`. code somewhere. It looks like it fails when it generates two `ProjectRef`s with the _same_ `build`, and `buildMap(ref.build).projectMap(ref.project)` then fails because the project doesn't exist in the second/other build. It _seems_ to be trigger more frequently by the change in [b35cfba8f](https://github.com/sbt/sbt/commit/4971db0fe397ea3f9510bdcdae8f12d66b58e0f0), most likely because the build URIs are more common perhaps.

I apologise for the poor error handling in hedgehog. I will aim to fix it ASAP so that errors in generation show up.

For now, I would suggest running `test:runMain sbt.ParseKey` which at least prints out the full stack trace (I'm surprised sbt test doesn't).

```
[error] Exception in thread "main" java.util.NoSuchElementException: key not found: lcsaa
[error]         at scala.collection.immutable.Map$Map2.apply(Map.scala:138)
[error]         at sbt.internal.TestBuild2$Env.project(TestBuild2.scala:134)
[error]         at sbt.internal.TestBuild2$Env.inheritProject(TestBuild2.scala:147)
[error]         at sbt.internal.TestBuild2$Env.$anonfun$delegates$4(TestBuild2.scala:155)
[error]         at sbt.internal.util.Dag$.visit$2(Dag.scala:56)
[error]         at sbt.internal.util.Dag$.$anonfun$topologicalSortUnchecked$1(Dag.scala:52)
[error]         at sbt.internal.util.Dag$.$anonfun$topologicalSortUnchecked$1$adapted(Dag.scala:52)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error] ainProj at sbt.internal.util.Dag$.visitAll$2(Dag.scala:52)
[error]         at sbt.internal.util.Dag$.topologicalSortUnchecked(Dag.scala:61)
[error]         at sbt.internal.util.Dag$.topologicalSortUnchecked(Dag.scala:46)
[error]         at sbt.Scope$.topologicalSort(Scope.scala:424)
[error]         at sbt.Scope$.linearize(Scope.scala:417)
[error]         at sbt.Scope$.delegateIndex(Scope.scala:400)
[error]         at sbt.Scope$.$anonfun$delegates$2(Scope.scala:392)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at sbt.Scope$.delegates(Scope.scala:390)
[error]         at sbt.Scope$.delegates(Scope.scala:293)
[error]         at sbt.internal.TestBuild2$Env.delegates$lzycompute(TestBuild2.scala:157)
[error]         at sbt.internal.TestBuild2$Env.delegates(TestBuild2.scala:149)
[error]         at sbt.internal.TestBuild2.structure(TestBuild2.scala:244)
[error]         at sbt.ParseKey$.$anonfun$arbStructure$4(ParseKey.scala:111)
```

**Comment by eed3si9n** [comment]
> I apologise for the poor error handling in hedgehog. I will aim to fix it ASAP so that errors in generation show up.

It's all open source, so plz don't apologize (for all we know it could be sbt that's eating the stack trace), and there's no need rush here.

**Comment by eed3si9n** [comment]
Added https://github.com/sbt/sbt/commit/a2753e0fe2b1880bb2c26893efd2453c4181a803 as a workaround.

... and I got to a failing test.

```
[info] - sbt.ParseKey.An unspecified project axis resolves to the current project: Falsified after 916 passed tests
[info] > StructureKeyMask(Env:
[info]     Tasks:
[info]     fn (delegates: )
[info] Build file:///aaaaaaa/#a :
[info]     Project fn
[info]       Delegates:
[info]
[info]       Configurations:
[info]         A
[info]     Project a
[info]       Delegates:
[info]
[info]       Configurations:
[info]         A
[info] current: ProjectRef(file:///aaaaaaa/#a,a)
[info] Settings:
[info] 	Global / <key>
[info] 	   fn
[info] All keys:
[info] 	fn,ScopedKey(Scope(Select(BuildRef(file:///aaaaaaa/#a)), Select(ConfigKey(A)), Select(fn), Zero),fn),ScopeMask(false,false,true,false))
[info] > === Not Equal ===
[info] > --- lhs ---
[info] > Select(ConfigKey(A))
[info] > --- rhs ---
[info] > Zero
[info] > === Not Equal ===
[info] > --- lhs ---
[info] > Select(ProjectRef(file:///aaaaaaa/#a,fn))
[info] > --- rhs ---
[info] > Select(ProjectRef(file:///aaaaaaa/#a,a))
[info] > Current: ProjectRef(file:///aaaaaaa/#a,a)
[info] > Key: {file:///aaaaaaa/#a} / A / fn / fn
[info] > Mask: ScopeMask(false,false,true,false)
[info] > Key string: 'fn / fn'
[info] > Parsed: Right(ProjectRef(uri("file:///aaaaaaa/#a"), "fn") / fn)
[info] > Structure: Env:
[info]     Tasks:
[info]     fn (delegates: )
[info] Build file:///aaaaaaa/#a :
[info]     Project fn
[info]       Delegates:
[info]
[info]       Configurations:
[info]         A
[info]     Project a
[info]       Delegates:
[info]
[info]       Configurations:
[info]         A
[info] current: ProjectRef(file:///aaaaaaa/#a,a)
[info] Settings:
[info] 	Global / <key>
[info] 	   fn
[info] All keys:
[info] 	fn
```

**Comment by charleso** [comment]
> It's all open source, so plz don't apologize (for all we know it could be sbt that's eating the stack trace), and there's no need rush here.

Thanks. I just felt a little embarrassed. :)

> and I got to a failing test.

Great! All those A's means the shrinking is doing _something_. Is that test failure useful/minimal for you?

**Comment by eed3si9n** [comment]
Yea. It looks much better than the Unicode character soup you get with a typical property based testing.

**Comment by charleso** [comment]
Yeah integrated shrinking really is quite nice/handy. No extra work
required and much better failure cases.

**Comment by charleso** [comment]
@eed3si9n other than fixing the error handling bugs you just ran in to, is there anything else I can do for you/this? Just out of curiosity, is there any reason/catalyst for the sudden interest from you, or just playing around?

**Comment by eed3si9n** [comment]
I haven't dug deep enough to know what help I could ask for, but the fact that I could just increase the example count from the code I think is a nice enhancement. IIUC, that not something ScalaCheck can do.

> Just out of curiosity, is there any reason/catalyst for the sudden interest from you, or just playing around?

There's no deep reason. We've shipped sbt 1.3.0 (and subsequent 1.3.2) after many months, so I am just checking around older issues that I didn't have bandwidth to look into before.

**Comment by eed3si9n** [comment]
I don't want to impose but having a normal version number like "0.1.0" might be useful, partly so we can talk about it like wine e.g. "1.2.8 turned out to be a stable work horse."
If you use https://github.com/dwijnand/sbt-dynver, it can combine both the last known tag + commit sha for in-betweens. Some projects also use https://github.com/olafurpg/sbt-ci-release to publish automatically to Maven Central based on tags.

**Comment by charleso** [comment]
> I don't want to impose but having a normal version number like "0.1.0" might be useful

@eed3si9n No fair enough, I knew this was [coming](https://github.com/hedgehogqa/scala-hedgehog/issues/103). I've just released `0.1.0`.

**Comment by charleso** [comment]
@eed3si9n Ok to close now?

**Comment by charleso** [comment]
🎉
