### ISSUE TITLE
Windows - output encoding seems incorrect

### ISSUE THREAD

**Issue by chester89** [sbt/sbt#4615]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
install sbt on Windows 
run `sbt compile` for your project

## problem
output encoding looks broken. Here's the piece I copied out:
```[0m[[0m[0minfo[0m] [0m[0mScalaTest[0m
[0m[[0m[0minfo[0m] [0m[0m[36mRun completed in 1 minutes, 8 seconds, 812 milliseconds.[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[36mTotal number of tests run: 514[0m[0m
```

## expectation
output encoding is correct

## notes

sbt version: *1.2.1*
JDK: openjdk version "1.8.0_202"
Windows 10 English

**Comment by eed3si9n** [comment]
@chester89 Thanks for the report.
What you're seeing is an ANSI X3.64 control sequences (aka [Console Virtual Terminal Sequences](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)), typically to add colors.
Are you using Command Prompt to run sbt? I am a bit surprised because I thought Windows 10 is supposed to have a better support for these things.

**Comment by eed3si9n** [comment]
Does `sbt -no-colors` work?

**Comment by chester89** [comment]
@eed3si9n it does. I was looking for permanent fix

**Comment by eed3si9n** [comment]
So which terminal application are you using?

**Comment by chester89** [comment]
@eed3si9n it's Console2

**Comment by eed3si9n** [comment]
ok so are you using CMD or Cygwin Bash?

**Comment by eed3si9n** [comment]
Works for me for CMD out of the box:

<img width="559" alt="Console2_" src="https://user-images.githubusercontent.com/184683/56424960-47b6a980-6280-11e9-8836-9b082eb30c3d.png">

For Cygwin I had to use ansicon:

<img width="747" alt="Color_on_Cygwin" src="https://user-images.githubusercontent.com/184683/56427272-3d4cdd80-6289-11e9-8d7e-a6c06eaf97c4.png">

**Comment by chester89** [comment]
I'll try ansicon, thanks
