### ISSUE TITLE
reintroduce support for build.scala project?

### ISSUE THREAD

**Issue by doofin** [sbt/sbt#4626]
- [ ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## problem

pure build.scala project is no longer support as of sbt 1.X

## expectation

 project with only build.scala should be supported,because .sbt is too hard to work with if the project is complex or you try to develop/customize plugins

## notes

sbt version: 1.X

**Comment by eatkins** [comment]
I could be mistaken, but I believe that at least part of the reason that build.scala is no longer supported is because we don't want *.scala files in the project base directory. You can still write your build in pure scala and just define a trivial build.sbt file that delegates to the objects created by your scala file.

For example, you could create a file called, say, project/build.scala that looks like:
```scala
import sbt._
object Build {
  val root = project in file(".")
}
```
and then your build.sbt file would just be:
```
  val root = Build.root
```

**Comment by eed3si9n** [comment]
`Build.scala`'s days were numbered when we introduced auto plugins with `autoImport` and `:=` macros in sbt 0.13. At that point `build.sbt` DSL were no longer Scala, but more like another language that can _interop_ with Scala (like Scala can interop with Java).

We removed `trait Build` because it does the same thing as `build.sbt`, and having two ways of doing the same thing was adding both confusion to users and maintenance cost.

See https://github.com/sbt/sbt/pull/2524#issuecomment-206620041 by ralph-tice (Apr 6, 2016):

> Nobody likes to see "their" feature or code path deprecated, and I personally am a big fan and proponent of `Build.scala`. But strictly from a maintainability standpoint, I don't think any open source project has the bandwidth to cater to a minority of users, nor should they. So I tried to find some sort of proxy for usage metrics, and the results (below) surprised me:
>
> - First, for the lulz, 1529 usages of `override lazy val settings` since it came up in the previous comment
https://github.com/search?q=%22override+lazy+val+settings%22+extension%3Ascala+path%3A%2Fproject&type=Code
> - 14,152 usages of `extends Build` (in `*.scala`)
https://github.com/search?o=desc&q=%22extends+build%22+extension%3Ascala+path%3A%2Fproject&s=indexed&type=Code
> - and 39,580 usages of `scalaVersion` (in `*.sbt`)  https://github.com/search?o=desc&q=%22scalaVersion%22+extension%3Asbt+path%3A%2F&s=indexed&type=Code
> 
> I think these searches are representative in that they count roughly similar things, and the data surprised me. I probably would not be using `Build.scala` today if there were some usage metrics available to help me choose what the community has de-facto voted for, and for me the schism between `Build.scala` and `build.sbt` is more confusing than it would have been to learn the build DSL in the first place.

As of today (April 2019), the gap is even wider:
- 13,449 usages of `extends Build` (in `*.scala`)
- 95,229 usages of `scalaVersion` (in `*.sbt`)

If you have a few minutes, see also this segment from Scala Days 2015 talk [The road to sbt 1.0 is paved with server (21:49)](https://www.youtube.com/watch?v=slkV-9uClUU&feature=youtu.be&t=21m49s).
