### ISSUE TITLE
ExclusionRule.artifact ignored

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#465]
This would be less severe if the default artifact wouldn't be `*.jar`. There's an [important difference](http://ant.apache.org/ivy/history/2.2.0/ivyfile/artifact-exclude.html) between a wildcard artifact and everything else:

A wildcard artifact excludes a complete module including transitive dependencies while any more specified artifact excludes just matching artifacts. The current behavior permits selectively excluding an implicit (transitive) dependency including all of its transitive dependencies.

**Comment by harrah** [comment]
@indrajitr Any comment on this?

**Comment by indrajitr** [comment]
Not sure what would be an elegant way. @jrudolph any advice?

**Comment by tlockney** [comment]
As part of fixing a related issue, I think I may have a fix for this, unless I'm misunderstanding the issue (certainly quite possible -- this was a big, deep dive for me into the SBT+Ivy innards). All it really took was passing in the artifact attribute of the exclusion rule and then adding that, instead of "jar", to the ArtifactId that's created in IvyScala.scala. I've got this currently working against 0.11.3 (you can see my changes [here](https://github.com/tlockney/xsbt/commit/1b718fa63fa3293c998cc295b44b134ae08cc22a)), but I'll submit a pull request for this on the 0.12 branch as soon as possible.

**Comment by indrajitr** [comment]
Looks very good to me, thanks @tlockney !

**Comment by tlockney** [comment]
@indrajitr Good to hear! I'm trying to get it tested under 0.12 (need to switch a couple projects over to test it on) and then I'll push the change up my fork.

**Comment by indrajitr** [comment]
@tlockney You might consider baselining against 0.13 instead :) If necessary, @harrah can backport it to 0.12.

**Comment by jrudolph** [comment]
@tlockney That looks exactly what I think I had in mind when I reported that first but I didn't take the time to do it myself. Thanks for following up and fixing it. That's great.

**Comment by tlockney** [comment]
@indrajitr yeah, you're probably right. @harrah and I talked about this a bit on IRC and he suggested he might do a 0.12.1 release not long after 0.12.0 comes out, so I just charged ahead putting it on that branch. But it likely does makes sense to put the changes on the latest code and let him backport when it's ready. The changes are simple enough, from what I've seen so far, that it is an easy port.

@jrudolph awesome -- very glad to have that validated. I'm thinking about pushing my builds to a GH hosted repo using the ol' local repo copied to gh-pages approach, in case others want to give it a try. It would also help me get my team set up so they can access the custom build for the 0.11 branch, which all of our projects are still using (maybe not for long, at least).

**Comment by harrah** [comment]
@tlockney All commits can go on 0.13 and I'll backport at the time of the release.

Do you need regular expressions for matchers or just "*"?  From http://ant.apache.org/ivy/history/latest-milestone/concept.html :

"Note also that with any matcher, the character '*' has the special meaning of matching anything. This is particularly useful with default values which do not depend on the matcher."

I'm not sure why Ivy uses Oro instead of the builtin regex (it seems likely that it was written before Java 1.4), but I'd rather not add another dependency.  If regex is important, I think it would be better to write the basic wrapper around the built-in regex.

**Comment by tlockney** [comment]
@harrah yeah, I was worried about the Oro inclusion. I'll experiment to see how hard it would be to switch to the using the builtin regex via a custom matcher. As for regex versus glob matchers -- my main reason for doing that was for matching on name and organization, where globs will often not be enough. I guess the best approach would be to allow for selecting a matcher to use as part of the ExclusionRule, but I was hoping to change as little code as possible. If you'd prefer a patch with that included, I can try to come up with an approach that's clean.

**Comment by harrah** [comment]
It isn't a choice between glob and full regex because it looks like both require Oro.  I think providing a single default is fine and there is no need to make it customizable at this time.  A PatternMatcher based on the built-in would be nice if you don't mind.  Otherwise, I'm happy to do that part myself.

Either way, the change that passes along the `artifact` part should be one commit and the regex change can be in a separate commit.  Thanks!

**Comment by tlockney** [comment]
Yeah, I was addressing the glob vs regex as a separate concern -- I think there's a valid reason for preferring the regex approach, if possible. Implementing a custom matcher looks like it should be pretty simple -- the interface is just two calls. I'll likely work on that over the weekend (if not later today) and send a new set of changes to look at (posted as separate commits, as you suggest).

**Comment by tlockney** [comment]
I've submitted two pull requests for this: [506](https://github.com/harrah/xsbt/pull/506) and [507](https://github.com/harrah/xsbt/pull/507). 507 is the one that specifically addresses the issue described by this ticket. 506 adds in the regex-based matcher, including a custom implementation to avoid the Oro dependency. I presume any additional comments specific to the code will go on those PRs.

**Comment by harrah** [comment]
This was fixed by @tlockney in #507.
