### ISSUE TITLE
Console not cleared between runs

### ISSUE THREAD

**Issue by japgolly** [sbt/sbt#4696]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

Add `triggeredMessage := Watched.clearWhenTriggered` to `build.sbt`
Run `~test:compile` and make changes

## problem

Console is never cleared.

## expectation

Console should be cleared between runs.

## notes

sbt version: 1.3.0-RC1

**Comment by eatkins** [comment]
@japgolly triggeredMessage is deprecated. You can get this behavior with `watchTriggeredMessage := Some(Watched.clearScreen)`. Also, if you want to clear your screen at the beginning, before anything runs, you can add `watchOnStart := { () => println(Watched.clearScreen) }`.

That being said, this not working in 1.3.0-RC1 was a bug and is fixed in #4745.

**Comment by japgolly** [comment]
That's great, thank you @eatkins !

**Comment by japgolly** [comment]
Hi @eatkins, I just tried this with 1.3.0-RC2 and there is no `watchOnStart` setting.

I've got ↓this↓ and it clears the screen between runs but it doesn't clear on start

```scala
watchTriggeredMessage in ThisBuild := { (_, _, _) => Some(Watched.clearScreen) }
```

**Comment by eatkins** [comment]
Yeah, sorry, I changed a few of the watch settings while writing documentation and realizing that they were a little awkward to use. The new setting that you want is `ThisBuild / watchBeforeCommand := Watch.clearScreen`. Apologies that the api changed. I don't expect that it will again.
