### ISSUE TITLE
[1.3.0-RC1] regression: bridge sources JAR not downloaded

### ISSUE THREAD

**Issue by dotta** [sbt/sbt#4712]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

Please see https://github.com/dotta/sbt-1.3.0-bridge-download-regression/ for a full reproducible with explanations in the README.

## problem

The configured bridge sources are not downloaded now that Coursier is the default dependency manager. It works fine if Ivy is used instead.

## expectation

The same resolvers are used to download the bridge component with both Ivy and Coursier.

## notes

sbt version: *1.3.0-RC1*

**Comment by eed3si9n** [comment]
@dotta Thanks for the report with repro project!

**Comment by eed3si9n** [comment]
For what it's worth, this problems happens with both Ivy and Coursier using sbt 1.3.0-RC1 with empty cache. `sbt -ivy cache`.

```
[error] (Compile / compileIncremental) sbt.internal.inc.InvalidComponent: The compiler bridge sources sbt.internal.librarymanagement.IvySbt$Module@5b95a080 could not be retrieved.
[error]
[error] 	Note: Unresolved dependencies path:
[error] 		com.triplequote:hydra-bridge_1_0:2.1.4
[error] 		  +- org.scala-sbt.temp:temp-module-42e96e401171547d94407ff72e6e0d24af27d5fc:2.1.4
```

https://github.com/sbt/sbt/blob/v1.3.0-RC1/main/src/main/scala/sbt/Defaults.scala#L557-L568
```scala
          case _ =>
            ZincLmUtil.scalaCompiler(
              scalaInstance = scalaInstance.value,
              classpathOptions = classpathOptions.value,
              globalLock = launcher.globalLock,
              componentProvider = app.provider.components,
              secondaryCacheDir = Option(zincDir),
              dependencyResolution = bootDependencyResolution.value,
              compilerBridgeSource = scalaCompilerBridgeSource.value,
              scalaJarsTarget = zincDir,
              log = streams.value.log
            )
```

To resolve the compiler bridge source, `bootDependencyResolution.value` is used. Keys.scala says `bootDependencyResolution` is

> "Dependency resolution to retrieve sbt's components."

The description matches up with the implementation:

https://github.com/sbt/sbt/blob/v1.3.0-RC1/main/src/main/scala/sbt/Defaults.scala#L2643
```scala
      bootDependencyResolution := (updateSbtClassifiers / dependencyResolution).value
```

(This reuse/conflation of "sbt's component" and "compiler bridge source" works ok for Zinc's default compiler bridge.)

https://github.com/sbt/sbt/blob/v1.3.0-RC1/main/src/main/scala/sbt/Defaults.scala#L2553-L2602.

The Ivy implementation of `bootDependencyResolution` constructs an elaborate `externalResolvers`. This could be summarized to "where one would normally grab sbt plugins or sbt itself from."

### why did it work on 1.2.8?

https://github.com/sbt/sbt/blob/v1.2.8/main/src/main/scala/sbt/Defaults.scala#L520-L531

```scala
          case _ =>
            ZincUtil.scalaCompiler(
              scalaInstance = scalaInstance.value,
              classpathOptions = classpathOptions.value,
              globalLock = launcher.globalLock,
              componentProvider = app.provider.components,
              secondaryCacheDir = Option(zincDir),
              dependencyResolution = dependencyResolution.value,
              compilerBridgeSource = scalaCompilerBridgeSource.value,
              scalaJarsTarget = zincDir,
              log = streams.value.log
            )
```

It worked on sbt 1.2.8 because `dependencyResolution.value` was passed in, instead of `bootDependencyResolution.value`. This was changed so we can download compiler bridge for nightlies - https://github.com/sbt/sbt/pull/4403

**Comment by eed3si9n** [comment]
There was a similar discussion about Dotty's compiler bridge in https://github.com/coursier/coursier/issues/1181 with @smarter. Different mechanism, but the conclusion is that custom bridge require custom tweaking.

Combined conclusion might be that I should not reuse  `bootDependencyResolution` and create `ThisBuild / scalaCompilerBridgeDependencyResolution` instance specifically for this purpose along with `ThisBuild / scalaCompilerBridgeResolvers`. Plugins should be able to re-define those keys and safely come up with settings that work for both sbt 1.2.x and 1.3+.

**Comment by smarter** [comment]
> There was a similar discussion about Dotty's compiler bridge in coursier/coursier#1181 with @smarter. Different mechanism, but the conclusion is that custom bridge require custom tweaking.

The problem in that issue is related to customizing scalaInstance (and what's more customizing it in the build of Dotty itself) and independent from the use of a custom bridge.

**Comment by dotta** [comment]
> For what it's worth, this problems happens with both Ivy and Coursier using sbt 1.3.0-RC1 with empty cache

Ah, you are absolutely right. I must have had the hydra-bridge in the ivy cache after the different tests I did (and I didn't know about that useful -ivy option!). Sorry for the misinformation.

> Combined conclusion might be that I should not reuse bootDependencyResolution and create ThisBuild / scalaCompilerBridgeDependencyResolution instance specifically for this purpose along with ThisBuild / scalaCompilerBridgeResolvers. Plugins should be able to re-define those keys and safely come up with settings that work for both sbt 1.2.x and 1.3+.

The problem for us is that sbt-hydra has to work across all sbt 1.x releases, as we really can't stop supporting old sbt releases at the moment. I'm wondering if the new setting can be introduced so that we can eventually move to it, but there can also be a workaround that can make it possible to download the bridge across all different sbt 1.x versions. Maybe, the logic could be slightly different if the stock sbt bridge is used vs a customized one? By the way, I'm happy to add code in our plugin if there is a source compatible way to do it.

**Comment by eed3si9n** [comment]
I have a PR - https://github.com/sbt/sbt/pull/4725
