### ISSUE TITLE
[1.3.0-RC1] ~ accumulates changes

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#4721]
run `~compile`
update a file, sbt will recompile it, update another, sbt will recompile both files, and so on
this is on windows 10, jdk1.8.0_181x64

**Comment by eed3si9n** [comment]
@OlegYch Thanks for the report. Could you split out steps, problem, and expectation for clarity please?

Are you saying that if you change `A.scala` save, wait for compilation, and then change `B.scala` save, it will invalidate both `A.scala` and `B.scala`?

**Comment by OlegYch** [comment]
@eed3si9n i'm not sure it invalidates them, but it keeps recompiling files without change
ie
touch A.scala - recompiled 1 file, touch B.scala - recompiled 2 files, touch C.scala - recompiled 3 files, touch A.scala again - recompiled 3 files
expected is one file every time (no api or impl changes in those files)

**Comment by eatkins** [comment]
@OlegYch, is what you mean that if you touched A.scala, it recompiled A.scala and that if you subsequently touched B.scala, it recompiled A.scala and B.scala even though A.scala hadn't changed since the last run and A.scala had no dependency on B.scala? Can you run with debug and see why the source files were invalidated? Sources can be invalidated by both source and product changes so it's impossible to tell from your description what is specifically causing the unwanted recompilation.

Also, does the issue go away if you set `watchPersistFileStamps := false` in your build?

**Comment by OlegYch** [comment]
yep `watchPersistFileStamps := false` fixes it
in debug i see that A.scala is kept in `All initially invalidated sources` and `Initial source changes: modified` even though it was just compiled and was not modified after it
there is no relationship between the files and the only change is whitespace

**Comment by OlegYch** [comment]
there is a suspicious
```
[debug] root / Compile / compile - Received event for path B.scala
[debug] Discarding entry for recently updated path B.scala. This event occurred 0 ms since the last event for this path.
```
just after it was compiled

**Comment by eatkins** [comment]
Thanks for the report and the additional details. That message isn’t necessarily unexpected. Sometimes the watch service will receive multiple events for the same file when it is modified. We generally don’t want to trigger multiple builds when this happens so we drop repeat events for files that occur in a narrow window. We try to log every file event however so in edge cases where compilation should be triggered but isn’t we can tell whether or not any file event was detected.

**Comment by eatkins** [comment]
@OlegYch I am interested in debugging this further now. Would you be able to provide some additional details about your project? You mentioned that you're using windows. Are you using the regular windows development environment (i.e. powershell), cygwin, or something else? What is the project layout? Is there a simple project that reproduces the issue? Windows debugging is difficult and time consuming for me because I have to use a vm. I unfortunately don't have the time or resources to experiment to reproduce your issue.

**Comment by OlegYch** [comment]
fwiw it is a play project, and the issue is reproducible on freebsd as well
i'll try to create a minimal repro

**Comment by eatkins** [comment]
Perfect. There seem to be a number of play related issues.

**Comment by OlegYch** [comment]
amazing, thanks @eatkins
