### ISSUE TITLE
sbt leaks metaspace when reloading an empty project

### ISSUE THREAD

**Issue by jm-g** [sbt/sbt#4773]
## steps
sbt version: from early 1.0.* up to and including 1.3.0-RC1

$ mkdir /tmp/empty-project
$ cd /tmp/empty-project
$ sbt -no-global -Dsbt.version=1.3.0-RC1 -J-Xmx200m -J-Xms200m -J-XX:+ExitOnOutOfMemoryError
...
> reload 
200x times

## problem
The jvm aborts with out of memory error

## expectation
The JVM always returns to the same memory usage it had after starting the first time.

## notes
A script to run sbt can be found here: https://gist.github.com/jm-g/c91823d8c4c4045728f63a8d2ba128cd

I have also a fix which I will publish soon. I am creating this issue for discussions.

**Comment by eatkins** [comment]
@jm-g thanks for the report. We've done work post 1.3.0-RC1 to reduce the metaspace utilization of sbt. I'm curious what your fix is. Can you describe the basic idea?

**Comment by jm-g** [comment]
Yes, I've pushed it to https://github.com/jm-g/sbt/tree/fix-4773-memory-leak . This branch is based upon 1.3.0-RC1, I can rebase it on develop this evening. 

The root problem imho are left over appender in the global log4j LogManager.  I've added an state exit hook to clear those up. Currently, there are log message in it, that I would change to debug. But I am in a hurry.

After these changes I can open  a pull request if you are interested.

**Comment by jm-g** [comment]
The above mentioned branch also contains my attempt to add scripted test for the memory leak. But it needs different scriptedLaunchOpts as all the other tests. Is it possible to set JVM parameters for only one test? Should I increase the number of reload attempts until it also fails with 1.5 GiB heap size? Do you want tests for memory leaks at all?

**Comment by eatkins** [comment]
I'm not surprised that the problem is the log appender. I am curious what happens if you run off of the develop branch because I fixed a log appender related leak after 1.3.0-RC1 in https://github.com/sbt/sbt/commit/20f6d2243952f09ef9290a4ea7747a8c682165c9.

I think a test is a good idea. My suggestion is that you might try a non-scripted test. You could more or less adapt your shell script approach to a scala test in the sbtProj. You could either reuse the infrastructure in ServerSpec, which spins up an sbt server process and sends commands via sbt's json api or you could just use the java.lang.Process api and write a number of reload commands using the Process outputStream. In either case, you should be able to set the heap parameters when the sbt process is forked.

**Comment by jm-g** [comment]
I've rebased my branch to develop and created a pull  request (https://github.com/sbt/sbt/pull/4779). But I have skipped the test, because your  (@eatkins)  metaspace fixes make the time to show the memory leak way longer. Now, it takes ca. 10 minutes of continous reloading, without my PR, to reach an oom. With my fix I can reload for 50 minutes without an oom. Those times make it impractical to run automated tests. But I am open to ideas, and I am willing to spend some more time to create a test. Or we could the script from the gist above to the sbt repository as a tool to check for memory leaks manually. 

If you look at the debug output during reload, you can see that with time more and more appenders are cleared by my fix. But the amount of classloaders does not grow. Which indicates to me, that there is something accumulating in State which leads to ever more appenders  are being added.
