### ISSUE TITLE
custom shell prompt disappears on the first line

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#493]
## steps
- customize `shellPrompt` as follows:

``` scala
shellPrompt := { state =>
  val extracted = Project.extract(state)
  import extracted._
  (name in currentRef get structure.data) match {
    case Some(name) => name + "> "
    case None => "> "
  }
}
```
- run sbt from Terminal.app (OS X 10.7.4)
- hit Command+K to clear console (not Ctrl+K)
- hit up arrow key
## problem

The command history does display correctly but the custom shell prompt is wiped out.
This only happens on the first line on the shell.
## expectation

The shell prompt stays.
It's a minor annoyance, but I wanted to report it to make sure it's not an indication of some jline issue.

**Comment by harrah** [comment]
I believe this happens for almost any interactive program.  You can see it with bash (or equivalent), sftp, and ghci, for example.  They might all just be using readline, though.  The problem is that the line handling program doesn't get informed that the screen was cleared (as far as I know) and needs to redraw the whole line.  As a workaround, do the reset when the line is blank and then press enter once after the reset.

**Comment by eed3si9n** [comment]
It doesn't happen with bash or sbt 0.11. 
When I hit Command+K (not Ctrl+K) on both sbt 0.11 and 0.12 the shell prompt is displayed.
It's what happens when I hit backspace or up arrow key that the behavior is different.
On sbt 0.11 hitting up arrow key several times displays shell prompt and the command history.
On sbt 0.12 hitting up arrow key several times displays command history with white spaces in front, sometimes part of the history chopped off.

**Comment by harrah** [comment]
For me, Ctrl+K kills all text from the cursor to the end of the line.  On both linux and mac, this presents no problems with history.  Resetting the terminal does, but that is the case for the interactive programs I tried as well.

sbt 0.12 uses jline 1.0, so that is different, but I can't otherwise reproduce this.  You could try putting jline 0.9.94 in boot/scala-2.9.2/org.scala-sbt/sbt/0.12.0-RC3/ instead of the jline jar that is there and see if it fixes it.

**Comment by eed3si9n** [comment]
I put in jline 0.9.94 but it did _not_ fix the problem.

```
$ cd ~/.sbt/
$ rm 0.12.0/boot/scala-2.9.2/org.scala-sbt/sbt/0.12.0-RC3/jline-1.0.jar
$ cp ~/work/quick-demo/tmp_jline/jline-0.9.94.jar 0.12.0/boot/scala-2.9.2/org.scala-sbt/sbt/0.12.0-RC3/
$ ls 0.12.0/boot/scala-2.9.2/org.scala-sbt/sbt/0.12.0-RC3/j*
0.12.0/boot/scala-2.9.2/org.scala-sbt/sbt/0.12.0-RC3/jline-0.9.94.jar  0.12.0/boot/scala-2.9.2/org.scala-sbt/sbt/0.12.0-RC3/jsch-0.1.46.jar
```

Also I've been writing Ctrl+K, but it's actually Command+K to clear the screen.
