### ISSUE TITLE
conflict with sbt-coursier

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5040]
## steps

Use sbt-coursier

## problem

There's been multiple reports on sbt 1.3.0 not working with sbt-coursier such as https://twitter.com/jaceklaskowski/status/1169296407733444609.

## expectation

We use the shaded version of Coursier specifically so that we can coexist with sbt-coursier or any plugin that pulls in Coursier.

**Comment by eed3si9n** [comment]
We're using shaded version of Coursier internal, so I am not sure what more we can do on sbt's end.

**Comment by alexarchambault** [comment]
I confirm that sbt-coursier can't be used as is with sbt 1.3.x, because sbt ships with `lm-coursier-shaded`, and sbt-coursier relies on `lm-coursier`, that has the same API as `lm-coursier-shaded`, but exposes more internal stuff (that sbt-coursier uses, and that end up being shaded in `lm-coursier-shaded`).

As a workaround, people can rely on the [coursier-based sbt launcher](https://github.com/coursier/sbt-launcher), that can be launched conveniently via [a custom sbt-extras script](https://raw.githubusercontent.com/coursier/sbt-extras/master/sbt). The coursier-based launcher detects that sbt-coursier is being used, and replaces `lm-coursier-shaded` by `lm-coursier` in that case.

But with sbt 1.3.x coursier support out-of-the-box, sbt-coursier doesn't bring much now. It can probably be dropped for most users.

That said, it can be interesting if users really want to test the very last coursier version. In that case, `sbt-lm-coursier` can be used instead of `sbt-coursier`, like
```scala
addSbtPlugin("io.get-coursier" % "sbt-lm-coursier" % "2.0.0-RC4")
```

**Comment by mushtaq** [comment]
@alexarchambault with coursier-2.x, instead of using sbt-extras script, it will be great if we could say `coursier install sbt` and it installs coursier-based sbt launcher. That will be very cool.

**Comment by dcsobral** [comment]
I'm very interested in coursier's most recent version for the fine grained version reconciliation. I've tried using `sbt-lm-coursier` for that as suggested by @alexarchambault and, though that does not cause errors, it does not provide the fine grained reconciliation. Specifically, while using `sbt-lm-coursier` I get this when adding a rule which shouldn't cause a failure:
```
lmcoursier.internal.shaded.coursier.error.conflict.StrictRule: Rule Strict(Set(ModuleMatcher(io.atomix:*)),Set(),true,true) ...
```
And using `sbt-coursier` I get no failure with that rule, but this with one that should cause failure:
```
coursier.error.conflict.StrictRule: Rule Strict(Set(ModuleMatcher(com.olegpy:*)),Set(),false,true,false) ...
```
Besides the obvious difference in number of parameters, one of these booleans, `includeByDefault`, is set to `true` in the first case, which causes _all_ modules to be considered, except the ones excluded.

**Comment by LeonardMeyer** [comment]
@alexarchambault sbt-coursier does bring stuff like `coursierDependencyTree`, which is very useful. Is there a way to still use that with SBT 1.3.x and without resorting to a custom launcher ?

**Comment by domainexpert** [comment]
@LeonardMeyer Yes, downgrading the coursier plugin to 1.0.3 worked for me with Sbt 1.3.6. I added `project/plugins.sbt` with the following content:
```
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.3")
```
