### ISSUE TITLE
Don't include javadocs in updateClassifiers

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5165]
A proposal from Contributors Summit on October 8th in Krakow. Proposed by @pavelfatin and @olafurpg?
 
For jump to definition feature IDEs need sources, but they don't need javadocs.

**Comment by eed3si9n** [comment]
```scala
transitiveClassifiers :== Seq(SourceClassifier, DocClassifier),
```

**Comment by olafurpg** [comment]
Turns out that sbt-bloop already updates `transitiveClassifiers` to only download sources (skip javadoc) so this has not been an issue in Metals. I think it would still make sense to change the default to skip Javadoc since I'm not aware of any tool that uses the javadocs. Either way, feel free to close this issue.

**Comment by eed3si9n** [comment]
Closing this for now.

**Comment by unkarjedy** [comment]
SBT 1.5.5 
By default classes, sources, javadocs are downloaded.
Interestingly, though, that setting `useCoursier := false` will make it not download java docs via ivy
