### ISSUE TITLE
sbt 1.3.3 - cannot resolve credentials. 

### ISSUE THREAD

**Issue by TimPigden** [sbt/sbt#5200]
## steps
sbt version: 1.3.3

I have a credentials file.
Under 1.2.8 I used

```scala
credentials += Credentials(Path.userHome / ".ivy2" / ".credentials")
```

## problem

With latest version it can no longer access my repository. The repository is a simple file-based respository. I get the following message

```
[error]   unauthorized: https://office.optrak.com/  full path name  /1.0.53/container-loading-1.0.53.pom

sbt:vrp-new> show credentials
[info] vrp-model / credentials
[info]  List(FileCredentials("/home/tim/.ivy2/.credentials"))
```

## expectation

We've been using this for years with no problem. In 1.3.3 it has stopped working. I reverted to 1.2.8 and it works again.

## notes

Some issues around list this or something similar as "closed" or duplicate. 

Using ldap
https://ldapwiki.com/wiki/Basic%20Authentication%20Scheme

**Comment by francisdb** [comment]
Have you tried this?

```
ThisBuild / useCoursier := false
```

**Comment by francisdb** [comment]
Have you tried this?

```
ThisBuild / useCoursier := false
```

**Comment by TimPigden** [comment]
I have now :-) 
Thanks
That does the trick but presumably, since Coursier is the "big new thing" in 1.3, it's still a bug

**Comment by eed3si9n** [comment]
@TimPigden Thanks for the report. This is likely a Coursier issue, so please report to coursier/coursier as well.

It would be helpful if you can provide steps to reproduce this behavior on Coursier developer's machines, for example using Docker.

**Comment by TimPigden** [comment]
grab this small repo

https://gitlab.com/wayne-optrak/sbt-bug-demo 

run sbt update and it fails

setting useCoursier :=  false in thisBuild and it works

set sbt to 1.2.8 and it works

**Comment by cchepelov** [comment]
It seems I have the same issue on sbt 1.4.6

@TimPigden's demo reproduces "as is" in sbt 1.4.6

**Comment by cchepelov** [comment]
Stepping through the sbt + lm-coursier code during the initial update (just before the failure to authenticate and download the plug-in in @TimPigden's reproduction case), I notice this:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/1515440/104562882-382ce600-5649-11eb-9d64-beec5acfdca6.png">

which seems to be a problem, since we have this in lm-coursier's [CoursierDependencyResolution](https://github.com/coursier/sbt-coursier/blob/master/modules/lm-coursier/src/main/scala/lmcoursier/CoursierDependencyResolution.scala#L97) 

<img width="706" alt="image" src="https://user-images.githubusercontent.com/1515440/104562987-64486700-5649-11eb-81c9-450e405b91d3.png">

The CoursierConfiguration (as prepared by sbt) contains the appropriate credentials, *but* appears to lack the proper repository -> credentials mapping at this point.
Not yet sure whether the fault lies with sbt proper (at the point of instantiating `CoursierConfiguration`) or within lm-coursier (at the point of filling it if it's been provided empty by the caller, i.e. sbt)

**Comment by cchepelov** [comment]
I *think* I now have the smoking gun [in sbt's LMCoursier](https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/coursierint/LMCoursier.scala#L149) :

the chained constructor/withFieldValues fails to call `.authenticationByRepositoryId(some_map)` 

We have a list of resolvers (`rs`) which seems legit
<img width="848" alt="image" src="https://user-images.githubusercontent.com/1515440/104568302-36b2ec00-5650-11eb-9b61-1a3179aad17e.png">
and we pass that to `.withResolvers(rs)`

we have a list of credentials, which we pass to `.withCredentials(creds)`
<img width="904" alt="image" src="https://user-images.githubusercontent.com/1515440/104568493-7548a680-5650-11eb-9403-b6def64a7ebb.png">
(note that these credentials were loaded from a file, but have been converted/flatmapped from FileCredentials to a sequence of `DirectCredentials` by the code in [CoursierInputTask](https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/coursierint/CoursierInputsTasks.scala#L229) )

but we lack a map binding the Resolver Id to [Authentication](https://github.com/coursier/sbt-coursier/blob/f80641a221fcb52d20dc36539c5262300b5b4567/modules/lm-coursier/src/main/scala/lmcoursier/definitions/Authentication.scala#L5) structures

**Comment by cchepelov** [comment]
**Edit: plan scrubbed, the issue is contained within Coursier.**. Updated plan is fix coursier, wait for release, bump coursier in sbt-coursier, wait for release, bump sbt-coursier here.


---

My plan:

1. extract the code from CoursierInputsTask that flatmaps the Seq[Credentials] that may contain Ivy or FileCredentials into a Seq[DirectCredentials] into a utility function
2. Create a method in LMCoursier that performs the "Resolvers & Credentials" matching and generates the "ID to Authentication" map, possibly applying again the previous method to only have 
3. In LMCoursier's `coursierConfiguration()`, use the method in point 2 to construct the Map[id:String, Authentication] and pass it into the `CoursierConfiguration`

Problem (possibly a security problem): there is nothing in point 2 that tells me which credentials to associate with which repository in case two repositories with distinct realms share the same host name. It should be rare, but should that happen there might be unwanted password sharing. 

So: 

4. In order to improve the "Repo/Credential" matching function, go and sniff the repo's root without any authentication to get the 401 and the correct expected realm back. While this would better be done using Coursier's own http library, it may be done with CoursierHttp.okhttpClient.value?

**Comment by cchepelov** [comment]
(a distinct disadvantage of going to every server to 'sniff' the realm is that we would be doing this unconditionally, before knowing whether we actually need to)

I still don't understand why this is even necessary. There is code within Coursier's [DirectCredentials](https://github.com/coursier/coursier/blob/v2.0.8/modules/util/jvm/src/main/scala/coursier/credentials/DirectCredentials.scala#L35) code that is supposed to be checked against the list of credentials (for which we _know_ we have some) once the remote repository bounces us back. 
It's difficult to step through Coursier's code from the context of sbt, since lm-coursier shades it... 

I'll try something before applying the plan above

**Comment by cchepelov** [comment]
Found the issue

Tim's Nexus, and mine, return a 
```
www-authenticate: Basic realm="some realm", charset="UTF-8"
```
header. The problem is that we try to match that with a regex that I reckon to be
`(?i)basic realm="([^\"]*)"$`

<img width="574" alt="image" src="https://user-images.githubusercontent.com/1515440/104597026-18abb280-5675-11eb-89bc-d8a59ed549bd.png">

This is within Coursier in [CacheUrl](https://github.com/coursier/coursier/blob/v2.0.8/modules/cache/jvm/src/main/scala/coursier/cache/CacheUrl.scala#L390)

The problem is that this regex leaves no space for the additional token 

==> I'll update https://github.com/coursier/coursier/issues/1421 and provide a PR asap.

@TimPigden , thank you *very much* for creating the repro and leaving it up there!

**Comment by cchepelov** [comment]
https://github.com/coursier/coursier/pull/1948 is on its way

Tim's example build does not build anyway (I suspect the 'dummy' account is rightfully closed), but I witnessed my debug build of sbt+coursier actually attempting to supply the (formerly) correct credentials now.

**Comment by fernanluyano** [comment]
This is still happening to me with Artifactory
