### ISSUE TITLE
sbt update command fails to look up new versions of dependencies in private maven repos

### ISSUE THREAD

**Issue by jmoodymarchex** [sbt/sbt#5377]
Since sbt updated to Coursier it seems as though `sbt update` no longer pulls new versions from remote repositories as expected, at least for private maven repositories. I've tried marking my dependency as "latest.version" changing(), and also tried a version ranges like "[1.0,)", but sbt continues to use the locally cached stale version, even though a newer version exists on our maven repository. I have not tried SNAPSHOT versions, but the problem may exist there as well.

This seems similar to a previous issue linked here, but rather than maven/ivy it seems to be happening with the new Coursier: https://github.com/sbt/sbt/issues/321

## steps
sbt version: *1.3.7*

* Set up an sbt project with an additional maven resolver.
```
resolvers +=
  "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
```

* Add a dependency on "latest.version" or an open range "[1.0,)"
```
libraryDependencies += "com.example.local" % "localproject" % "latest.version" changing()
```

* Build the project.
* Publish an update to the dependency.
* Run `sbt update`
* The new version is not pulled.

## problem
`sbt update` does not inspect the remote maven repository for the latest version, and instead continues to use the locally cached stale version.

## expectation
`sbt update` should cause new versions to be pulled from a maven repository as appropriate based on the specified version range or "latest.version".

**Comment by eed3si9n** [comment]
@jmoodymarchex Thanks for the report. If you suspect this is an upstream issue, please report it to coursier/coursier as well.

**Comment by jmoodymarchex** [comment]
After further investigation I was able to determine that Coursier's 24hour default TTL was the root of my issue. Nonetheless, this behavior is still unexpected. According to sbt documentation here: https://www.scala-sbt.org/1.x/docs/Dependency-Management-Flow.html (Caching and Configuration item #3) running sbt update should resolve SNAPSHOT versions (and, I assume, ranges, and latest.version). With Coursier's 24 hour TTL, however, this is no longer the case. Therefore, my preference would be for sbt's update command to automatically set Coursier's TTL to 0s in order to get the desired behavior.

**Comment by eatkins** [comment]
> Therefore, my preference would be for sbt's update command to automatically set Coursier's TTL to 0s in order to get the desired behavior.

This change scares me. The problem with invalidating the snapshots every time is that it makes working with local snapshots very painful because snapshot resolution can easily take 1 second per artifact. If you are testing a project like sbt which has roughly 20 snapshot dependencies, that means a test build of sbt takes roughly 20 seconds longer to initialize every time you run it. For me personally, the coursier local snapshot resolution is by far the biggest benefit of coursier compared to ivy (I'm likely an exception though because most of my coding is actually on sbt itself).

There is no default value that is perfect for all builds. We feel that, in the sbt world, non local SNAPSHOTs are an anti-pattern. This is not to say that you don't have a valid use case for non local SNAPSHOTs. It just isn't the use case that we wish to optimize sbt for. That being said, I'm not sure what the impact of changing the coursier TTL would be. I just know that ivy resolutions of SNAPSHOTs were very slow and coursier resolutions are generally fast.

**Comment by jmoodymarchex** [comment]
I agree that it is undesirable to slow down builds for people unnecessarily. However, for use cases where the user needs to pull down new SNAPSHOTS & ranged versions immediately, it would be great if there were a straightforward mechanism to do so. It used to be that the "sbt update" command would do this, but that no longer seems to be the case. To work around I can set the environment variable COURSIER_TTL=0s before running sbt update, but it would be great if sbt had a built in mechanism for this. Perhaps a new command, or a setting that can modify sbt update's behavior?
