### ISSUE TITLE
Batch mode run file

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#5387]
Java proper allows to run a file from the command line:

~~~
$ jdk-13.0.2/bin/java hello.java
Hello, World!
~~~

I checked here:

https://scala-sbt.org/1.x/docs/sbt-by-example

but it appears that SBT cannot do this. Is that the case? I understand that it
will be slower, but I would prefer to do it this way if possible.

**Comment by eatkins** [comment]
As far as I know, this functionality is not provided by sbt. I think it would be relatively simple to write a plugin that provided that functionality so that you could do something `sbt run-file hello.java` or call `> run-file hello.java` from the sbt console. It's also possible that there is a plugin that already does this but I haven't looked into it.

**Comment by ghost** [comment]
Ah, I missed that its lower on the page:

https://scala-lang.org/download#download-binaries

**Comment by eed3si9n** [comment]
See https://www.scala-sbt.org/1.x/docs/Scripts.html There's a mode in sbt called script mode that can in fact run `*.scala` file with an embedded build definition.
