### ISSUE TITLE
SBT installs Java 13 rather than using already installed java

### ISSUE THREAD

**Issue by samthebest** [sbt/sbt#5507]
## steps

```
brew cask install adoptopenjdk/openjdk/adoptopenjdk8
brew install sbt
```

## problem

Even though Java 8 has already been installed, SBT ignores this and installs Java 13.

Consequently get the usual `java.lang.IllegalArgumentException: Unsupported class file major version 57` when trying to run any `sbt` command (like `sbt test`).

## expectation

SBT should (as it used to I'm sure) use the Java on the machine, not download a different one.

**Comment by eed3si9n** [comment]
Yea. I've been warning people about this on release notes http://eed3si9n.com/sbt-1.3.10 too, but this is an intentional behavior by Homebrew https://github.com/Homebrew/homebrew-core/issues/50649. The fix is to use jEnv, set JAVA_HOME (this would have other consequences), or switch to some other package manager like SDKMAN.
