### ISSUE TITLE
BspClient could be folded into NetworkClient

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#5652]
The `BspClient` copies some code for forking a server from `NetworkClient`. It would be better to reuse that code. I also don't know if it would be beneficial, but `BspClient` would definitely compile using graalvm and could be incorporated into `sbtc` (#5620).

**Comment by adpi2** [comment]
Thank you @eatkins for issuing this. I also think that we should reduce the code duplication here.

One thing I remember is that the `BspClient` does not work under the `Terminal.withStreams` scope in `xMain` because it needs full control over the `System.in` and `System.out` streams. It is not a shell. Apart from that it is quite similar to `NetworkClient` in the way it forks the server and connects to it.

Having `BspClient` in sbtc would be great because it will shorten the IDE connection time. Will `sbtc` be available by default on all `sbt` installation?

**Comment by adpi2** [comment]
Implemented in #6114
