### ISSUE TITLE
🚲🏚️ What should we name different programs and how are they invoked?

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5665]
## issue

Once https://github.com/sbt/sbt/pull/5620 lands, we will have a compelling thin client that people may want to use for day-to-day coding.

I'm not sure if this would be internal JAR names or actual programs people invoke, but I think we should discuss the names of things. Overall goal is so people can configure what `sbt` command does in the terminal.

## proposal

- sbt server, which is represented by `sbt-1.x.y.jar`. We might need a retronym for "sbt" like the existence of oat milk and skim milk now necessitates the term _whole milk_, as opposed to _milk_. Let's say it's called `sbt-server`. When the user types `sbt --server`, it should always invoke the server like sbt 1.3.x.
- native thin clients, which will be represented by Graal native images. `sbtn` could be the name to always invoke the native thin client. When the user type in `sbt --client` the native thin client is invoked.
- Fallback bridge (JVM thin client). It would be an implementation detail of `sbtn` or  `sbt --client`. 
- sbt shell script. `sbt`. Depending on the setting (environmental variable?) it would invoke either sbt server or native thin client.

(2020-10-10: Retroactively renamed to sbtn to avoid confusion)

## notes about `sbt`

`sbt`-the-script has a responsibility to launch all of sbt 0.13 and sbt 1.x. So if we want it to automatically use the native version for sbt 1.4.0, it needs to at least support parsing of `project/build.properties`.

**Comment by eatkins** [comment]
@eed3si9n and I discussed offline that `sbtc` makes him think `sbt compiler` or something like that because of the analogy with `scala` and `scala`. I don't love `sbtc` or `sbtb` because I'm a mediocre typist and neither is easy to type. I find `sbtc` slightly more ergonomic than `sbtb` (I find the `btb` awkward to type). Since sbt is meaningless at this point anyway, I propose that we could get a little creative. For me, the most ergonomic name that contains an sbt prefix is `sbtl`. I could invent some weird explanation about how `l` stands for limited or local or something but I care more about ergonomics than the actual name. If we care about the meaning, I prefer `rsbt` to `sbtb` where `r` stands for relay. I find `rsbt` easier to type than `sbtr`.

**Comment by eed3si9n** [comment]
If we use `sbt` as the primary entry point, then I'm not sure if ergonomic matters too much. Typing four characters is going to be somewhat awkward initially. For the purpose of debugging, it would be useful that it's memorable.

**Comment by eatkins** [comment]
> If we use sbt as the primary entry point, then I'm not sure if ergonomic matters too much.

True, but I don't think that we can make the client the primary entry point until at least 1.5.0. That being said, there is nothing to stop anyone from aliasing the thin client to `sbt`.

> For the purpose of debugging, it would be useful that it's memorable.

To me, all of these options are roughly equally memorable except `sbtl` which is admittedly kind of out there though I still think ergonomics is not a bad reason for a name! sbtc is still probably the easiest for me to remember because we call the feature the thin client so I hear client not compiler when I see the c. That being said, I like `rsbt` the best of the options I proposed because it's easy to type and relay maps to my personal mental model better than bridge.

**Comment by eed3si9n** [comment]
In the meeting yesterday Ethan pointed out that calling `sbt` might not work since it won't be able to run builds prior to sbt 1.4.0. I guess unless we implement some crude properties file parsing in Bash and Batch.

`sbtq` for sbt quick?

**Comment by eed3si9n** [comment]
`sbtn` for sbt native?

**Comment by eed3si9n** [comment]
I ran a poll for 3h hours and here's the result - https://twitter.com/eed3si9n/status/1293929167365570563

**Comment by eatkins** [comment]
I'm fine with sbtn. It's easy to type. I had a knee jerk reaction that it implies that sbt itself is native but it doesn't seem like a common instinct.

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-launcher-package/pull/328 implements `--client` option.
