### ISSUE TITLE
Transfer 0.7.x documentation to scala-sbt.org

### ISSUE THREAD

**Issue by greenrd** [sbt/sbt#568]
It would need to be clearly labelled as documentation for 0.7.x versions only, and should retain links to the newer documentation, IMO. (Although since github docs have largely moved to scala-sbt.org, these should generally point to elsewhere on scala-sbt.org rather than the github wiki as they do now.)

**Comment by harrah** [comment]
The wiki contents are archived in HTML form at http://www.scala-sbt.org/0.7.7/docs/.  The Google Code wiki contents have been removed and now point to the equivalent page in the archive along with a notice that 0.7.7 is not maintained.  There are no links to the new documentation from the archived pages.  Instead, the archived docs are not indexed (via a <meta> tag)

Archiving code here: https://gist.github.com/3866442.  It requires the wiki to be reverted to the original content, because there is no official standalone tool to read Google Code wiki syntax other than pulling it over the web.
