### ISSUE TITLE
Per-subproject opt-out of pipelining

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5762]
## steps

In a complicated multi-project build involving macros, we need a way of opting out of pipelining for some of the subprojects without blocking the downstream.

Given projects mainProj, utilLogging, and coreMacro, I should be able to say:

```scala
ThisBuild / usePipelining := true

lazy val mainProj = project
  .dependsOn(utilLogging)
  .settings()

lazy val utilLogging = project
  .dependOn(coreMacro)
  .settings(
    // This should still produce an early output so mainProj can do pipelining
    // implicitly we need something like `exportPipelining := true` when (ThisBuild / usePipelining) is on.
    usePipelining := false
  )

lazy val coreMacro = project
  .settings()
```

**Comment by sjrd** [comment]
I think the proposed semantics are not in the best direction. You're proposing that this opt out means: don't start building this project before all its dependencies are complete, but it's OK for further downstream projects to start using my early result.

I propose the other way around: it's OK to start building this project as soon as the early result of upstream projects are available, but downstream projects must wait for my *complete* result before being compiled.

With those semantics, you'd put `usePipelining := false` in `coreMacro` instead, and in general in projects defining macros. It essentially means: my early result is not usable.

That would make much easier to correctly configure builds. For example, in your example there is a latent potential misconfiguration: if `mainProj` stops depending on `utilLogging` and instead directly depends on `coreMacro`, you'd have to remember to also deactivate pipelining on it at the same time. That's because with your semantics, the setting must be in all projects that depend on a project defining macros; whereas with my proposed semantics, the setting must only be in projects defining macros themselves.

**Comment by eed3si9n** [comment]
Defining macros would automatically [ping the downstream](https://github.com/sbt/zinc/blob/v1.4.0-M9/internal/compiler-interface/src/main/java/xsbti/compile/CompileProgress.java#L46-L52) to wait for the real JAR, and the build users normally wouldn't have to do anything manually.

The problem I'm seeing with `utilLogging` subproject is that it defines a macro, but the implementation is in `coreMacro`, and it's using the macro within `utilLogging`. 

https://github.com/sbt/sbt/blob/b09fd9d640e211003af820ba586588c89133b25c/internal/util-logging/src/main/scala/sbt/internal/util/StringTypeTag.scala#L20-L21

So even though `coreMacro` actually doesn't define `macro` exactly, `utilLogging` can't start early.

In general it would be useful to have two settings for "I use early outputs" and "I export early outputs". Maybe this could make a better case:

```scala
ThisBuild / usePipelining := true

lazy val mainProj = project
  .dependsOn(utilLogging)
  .settings()

lazy val utilLogging = project
  .dependOn(coreMacro, utilInterface)

lazy val utilInterface = project
  .settings()

lazy val coreMacro = project
  .settings(
    exportPipelining := false
  )
```

In this case, `utilLogging` would wait only for `coreMacro`'s bytecode JAR, but can use `utilInterface`'s early JAR.
