### ISSUE TITLE
sbt 1.3 is not resolving all transitive dependencies of maven published projects

### ISSUE THREAD

**Issue by lukestephenson-zendesk** [sbt/sbt#5781]
## steps

I've created a project with the following structure:

`project/build.properties`:
```
sbt.version = 1.3.13
```

`project/plugins.sbt`:
```
addSbtPlugin("org.xerial.sbt" % "sbt-pack" % "0.12")
```

`build.sbt`:
```
version := "0.1"

lazy val sbtBug = project.in(file("."))
  .settings(
    name := "sbt-bug",
    scalaVersion := "2.13.3",

    packMain := Map(
      "foo" -> "foo.Main",
    ),

    libraryDependencies ++= {
      Seq("com.zendesk" % "maxwell" % "1.27.1")
    }
  ).enablePlugins(PackPlugin)
```

## problem

sbt correctly determines the project has a transitive dependency on `com.amazonaws:aws-java-sdk-sqs:1.11.800`.  However, that dependency has a transitive dependency on `com.amazonaws:aws-java-sdk-core` which sbt fails to handle.

If I use this project in intellij, then the dependency is not present.

Similarly, with `sbt pack`, the dependency is not included in `target/pack/lib`.

As a workaround, setting `useCoursier := false,` causes the transitive dependency to be resolved correctly again.

## expectation

All transitive dependencies should be included.

**Comment by eed3si9n** [comment]
@lukestephenson-zendesk Thanks for the report. sbt 1.4.0-M2 uses more recent version of Coursier. Could you check if the problem still happens with sbt 1.4.0-M2?

**Comment by lukestephenson-zendesk** [comment]
@eed3si9n I can confirm this is still an issue for me with `1.4.0-M2`

**Comment by SethTisue** [comment]
I'm looking through old issues and I'm not sure what to make of this one. Another 2.5 years have passed, so I wonder if it's still an issue.

But also, I think the reason that issue has languished is that it's not clear what the scope of the bug is — the underlying cause. Most of the time Coursier (and sbt) handle transitive dependencies fine. So what's needed for this to progress is to identify what is unusual about this particular transitive dependency.

I believe that identifying that is the bug reporter's responsibility, so that the specific nature of the issue or bug is clear. There's no way this is going to progress otherwise.

**Comment by lukestephenson-zendesk** [comment]
I'm happy to close this. Hasn't got in my way recently.
