### ISSUE TITLE
BSP: resolving targets does not reload build

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#5783]
## steps

1. import an sbt project set to version `1.4.0-M2` as BSP project into IntelliJ
2. make some change in build.sbt that would cause an error
3. do a project refresh in IntelliJ

## problem

The import works just like before - the project was not refreshed.
To trigger a refresh, it must be manually run from an sbt shell connected to the same server, or the connection and server process must be forcibly closed.

## expectation

Ideally, sbt detects in any project refresh is necessary when calling certain BSP requests, such as `workspace/buildTargets`, and does a reload before answering. If the reload fails, these requests respond with an error.

**Comment by adpi2** [comment]
Sorry for taking so long before answering on this issue.
I will now allocate time to work on it and I hope we will be able to solve it in 1.4.0.

I can think of two possible solutions and I have a preference for the second one.

### First solution: sbt reloads on `workspace/buildTargets` if necessary

This is the solution proposed by @jastice, which makes perfect sense in the given scenario.

But there are other cases when a client wants to send a `workspace/buildTargets` without the agreement of the user. Which would be dangerous, because it might trigger a reload that might fail.

One bad scenario would be:
- I have imported my project in one IDE
- I change the `build.sbt` file
- I open another IDE that automatically sends the `workspace/buildTargets`
- sbt stops working for both IDEs

Also it is not very convenient in case the user wants to force a reload.

### Second solution: add a custom task `workspace/reload`

This means we will have two separate requests:
- `workspace/buildTargets`: This one is perfectly safe. any client can send it at any time, but the response might not reflect the current state of the `build.sbt`.
- `workspace/reload`: This request forces a reload of sbt. It must be sent with the agreement of the user, typically when it clicks reimport. 

Additionally we can have sbt send a `buildTarget/didChange` notification whenever it reloads itself to signal to its clients that they should import the `workspace/buildTargets` again.

The task `workspace/reload` does not exist yet. We can either make it official or make it a custom sbt task (`sbtWorkspace/reload`).


@jastice @eed3si9n What do you think?
- is it ok to have `workspace/buildTargets` reload automatically? (I think it is not)
- is it reasonable to add a `workspace/reload` task?
- would that solve the issue?

**Comment by jastice** [comment]
From my point of view having `workspace/buildTargets` detect reload as necessary would be easier of course, but a `workspace/reload` request would also not be too disruptive, as long as it's indicated in `InitializeBuildResult` that this request is supported.

Should this be a part of the main protocol, what do you think @olafurpg @jvican ?

**Comment by eed3si9n** [comment]
Note that as of sbt 1.3.0 there's a key `Global / onChangedBuildSource` that lets user reload the build automatically by setting it to `ReloadOnSourceChanges`.

> The import works just like before - the project was not refreshed.

If the `build.sbt` was edited but hasn't been reloaded, then I would say that as far as sbt server is concerned the change has _not_ taken place yet. So I think the current behavior is ok.

**Comment by adpi2** [comment]
> If the build.sbt was edited but hasn't been reloaded, then I would say that as far as sbt server is concerned the change has not taken place yet. So I think the current behavior is ok.

That I agree.

But still, build clients need a proper way to force the reload, in case `Global / onChangedBuildSource` is not set. We dont want to impose that setting on all users.

As a temporary hack IntelliJ can use the `sbt/exec` request with params `{ "commandLine": "reload" }` that already exists. Have you tried it @jastice?

However it is better if it is specified in BSP so that you don't have to make an exception for sbt.

**Comment by jastice** [comment]
> As a temporary hack IntelliJ can use the `sbt/exec` request with params `{ "commandLine": "reload" }` that already exists. Have you tried it @jastice?

I haven't tried it yet but it sounds like a good interim solution!

Agree a proper protocol extension would be good for other build tools that have a concept of server state / reloading

**Comment by olafurpg** [comment]
When to "reload" the build has been a recurring issue in Bloop as well so it's clear we're missing an endpoint for this functionality in BSP. We currently have custom logic in Bloop to trigger a build refresh on `workspace/buildTargets` only when IntelliJ is the client, which is a hack that I would love to get rid of.

Related sidenote: Metals uses BSP a bit differently compared to IntelliJ by the fact that Metals doesn't persist the result of `workspace/buildTargets`, it only stores the build graph in-memory for the lifetime of the Metals process or until the next "Import build" command. 

I like the proposal by @adpi2 in https://github.com/sbt/sbt/issues/5783#issuecomment-688955751 I'd be happy to LGTM a PR adding this extension to BSP. It might be worth mentioning in the BSP documentation that `workspace/reload` has a higher risk of failing than `workspace/buildTargets`. The way I think of is that `workspace/buildTargets` should ideally return the "last well known state of the build", even if the current build definition has a problem. Not sure if this is easy to implement on the server side in practice but it would be a helpful concept from the IDE client's perspective.

**Comment by jvican** [comment]
I think that proposal makes sense too and I agree that `workspace/buildTargets` should be a best-effort task to return the latest up-to-date targets 👍

**Comment by jastice** [comment]
Great, I'll open a PR for the `workspace/reload` request in BSP then!
