### ISSUE TITLE
Service loading (compiler bridge discovery) doesn't work reliably

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5802]
This is an offshoot from https://github.com/sbt/zinc/pull/903 / https://github.com/sbt/sbt/issues/5798 reported by @eatkins 

## steps

```
scripted actions/cross-multi-project
```

## problem

`scripted actions/cross-multi-project` successfully loads the instance of CompilerInterface2 for Scala 2.13.1 but not for 2.12.12.

## expectation

It works consistently.

## notes

It seems like maybe there is some kind of conflict between the sbt metabuild loader (or launcher loader?) and the Scala instance class loader.

https://github.com/sbt/zinc/pull/903 contains a workaround for this issue, so if we want to investigate the root cause we need to remove the fallback added in there.

**Comment by eatkins** [comment]
Yeah, I think that the service is being loaded from the SbtMetaBuildLoader when 2.12 is used but I'd have to verify that.

**Comment by eed3si9n** [comment]
Works-for-2.13-but-not-2.12.12 makes me think it's related somehow to scalaInstanceTask - https://github.com/sbt/sbt/blob/1b99049fbca6439280631b800cc237a171301878/main/src/main/scala/sbt/Defaults.scala#L898-L926 then the bridge and `AnalyzingCompiler` are constructed around here? - https://github.com/sbt/sbt/blob/1b99049fbca6439280631b800cc237a171301878/main/src/main/scala/sbt/Defaults.scala#L669-L691

I wonder if `classLoaderCache` would play a role in any of this.

**Comment by eatkins** [comment]
Aah, yeah, this could definitely be why the behavior is different depending on scala version.

**Comment by eed3si9n** [comment]
> Aah, yeah, this could definitely be why the behavior is different depending on scala version.

If it works for 2.13, then I feel like we can absolve Zinc, and place the responsibility on sbt to properly setup a ClassLoader layer? Were you using sbt 1.3.x to build sbt/sbt? If so I wonder if the compiler bridge for sbt 1.3.x is leaking over to the scripted test.

**Comment by eatkins** [comment]
>  Were you using sbt 1.3.x to build sbt/sbt?

No. I am trying to help get 1.4.0 out the door ASAP so I dogfood the latest code (sometimes including unmerged workarounds) unless I have to use 1.3.13 for something that I don't have a workaround or a fix for.

> then I feel like we can absolve Zinc

I don't fully agree. I think `DualClassLoader` is a flawed construct that is very prone to buggy behavior. Every time I have tried to use it (or my own home rolled version) something goes wrong. The fundamental flaw is that `DualClassLoader` makes strong assumptions about what classes can be loaded in each loader. This can be problematic if the same classes are available in both loaders. Suppose you have classes foo.A, bar.B. Now suppose that the `DualClassLoader` is set up to load foo.A from the left loader, A, and bar.B from the right loader, B. Now assume further than foo.A is a dependency of bar.B and is available in a parent of the loader B and that bar.B is loaded before foo.A by the `DualClassLoader`, then foo.A will be loaded by loader B for for.B even though the dual loader is supposed to only load foo.A from loader A. This is because the `DualClassLoader` as currently written cannot prevent a parent loader from loading a class that it isn't supposed to. To fix this, we'd need to make `DualClassLoader` recursive in the sense that we need to make every layer of the loader a `DualClassLoader`.

To make the example above concrete, my guess is that what is happening is that `xsbti.compile.CompilerInterface2` is being loaded by the meta build class loader because the dual loader is being constructed like so:
```
createDualLoader(scalaInstance.loader(), getClass.getClassLoader) 
```
The `getClass` in this case is the class of `AnalyzingCompiler`, which is provided by the sbt meta build loader. I think that the service loader is able to load `xsbt.CompilerBridge` from the meta build loader using reflection but that it has the wrong kind of `xsbti.compile.CompilerInterface2` so it is rejected as a viable service. I haven't actually tested this but this would be consistent with some of the things I've seen when debugging.

Now, if what I wrote is correct, then one way to fix this would be to do something similar to what I did with the test-interface jar and add a class loader layer between the test-interface loader and the meta build loader (or add the compiler-interface jar to the test-interface layer). If we did this, I think we could get rid of the `DualClassLoader` usage in AnalyzingCompiler though I'm not sure if it would break other consumers of zinc. It's also possible that `DualClassLoader` is necessary even if we rework the layers of the meta build loader but I'm not really sure. I just woke up with this hypothesis and am documenting it.

**Comment by eatkins** [comment]
I verified that service loading works if we put the compiler interface jar in the same classloader as the test interface jar above the rest of the sbt classpath in the classloading hierarchy.

**Comment by eatkins** [comment]
I think we can close this, see https://github.com/sbt/zinc/pull/903#issuecomment-683979214

**Comment by eed3si9n** [comment]
That's a good news.
