### ISSUE TITLE
Undocumented and unexpected behaviour of SBT multimodal tests

### ISSUE THREAD

**Issue by Somewater** [sbt/sbt#5821]
Looks like `sbt test` run any module tests as separated process or something. And SBT initialize any `object` multiple times, one time per any module.
I didn't find anything about it in documentation.

## steps

See simple example:
https://github.com/Somewater/sbt_test_behaviour

```
sbt test:compile
sbt testOnly
```

## problem

Observed behavior: `~~ Base created ~~` will print twice, one time from every module

## expectation

Expected behavior: `~~ Base created ~~` will print only once because it's action inside of `object Base` initialization

## notes

Works the same on junit and specs2 framework. So I think it's a feature of SBT itself.

**Comment by eed3si9n** [comment]
@Somewater Thanks for creating a repro project. I pulled out steps, problem, and expectation from the readme of the repo.

If I understand correctly about what's being reported, the behavior works as we (sbt developers) intended, so in that sense it's not a bug. I'd be happy to link to documentation or discuss improvements we can make either to the test or the docs.

### default root project

I think the main points are covered in https://www.scala-sbt.org/1.x/docs/Multi-Project.html.
First, your build is missing a root project, which is perfectly fine, but that would create a [_default root project_](https://www.scala-sbt.org/1.x/docs/Multi-Project.html#Default+root+project), which aggregates all defined subprojects in the build.

So imagine there's something like:

```scala
lazy val root = (project in file("."))
  .aggregate(base, foo, bar)
```

### aggregation

When you run `sbt test` or `sbt testOnly` you're issuing the task to the root project. The root itself does not define any tests, but it has [aggregation](https://www.scala-sbt.org/1.x/docs/Multi-Project.html#Aggregation):

> Aggregation means that running a task on the aggregate project will also run it on the aggregated projects. 

So running `sbt test` is equivalent to issuing `sbt "all base/test foo/test bar/test"`, which tells sbt to execute 3 tasks in parallel.

### running foo/test

Let's look at `foo/test` alone. sbt will try to emulate an isolated test runner (test runners are provided by the test framework or junit-interface), and construct a sandbox ClassLoader to execute test suites in `foo` subproject only.

Similar thing takes place _concurrently_ for `bar/test`.

Note here concurrency means that neither `foo/test` or `bar/test` depend on each other, and therefore execution order does not affect the results of the test. Depending on the work load sbt task scheduler may chose to execute `foo/test` first, `bar/test` first, or both overlapping. All this is possible because we treat `foo/test` and `bar/test` as individual tasks.

**Comment by Somewater** [comment]
Thanks @eed3si9n ! Great explanation!
