### ISSUE TITLE
Make remoteCacheId content-based

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5842]
## steps

Assuming subprojects `app` and `core`

```
pushRemoteCache
// make some changes to app
// git commit -m "wip"
pushRemoteCache
```

## problem

This would create a new remote cache for all subprojects.

## expectation

Ideally, we should generate remoteCacheId based content hash, so if I didn't change `core`, the remoteCacheId remains the same, and thus I don't need extra network IO to push/pull the same JARs.

**Comment by melezov** [comment]
I'm trying out something like this, but unsure what to do with external files... :/

    remoteCacheId := {
      // normalize Windoze / linux newlines, simple version
      // e.g. this should only be done if scala.util.Properties.isWin
      val base = baseDirectory.value.getAbsolutePath.replace('\\', '/') + '/'

      val hashes = (Compile / sources).value.map { srcFile =>
        val srcPath = srcFile.getAbsolutePath.replace('\\', '/')
        val relPath = if (srcPath.startsWith(base)) {
          // this looks horribly awful given that you've already plugged in
          // that ${BASE} file path virtualisation, but unsure how to get to that
          srcPath.substring(base.length)
        } else {
          // decide what to do with external source paths
          sys.error("Cannot produce relative path: " + srcPath)
        }

        // not very efficient, but it's in SBT already
        val srcHash = sbt.io.Hash(new FileInputStream(srcFile))
        relPath -> srcHash
      }

      // wait to collect all the hashes before trying to merge them
      // we want to ensure order of relative paths which may not be guaranteed across machines
      val hasher = MessageDigest.getInstance("SHA")
      hashes.sortBy(_._1).foreach { case (relPath, fileHash) =>
        hasher.update(relPath.getBytes("UTF-8"))
        hasher.update(0: Byte)
        // use 0: Byte splitters to prevent funny business 
        // e.g. FileA.txt: "TEST1", FileB.txt: "TEST2"
        // e.g. FileA.txt: "TEST1F", ileB.txt: "TEST2"
        hasher.update(fileHash)
        hasher.update(0: Byte)
      }
      sbt.io.Hash.toHex(hasher.digest())
    }

**Comment by melezov** [comment]
A few issues I've noticed with this naive approach:

1) Any insignificant change to the source files will completely change the digest hash, making any match impossible (unless the EXACT same change was already cached on remote). This makes it not very usable in practice.

2) Interop with generated sources
This solution requires all source generators to run before calcing the hash.
It may be good to think about hashing only unmanaged files since source generation can either take a long time or produce unstable hashes (e.g. by embedding build time / commits a'la buildinfo).

Not depending on source generators would also make 1) simpler since we could "just" depend on `git HEAD` revision, producing consistent hashes even if files were changed in working directory.

**Comment by melezov** [comment]
I'm investigating an approach which seems much better than hashing files in the working directory.
The approach uses JGit to directly consume hashes of sources backwards throughout the commit history.
This allows to calculate hashes per project instead of the global commit ID.
An added benefit is that SBT would not depend on an external installation of git as it currently does, but would be "packing one via dependencies".
Will post some code if it would be interesting for consideration.
