### ISSUE TITLE
clean should not follow symlinked directories in `target/`

### ISSUE THREAD

**Issue by michalrus** [sbt/sbt#5852]
## steps

```
sbt.version=1.3.0
```

Any `build.sbt`.

Steps:

```
mkdir ~/sbt-test/
echo test > ~/sbt-test/file.txt
cd /some/sbt/project/
mkdir target/
ln -s ~/sbt-test/ target/

sbt clean
```

## problem

If you do the above ↑, then `file.txt` is gone from the system. Data loss. This is absurd.

## expectation

Remove just the `target/sbt-test` *symlink*, and not files inside its target.

## notes

Imagine if `rm -r` did that…

**Comment by eed3si9n** [comment]
The intent of `clean` task is to remove the _contents_ under `target`. I guess we can change it to not _follow_ symlinks.

**Comment by eed3si9n** [comment]
Relevant part of the code is likely - https://github.com/sbt/sbt/blob/70111bb6892e333f5427c4146797f39f904ac28d/main/src/main/scala/sbt/internal/Clean.scala#L33-L51

**Comment by eatkins** [comment]
#5855 should fix this

> If you do the above ↑, then file.txt is gone from the system. Data loss. This is absurd.

I'm sorry that you experienced data loss. sbt is run by volunteers who are doing their best. When reimplementing clean a while back, I tried to be as careful as possible with clean to ensure that we didn't delete files outside of the target directory. Normally the target directory is reserved for files that are created as output of sbt tasks and I unfortunately didn't think of the use case of a user symlinking a directory. I absolutely agree that if this behavior had been present by design then it would have been absurd but it was just an unfortunate oversight.

**Comment by michalrus** [comment]
@eed3si9n @eatkins great, thanks so much for a quick reaction and a fix! :green_heart:

I’m sorry that my report was too rough, the data has been reconstructed (thankfully not by humans :stuck_out_tongue:), it took several hours.

**Comment by eatkins** [comment]
Water under the bridge. I'm glad that you were able to restore the lost data.
