### ISSUE TITLE
[1.4.0-RC1] ${BASE} in paths reported from compiler breaks hyperlinking to source

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#5853]
## steps

use sbt 1.4.0-RC1, compile a project with some warnings or errors

## problem

compiler messages are reported like `[warn] ${BASE}/modules/magnolia/src/test/scala/A.scala:166:18:` which makes tools like intellij unable to recognize that this refers to a file and provide hyperlinks

## expectation

compiler messages report full paths to files like `[warn] /home/user/modules/magnolia/src/test/scala/A.scala:166:18:` so that tools are able to parse the log

**Comment by eed3si9n** [comment]
@OlegYch Thanks for the report. I've noticed this too.

When I originally implemented virtualization I think I did implement this in https://github.com/sbt/sbt/pull/5417/commits/3ce4d22b84aa6b4140907fcfcffcb521f82c5a81#diff-58c1ab41b5ea609053ceb7f30c2f660d, but maybe it regressed when the reporter moved to https://github.com/sbt/sbt/blob/70111bb6892e333f5427c4146797f39f904ac28d/main/src/main/scala/sbt/internal/server/BuildServerReporter.scala. /cc @adpi2

Maybe we could add a setting (default enabled) that would display the full path like current sbt 1.3.x since some people may prefer the machine-independent path.

**Comment by OlegYch** [comment]
@eed3si9n sounds like a good plan

**Comment by adpi2** [comment]
Actually this issue is caused by the `Problem` value that is built by Zinc. It contains a `Position` made of `sourceFile`, the real file, and `sourcePath`, which happens to be the machine-indepentent path aka the virtual file id. [Here is the code](https://github.com/sbt/zinc/blob/67afa3062985e1be1b3f3df89a14cd8f4f94f4e1/internal/compiler-bridge/src/main/scala/xsbt/DelegatingReporter.scala#L93-L97).

It would be rather easy to fix this issue on Zinc side by setting the absolute path of the file to `sourcePath`. It should be safe since it is only consumed by the implementation of `Reporter` (`BuildServerReporter` and `LoggedReporter`).

Then if we want to implement your proposition @eed3si9n we can use the `FileConverter`.

**Comment by adpi2** [comment]
I have an alternative solution which is to use a `sourcePositionMappers` that will convert all `Position` to absolute depending on a Boolean setting `reportAbsolutePath`. I try this out.
