### ISSUE TITLE
Remove eviction warnings

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#5976]
The reality is that eviction warnings do not help. The problem is not that they might point to a problem but that, in practice, every project *takes advantage* of evictions to solve the dependency problem, so evictions are expected in a project of a certain size. Any real problem will be dominated by a multitude of false positives.

And false positives are in there by design, because
 1. eviction is the main feature of the dependency resolution engine
 2. compatibility rules are different for different projects (so sbt falls back on the most pessimistic interpretation of "every two distinct versions might be incompatible")
 3. even if rules like semver exist, the opposite of "guaranteed backward compatibility" is not "incompatibility" but "maybe a potential probability of incompatibility in particular parts but most likely everything is fine"

The intention might have been good, but the reality makes those useless and annoying.

**Comment by eatkins** [comment]
My first thought was to reduce the level of eviction warnings to debug but debug logging is almost useless for most users because it is so verbose. If they were reduced to info, which sort of makes sense, it doesn't help anything since the default logging level is info.

This reveals a broader issue that I have with the sbt logging system. In my opinion, the tagged logging is a bit overused. Right now almost all of the sbt logging that is displayed to the user is at the info level with the `[info]` tag. This makes the sbt output very verbose by default for many tasks. Often the majority of the output isn't useful. Running at the warn level though actually breaks the ux of certain features like `~`, where the instructions are logged at the info level (which was a change I made because at the time of the change, using println could cause the instructions to be printed before the previous task had finished logging). If you run `sbt -warn`, you also wont see any output at all until the eviction warning is printed and the shell prompt appears.

This may be a complete nonstarter for legacy reasons, but the change I would make if it were solely up to me is that I would change logger.out and logger.err to just print to stdout and stderr without adding a tag. There are a number of messages that are logged at the info level, like the welcome banner and the `~` instructions that I would change from logger.info to logger.out. I would also change the default log level to warn. I think that would make the overall ux much more pleasant for the majority of use cases while still allowing users to turn on info logging if they need more information. Basically I think that if there are no warnings or errors, a user shouldn't see any tagged output. This would make the sbt output more similar to what you see from other tools like gradle and mill which are generally significantly less verbose than sbt.

I know this isn't entirely germane to the actual issue but this has been kicking in my head for a little while but didn't feel quite worthy of making a standalone issue.

**Comment by eed3si9n** [comment]
IMO laissez-faire JAR-swapping is one of the largest threats to JVM ecosystem. What's the point of carefully crafting type system, if we're all going to swap it out with a mystery JAR right when we're about to deploy the service? I'd say precisely _because_ the evictions are unavoidable once the classpath becomes large, we should highlight the potential problematic evictions that human may miss.

I'd be the first to admit that the current implementation leaves much to be desired, but given that many projects fit into certain mold, I personally think it's not impossible to reduce the false positives for the majority of the users. Instead of removing seat belts from the cars, I think we need to improve on the safety by making it detect the dangers at better precision.

**Comment by eatkins** [comment]
The more I think about it, it's kind of a damned if you do, damned if you don't situation. Right now, the eviction warnings feel like a broken check engine light. It is impossible to tell from the warning whether or not there is actually a problem so it feels annoying rather than helpful. I am not sure that I believe this, but I could make an argument that the warnings are actually harmful because the high false positive rate cause it to be ignored. Let's say a user's build is working great but there are some harmless evictions and then the user adds a new library that causes an eviction that actually breaks the application. Because they were being warned before and the application was working, they probably won't even think to check if there is a problem with the new library. That's why I find the false positives problematic.

On the other hand, you make a great point about the type system. You're actually kind of lucky though if the reason for the eviction is type related. The problem that you see would then be likely to be a runtime crash. What is more insidious is a library that uses semantic versioning but introduces a regression in an implementation in a newer version. I don't know how any dependency management system could guard against that so that is an argument for displaying eviction warnings.

Given the high rate of false positives, maybe this can be made to be more like the unused setting lint rules? I'm thinking of something like expanding EvictionWarningOptions to allows the user to whitelist certain artifacts from warnings? What is frustrating about the current state of affairs is that there is no way to turn off harmless warnings besides disabling the warning entirely which could then mask a real problem when a new library is introduced.

**Comment by japgolly** [comment]
Hi! Just chanced upon this discussion and will add my 2c

> I am not sure that I believe this, but I could make an argument that the warnings are actually harmful because the high false positive rate cause it to be ignored

That's exactly what happened in my case. I thought this was such a great idea when it first came out. Now I have no faith in it at all to provide me with any value and I just want to disable it to stop it spamming me. I'm always in the sbt shell; it's my primary interface and to me personally, useless log lines has a high impact and I really strive to remove them. When the evicted feature first came out, I used to run `evicted` and look at what it's reporting but everything it reported was a completely acceptable (and desirable) eviction. Now I've come to subconsciously just treat this feature as noise.

> JAR-swapping is one of the largest threats to JVM ecosystem

Personally I have this problem no more frequently than once every 5-10 years.

> Instead of removing seat belts from the cars, I think we need to improve on the safety by making it detect the dangers at better precision

I agree with the attitude, it would be great if this 1) became practically useful, and 2) stopped annoying users, but we're not there yet. It's a good argument for wanting to spend time in the future to improve the feature, but it's a not a good argument for keeping the status quo, knowing that it's having a primarily negative impact (at least IMO). So if your seatbelts don't work and you're hoping to fix them in a year's time, you should remove the seatbelts until they're fixed. If you don't, we drivers will and we probably won't put them back in our metaphoric cars once seatbelts v2 arrive because we've learned to just write-off the potential usefulness of the feature.

**Comment by eed3si9n** [comment]
Here's my proposal to remove eviction warning in 1.5.0, and replace it with something better, which instead of warning it would actually fail the `update` task, but only do so when it's 100% sure, and remove the guessing completely:
https://eed3si9n.com/enforcing-semver-with-sbt-strict-update
