### ISSUE TITLE
sbt should reject projects with dependencies on multiple versions of the same artifact

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#603]
I recent was bitten when a project had a direct dependency on one version of an artifact, but an indirect dependency on a different version of the same artifact. The result was to silently place the indirect dependency on the classpath, leading to extremely difficult to diagnose compilation errors.

IMHO, sbt should refuse to accept a project definition in such cases, and provide helpful diagnostics about the conflicting versions and where they come from in the dependency graph.

**Comment by markkolich** [comment]
+1

It would be nice to be warned about such conflicts, if not natively from SBT maybe via a plugin.

It's my understanding you can use the "exclude" directive to exclude an indirect dependency pulled in by a direct dependency but you have to ~know~ to do that &mdash; there's no automatic conflict warning afaik stating "SBT has resolved all dependencies, and btw, you have (2) versions of the same artifact on your classpath."

``` scala
libraryDependencies += "foo" % "bar" % "0.7.0" exclude("org.baz", "bam")
```

Indirectly, the behavior & checks provided by something like Maven Enforcer would be very helpful:

http://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html

**Comment by harrah** [comment]
Some quick notes:
1. This behavior is configured via a conflict manager.
2. The default conflict manager selects the latest revision.
3. There is a strict conflict manager that does not allow conflicts.  It is rather unlikely this would be the default any time soon, just because too many people expect conflicts to be auto-resolved and I'm not sure what it does to the transitive library situation.
4. I believe the default conflict manager for Maven is something called "nearest", which selects the version by the dependency's distance from the root.
5. You should not get two versions of the same artifact on the classpath- one should be evicted.
6. The result of `update` is an [UpdateReport](http://www.scala-sbt.org/release/docs/Detailed-Topics/Update-Report.html), which includes all evicted dependencies.  It doesn't include the resolved tree like you would need for the full Maven Enforcer functionality, but that could be added.
7. If you've ever seen a warning about conflicting versions of Scala or sbt, this is from the conflictWarning setting, which by default only warns about conflicts from these two, but can be configured to warn more.  Again, there is no path from explicit dependencies printed.
8. The XML reports in target/resolution-cache can be viewed in a web browser and give details about the resolution, including paths I think.
9. The force() method on a dependency (ModuleID) will tell Ivy to fix the revision to that one.

I have omitted details, like how to configure the conflict manager and conflict warnings.  (I don't think there is a setting for the conflict manager yet.)  This is mainly to inform further discussion.

**Comment by ghost** [comment]
Mark, this is awesome information, thanks!

One FYI: I have to roll d20 to disbelieve point 2; I very definitely was getting compiles against an indirectly-depended-upon old version of an artifact I had a direct dependency on a newer version of. I'm perfectly prepared to believe that's due to an Ivy2 bug.

Personally, I would love the information about configuring the conflict manager and warnings, as well as supported access to the strict conflict manager. It's frankly a bit surprising to me that the expectation seems to be that conflicts are automagically resolved in favor of the latest version. The implicit assumption that whatever depends on the old version of the artifact will work with the newer version seems... optimistic... to me. :-)

Thanks again!

**Comment by harrah** [comment]
I'd probably need to see an example to comment more on the issues with resolution picking an older version.  There are two situations that I know of that could be problematic, though.  First, Scala is treated specially for various reasons and conflicts there may be automatically resolved to be `scalaVersion`.  Second, because of limitations of the pom format, cross versioning has to modify the module ID, which means resolution doesn't know that x_2.9.1 is the same module as x_2.9.2 and so conflicts can't be resolved.

The conflict manager is indeed not currently configurable, so this bug will be for a) documentation b) a configurable conflict manager.  As for resolving conflicts, the main problem in my opinion is a deficient metadata model.  You need to know the unique version, source compatibility version, and binary compatibility version to do automatic resolution properly (in my opinion).  The pom format isn't changing, so we have to work with what we have or make a new one, unfortunately.

Here is how to set the conflictWarning setting to fail `update` on conflicts.  This conflict checking is done by sbt after `update` completes,  so it can't avoid unnecessary downloads like a proper conflict manager inside Ivy would.

``` scala
conflictWarning ~= { cw => 
  cw.copy(filter = (id: ModuleID) => true, group = (id: ModuleID) => id.organization + ":" + id.name, level = Level.Error, failOnConflict = true)
}
```

The `group` value determines how to group dependencies to check for conflicts.  `level` is the logging level to write the message at.  `failOnConflict = true` means the `update` task will fail if there are any conflicts.  `filter` can be used to only do conflict detection for the selected modules.  We set it to accept everything here because by default, it is enabled only for sbt and Scala artifacts.

This is really a workaround for not being able to configure the conflict manager, but let me know if you have any issues.
