### ISSUE TITLE
sbt 1.4.2 BSP disabled still generates .bsp/sbt.json which causes problems with IntelliJ IDEA

### ISSUE THREAD

**Issue by hamnis** [sbt/sbt#6066]
## steps
Bloop sbt-plugin installed
```
bloopExportJarClassifiers in Global := Some(Set("sources"))
bspEnabled := false
```
run `sbt bloopInstall`

## problem
`.bsp/sbt.json` is till generated which intellij tries to read and that causes some problem

## expectation
Do not generate any files in `.bsp`

**Comment by eed3si9n** [comment]
@hamnis Thanks for the report.

**Comment by tanishiking** [comment]
I also think it would be ideal if there's a way not to write the BSP connection file, because if there's a `.bsp/sbt.json`, [metals.bsp-switch](https://scalameta.org/metals/blog/2020/11/06/sbt-BSP-support.html#metalsbsp-switch) shows `sbt` as its candidate, even though sbt doesn't provide some BSP functionalities (if we set `bspEnabled := false`). It might be a bit confusing for users, though it's a niche case.

So, I took a quick look at this issue.

The `.bsp/sbt.json` is written by [BuildServerConnection.writeConnectionFile](https://github.com/sbt/sbt/blob/f4921e3dd7ec18aa026e603ee31dd79d03e41365/protocol/src/main/scala/sbt/internal/bsp/BuildServerConnection.scala#L21-L39) and it is called from

- on sbt server starts https://github.com/sbt/sbt/blob/f4921e3dd7ec18aa026e603ee31dd79d03e41365/main-command/src/main/scala/sbt/internal/server/Server.scala#L100-L103
- and from `bspConfig` https://github.com/sbt/sbt/blob/f4921e3dd7ec18aa026e603ee31dd79d03e41365/main/src/main/scala/sbt/internal/server/BuildServerProtocol.scala#L81-L84

---

As `bspEnabled` is `SettingKey`, to prevent (or not) sbt from writing the BSP connection file, it would be perfect to check if `bspEnabled` is `false` **for all scopes**, I guess.

So here're questions,

- Is there a reasonable way to check the value for all scopes?
- Or should we add another **global** boolean setting that controls whether sbt writes the BSP connection file or not?

**Comment by jastice** [comment]
For what it's worth, I also intend to fix this on IntelliJ side: https://youtrack.jetbrains.com/issue/SCL-18503

**Comment by fooblahblah** [comment]
I have the `bspEnabled := false` all over the place in my build and sub-projects and am still seeing the file `.bsp/sbt.json` get created when I enter sbt in interactive mode. Is this feature working for others? I'm using SBT 1.4.5, but also tried 1.4.4.

It appears to be when the sbt server starts. I changed the permissions on `.bsp` removing write privs and got this:
```
[info] set current project to homebay (in build file:/home/jsimpson/workspace/homebay/)
[info] sbt server started at local:///home/jsimpson/.sbt/1.0/server/25213a577b082d7e9512/sock
Exception in thread "sbt-socket-server" java.io.FileNotFoundException: /home/jsimpson/workspace/homebay/.bsp/sbt.json (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at sbt.io.Using$.$anonfun$fileWriter$1(Using.scala:108)
	at sbt.io.Using$$anon$3.openImpl(Using.scala:86)
	at sbt.io.OpenFile.open(Using.scala:53)
	at sbt.io.OpenFile.open$(Using.scala:47)
	at sbt.io.Using$$anon$3.open(Using.scala:85)
	at sbt.io.Using$$anon$3.open(Using.scala:85)
	at sbt.io.Using.apply(Using.scala:25)
	at sbt.io.IO$.writer(IO.scala:954)
	at sbt.io.IO$.write(IO.scala:948)
	at sbt.internal.bsp.BuildServerConnection$.writeConnectionFile(BuildServerConnection.scala:38)
	at sbt.internal.server.Server$$anon$1$$anon$2.run(Server.scala:103)
[warn] sbt server could not start in 10s
```
