### ISSUE TITLE
github actions scripted failures

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#6123]
The scripted tests: project/sbt-file-project and project/src-scala-binary-version are failing. In the case of project/src-scala-binary-version, it was recently marked pending and can be fixed by reverting 3d02f8902eade8151a94459228d5985bd9f9174a. I don't know why project/sbt-file-project is failing. It works fine locally.

**Comment by eed3si9n** [comment]
### project/src-scala-binary-version

https://github.com/sbt/sbt/tree/develop/sbt/src/sbt-test/project/src-scala-binary-version

In https://github.com/sbt/sbt/pull/6077 `project/src-scala-binary-version` was failing as https://github.com/sbt/sbt/pull/6077/checks?check_run_id=1371804586

```scala
[info] Running project/src-scala-binary-version
[info] [info] welcome to sbt 1.4.3-SNAPSHOT (AdoptOpenJDK Java 11.0.9)
[info] [info] loading settings for project sbt_b8f3399b from build.sbt ...
[info] [info] loading settings for project b from build.sbt ...
[info] [info] set current project to a (in build file:/tmp/sbt_b8f3399b/)
[info] [error] Not a valid command: check (similar: help)
[info] [error] No such setting/task
[info] [error] check
[info] [error]      ^
Error:  x project/src-scala-binary-version 
Error:   Cause of test exception: {line 1}  Command failed: check failed
```

### project/sbt-file-projects

https://github.com/sbt/sbt/blob/develop/sbt/src/sbt-test/project/sbt-file-projects/build.sbt

In https://github.com/sbt/sbt/pull/6121 `project/sbt-file-projects` is failing in a similar fashion - https://github.com/sbt/sbt/pull/6121/checks?check_run_id=1425270690

```scala
[info] Running project/sbt-file-projects
[info] [info] welcome to sbt 1.5.0-SNAPSHOT (AdoptOpenJDK Java 11.0.9)
[info] [info] loading global plugins from /tmp/sbt_49ed9688/global/plugins
[info] [info] loading settings for project a from a.sbt ...
[info] [info] loading settings for project b from build.sbt ...
[info] [info] loading settings for project sbt_49ed9688 from build.sbt,other.sbt ...
[info] [info] set current project to a (in build file:/tmp/sbt_49ed9688/)
[info] [error] Not a valid command: g
[info] [error] No such setting/task
[info] [error] g
[info] [error]  ^
Error:  x project/sbt-file-projects 
Error:   Cause of test exception: {line 1}  Command failed: g failed
```

### observation

These both have:

```
[info] [info] set current project to a (in build file:/tmp/sbt_b8f3399b/)
[info] [info] set current project to a (in build file:/tmp/sbt_49ed9688/)
```

If somehow there's an onLoad action to change the subproject it would explain why `g` task is not visible.

I wonder if there's some leakage among the batched scripted test that we're now seeing due to some change in sorting order and/or concurrency of the scripted tests.

**Comment by eatkins** [comment]
Aah, that does make sense because I noticed that when I run sbt-file-projects with `scriptedBufferLog := false` that I see two instances of project loading before it runs anything.

**Comment by eatkins** [comment]
Sorting the tests does seem to "fix" it: https://github.com/sbt/sbt/pull/6125. Even though it probably doesn't address the underlying problem, at least it should be easier to reproduce issues locally with deterministic test ordering.
