### ISSUE TITLE
problem using scala 2.13.4 when Global / semanticdbEnabled := true

### ISSUE THREAD

**Issue by pjfanning** [sbt/sbt#6144]
## steps

* SBT 1.4.3
* tried to change https://github.com/pjfanning/swagger-akka-http-sample/blob/master/build.sbt to use scala version 2.13.4
* I also have

```
~/.sbt/1.0/global.sbt 

Global / semanticdbEnabled := true
```

## problem

Get an issue fetching a jar:

[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.13.4:4.3.20

## expectation

org.scalameta:semanticdb-scalac_2.13.4:4.4.0 is available - would it be possible to do an sbt release that upgrades the semanticdb-scalac dependency?

## notes

I probably don't need to set semanticdbEnabled -- https://github.com/sbt/sbt/issues/5977

**Comment by adpi2** [comment]
Hi @pjfanning! Thank you for reporting.

It is not really an sbt bug.

The issue is rather that the version `4.3.20` of the `semantic-scalac` plugin is not available for the very new Scala `2.13.4`. But the version `4.4.0` is available: https://mvnrepository.com/artifact/org.scalameta/semanticdb-scalac_2.13.4.

So you just need to set
```
Global / semanticdbVersion := "4.4.0"
```
