### ISSUE TITLE
prominent warning when depending on "binary" Scala version

### ISSUE THREAD

**Issue by adriaanm** [sbt/sbt#622]
scenario:
1. you have a project using scala 2.10.0 with a lot of dependencies, some cross-versioned in full (2.10.0), others depending on (2.10)
2. we release 2.10.1
3. you depend on a new version of a binary-versioned dependency
4. you don't realize you should also make sure to bump your scalaVersion to 2.10.1
5. that newer version is missing a method --> NoSuchMethodError
6. sadness

I think it would be good if step 4. would pre-empt the original ones and its successors:

_4._ SBT says: 'WARNING WARNING you should upgrade to the latest scala 2.10 release as you're depending on a "binary versioned" dependency that might depend on a newer scala version than 2.10.0'

**Comment by harrah** [comment]
As of 0.13, the situation in 1 won't happen by default because sbt will generate an error when cross-versions are mixed.  Also, because Scala is treated as a normal dependency now, the Scala version retrieved because of 3 should be 2.10.1.  In light of this, I believe this can be closed.  Please comment if you disagree and I'll reopen.

**Comment by adriaanm** [comment]
Agreed.
