### ISSUE TITLE
ArtifactId of the cross-built plugin drops the suffix for scala and sbt version

### ISSUE THREAD

**Issue by moznion** [sbt/sbt#6479]
## steps

Once I've cross built a plugin according to "[sbt Reference Manual — Cross building plugins](https://www.scala-sbt.org/1.x/docs/Cross-Build-Plugins.html)", it drops the suffix for scala and sbt version (i.e. `_${scalaVersion}_${sbtVersion}`) from the `ArtifactId`.

In fact, this can be reproduced by running `sbt publishM2` on [moznion/sbt-spotless](https://github.com/moznion/sbt-spotless).

## problem

As [this issue](https://github.com/moznion/sbt-spotless/issues/29) reported, sort of the maven proxy raises an error because the artifact path and the artifactId are conflicted.

For example, in case of `sbt-spotless`, the output artifact path is `sbt-spotless_2.12_1.0` but the `artifactId` is `sbt-spotless`. I put the entire pom file below.

<details>
<summary>sbt-spotless-0.1.4-SNAPSHOT.pom</summary>

```xml
<?xml version='1.0' encoding='UTF-8'?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>net.moznion.sbt</groupId>
    <artifactId>sbt-spotless</artifactId>
    <packaging>jar</packaging>
    <description>An sbt plugin for spotless</description>
    <url>https://github.com/moznion/sbt-spotless</url>
    <version>0.1.4-SNAPSHOT</version>
    <licenses>
        <license>
            <name>Apache-2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <name>sbt-spotless</name>
    <inceptionYear>2020</inceptionYear>
    <organization>
        <name>moznion.net</name>
        <url>https://moznion.net</url>
    </organization>
    <scm>
        <url>https://github.com/moznion/sbt-spotless</url>
        <connection>scm:git:https://github.com/moznion/sbt-spotless.git</connection>
        <developerConnection>scm:git:git@github.com:moznion/sbt-spotless.git</developerConnection>
    </scm>
    <developers>
        <developer>
            <id>moznion</id>
            <name>Taiki Kawakami</name>
            <url>https://moznion.net</url>
            <email>moznion@gmail.com</email>
        </developer>
    </developers>
    <properties>
        <scalaVersion>2.12</scalaVersion>
        <sbtVersion>1.0</sbtVersion>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>2.12.10</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.scala-sbt</groupId>
            <artifactId>sbt</artifactId>
            <version>1.2.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.diffplug.spotless</groupId>
            <artifactId>spotless-lib</artifactId>
            <version>1.28.1</version>
        </dependency>
        <dependency>
            <groupId>com.diffplug.spotless</groupId>
            <artifactId>spotless-lib-extra</artifactId>
            <version>1.28.1</version>
        </dependency>
    </dependencies>
</project>
```

</details>

It seems if `build.sbt` has `enablePlugins(SbtPlugin)`, it drops that but I think it needs `SbtPlugin` to do cross-building.

## expectation

I've expected the `artifactId` has the version suffix. In case of the above, `artifactId` would like to be `sbt-spotless_2.12_1.0`.
Has there already been any workaround?

**Comment by eed3si9n** [comment]
@moznion Hi this was a deliberate design choice to encode Ivy's concept of extra attribute to Maven.
There's an existing issue discussing this in detail - https://github.com/sbt/sbt/issues/3410

**Comment by moznion** [comment]
Thank you for the information. I'm sorry for bothering you and your team :bow:
FYI: @domdorn

**Comment by eed3si9n** [comment]
Please don't apologize. This is a legitimate issue.

**Comment by domdorn** [comment]
@eed3si9n: So you say, that the current behavior is intended, right?.. 
That means, I (and everyone else who has to use Artifactory) have to disable "pom file verification" in Artifactory for it being able to resolve (maven-layout published) sbt plugins correctly. 

I'd like to raise my concern, that this is a very sub-optimal solution. Why?
* I (and everyone in a corporate setting who **_has to_** use Artifactory) now have to battle the operations department for this check to be disabled, 
* have to proof that this is necessary and 
* it will show up in security audits where again my team has to explain why this is the way it is and why its "not a problem". 

It also means additional effort required for almost every sbt plugin included in our projects. 
And its another thing stopping people from adopting scala in their work-projects as it needs custom handling vs. just works out of the box. 

This is very annoying, especially as we **_don't want_** to use Artifactory, but **_have to_** use it, for "reproducable" builds. Till recently, we could have said that artifactory is not required because we have maven central, bintray etc. Now that bintray shuts down, its proof for the people forcing us to use Artifactory. 

I hope your last comment on https://github.com/sbt/sbt/issues/3410 means that this will be fixed / the behavior changed.

**Comment by eed3si9n** [comment]
Yes. I completely understand using "suppress POM consistency checks" is suboptimal. This was a technical decision made before my time, and I guess we didn't have that many sbt plugins published in Maven layout so it was not considered to be a huge issue?
