### ISSUE TITLE
Make `/` operator's precedence higher than `:=` operators.

### ISSUE THREAD

**Issue by ohechtl** [sbt/sbt#6535]
## steps

In an build.sbt file if I have an inline config like this:
```
lazy val `example` = (project in file("."))
  .settings(
    (Compile / mainClass) := Some("org.scala.MainApp")
)
```
I need to add parentheses to the `Compile / mainClass` , or any other setting where I need to use `/` operators, otherwise sbt will report errors and refuse to load the build.sbt.

I've spend a couple of hours figuring out this error and failed, my colleague helped me.
I think this is both confusing and hard to debug, and the `/` operator should have higher precedence than the `:=` one.

What is your opinion about this?

**Comment by adpi2** [comment]
This is a surprising behavior, and I cannot reproduce it with the given build.sbt file.

Note that the operator's precedence is defined in the Scala specification and that we cannot change it in sbt (or we should use another operator). Also `/` already has higher precedence than `:=` (because `:=` starts with `:`) as explained [here](https://docs.scala-lang.org/tour/operators.html).

Can you give use more details on how to reproduce?

**Comment by ohechtl** [comment]
oh, it seems that the error was on my part, the compile error came from the problem where the operands were swapped like:
`libraryDependencies in Compile` should become `Compile / libraryDependencies`, and I didnt swap the operands. Thanks for looking into this!
