### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by okarmusk** [sbt/sbt#6541]
I'm trying to build a executable `jar` with `sbt` and unfortunately jar cannot be started cause of:
```
Error: Could not find or load main class target.scala-3.0.0.scala-cheat-sheet_3-1.0.jar
Caused by: java.lang.ClassNotFoundException: target.scala-3.0.0.scala-cheat-sheet_3-1.0.jar
```

My `build.sbt` looks like:
```
name := "scala-cheat-sheet"
version := "1.0"
scalaVersion := "3.0.0"

mainClass in (Compile, packageBin) := Some("com.okarmusk.Main")

crossScalaVersions ++= Seq("2.13.6", "3.0.0")
```

The main:
```
package com.okarmusk

object Main {
  def main(args: Array[String]): Unit = {
    println("Hello world!")
  }
}
```
I've compile project with `sbt compile` then `sbt packageBin` and finally executed `scala target/scala-3.0.0/scala-cheat-sheet_3-1.0.jar` then mentioned error appears.

Worth to mention is that if I run `sbt run` program works.

Scala version: `Scala code runner version 3.0.0 -- Copyright 2002-2021, LAMP/EPFL`
sbt version: `sbt version in this project: 1.5.2
sbt script version: 1.5.2`

**Comment by adpi2** [comment]
This seems to be an issue with the `scala` command rather than an issue with sbt itself. Which `scala` command are you using and how did you install it?

**Comment by okarmusk** [comment]
@adpi2
I installed it from binary on xubuntu 20.04. I put a script to `/etc/profile.d/` what looks like:

```
#!/bin/sh

export SCALA_HOME="/usr/lib/jvm/scala-3"
export PATH=$SCALA_HOME/bin:$PATH
```
Scala is normally visible from bash. Btw I install that way all of JDK connected stuff and every time it works...

**Comment by adpi2** [comment]
Then the issue seems to be https://github.com/lampepfl/dotty/issues/12569

I suggest you use java to run your jar file. But to do so you would have to add the scala libraries to the classpath:
```
java -cp <path to scala-library.jar>:<path to scala3-library.jar>:target/scala-3.0.0/scala-cheat-sheet_3-1.0.jar com.okarmusk.Main
```
An easier alternative is to use the [sbt-assembly](https://github.com/sbt/sbt-assembly) plugin to create a fat jar: a jar that contains the app and all its dependencies

1. Add the plugin in your `project/plugins.sbt` file
```scala
// project/plugins.sbt
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "1.0.0")
```
2. Run `sbt assembly`
3. Run `java -cp target/scala-3.0.0/scala-cheat-sheet-assembly-1.0.jar com.okarmusk.Main`

**Comment by okarmusk** [comment]
Thank you for help, it looks like scala 3 issue.
