### ISSUE TITLE
[BSP] - Scalafix compilation failure 

### ISSUE THREAD

**Issue by github-samuel-clarenc** [sbt/sbt#6562]
## steps

A SBT (1.5.4) / Scala (2.13.6) project with a [scalafix](https://github.com/scalacenter/scalafix) rule that generates a compilation error (with `scalafixOnCompile := true`)

## problem

No information about the error is sent to BSP (and retrieved in Intellij as well). The [CompileResult](https://build-server-protocol.github.io/docs/specification#compile-request) gets a 2 statusCode but no error message is given. 

## expectation

It would be nice to have some information about the failing issue. 

## notes

The [BuildServerProtocol.bspBuildTargetCompile](https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/internal/server/BuildServerProtocol.scala#L155) does not use the [CompileResult.data](https://build-server-protocol.github.io/docs/specification#compile-request) property, maybe we could add this information in this field. 

I can't understand anyway the difference between a "real" compilation error, that actually returns some information about the error and a scalafix generation error, that does not.

**Comment by adpi2** [comment]
When `scalafixOnCompile := true`, the `compile` task run the original `compile` task then it runs the `scalafix` task.

In your case, the original `compile` task probably succeeds and that's why you don't receive any diagnostics. But then the `scalafix` task throws an error. When we catch the error in https://github.com/sbt/sbt/blob/9274a3e365d3cb826ede31598afde412ab6625c1/main/src/main/scala/sbt/internal/server/BuildServerProtocol.scala#L510-L512

We don't make any difference between a "real" compile error and anything else (like a crash of the compiler or a scalafix error). It would probably be a good idea to do so.

**Comment by github-samuel-clarenc** [comment]
OK thanks for your answer, I'll have a look at this point !

**Comment by bjaglin** [comment]
Thanks for putting https://github.com/sbt/sbt/pull/6565 together @adpi2!

If I understand the PR well, and looking at how sbt-scalafix fails compile, it will return an error `(Compile / scalafix) scalafix.sbt.ScalafixFailed: LinterError` (`ScalafixFailed` being a `sbt.FeedbackProvidedException`).

That's already much better than nothing, but I was wondering whether we could go a step further in sbt-scalafix by mapping the error logs [normally sent to the streams logger](https://github.com/scalacenter/sbt-scalafix/blob/9c35cdb3514c1c1f33e0cc762dd46c862c2a88c2/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L350-L355) to `BuildServerReporter.log(Problem)` via `compile / bspReporter`?

The problem I foresee is that `build/publishDiagnostics` is flushed by `compileIncremental`, so before scalafix gets to run. I assume sending 2 diagnostics for a single `build/compile` will cause all sorts of problems on the client side. If we could override `compile / bspReporter`, we could accumulate diagnostics a bit more and postpone the flush, but `BuildServerReporter` being sealed, it looks impossible.

Is it a conscious decision to prevent sbt plugins to customize the BSP diagnostics? If not, can you think of a way to make it possible? Delay the flush to `bspCompileTask` maybe?

**Comment by adpi2** [comment]
> Is it a conscious decision to prevent sbt plugins to customize the BSP diagnostics? If not, can you think of a way to make it possible? Delay the flush to bspCompileTask maybe?

I sealed the interface to prevent any breakage when I had to change it. Now it should be more stable, but I wish plugin authors to be able to use it without overriding it.

The flush cannot happen in the `bspCompileTask` because we also need to flush if the compilation is triggered transitively (a project dependency) or even outside BSP (eg. the user run `compile` manually). Also we want the flush to happen as soon as possible.

Currently, the way it works is:
- the client has received some diagnostics from the previous compilation (they won't disappear until the server send a reset)
- a new compilation is triggered, we use a new reporter (which is empty)
- each new problem is published immediately and stored in the reporter
- when the compilation ends, the reporter sends a reset diagnostic which only contains the stored problems (the old diagnostics disappear)

If the scalafix task sends some diagnostics after that it should work. The only glitch I can think of is some blinkering:
Suppose the client has received a scalafix linting diagnostic and we trigger a new compilation. When the compilation ends the reset is sent and the linting diagnostic disappears. Then scalafix re-publishes it.

Do you think this situation is acceptable? Let me know if you try to implement that in sbt-scalafix.

**Comment by bjaglin** [comment]
> Do you think this situation is acceptable?

Totally, thanks for clarifying the lifecycle of diagnostics :+1: 

> Let me know if you try to implement that in sbt-scalafix.

Sure, I will give it a try in the coming weeks and will ping you on the PR.
