### ISSUE TITLE
Code Cache Always Runs Out

### ISSUE THREAD

**Issue by AugustNagro** [sbt/sbt#6568]
Hi, I'm using Scala 3, metals and the latest SBT with default settings.

In every project I use, which have very minimal/standard configurations, SBT exhausts the CodeCache within 30 minutes or so of development, at which point performance dramatically decreases.

Am I the only one that experiences this?

I'm sure the cause is repeatedly loading new code when `~test`ing, which begs the question, could we use something like [drip](https://github.com/ninjudd/drip#how-does-it-work) to run tests in forked VMs by default, at the same performance?

**Comment by eed3si9n** [comment]
> Am I the only one that experiences this?

It doesn't seem to be the experience for most people. I don't know if it's a specific choice of `Test` or `Compile` dependencies that are not cleaning up after itself, or some other cause. In general it's difficult to either work on this issue or discuss this without reproduction steps. Otherwise, we should close this as a duplicate of https://github.com/sbt/sbt/issues/6413.

**Comment by AugustNagro** [comment]
Sounds good; I will try to make a minimal reproducer to share.
