### ISSUE TITLE
Accessing lmcoursier shaded dependencies triggers Symbol 'term <root>.coursier' is missing from the classpath

### ISSUE THREAD

**Issue by worekleszczy** [sbt/sbt#6651]
## steps

Create a source file under project directory and import any class from `lmcoursier` shaded dependency: eg `project/Trigger.scala`:
```
import lmcoursier.internal.shaded.coursier.Resolve

object Trigger {

}
```
and run sbt command in root directory.

Scala versions tested: `2.11`, `2.13`
Sbt version tested: `1.4.6`, `1.5.5`

## problem

Build fails with following exception:
```
[error] /Users/piotrjosiak/scalac/rallyhealth/lib-arcade-commons/project/Trigger.scala:1:8: Symbol 'term <root>.coursier' is missing from the classpath.
[error] This symbol is required by ' <none>'.
[error] Make sure that term coursier is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of <root>.
[error] import lmcoursier.internal.shaded.coursier.Resolve
[error]        ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

## expectation

I'd expect to be able to use shaded coursier dependency to implement custom tasks without build failing or adding additional coursier dependency. Another thing is that this seems unnatural to me - referenced classes exists inside `lmcoursier` jar file, so if I can access any other class from this jar I should be able to access those from `shaded` package as well. 

##  notes

There seems to be a problem only with shaded dependencies - importing eg `lmcoursier.internal.SbtBootJars` is fine even though there are in the same jar.

**Comment by adpi2** [comment]
This behavior seems intentional to me. The coursier dependency in lmcoursier is shaded to avoid compatibility issues with the classpath of the user's build or plugin:
- as a user you can use the version of coursier that you need
- sbt maintainers can upgrade the version of coursier without breaking anyone's build

**Comment by worekleszczy** [comment]
@adpi2 Thanks for prompt response 🙂 I understand the reasons behind shading. At understand why this is not a great way to use coursier - I stumbled upon this doing PoC of a plugin and this got me thinking - how is this bug even possible? Is sbt somehow guarding this? IMO after this jar is on a classpath all it's parts should be available to use, even though if it's not a good practice 🙂 
Other thing is that after I add this to `plugins.sbt`
```
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "2.0.5")
```
and run update, I get an error:
```
sbt:lib-models> update
[error] stack trace is suppressed; run last coursierResolutions for the full output
[error] (coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] Total time: 0 s, completed 2021-09-06 15:30:23
```

**Comment by adpi2** [comment]
> how is this bug even possible? Is sbt somehow guarding this?

I suspect the problem is that the Scala compiler cannot consume shaded classes. It reads the Scala signatures that are stored in the class files (in the pickle format). But those signatures have become inconsistent after shading, hence the error: `Symbol 'term <root>.coursier' is missing from the classpath.`.

Note that it does work if you consume it from Java directly, in a `project/Trigger.java` file:
```java
import lmcoursier.internal.shaded.coursier.Resolve$;
import lmcoursier.internal.shaded.coursier.core.Dependency;

public class Trigger {
  public void foo(scala.collection.Seq<Dependency> deps) {
    Resolve$.MODULE$.apply().addDependencies(deps);
  }
}
```

But this is not the recommended way.

The best solution for me is to add the dependency to coursier explicitly in your `project/plugins.sbt` file:
```
libraryDependencies += "io.get-coursier" %% "coursier" % "2.0.16"
```
