### ISSUE TITLE
sbt + Scala 3 prints error summary twice

### ISSUE THREAD

**Issue by reibitto** [sbt/sbt#6687]
## steps

- Create a Scala 3 project with `sbt new scala/scala3.g8`
- Intentionally introduce a compile error, like trying to call a method that doesn't exist. 

## problem

`[error] one error found` gets printed twice. Example output:

```
[info] compiling 1 Scala source to C:\reference\scala-3-project-template\target\scala-3.0.2\classes ...
[error] -- [E006] Not Found Error: C:\reference\scala-3-project-template\src\main\scala\Main.scala:4:2
[error] 4 |  someMethodThatDoesNotExist
[error]   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]   |  Not found: someMethodThatDoesNotExist
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed Oct 9, 2021, 1:28:55 AM
```

## expectation

The error summary should only be printed once

## notes

I confirmed that using the same project with Scala 2 does not have this problem.

**Comment by er1c** [comment]
Confirmed this still happens in `1.6.0-M1`

**Comment by adpi2** [comment]
The root cause of this issue is in the dotty repo, `printSummary` is called twice:
- https://github.com/lampepfl/dotty/blob/29f03741b9668c5052ec2b9502d061b7ecd614df/compiler/src/dotty/tools/dotc/Driver.scala#L53
- https://github.com/lampepfl/dotty/blob/29f03741b9668c5052ec2b9502d061b7ecd614df/sbt-bridge/src/dotty/tools/xsbt/CompilerBridgeDriver.java#L96

**Comment by eed3si9n** [comment]
Could someone report to lampepfl/dotty as well plz?
