### ISSUE TITLE
Update log4j 2

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#6742]

**Comment by rfan-debug** [comment]
Hey, @eed3si9n is it still viable to upgrade sbt 1.3.x series with the `log4j 2.15`?  I am trying to submit a PR but the `sbt:1.3.x` branch seems gone.

**Comment by eed3si9n** [comment]
@rfan-debug Is there a problem with using sbt 1.5.6?

**Comment by rfan-debug** [comment]
@eed3si9n The behavior is a bit different in our company's internal CI pipeline when sbt-1.5.6 tries to resolve`javaHome` options. 

I just resolved it by adding `export JAVA_HOME=<absolute path to java home>` in our building script and then use `System.getEnv` to find the correct javaHome. So, for me, no need to upgrade 1.3.x any more.

**Comment by rfan-debug** [comment]
@eed3si9n A new CVE of log4j-core came up.  https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046 
Could you bump up the version of log4j-core/impl again? Thank you very much! 

This one is less urgent tho.

**Comment by eed3si9n** [comment]
@rfan-debug Released sbt 1.5.7 https://eed3si9n.com/sbt-1.5.7

**Comment by mallman** [comment]
@eed3si9n Which versions of sbt are affected by https://nvd.nist.gov/vuln/detail/CVE-2021-44228 and which will be patched to include a fix?

Since sbt of many versions exists in a massive diaspora, can the official sbt documentation or blog or whatever state the vulnerable versions of sbt and how to remediate?

**Comment by mallman** [comment]
For example, I have projects on the 0.13 series of releases. Will there be a compatible update to this series? Is it even vulnerable? How can I check?

**Comment by mallman** [comment]
Also, has there been a known exploit of this vulnerability in sbt? And how could an attacker exploit this vulnerability in sbt in theory?

I understand you don't have all the answers, but as the project owner maybe you could help gather some?

**Comment by eed3si9n** [comment]
I'll work with @adpi2 at Scala Center to draft a security bulletin.

For sbt, sbt 0.13 doesn't come with log4j, sbt 1.x includes log4j but it's enabled by default only for sbt 1.0 ~ 1.3 since we implemented our own logger in sbt 1.4.

As far as I know, there has not been any exploit around this vulnerability, but I'd be careful in communicating any details around the attack vectors until the ecosystem has upgraded to secure versions.

**Comment by jornfranke** [comment]
Log4j2 2.17 is out: https://logging.apache.org/log4j/2.x/security.html
(and thanks for all the work and effort)

**Comment by eed3si9n** [comment]
I've released sbt 1.6.0-RC2 with log4j 2.17.0 yesterday - https://github.com/sbt/sbt/releases/tag/v1.6.0-RC2

**Comment by frankivo** [comment]
Shouldnt there also be a 1.5.8 with this fix?

**Comment by augi** [comment]
We are also awaiting `1.5.8`. [The PR to update log4j to 2.17.0 in 1.5.x branch](https://github.com/sbt/sbt/pull/6755) was merged on Saturday 🙏

**Comment by eed3si9n** [comment]
ok. here's sbt 1.5.8 - https://eed3si9n.com/sbt-1.5.8

**Comment by mallman** [comment]
> I'll work with @adpi2 at Scala Center to draft a security bulletin.

Hello. I'd like to share this kind of information with my coworkers. Is this still a WIP?

**Comment by eed3si9n** [comment]
It's already published - https://www.scala-lang.org/blog-detail/2021/12/16/state-of-log4j-in-scala-ecosystem.html

**Comment by mallman** [comment]
> It's already published - https://www.scala-lang.org/blog-detail/2021/12/16/state-of-log4j-in-scala-ecosystem.html

Thank you, Eugene. I overlooked this.

**Comment by hertg** [comment]
Would it be possible to release patches for previous sbt versions (eg. `1.2.x`, `1.3.x`, `1.4.x`, ...)?
Some projects may rely on sbt-plugins which aren't compatible with the latest `1.5.x` versions yet, those projects are unable to get the log4j patches introduced in `1.5.6+`.

**Comment by eed3si9n** [comment]
@hertg As a hobbyist maintainer, I am personally not interested in backporting unless it's blocking a large chunk of community for some reason or https://twitter.com/eed3si9n/status/1471693249811255299
If other maintainers from Lightbend or Scala Center wants to maintain older branches, I'd be happy to help them.

**Comment by hertg** [comment]
I understand, our perfect path would be for sbt-plugins to update to sbt `1.5.x`, we are waiting for feedback on that. Should older branches generally be expected to not receive any security updates if newer minor versions are released? Asking because I saw that there already is a RC for `1.6.x`. And it would be good to know so we can estimate how to handle sbt updates in the future. Also, if potential exploits for sbt `1.0 - 1.4` start to appear, is there a channel where we could get updates about that?

Thank you very much for your work on the project.

**Comment by eed3si9n** [comment]
It's case by case to some extent, but generally only one stable branch would be patched by default. deveop branch is already moved on to the next version (sbt 2.x), so even maintaining 1.6.x and 1.5.x is already triple work.

> Also, if potential exploits for sbt 1.0 - 1.4 start to appear, is there a channel where we could get updates about that?

By potential exploits do you mean theoretical vulnerabilities, or potential evidences that someone may have made a malicious attack to some company's build system by hopping on to sbt 1.4?

**Comment by sjrd** [comment]
> Would it be possible to release patches for previous sbt versions (eg. `1.2.x`, `1.3.x`, `1.4.x`, ...)? Some projects may rely on sbt-plugins which aren't compatible with the latest `1.5.x` versions yet, those projects are unable to get the log4j patches introduced in `1.5.6+`.

If you are in such a situation, and you assess that the build itself is at risk of being exploited, you can force an upgrade of log4j in your build, *without* upgrading sbt. Add the following to `project/plugins.sbt` (or any other `.sbt` file in `project/`):
```scala
libraryDependencies ++= Seq(
  "org.apache.logging.log4j" % "log4j-api" % "2.17.0",
  "org.apache.logging.log4j" % "log4j-core" % "2.17.0",
  "org.apache.logging.log4j" % "log4j-slf4j-impl" % "2.17.0",
)
```
This will force sbt to use a newer version of log4j. Just like, if used in a project's settings, it would force that project's transitive dependencies to use the newer version of log4j.

Note that this does not affect the *meta-build*, so the meta-build still uses the old version of log4j. Normally, AFAICT, the meta-build only logs messages that are hard-coded in sbt and only depend on file paths, so probably not exploitable? If you have custom logic in your meta-build, or even sbt plugins in your meta-build (like in `project/project/plugins.sbt`), then you can repeat the process ad libitum, by putting the same settings above in `project/project/plugins.sbt`.

**Comment by hertg** [comment]
> By potential exploits do you mean theoretical vulnerabilities, or potential evidences that someone may have made a malicious attack to some company's build system by hopping on to sbt 1.4?

Both would be of interest, the latter would obviously be extremely important to know in order for us to react fast. For now I'm following this issue, watching the [Security Advisories](https://github.com/sbt/sbt/security/advisories) of the sbt and scala repository, and am subscribed to the [Scala Blog RSS Feed](https://www.scala-lang.org/feed/blog.xml) (Sidenote: somehow the [post about log4j](https://www.scala-lang.org/blog-detail/2021/12/16/state-of-log4j-in-scala-ecosystem.html) doesn't show up in that feed, which is why I missed it at first). If there are other channels you'd recommend me to follow please let me know.

---

@sjrd Thank you very much for the informative feedback. We'll apply that workaround if the sbt-plugins we rely on won't update their sbt compatibility in the foreseeable future.

**Comment by hertg** [comment]
@eed3si9n This might not exactly be the right place, but...

Our company is aware of the importance of open-source and we are aware of the value independent / hobbyist developers provide to those projects. We are interested in supporting independent open-source projects that we rely on, and that enable us to provide our products and services. But in the spirit of open-source we'd like such support to be as transparent as possible.

Our company is already sponsoring [Play Framework](https://opencollective.com/playframework) via Open Collective. So if there is a possibility to transparently support sbt as a project please let me know, so I can forward that to the right place. 

*Depending on the overlap between sbt / play (meaning how many are using sbt **because** they are using play), it might be an option to attach "maintaining sbt" as an interest of the Play Framework Open Collective. But this is just a hint, I am not involved with the collective.*
