### ISSUE TITLE
SBT 1.5 prompt seems broken in git-bash + Windows.

### ISSUE THREAD

**Issue by bjhartin** [sbt/sbt#6815]
### Minimal reproduction

_I understand this may or may not be a bug in SBT since it only seems to occur with git-bash + Windows, but I am guessing so at this point._

```bash
$ mkdir test
$ cd test
$ touch build.sbt
$ echo "sbt.version = 1.5.0" > project/sbt.properties
$ sbt 
[info] welcome to sbt 1.5.0 (Amazon.com Inc. Java 1.8.0_282)
[info] loading settings for project global-plugins from global.sbt,idea.sbt ...
[info] loading global plugins from C:\Users\V8ZNX3A\.sbt\1.0\plugins
[info] loading settings for project isg-swagger-codegen-build from plugins.sbt,scalapb.sbt ...
[info] loading project definition from C:\bench\streaming-data\isg-swagger-codegen\project
[info] loading settings for project root from build.sbt,version.sbt ...
[info] set current project to isg-swagger-codegen (in build file:/C:/bench/streaming-data/isg-swagger-codegen/)
>....>....>....>....
```

Same behavior on a fleshed-out project.

## problem

After changing build.properties to upgrade from 1.3.13 to 1.5.0, the SBT prompt is broken in git-bash on Windows.  It displays `>...` instead of the expected `sbt:my-project>`.  In addition, the enter key does not create a new line (see above).

Change the version to 1.3.13, no problem.

Change to 1.4, and you get a different problem, but that's a separate issue.

In general, whenever I upgrade SBT, the 'git-bash' experience on Windows changes significantly with regard to the terminal, keystrokes, text wrapping, etc.

## expectation

Normal prompt displayed.

## notes

This works fine in Powershell, but that's not an option for me, nor is switching operating systems.

**Comment by eed3si9n** [comment]
Since most sbt maintainers and contributors don't run Windows regularly, to some extent these regressions are expected esp for things like git bash. The terminal in VS Code works on macOS, so maybe it's worth giving it a shot on Windows as well? Another alternative might be trying Windows Terminal (https://github.com/Microsoft/Terminal), which I think was supposed to have terminal emulation on par with those that come with Linux.

**Comment by CervEdin** [comment]
I'm experiencing the same issue.

sbt 1.6.2
git version 2.35.1.windows.2
GNU bash, version 4.4.23(2)-release (x86_64-pc-msys)
mintty 3.5.2 (x86_64-pc-msys)

I'm running Windows 10 with code page set to utf-8

I tried to investigate the cause by inspecting `sbt.sh` (`sbt`), but the file appears to be rather new in the repo :/

I experienced the problem using [sbt 1.3.13](https://github.com/sbt/sbt/releases/download/v1.3.13/sbt-1.3.13.msi) as well as [sbt 1.2.8](https://github.com/sbt/sbt/releases/download/v1.2.8/sbt-1.2.8.msi)

Running  `winpty sbt` solves the issue of not seeing the input, instead with the lovely side-effect that all control characters are rendered:
`?[0J?[0J?[2K?[1000D?[0J?[2K?[1000D?[0J?[0J?[2K?[1000D?[0J?[2K?[1000D?[0J?[?1h?=?[?2004hsbt:hello-world?[36m> ?[0`

sbt runs fine using git-bash in the windows terminal

Basically, it seems to be the reverse of [this coc.nvim issue](https://github.com/neoclide/coc.nvim/issues/2309)

My guess is that it's a control character problem. It'd be great if control characters could be disabled.

*Update*:
I found this [stackoverflow thread](https://stackoverflow.com/questions/66395499/sbt-has-lost-its-ability-to-format-a-screen-with-ctrl-characters-why) (which mentions a [possibly related issue](https://github.com/sbt/sbt/issues/4173)). In it, a suggestion was to disable color `sbt -no-colors`, which greatly alleviated the control character problems of running `winpty` but some control characters remain. My guess is that it's the ANSI codes that are the root cause of the incompatibility.

It's a pretty hard to figure out what the escape codes sent are (and which are causing the problem) but this is the `winpty sbt -no-colors` output
```
?[?1h?=?[?2004hsbt:hello-world>
?[?1l?>?[?1000l?[?2004l?[?1h?=?[?2004hsbt:hello-world>
```

**Comment by matthedude** [comment]
I had the original prompt problem and then using `winpty` produced the same output as @CervEdin. I found a combination worked of using `ansicon` and using `winpty`:

* [Download ](http://adoxa.altervista.org/ansicon)and in a terminal:
`unzip ansicon-(version).zip`
* In a terminal in the unzipped `ansicon` sub-directory for your chip architecture:
`ansicon.exe -i`
* Open new terminal.
* Open sbt with `winpty`:
`winpty sbt`
 (or give the full path of `sbt.bat` if not on PATH)

The strange characters are no longer there and it works as it should.

**Comment by Friendseeker** [comment]
<img width="628" alt="image" src="https://github.com/user-attachments/assets/736b361c-fcba-4b30-aeb8-49889b44b7a5">

No longer reproducible

**Comment by ekrich** [comment]
Which version of git bash do you have @Friendseeker ?

**Comment by ekrich** [comment]
I noticed when installing this dialog. Seems like the default may not work great as some of the solutions in the ticket suggest `winpty`.
![image](https://github.com/user-attachments/assets/b828529f-8c5b-4d6f-ba00-7e9425f84924)

**Comment by ekrich** [comment]
Ok, updating/upgrading git bash fixed the issue.
