### ISSUE TITLE
sbt-dotty is gone, but sbt still reference it?

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#6954]
https://github.com/sbt/sbt/search?q=sbt-dotty

sbt-dotty is official dropped. not maitained anymore, 
sbt still reference it?

**Comment by ghost** [comment]
https://github.com/lampepfl/dotty/commit/1092b356e6f032978e04963ad8e76cd2b905d803

by dotty commit message, we know sbt-dotty was not continue , and been dropped since then

**Comment by eed3si9n** [comment]
Yes. sbt 1.5.0 released in 2021 (https://eed3si9n.com/sbt-1.5.0) folded Scala 3 support into sbt, a month before the release of Scala 3.0.0. During the beta development, _sbt-dotty_ implemented the integration and we still have the remnant in the integration test, which we probably kept around since we wanted to make sure that the presence of sbt-dotty doesn't break sbt, especially during the transition period. Now that sbt 1.5.0 transition is behind us, we can probably remove reference to sbt-dotty.

If you're up for it, we'd be happy to accept pull requests to remove those tests.
