### ISSUE TITLE
sbt waits indefinitely for blocked child powershell processes to finish

### ISSUE THREAD

**Issue by softwareCobbler** [sbt/sbt#7198]
## steps
I'm not sure if I have a consistent cross-machine repro, but this happens basically every time I start a new Scala project and do a fresh invocation of SBT in that new project folder. I have made many new Scala project folders recently to get a feel for what it takes to start working with Scala.

- on windows 10, install SBT 1.8.2 (last stable at time of writing this) 
- run sbt (either directly through a command line invocation, or indirectly via Metals in vscode)
- get stuck on a message indicating it's downloading artifacts and that it "may take a while"
- notice that it only makes progress if child powershell process are killed

## problem

Something about the https://github.com/dirs-dev/directories-jvm (transitive) dependency?

## expectation

As a developer looking to get started with Scala, it would ease the onboarding process if sbt did not silently "do nothing". 

## notes
To spin up Metals in vscode, I keep Sysinternals process explorer open and during Metals startup kill 6 separate blocked invocations of powershell, after which Metals starts up.

**Comment by eed3si9n** [comment]
@softwareCobbler If you suspect this is caused by directories-jvm, and Coursier that depends on directories-jvm, could you report this issue to the upstream as well?

Because of these issues sbt main artifact already avoids asking Coursier to figure out the cache directory (https://github.com/sbt/sbt/blob/v1.8.2/main/src/main/scala/sbt/coursierint/LMCoursier.scala#L61-L70), but I am not doing that for sbt launcher code - https://github.com/sbt/launcher/blob/d9e0cbd5dc7064c264f1f23e72425f52fc987684/launcher-implementation/src/main/scala/xsbt/boot/CoursierUpdate.scala#L29-L33. We should probably copy-paste the workaround.

**Comment by softwareCobbler** [comment]
related: https://github.com/dirs-dev/directories-jvm/issues/55

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/launcher/pull/102
