### ISSUE TITLE
xsbti.FileChanges uses URI

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7252]
## steps

Unreleased `xsbti.FileChanges` looks like

```java
/** A collection of TextEdits that belong to a given URI. */
public interface FileChanges {

  /** The URI that the edits belong to. */
  URI uri();

  /** The edits belonging to the URI. */
  List<TextEdit> edits();
}
```

## problem

At the BSP level, [SourceItem](https://build-server-protocol.github.io/docs/specification#buildtargetsources-request) is tracked as `URI`.

## expectation

We probably should use `Optional[String]` and `Optional[File]` like we do currently in Position - https://github.com/sbt/sbt/blob/v1.9.0-RC2/internal/util-interface/src/main/java/xsbti/Position.java#L25-L27:

```java
public interface Position {
....

  Optional<String> sourcePath();

  Optional<File> sourceFile();
```

## notes

Inside the compiler, source files are represented as virtual [SourceFile](https://github.com/scala/scala/blob/v2.13.10/src/reflect/scala/reflect/internal/util/SourceFile.scala)s, and currently we send information from the compiler to Zinc:
- in https://github.com/sbt/zinc/blob/v1.9.0-RC2/internal/compiler-bridge/src/main/scala/xsbt/DelegatingReporter.scala (for Scala 2.x).
- or in https://github.com/lampepfl/dotty/blob/3.3.0-RC6/sbt-bridge/src/dotty/tools/xsbt/PositionBridge.java#L83-L102 (for Scala 3.x)

using `Optional[String]` and `Optional[File]`.

At the BSP server level in https://github.com/sbt/sbt/blob/v1.9.0-RC2/main/src/main/scala/sbt/internal/server/BuildServerReporter.scala we already know the association between source files and problems (after the compilation is done), and BSP server also knows how to convert the source file into URI that _it_ told the BSP client.

**Comment by ckipp01** [comment]
> At the BSP server level in https://github.com/sbt/sbt/blob/v1.9.0-RC2/main/src/main/scala/sbt/internal/server/BuildServerReporter.scala we already know the association between source files and problems (after the compilation is done), and BSP server also knows how to convert the source file into URI that it told the BSP client.

~So this is true for the current file that holds the diagnostic, but the `Action` may have edits that originate from that position, but belong to another URI. That's one of the main reasons I went this route since let's say we have:~

```
A.scala <- This file has a diagnostic
B.scala
C.scala
```
~`A.scala` is where the diagnostic originates from, but it could be that the `Action` it contains holds a `WorkspaceEdit` with file changes for `B.scala` and `C.scala`. With that in mind, wouldn't this need to be a valid URI? Or a string representation of the URI if that is more favorable?~

EDIT: Thinking about this a bit more, maybe we don't even need this layer. In LSP we have this mapping `Map[Uri, TextEdit]`, but in reality the `TextEdit`s also have a position, so maybe what I said up above is incorrect. For example [`DocumentChanges`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceEdit) has no mapping like this, so I think the edits are indeed just grouped by URI, and the example I gave up above isn't correct. In theory at the BSP level, we could just break away a _bit_ further from the LSP way of doing things and minimize even further. We could make our `WorkspaceEdit` be:

```java
public interface WorkspaceEdit {
  List<TextEdit> changes();
}
```

And then get rid of the `FileChanges.java` altogether since in reality, we'd have the information necessary to put together the `changes` mapping in the server. So this would mean that the server would have to do a _bit_ more mapping from this to the LSP `WorkspaceEdit`, but I don't think that'd be a huge deal.

CC'ing @tgodzik as well.

@eed3si9n do you think this could work? If so I'll shoot in a PR to:

- Make our `WorkspaceEdit` reflect the above
- Remove the `FileChanges.java` (which would rid the need of that URI at all)

**Comment by eed3si9n** [comment]
> @eed3si9n do you think this could work?

Sounds good to me. Ideally we should try to get end-to-end working in Zinc using some hardcoded compilation warning or error on Scala 2.13, like deprecation of procedure syntax.

**Comment by eed3si9n** [comment]
Since we're looking into it, do we need `WorkspaceEdit`? Can `changes` be part of `Action`?

**Comment by ckipp01** [comment]
> Since we're looking into it, do we need `WorkspaceEdit`? Can `changes` be part of `Action`?

Ideally we'd leave that there. In the future we have plans of introducing resource operations like renaming, deleting files, etc. In order to do that we'd need something different than a `TextEdit`. So we wanted to sort of go parallel with the LSP spec here where `changes` was the bare minimum option that supported basic edits in-file, when later we'd introduce and start using [`DocumentChanges`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceEdit) under a `documentChanges` field that could both contain the `TextEdits` and the other operations.

**Comment by eed3si9n** [comment]
> Ideally we'd leave that there. In the future we have plans of introducing resource operations like renaming, deleting files, etc.

ok.
