### ISSUE TITLE
resolvers aren't imported from subprojects

### ISSUE THREAD

**Issue by crocket** [sbt/sbt#743]
I have a main project that depends on a subproject.
The subproject has a line as below
resolvers += "Sonatype OSS Snapshots" at "https://blahblah..."

Since the subproject has a dependency that exists only in "Sonatype OSS Snapshots" and resolvers aren't imported from subprojects,
when I execute "compile" or anything else in the main project,
sbt fails to resolve that dependency.

Thus, I have to replace that resolver line in the subproject with
resolvers in ThisBuild += "Sonatype OSS Snapshots" at "https://blahblah..."

It looks lame.

A sample sbt application that depicts this issue is hosted on https://github.com/crocket/sbtTest

Can there be any fix?

**Comment by harrah** [comment]
Please do not both post to the mailing list and open an issue to discuss a change.

**Comment by crocket** [comment]
Nobody cared about this in the mailing list.

But I think it should be addressed properly as an issue in github.

Can you reopen this issue?

**Comment by jsuereth** [comment]
I think this needs more discussion in the ML, and I'm sad because I did not see the conversations in the ML at all (can you post a link so I can start the discussion?).   

Basically, when it comes to resolvers, I'm almost of the opposite opinion, that project-specific reosvlers are a mistake and you should always use build-level resolvers.   In fact, the _name_ of the resolver is dramatically important for your entire build.    In my own projects, we usually specify all the default resolvers in a common project setup method, and use that to define all projects so all resolvers are the same.

**Comment by crocket** [comment]
jsuereth : I posted a message to the ML.
