### ISSUE TITLE
Search for binary compatible scala versions

### ISSUE THREAD

**Issue by hsn10** [sbt/sbt#761]
If you have statement like that:

libraryDependencies ++= Seq(
  "org.specs2" %% "specs2" % "1.13" % "test"
)

and there is no version for scala 2.9.3 but there is for 2.9.2, then sbt should be smart enough to do fallback to binary compatible version.

**Comment by Rogach** [comment]
My humble opinion: not a good idea. There are several problems with this:
- 2.9.x releases are not binary compatible between each other (even 2.9.3 and 2.9.2 are `almost compatible`, not totally), thus silently using 2.9.2 version instead of 2.9.3 may introduce problems. Even worse, those problems will be totally cryptic for newcomers.
- Libraries compiled for 2.10.x are released with 2.10 version tag (since 2.10.x releases _are_ binary compatible), thus proposed feature is already obsolete in that sense.
- In general: telling user that he uses one version of library, and silently using another version - _very bad idea_. At the very least, this will require big flashy warnings on every compilation (which nobody likes).

By the way, the best approach in such situations will be to alert the library developer about the fact that the needed version can't be found. Have you tried opening a bug against specs2 library?

**Comment by hsn10** [comment]
Yes, i see it that way too, i didnt knew about 2.10 change when i wrote ticket. I just have to survive before twitter moves to 2.10 and until then recompile libraries myself.
