### ISSUE TITLE
sbt >= 1.9.4 doesn't handle packaging type ejb properly

### ISSUE THREAD

**Issue by thescouser89** [sbt/sbt#7612]
## steps
The reproducer can be found here: https://github.com/thescouser89/ejb-sbt-issue

Just run:
```
sbt run
```
in each sub-folder inside.

## problem
sbt >= 1.9.4 gets confused by the packaging type "ejb" for a Maven dependency and tries to download the dependency.ejb file instead of the dependency.jar file. sbt 1.9.3 handles this properly.

The dependency we hit the issue is: https://repo1.maven.org/maven2/org/jboss/da/reports-model/2.1.0/reports-model-2.1.0.pom

## expectation
sbt downloads the proper jar file.

**Comment by eed3si9n** [comment]
@thescouser89 Thanks for the report! I'm guessing that the root cause is likely in the Coursier, so could you also report to coursier/coursier as well please?

https://github.com/sbt/sbt/releases/tag/v1.9.4 updated lm-coursier-shaded from 2.1.0 to 2.1.1, and according to https://github.com/coursier/sbt-coursier/compare/v2.1.0...v2.1.1, that updated **Cousier from 2.1.2 to 2.1.6**. Maybe https://github.com/coursier/coursier/pull/2718 has triggered this new behavior?

**Comment by thescouser89** [comment]
Thanks @eed3si9n ! Created https://github.com/coursier/coursier/issues/3040 on the coursier side.
