### ISSUE TITLE
Bump CI to JDK 21

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7731]
Ref https://github.com/scala/docs.scala-lang/pull/3082#issuecomment-2395625368

/cc @Friendseeker

**Comment by Friendseeker** [comment]
Here's the interim test result:

https://github.com/Friendseeker/sbt/actions/runs/11207433934

There's quite a few CI failures. I guess we need to do some work to quash the bugs.

**Comment by Friendseeker** [comment]
Instead of enabling full coverage of all OS / LTS combination, maybe we shall strive for the less ambitious goal of simply let the existing Java 17 jobs to run with Java 21 for now, as per the title of the issue.

Full coverage of all OS / LTS combination is certainly something handy to have, and some of their [failures](https://github.com/Friendseeker/sbt/actions/runs/11207433934) likely indicate real issues, but it would require a significantly greater time investment to address them.

We can open another ticket for full coverage.

**Comment by eed3si9n** [comment]
Yea. I think we mostly want the boundary checks JDK 8 and whatever the latest we support.
