### ISSUE TITLE
`usePipelining` prevents incremental compilation from working when `version` is changed

### ISSUE THREAD

**Issue by SakulK** [sbt/sbt#7767]
## steps

Here's a minimal project to demonstrate the problem, including steps to reproduce: https://github.com/SakulK/sbt-usePipelining-version-interaction

## problem

Enabling `usePipelining` means changing the `version` of a projects prevents incremental compilation from working, because of a change in the scalac options. This is especially unfortunate when using the `GitVersioning` plugin, then the `version` changes with every commit.

## expectation

Maybe the `earlyOutput` path that is used for `-Ypickle-write` option could skip the `version` part? That should resolve this issue, but I'm not sure if it could introduce another one.

**Comment by eed3si9n** [comment]
@Friendseeker is working on a PR for this it seems. I also wonder if there are going to be more issues if packageBin changes the name and if you have exportyJars set to true. I feel like the issue is changing the version frequently, not pipelining, maybe? I use tag version but in between keep it as SNAPSHOT because I don't expect to publicly publish untagged things.
