### ISSUE TITLE
[1.x] Consider adding `sbt/sbt` to Scala Steward?

### ISSUE THREAD

**Issue by Friendseeker** [sbt/sbt#7908]
I definitely see why this is not done before. `sbt` is a large repo, as a result bumping certain deps is not quite as simple as letting Scala Steward to auto generate a PR (i.e. bump Scala version, sbt version).

However I still do feel the pro outweighs the con, and with some configurations to opt-out certain dependencies, Scala Steward can still be a valuable companion.

@eed3si9n @adpi2 @BillyAutrey What do you think?

**Comment by eed3si9n** [comment]
Automation is useful if it makes the job of the maintainers easier. For sbt and even Zinc, I honestly I'm not sure if it ends up adding toil or saves work. As a program that ends up on many people's machines, tooling needs to be careful about adding or updating dependencies. Being aware of new versions might be useful, but having a PR ready for every little things, including plugins, isn't always helpful if I have to take time out of my free time to check defensively in case some other people with commit rights might merge it. General setup of auto version update isn't really conducive to careful analysis since you kind of get numb to version number going up, and the community doesn't really have time to realize if there are about to break compatibility or land a zero-day attack.

**Comment by Friendseeker** [comment]
> but having a PR ready for every little things, including plugins, isn't always helpful if I have to take time out of my free time to check defensively in case some other people with commit rights might merge it

This makes a lot of sense. Waking up every day and having to review a bunch of PRs from Scala Steward is probably not fun. Especially when `sbt` is a critical infrastructure with a large set of dependencies, one needs to carefully review all of the dependencies.

While there's benefit to keep deps up to date, just adding `sbt/sbt` to Scala Steward is probably not the way to go.

**Comment by SethTisue** [comment]
Not pushing, but just a thought about this:

A possible middle path would be to enable the Steward but decrease the update frequency (it's configurable) to some sufficiently low value like once a month, once every 3 months, something like that.

**Comment by eed3si9n** [comment]
Recently Steward sent https://github.com/sbt/io/pull/399 (Update scala-compiler, scala-library to 2.13.16) and I thoughtlessly landed the PR. This was actually not a zero-cost bump, because it turns out, because Scala 2.13.x is no longer forward compatible, sbt/sbt can no longer perform multi-repo integration test. So this was yet another example, where in theory the idea of bumping version number is good, but Steward PRs doesn't make the _tradeoff space_ clear to humans.

So a reminder to myself and other maintainers: AT WHAT COST?!
