### ISSUE TITLE
Invalid generated name for meta-project

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#801]
[D:\Program Files\ConEmuPack\2013-06-27-16-14]xsbt
[info] Loading global plugins from C:\Users\OlegYch.sbt\0.13.0-Beta2\plugins
[error] Invalid project ID: Expected letter
[error] 2013-06-27-16-14-build
[error] ^

**Comment by harrah** [comment]
See also https://groups.google.com/d/msg/simple-build-tool/inqxjBHyHns/RvKW0CUj60EJ, https://groups.google.com/d/msg/simple-build-tool/ShikT6VAd_g/edoQUic4F44J, and https://github.com/sbt/sbt/commit/ce1c8b0ebc4a18d2fcd61b8fbe43d03c5a06086a.  I do not intend to do anything about this for 0.13 unless a straightforward, easy alternative behavior is identified (soon).

The output with the latest 0.13, implemented since those threads, is:

```
[error] Could not derive root project ID from directory /home/user/2013-06-27-16-14:
[error] Expected letter
[error] 2013-06-27-16-14
[error] ^
[error] Rename the directory or explicitly define a root project.
```

**Comment by OlegYch** [comment]
well this is a very unfortunate breaking change
also, you have to consider that there is no way to change this id for meta projects (note that i'm specifically talking about metaprojects)
you could just append "build-" in the beginning of the name instead of end

**Comment by harrah** [comment]
The auto-generated meta project name will only be invalid if the root project name is invalid.  With the latest changes, loading should not make it to the meta project.  It would be possible to use the old behavior and randomly generate an ID when the ID is invalid.

**Comment by harrah** [comment]
7992997ac14894d0fbd8028a1f48768387fceab2 prepends "root-" if the initial character is invalid.  There is no fallback implemented at this time.
