### ISSUE TITLE
'latest.integration' as version for plugins does not find the latest local snapshot

### ISSUE THREAD

**Issue by gseitz** [sbt/sbt#805]
When using `latest.integration` as version for plugins, it seems that a locally published snapshot (e.g. `0.2.4-SNAPSHOT`) is not found, but instead the latest release (e.g. `0.2.3`) is chosen instead.

@eed3si9n also ran into this problem in [this thread](https://groups.google.com/forum/#!topic/simple-build-tool/Nm3CMft6CDw) on the mailing list, and adding `force()` doesn't help resolve the issue either.

**Comment by harrah** [comment]
The test case I came up with only failed because I put the snapshot repository after the stable one.  sbt configures Ivy to stop after the first resolver containing a matching module, so it is expected that Ivy stops at the stable one.

It is possible to configure Ivy to search all resolvers when using dynamic revisions/snapshots, but this will increase resolution time significantly.

However, it doesn't seem like the test case aligns with your situations.  It sounds like you have a stable release in a remote repository and a snapshot release in the local repository.  Because the local repository comes before user-defined repositories by default, I wouldn't expect a problem.  Can you confirm that local is before your stable, remote repository?  To reopen, I need a reproducible test case or some agreement that for dynamic revisions, Ivy should search all resolvers.
