### ISSUE TITLE
0.13.0-RC1 not fetching dependencies correctly

### ISSUE THREAD

**Issue by hgiddens** [sbt/sbt#810]
Using the following build.sbt, 0.13.0-RC1 (also reproduced vs. 7278fbc) doesn't appear to create the entries in the Ivy cache that would allow it to put some dependencies on the classpath.

``` scala
libraryDependencies += "com.datastax.cassandra" % "cassandra-driver-core" % "1.0.1"
```

To reproduce:
1. Start with an empty Ivy cache
2. Shove above build.sbt somewhere
3. Using sbt 0.13.0-RC1, run `sbt console`
4. At the Scala prompt, run e.g. `import org.apache.thrift.TException`
5. Note the complaining about being unable to import the class

```
scala> import org.apache.thrift.TException
<console>:7: error: object thrift is not a member of package org.apache
       import org.apache.thrift.TException
```
- Using 0.12.4 and a clean Ivy cache, the import succeeds.
- The import will also succeed under 0.13.0-RC1 _if_ the Ivy cache entries were created by 0.12.4.
- The import fails under 0.12.4 using a cache built using 0.13.0-RC1.

Some brief cache spelunking yielded this (partial) diff, where `bad/ivy2` is the Ivy cache generated by 0.13.0-RC1 and `good/ivy2` is generated by 0.12.4. Note that libthrift provides the `TException` class:

``` diff
diff -ru bad/ivy2/cache/org.apache.thrift/libthrift/ivydata-0.7.0.properties good/ivy2/cache/org.apache.thrift/libthrift/ivydata-0.7.0.properties
--- bad/ivy2/cache/org.apache.thrift/libthrift/ivydata-0.7.0.properties 2013-07-10 13:52:13.000000000 +1000
+++ good/ivy2/cache/org.apache.thrift/libthrift/ivydata-0.7.0.properties        2013-07-10 13:55:10.000000000 +1000
@@ -1,8 +1,12 @@
 #ivy cached data file for org.apache.thrift#libthrift;0.7.0
-#Wed Jul 10 13:51:48 EST 2013
-artifact\:ivy\#ivy\#xml\#-1201192.location=http\://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.7.0/libthrift-0.7.0.pom
+#Wed Jul 10 13:53:31 EST 2013
 artifact\:ivy\#ivy\#xml\#-1201192.is-local=false
+resolver=sbt-chain
+artifact\:ivy\#ivy\#xml\#-1201192.exists=true
+artifact\:libthrift\#pom.original\#pom\#-1180385577.exists=true
 artifact\:libthrift\#pom.original\#pom\#-1180385577.location=http\://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.7.0/libthrift-0.7.0.pom
+artifact\:libthrift\#jar\#jar\#1462019057.location=http\://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.7.0/libthrift-0.7.0.jar
+artifact\:ivy\#ivy\#xml\#-1201192.location=http\://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.7.0/libthrift-0.7.0.pom
 artifact\:libthrift\#pom.original\#pom\#-1180385577.is-local=false
-artifact\:libthrift\#pom.original\#pom\#-1180385577.exists=true
-artifact\:ivy\#ivy\#xml\#-1201192.exists=true
+artifact\:libthrift\#jar\#jar\#1462019057.exists=true
+artifact\:libthrift\#jar\#jar\#1462019057.is-local=false
Only in good/ivy2/cache/org.apache.thrift/libthrift: jars
```

**Comment by eerok** [comment]
Not sure if relevant or not, but the pom file for libthrift (http://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.7.0/libthrift-0.7.0.pom) has a packaging element of type pom. Maybe Ivy is not mapping that to .jar file extension?

**Comment by harrah** [comment]
@hgiddens Thanks for the detailed report and @eerok thanks for the relevant diagnosis.  

This was an intentional change.  Modules with packaging="pom" should not have jars and checking for them is expensive since they don't usually exist and repository misses are slow.  The bug was #636.

See http://www.scala-sbt.org/0.13.0/docs/Detailed-Topics/Library-Management.html#packaging-pom, which includes the workaround.  (It was also listed in the [changes with compatibility implications](http://www.scala-sbt.org/0.13.0/docs/Community/ChangeSummary_0.13.0.html#features-fixes-changes-with-compatibility-implications-incomplete-please-help) section.)

It might be possible to collect a list of modules with packaging="pom" and a jar in order to provide a better error message.  I'll leave this open until I determine that.

**Comment by harrah** [comment]
Of the ~10,000 modules (groupID:artifactID) in Maven Central that have packaging="pom", only 59 have an associated jar.  It might be possible to explicitly recognize these existing modules and continue to look for the jar in order to make it easier for users to move from 0.12 to 0.13 without changes.  That might be more confusing than just a warning, though, since new modules that do this or modules in other repositories would fail.

The linked workaround in the previous comment unfortunately does not work for dependants, so users of a library would have to add the workaround as well, breaking transitivity.  I don't see a way to avoid this.

Another option is to have a `workaroundPomPackaging` setting that configures looking for the jar.  It would still have to be set for dependants if it is false by default, but it would be easier than copying dependencies around.  This approach will still make it so that only projects using these broken modules take longer to resolve.

**Comment by harrah** [comment]
The list of broken modules on Maven Central (out of 10,000 modules with `packaging="pom"`):

org.modeshape:modeshape-client
org.neo4j.doc:neo4j-manual
org.jnario:org.jnario.standalone.maven
org.picketlink.distribution:picketlink-jbas7
org.picketlink.distribution:picketlink-jbas5
org.picketlink.distribution:picketlink-tomcat7
org.picketlink.distribution:picketlink-tomcat5
org.neo4j.build.plugins:neo4j-doctools
com.sun.xml.ws:jaxws-tools
com.sun.xml.ws:jaxws-rt
org.picketbox:picketbox
org.picketbox:jbosssx
org.picketbox:jboss-security-spi
org.icefaces:icefaces-compat
org.icefaces:icefaces-ace
com.projetloki:genesis
org.zkoss.theme:zktheme
org.mortbay.jetty.testwars:dummy-scm-lib
ch.imvs:sdes4j
org.semanticweb.elk:elk-standalone
org.testinfected.hamcrest-matchers:all-matchers
org.ow2.easybeans:easybeans-component-smartclient
org.apache.zookeeper:zookeeper
org.apache.thrift:libfb303
org.apache.thrift:libthrift
org.springframework.security:spring-security-parent
org.picketlink:picketlink-consolidated-social
org.primefaces.extensions:all-themes
org.odata4j:odata4j-dist
org.apache.axis2:axis2
org.picketlink:picketlink-fed
org.jboss.errai.io.netty:netty
org.ow2.easybeans:easybeans-uberjar-toplink-essentials
org.ow2.easybeans:easybeans-uberjar-openjpa
org.ow2.easybeans:easybeans-uberjar-hibernate
org.ow2.easybeans:easybeans-uberjar-eclipselink
net.sf.jmatchparser:jMatchParser-all
org.keymg:keymg-server
org.keymg:keymg-client
velocity:velocity
org.apache.openejb:openejb-itests-standalone-client
org.sonatype.spice.inject:guice-patches
org.picketlink.idm:picketlink-idm
org.objectweb.joram:jftp
org.jboss.integration:jboss-integration
org.microemu:microemulator
org.jboss.javaee:jboss-javaee
org.apache.cactus:cactus.core.framework.uberjar.javaEE.15
org.apache.cactus:cactus.core.framework.uberjar.javaEE.14
org.apache.cactus:cactus.core.framework.uberjar.javaEE.13
org.apache.cactus:cactus.core.framework.uberjar.javaEE.12
hibernate:hibernate-entitymanager
org.hibernate:ejb3-persistence
org.apache.jcs:jcs
com.google.code.guice:guice
org.apache.geronimo.javamail:geronimo-javamail_1.3.1_mail
org.openwfe:openwfe-embed-wom
org.apache.geronimo.specs:geronimo-j2ee_1.4_spec
plexus:plexus-mail-sender
plexus:plexus-mail-senders

**Comment by harrah** [comment]
Posted summary to the mailing list: https://groups.google.com/d/msg/simple-build-tool/DekTrHQEWcs/Jh4MQ3L6RSIJ

**Comment by copumpkin** [comment]
Is #987 related to this?
