### ISSUE TITLE
pomOnly transitive dependencies failing

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#861]
I've heard from [users of my library](https://github.com/scalanlp/breeze/commit/8241520a4e00eb5ecdfdf39d10104b345f23afc5#L3R65) that [the instructions](https://github.com/fommil/netlib-java)

```
"com.github.fommil.netlib" % "all" % "1.0" pomOnly()
```

do not work and some of the transitive libs are not being pulled in.

This works fine in Maven, so I think it's a bug in SBT :-(

**Comment by jsuereth** [comment]
It's not pulling in the library because it's marked with scope "provided" on the dependency.   Ivy, IIRC, has an issue pulling in transitive provided dependencies.   E.g. Lombok is also announces as provided, and does not come.

This appears to be a relevant ivy issue: http://stackoverflow.com/questions/12204598/ivy-not-resolving-transitive-dependencies-from-public-maven-repos.

For your users, I recommend the following workaround:

``` scala
val netlibVersion = "1.0"


val netlibs = Seq(
  "com.github.fommil.netlib" % "all" % netlibVersion pomOnly(),
  "com.github.fommil.netlib" % "core" % netlibVersion % "provided->provided")

libraryDependencies ++= netlibs
```

This is explicitly saying that our provided scope depends on the provided scope from core, which bring in lombok and that other thing.  I'd update your documentation for now with this workaround.   It may be a while before we can dig into the underlying issue in Ivy.

Hope that helps!
- Josh

**Comment by fommil** [comment]
@jsuereth thanks for the workaround!

Indeed, Lombok is supposed to remain compile-time only so is marked `provided`. However, the `arpack_combined_all` is **not** `provided`. But it's `javadoc` classifier **is** `provided` and that may be the cause of the bug (something somewhere is forgetting to keep track of the classifiers):

``` xml
            <dependency>
                <groupId>net.sourceforge.f2j</groupId>
                <artifactId>arpack_combined_all</artifactId>
                <version>0.1</version>
            </dependency>
            <dependency>
                <groupId>net.sourceforge.f2j</groupId>
                <artifactId>arpack_combined_all</artifactId>
                <classifier>javadoc</classifier>
                <scope>provided</scope>
                <version>0.1</version>
            </dependency>
```

**Comment by jsuereth** [comment]
Ah. Ivy is merging those two together when it does your "uber pom" and freaks out.   We should probably opena bug against ivy if it does not already exist.

Look at what ivy is resolving to it's `ivy.xml` from your core `pom.xml`:

```
<m:dependency.management__net.sourceforge.f2j__arpack_combined_all__scope>provided</m:dependency.management__net.sourceforge.f2j__arpack_combined_all__scope>
                <m:dependency.management__net.sourceforge.f2j__arpack_combined_all__version>0.1</m:dependency.management__net.sourceforge.f2j__arpack_combined_all__version>
```

You can see that it's lost any info about javadoc by this point.  I'm curious if you put the javadoc dependency above the non-javadoc one, if it fixes ivy.   In any case, thanks for helping debug further.

**Comment by fommil** [comment]
good stuff. I'll change the order for the snapshots and we'll see

**Comment by harrah** [comment]
This is a bug in Ivy's support for dependencyManagement, similar to this bug but for classifiers: https://issues.apache.org/jira/browse/IVY-974.  It isn't something that can be worked around in sbt, unfortunately.

**Comment by fommil** [comment]
meh. I worked around it on my side, poo poo to ivy.
