### ISSUE TITLE
fork in Test := true doesn't run any tests with the new test interface

### ISSUE THREAD

**Issue by etorreborre** [sbt/sbt#868]
You can checkout [specs2-test](https://github.com/etorreborre/specs2-test) and run one of the specifications with sbt 0.13:

```
sbt>testOnly *examples.HelloWorldSpec*
```

This is ok, the results are displayed. But:

```
sbt>set fork in Test := true
sbt>testOnly *examples.HelloWorldSpec*
```

doesn't display anything

**Comment by etorreborre** [comment]
Can it be related to [this fix](https://github.com/sbt/sbt/commit/c2df1e8d684900e3f262fd089d137c1eb0d7da83)? Does that suggest a workaround?

**Comment by ijuma** [comment]
Somewhat related, I noticed that "fork in test" (note lowercase `test`) doesn't work in SBT 0.13 (that is, the tests are executed without forking). Just `fork` has the desired effect (although with less granular control). So, it seems like more than one issue has creeped up when it comes to this functionality.

**Comment by harrah** [comment]
The problem is in the specs2 runner: https://github.com/etorreborre/specs2/blob/master/src/main/scala/org/specs2/runner/SbtRunner.scala#L56

The fingerprint that is provided to the framework is only guaranteed to be a SubclassFingerprint or AnnotatedFingerprint and not the exact subclass provided by the framework initially.  When not forking, it is the same one, but when forking, it isn't because we can't (and don't want to) assume the user's fingerprint type is Serializable.

**Comment by harrah** [comment]
@ijuma please open a separate issue for `fork in test`

**Comment by etorreborre** [comment]
Ok, I fixed it. Thanks Mark.
