### ISSUE TITLE
onUnload is not called when sbt exits

### ISSUE THREAD

**Issue by huntc** [sbt/sbt#897]
Ctrl-D, Ctrl-C, being killed etc. or just plain "exit" should cause the onUnload callback to be called - but it doesn't.

**Comment by harrah** [comment]
Can you motiviate your use case/expectations more?  This behavior is by design, since a standard Java exit hook does what you want already.

Edit, clarification:  The standard Java shutdown hook is what would be necessary to provide this behavior consistently anyway.  At best, sbt would manage it for you, but it doesn't seem like existing `onUnload` usages need this (or they don't know they need it).

**Comment by huntc** [comment]
It would be nice to not have to factor out the code in unload to handle an extra case. My motivation can hopefully be conveyed by the use case here:

https://github.com/huntc/jslint-sbt-plugin/blob/master/src/main/scala/com/typesafe/sbt/jslint/Plugin.scala#L43

Failing to call unload can leave a process running in the background. This is not a terrible situation but I would prefer to avoid that for common use cases.

**Comment by harrah** [comment]
I agree the process should be killed.  The problem is that `onUnload` is not a good match for this.  State itself isn't side effecting- it is interpreted by the State processor (the command system).  You could request that a shutdown hook get added, but it wouldn't happen until the end of the current command/task and the system might shutdown before then.  What you'd probably want to do is:
1. define a shutdown hook to kill the process
2. add to `onUnload` to kill the process and remove the shutdown hook to avoid leaks

There could be a helper method to do this.  I think making the `onUnload` hook execute on shutdown is a mismatch, though.
