### ISSUE TITLE
regression: fork in test doesn't work anymore

### ISSUE THREAD

**Issue by backuitist** [sbt/sbt#975]
## steps

``` scala
fork in test := true
```
## problem

Test does not fork
## expectations

Test forks.
## notes

 `fork in Test` works. Also see [Enable forking](http://www.scala-sbt.org/0.13.2/docs/Detailed-Topics/Forking.html#enable-forking):

> To enable forking all test tasks only, set fork to true in the test scope:
> 
> ```
> fork in test := true
> ```

**Comment by eed3si9n** [comment]
Here's what I have so far. This was introduced by sbt/sbt@0bb460c03ed9940c67c9048d353dfd151a5bfdd0 around line 377 of Defaults.scala:

```
 -      testExecution <<= testExecutionTask(key),
 -      testGrouping <<= testGrouping or singleTestGroup(key)
 -  ) )
 +      testExecution <<= testExecutionTask(key)
 +  ) ) ++ Seq(
 +      derive(testGrouping <<= singleTestGroupDefault)
 +  )
```

The commit message says it fixes #539. The actual fix I think is coming from the fact that it's now a derived setting, and the reported behavior is coming from the fact that `singleTestGroup(key)` was changed to `singleTestGroupDefault`, which is no longer scoped to the passed in `key` (e.g. `test` task).

``` scala
    def singleTestGroup(key: Scoped): Initialize[Task[Seq[Tests.Group]]] = inTask(key, singleTestGroupDefault)
    def singleTestGroupDefault: Initialize[Task[Seq[Tests.Group]]] = Def.task {
        val tests = definedTests.value
        val fk = fork.value
        val opts = forkOptions.value
        Seq(new Tests.Group("<default>", tests, if(fk) Tests.SubProcess(opts) else Tests.InProcess))
    }
```

Currently `Tests.Group` carries the knowledge of both the sequence of `TestDefinition` and `TestRunPolicy`, which controls forking.
So why was `singleTestGroup(key)` changed to `singleTestGroupDefault`? Here's what happens if you change it back:

```
[info] java.lang.RuntimeException: Scope cannot be defined for dependency baseDirectory of derived setting testGrouping defined at (sbt.Defaults) Defaults.scala:405
[info]  at scala.sys.package$.error(package.scala:27)
[info]  at scala.Predef$.error(Predef.scala:142)
[info]  at sbt.Init$$anonfun$derive$1.apply(Settings.scala:92)
[info]  at sbt.Init$$anonfun$derive$1.apply(Settings.scala:92)
[info]  at scala.Option.foreach(Option.scala:236)
[info]  at sbt.Init$class.derive(Settings.scala:92)
[info]  at sbt.Def$.derive(Def.scala:10)
[info]  at sbt.BuildCommon$class.derive(Defaults.scala:1730)
[info]  at sbt.Defaults$.derive(Defaults.scala:35)
[info]  at sbt.Defaults$.testTaskOptions(Defaults.scala:405)
```

`Def` object [limits](https://github.com/sbt/sbt/blob/3aa70b914ab81b4614c8f2947321f784487c6df1/main/settings/src/main/scala/sbt/Def.scala#L42-45) derived setting to work only for keys that are not scoped:

``` scala
    override def deriveAllowed[T](s: Setting[T], allowDynamic: Boolean): Option[String] =
        super.deriveAllowed(s, allowDynamic) orElse
        (if(s.key.scope != ThisScope) Some(s"Scope cannot be defined for ${definedSettingString(s)}") else None ) orElse
        s.dependencies.find(k => k.scope != ThisScope).map(k => s"Scope cannot be defined for dependency ${k.key.label} of ${definedSettingString(s)}")

```

@dansanduleac, since you're a derived setting expert, do you think this limitation is necessary? Can we derive task-scoped keys?

**Comment by dansanduleac** [comment]
I'm not entirely sure how to fix this, but regarding derived settings the limitation does make sense. A derived setting is essentially a setting template, creating settings whose _scope_ is derived (I.e. If the setting's deps all exist in scope x, then the setting itself will also be derived in scope x). So, the scope is being determined dynamically.
It makes sense to limit what scopes the setting may be derived in, though. Don't remember if you can already do this.

**Comment by eed3si9n** [comment]
Closing this since we likely won't fix this.
